### ISSUE TITLE
Start google-cloud-gcp-pubsub

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-gcp#1]
Starter project to deal with MessaConverters, ResourceManagement, MessagingTemplate, MessageContainers.
Making the bridge between spring-messaging and pubsub

**Comment by joaoandremartins** [comment]
@viniciusccarvalho what do you think is left to consider this issue resolved?

**Comment by joaoandremartins** [comment]
I think this is now started. There is a bunch of existing stuff that we're not using. We should probably get around to figuring out if we really need it. e.g., `*PubSubSenders`, `*Converters`, etc.
