### ISSUE TITLE
Enhance the PubsubTemplate

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-gcp#10]
This is more of a placeholder for whomever is going to work in this story. Just make sure we have a good implementation with reasonable defaults for users to springify their pubsub experience ;)

**Comment by joaoandremartins** [comment]
Would be great to eventually come down with a list of requirements for the template so we can close this off.

**Comment by joaoandremartins** [comment]
In lieu of specific requirements here, I suggest we follow up on actual actionable issues and close this one out.
Thoughts?
