### ISSUE TITLE
No 1.0.0.RELEASE build for spring-cloud-gcp-starter-data-spanner

### ISSUE THREAD

**Issue by mattysweeps** [spring-cloud/spring-cloud-gcp#1006]
Attempting to use `spring-cloud-gcp-starter-data-spanner` with the `spring-cloud-gcp-dependencies` BOM at version `1.0.0.RELEASE` fails.

This is because the `spring-cloud-gcp-dependencies` BOM uses the same versions for its dependencies: https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-dependencies/pom.xml#L95 and no `1.0.0.RELEASE` exists for  `spring-cloud-gcp-starter-data-spanner` in the spring milestone repo https://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-gcp-starter-data-spanner/

**Comment by meltsufin** [comment]
That's intentional. Spanner support was not part of the 1.0 release because the Cloud Spanner Java client library is not GA yet.

**Comment by mattysweeps** [comment]
Thanks! Wasn't sure, so just wanted to double check.
