### ISSUE TITLE
Datastore Ancestors feature support for non Datastore-Key type ID properties

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#1008]
Up to now we assume all keys do not have any ancestors unless the Id property is of the Key type. 

We need to provide a way for users to define ancestor relationships between keys/entities. 

The top benefits of ancestors are:
- guarantees unique keys are allocated between all entities in a family tree
- allows queries in a single family tree to be strong consistent instead of just eventually consistent (this could be because members of a family tree are all stored together physically)

**Comment by ChengyuanZhao** [comment]
One idea is to combine this with #1007 and use the relationships defined with POJOs to define the ancestor-data for the keys. If any POJO in that family tree has a Key-type Id property with a value that doesn't match what is expected from its parent POJOs then an exception is thrown. @meltsufin @dmitry-s what do you think?

**Comment by meltsufin** [comment]
@ChengyuanZhao Is the intent of this issue to support an alternative to the `Key` class for representing composite keys that include ancestor key part? I think we need to discuss various ideas for this more, and how useful this would be.

**Comment by ChengyuanZhao** [comment]
@meltsufin That's part of the rationale, yes. I don't want to force users to only use the `Key` type if they want access to this core feature in Datastore. Let me list out the other reasons below:

- if we make the ancestor paths implied by POJO relationships, then we can always ensure that an entire family tree of POJOs can be retrieved efficiently. 
- one of the main benefits of ancestors in Datastore is the co-location of the data and the strong consistency of any operations on that family tree. This is very useful for POJO relationships because we can make sure that any POJO-family-tree save or read operation is strong consistent. 
- not to mention, I think the POJO-relationship to ancestors correspondence is a very clean and elegant way to expose the Datastore ancestor feature in a very Java-ish way. 

We should discuss on this thread so that we don't forget our rationales later on.

**Comment by ChengyuanZhao** [comment]
I am implementing ancestors support as discussed via the descendants annotation in the linked ticket. Closing this one
