### ISSUE TITLE
`checkstyle.xml` import order should be in sync with `eclipse.importorders`

### ISSUE THREAD

**Issue by jabubake** [spring-cloud/spring-cloud-gcp#101]
Using [eclipse.importorders](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/src/eclipse/eclipse.importorder) in IntelliJ leads to conflicts with [checkstyle](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/src/checkstyle/checkstyle.xml#L90).

**Comment by meltsufin** [comment]
Thanks Jisha! Is this an easy fix, @joaoandremartins?

**Comment by joaoandremartins** [comment]
It works fine for me. What usually happens is IntelliJ auto-arranges imports with its own rules and I need to manually Optimize Imports (Ctrl + Alt + O). Does that help in your case @jabubake ?

**Comment by jabubake** [comment]
Not really, I do have it set to use the Eclipse importer to auto arrange the imports, on IntelliJ Ultimate. If it does work for you without any changes, I'll take a look later today at my end.

**Comment by artembilan** [comment]
I wonder if you have this problem: https://github.com/spring-cloud/spring-cloud-gcp/pull/55#discussion_r121004223

**Comment by jabubake** [comment]
@artembilan : yes that seems like it. The Eclipse formatter when used within the IntelliJ has reversed the order as stated : I had to manually organize the imports to match the checkstyle settings.

**Comment by saturnism** [comment]
Interesting. I'm using IJ CE, w/ the Eclipse Formatter - it's been working for me

**Comment by artembilan** [comment]
@saturnism ,

It might just be a fact that your IDEA order is the same like in the Eclipse Formatter, or you just have `Optimize imports on the fly` turned off.
My idea with this ticket that we have to add a not into CONTRIBUTION about exactly turning that off: https://github.com/spring-cloud/spring-cloud-gcp/pull/55#discussion_r121155979

**Comment by joaoandremartins** [comment]
This information is already in [CONTRIBUTING.adoc](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/CONTRIBUTING.adoc). Refer to the last bullet.

Let me know if I'm missing anything.
