### ISSUE TITLE
FR: Spring Security Autoconfiguration to validate IAP header and extract principle

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#1016]
See https://cloud.google.com/iap/docs/signed-headers-howto

**Comment by meltsufin** [comment]
Note that Identity-Aware Proxy is currently in Beta. So, we can't yet include it in our GA releases.

**Comment by meltsufin** [comment]
Disregard the previous comment. I guess it's only the case for App Engine Flex that it is in Beta.
