### ISSUE TITLE
Questions/issues with GCP Pub/Sub on PCF

### ISSUE THREAD

**Issue by brightzheng100** [spring-cloud/spring-cloud-gcp#1027]
## Context:

I'm trying out `GCP Service Broker`'s `Pub/Sub` and deploying apps to `PCF`. 

There are two apps: one acts as `server` deployed in `PCF` and one acts as `client `standalone.
And there are 2 topics & 2 subscriptions:
1. topic-server; subscription-server;
2. topic-client; subscription-client

So the `server` is going to publish messages to `topic-client` while listening to `subscription-server`; similarly, `client` is publishing messages to `topic-server` while listening to `subscription-client`.

## Questions / Issues

**1. What are the practices for the `server` app to consume multiple topics and/or subscriptions?**

Currently I have to `cf create-service` twice for two service instances and bind them to server app -- but how if I have 20 or more subscriptions to listen to?

**2. How to fully enable `spring-cloud-gcp-autoconfigure`?**

Note: I tried put it as dependency but didn't work if I didn't specify the `spring.cloud.gpc.*` (e.g. project-id) explicitly.
```
2018-09-18T10:34:58.35+0700 [APP/PROC/WEB/0] OUT Caused by: java.lang.IllegalArgumentException: The project ID can't be null or empty.
   2018-09-18T10:34:58.35+0700 [APP/PROC/WEB/0] OUT 	at org.springframework.util.Assert.hasText(Assert.java:276) ~[spring-core-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
   2018-09-18T10:34:58.35+0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.gcp.pubsub.support.DefaultPublisherFactory.<init>(DefaultPublisherFactory.java:75) ~[spring-cloud-gcp-pubsub-1.1.0.M1.jar!/:1.1.0.M1]
   2018-09-18T10:34:58.35+0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.gcp.autoconfigure.pubsub.GcpPubSubAutoConfiguration.defaultPublisherFactory(GcpPubSubAutoConfiguration.java:275) ~[spring-cloud-gcp-autoconfigure-1.1.0.M1.jar!/:1.1.0.M1]
   2018-09-18T10:34:58.35+0700 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.gcp.autoconfigure.pubsub.GcpPubSubAutoConfiguration$$EnhancerBySpringCGLIB$$e183b0f6.CGLIB$defaultPublisherFactory$15(<generated>) ~[spring-cloud-gcp-autoconfigure-1.1.0.M1.jar!/:1.1.0.M1]
```

**3. As the `client` app is run standalone and there are two service accounts created during the `cf bind-service`, what is the practice for such standalone `client` app to talk to these 2: `topic-server` and `subscription-client`? Should we create another service account for that so that we have only one `credentials.location`?**

**Comment by ChengyuanZhao** [comment]
I just want to quickly give an answer to 2.) before getting into the other questions that are move involved. 

To take advantage of our auto-config for pubsub take a look at the sample for pubsub:  https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-sample/pom.xml

You can use the starter-module instead of the auto-config module directly. 

As for specifying the project-id you can use a json service account credential file supplied via the application.properties, and those files can specify the project-Id. If you don't provide a json file like this the module will try to use the gcloud default credentials, and if you haven't set a default project id in gcloud then you need to give it explicitly in application.properties.  

Take a look here at the bottom section that describes the different ways to specify project-id and credentials: https://github.com/spring-cloud/spring-cloud-gcp/blob/master/README.adoc 
The settings described there will apply to all of our GCP modules. You can specify them for just pubsub by using the `spring.cloud.gcp.pubsub` prefix instead.

**Comment by ChengyuanZhao** [comment]
It looks like `cf create-service google-pubsub` as you're doing is the way to create topics and subscriptions, and it only does so one at a time. Are you encountering difficulties doing this repeatedly for 20 or many subscription/topics?

**Comment by ChengyuanZhao** [comment]
Regarding 3.), You can give the client its own service account credential and then give that service account the necessary permissions on its relevant topics and subscriptions: https://cloud.google.com/pubsub/docs/access-control#api

**Comment by brightzheng100** [comment]
Thanks for your prompt follow up @ChengyuanZhao, really appreciate that.

> You can use the starter-module instead of the auto-config module directly.

Actually I used both as I was trying to see whether this setting could be automatically extracted from bindings and properly set:
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-gcp-autoconfigure</artifactId>
        </dependency>
```
Looks like it's not there yet and we have to compile the `pring.cloud.gcp.pubsub.*` in `application.yml` or manually `cf set-env` maybe.
Please correct me if I'm wrong.


> Are you encountering difficulties doing this repeatedly for 20 or many subscription/topics?

It may not about difficulty. Instead, it's about UX on how to define and bind more topics/subscriptions.


> You can give the client its own service account credential and then give that service account the necessary permissions on its relevant topics and subscriptions

Okay, got it. So it's better to define another dedicated service account and assign corresponding permissions for the `client` to talk to the desired topics/subscriptions.

**Comment by meltsufin** [comment]
#1678 should resolve the first question, and please re-open if the second question is still an issue.
