### ISSUE TITLE
Implement new methods in ExtendedBindingProperties

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1034]
In 2.1, two [new methods were added](
https://github.com/spring-cloud/spring-cloud-stream/commit/07b5a691d4fe390d1f2e92f11614e62c1a1a39b9#diff-0a2bfdd7dbaeb4ebf847742d1da4c03c) to the `ExtendedBindingProperties` interface.
We need to implement them.

@artembilan Do you know what this is about, and how we should go about implementing them?

**Comment by meltsufin** [comment]
I see that there is already a `spring-cloud-stream` `2.1.0.M2` [release](https://github.com/spring-cloud/spring-cloud-stream/releases/tag/v2.1.0.M2). @artembilan Is this the version that will go into `Greenwich.M1`? In that case we don't need to worry about it yet.

**Comment by sobychacko** [comment]
@meltsufin this change is added (merged upstream today) to address the use case of allowing default extended producer/consumer properties. See [this issue](https://github.com/spring-cloud/spring-cloud-stream/issues/1360) for more details. There are PR's in review in Kafka and Rabbit binders at the moment to address these changes.
