### ISSUE TITLE
Send our credentials provider to the Cloud SQL socket factory

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#104]
Now that https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/41 is closed, we should fix the TODO in the [Cloud SQL Boot starter](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql/src/main/java/org/springframework/cloud/gcp/sql/autoconfig/DefaultCloudSqlJdbcInfoProvider.java#L81).

It's still unclear where the fix should go. I don't think the current location of the TODO is the right place to fix. It should go somewhere in `GcpCloudSqlAutoConfiguration`. The user can provide both their own `CloudSqlJdbcInfoProvider` and `DataSource`, but I would argue the Google magic is added in the `CloudSqlJdbcInfoProvider`, so we should probably add the fix to both the `Default` and `AppEngineCloudSqlJdbcInfoProvider`.

**Comment by meltsufin** [comment]
I would just suggest picking the place you think is best and having the discussion in the PR.
