### ISSUE TITLE
Publish reference document

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#105]
We should write up and publish a reference document and link it from our [project's page](http://cloud.spring.io/spring-cloud-gcp/).

@sobychacko can you help with the process to publish the document to the gh-pages branch?

@garyrussell can you help with why the page is linking to a strange link in `docs.github.io` and the URL contains `spring-new`? http://docs.spring.io/spring-new/docs/1.0.0.BUILD-SNAPSHOT/spring-cloud-gcp/htmlsingle/

**Comment by garyrussell** [comment]
Sorry about that; I missed the `spring-new`; link is now

http://cloud.spring.io/docs/1.0.0.BUILD-SNAPSHOT/spring-cloud-gcp/htmlsingle/

**Comment by joaoandremartins** [comment]
@sobychacko friendly ping. Would be great to get started on publishing the reference docs using best practices as soon as possible!

**Comment by sobychacko** [comment]
@joaoandremartins the docs are now getting published to http://docs.spring.io/spring-cloud-gcp/docs/1.0.0.BUILD-SNAPSHOT/reference/.  
The docs link on http://cloud.spring.io/spring-cloud-gcp/ is updated to the above link as well.

**Comment by garyrussell** [comment]
Thanks, Soby.

**Comment by meltsufin** [comment]
Perfect! Thank you, Soby!
