### ISSUE TITLE
Create AckDeadlineManager support class

### ISSUE THREAD

**Issue by dhoard** [spring-cloud/spring-cloud-gcp#1053]
We have a use case where we need to pull a batch of messages via a synchronous batch pull, then process the messages.  Due to long processing time, the ack deadline needs to be extended.

I propose that we create a new support class `AckDeadlineManager` that would easily manage this automate ack deadline extension with an internal timer.  The default key would be the `AcknowledgeablePubsubMessage` `ackId` ... but other keys / key types could be used.

Thoughts on code ...

```
public class AckDeadlineManager {

    public AckDeadlineManager(int ackDeadlineExtensionSeconds) { }

    public void add(AcknowledgeablePubsubMessage message) { }

    public void add(String key, AcknowledgeablePubsubMessage message) { }

    public void addAll(Collection<AcknowledgeablePubsubMessage> messages) { }

    public void remove(AcknowledgeablePubsubMessage message) { }

    public AcknowledgeablePubsubMessage remove(String key) { }

    public Collection<AcknowledgeablePubsubMessage> removeAll() { }

    public AcknowledgeablePubsubMessage get(String key) { }

    public void ackAll() { }

    public void nackAll() { }
```

Thoughts on usage ...

```
int ackDeadlineExtensionSeconds = 60;
AckDeadlineManager ackDeadlineManager = new AckDeadlineManager(ackDeadlineExtensionSeconds);

List<AcknowledgeablePubsubMessage> messages = pubSubScriberTemplate.pull("subscriptionName", 1000, true);

try {
    ackDeadlineManager.addAll(messages);

    // process messages ... could take hours

    ackDeadlineManager.ackAll();
}
catch (Throwable t) {
    ackDeadlineManager.nackAll();
}
finally {
    ackDeadlineManager.removeAll();
}
```

**Comment by meltsufin** [comment]
@dhoard Why is calling `PubSubTemplate.modifyAckDeadline` not sufficient to extend the deadline?

**Comment by dhoard** [comment]
`PubSubTemplate.modifyAckDeadline` / `modifyAckDeadline()` can only extended the deadline for a maximum of `600` second (10 minutes) per call.  If you need more than 10 minutes to process a message, you have to implement code to handle extending the messages.

The `AckDeadlineManager` would contain a timer / thread that ran through all managed messages every `X` seconds, calling `pubSubMessage.modifyAckDeadline()` with the associated ackDeadline `Y` on each message to extend them.

I would consider this a support or helper class.

**Comment by meltsufin** [comment]
I understand the use case now, but part of me feels it's the wrong thing to do:
1) 10 min deadline max seems like an intentional restriction in Pub/Sub, and if it made sense to make it longer, why wouldn't Pub/Sub service implement it?
2) If you require more than 10 minutes to process a single message, maybe there is an opportunity for better design. For example, if the message comes back, and you're in the middle of a long process that the same message triggered, you should be able to recognize that and ignore it. Remember that Pub/Sub only has an at-least-once delivery guarantee. There's always a possibility for you to receive the same message twice, even if you process them quickly and ack. Your design should accommodate that.

**Comment by dhoard** [comment]
For the subscriber model, `Subscriber` does implement the auto `modifyAckDeadline` / extension functionality.

From docs that reference such behavior when using the GCP `Subscriber`...

https://cloud.google.com/pubsub/docs/subscriber

"The subscriber can dynamically modify the ack deadline, allowing message processing to be arbitrarily long."

https://cloud.google.com/pubsub/docs/pull

"Because the client library repeatedly extends the acknowledgement deadline for backlogged messages, those messages continue to consume memory, CPU, and bandwidth resources. As such, you might experience out-of-memory issues."


 I will concede point 2 😄 

I'm fine with closing as no plans to implement.

**Comment by meltsufin** [comment]
Right, the subscriber side does it, and I'm not too thrilled with that either. Ideally, the service itself would allow longer than 10 min deadline. I'll close this for now, but will definitely keep an eye out for other customers voting for the same feature.
