### ISSUE TITLE
How Google datastore vcap_services Json object looks like?

### ISSUE THREAD

**Issue by gouthamkunduru90** [spring-cloud/spring-cloud-gcp#1068]
i have a spring boot application having google cloud data store as back end. my application will going to deploy to PCF in future. we are still in the process of integrating PCF and GCP using service broker. i have written a configuration file for Datastore bean attached code below. i wanted to test it from my local machine by passing a private key data(i got it by using gcp service account json file) and project id from command line. my question is only private key data is enough to get the GoogleCredentials?

/****/
@Configuration
public class GcpDatastoreConfig {

	/**
	 * Returns Google datastore credentials from PCF at runtime (VCAP_SERVICES) and
	 * Sets the service authentication credentials
	 * 
	 * @return GoogleCredentials
	 * @throws IOException
	 * @throws JSONException
	 */
	@Bean
	public GoogleCredentials credential() throws IOException, JSONException {

		String env = System.getenv("VCAP_SERVICES");
		if (env != null) {
			JSONObject vcapServicesObject = new JSONObject(env);
			if (vcapServicesObject.has("google-datastore")) {
				String privateKeyData = vcapServicesObject.getJSONArray("google-datastore").getJSONObject(0)
						.getJSONObject("credentials").getString("PrivateKeyData");
				InputStream stream = new ByteArrayInputStream(Base64.getDecoder().decode(privateKeyData));
				return GoogleCredentials.fromStream(stream);
			}

		}
		return null;

		/*String PATH_TO_JSON_KEY = "src/main/resources/spatial-acumen-213021-2a71c0e3a819.json";
		return GoogleCredentials.fromStream(new FileInputStream(PATH_TO_JSON_KEY));*/
	}

	/**
	 * Configure datastore API to use provided Google credentials
	 * 
	 * @param credentials
	 * @return DatastoreOptions
	 * @throws IOException
	 */
	@Bean
	@ConditionalOnBean(name = "credential")
	public DatastoreOptions datastoreOptions(GoogleCredentials credential) throws IOException {
		if (credential != null) {
			return DatastoreOptions.newBuilder().setProjectId("spatial-acumen-213021").setCredentials(credential)
					.build();
		}
		return null;
	}

	/**
	 * Returns Instance of Google's datastore API
	 * 
	 * @param datastoreOptions
	 * @return Datastore
	 * @throws IOException
	 */
	@Bean
	@ConditionalOnBean(name = "datastoreOptions")
	public Datastore getDatastore(DatastoreOptions datastoreOptions) throws IOException {
		if (datastoreOptions != null) {
			return datastoreOptions.getService();
		}
		return null;
	}
}

**Comment by ChengyuanZhao** [comment]
@gouthamkunduru90 I believe only the json key file for the service account is necessary to work with Datastore.

**Comment by meltsufin** [comment]
See #1069 for related issue.

**Comment by gouthamkunduru90** [comment]
@ChengyuanZhao i am able to authenticate when i use the json file using below code. But my end goal is get the details from vcap_services when deployed to pcf.
        String PATH_TO_JSON_KEY = "src/main/resources/spatial-acumen-213021-2a71c0e3a819.json";
	return GoogleCredentials.fromStream(new FileInputStream(PATH_TO_JSON_KEY));

**Comment by josephlewis42** [comment]
Here's an example grabbed from Pivotal Apps Manager for a bound service:

```json
{
    "VCAP_SERVICES": {
      "google-datastore": [
        {
          "name": "datastore-instance",
          "instance_name": "datastore-instance",
          "binding_name": null,
          "credentials": {
            "Email": "pcf-binding-xyz@project-id.iam.gserviceaccount.com",
            "Name": "binding-name",
            "PrivateKeyData": "<base64 account credential>",
            "ProjectId": "project-id",
            "UniqueId": "123456789123456789"
          },
          "syslog_drain_url": null,
          "volume_mounts": [],
          "label": "google-datastore",
          "provider": null,
          "plan": "default",
          "tags": [
            "gcp",
            "datastore"
          ]
        }
      ]
    }
}
```
