### ISSUE TITLE
Database initialization uses INT64 Spanner column type for primitive doubles

### ISSUE THREAD

**Issue by mattysweeps** [spring-cloud/spring-cloud-gcp#1070]
The method `SpannerSchemaUtils.getCreateTableDDLString` will create a SQL statement which incorrectly uses INT64 for primitive doubles.

The `getCreateTableDDLString` method calls `ConverterAwareMappingSpannerEntityProcessor.getCorrespondingSpannerJavaType`:

https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/admin/SpannerSchemaUtils.java#L187

Which iterates through the `ConverterAwareMappingSpannerEntityWriter.singleItemType2ToMethodMap` map:
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/convert/ConverterAwareMappingSpannerEntityProcessor.java#L104
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/convert/ConverterAwareMappingSpannerEntityWriter.java#L90

In that map, `Long` is ordered before `Double`.

Thus a `Long` conversion is tested, which happens to evaluate to true. (Something to do with Spring type converter support with the `java.util.Number` class. double -> Number -> INT64)

Here's a stacktrace from my local debugging:
```
getConverter:257, GenericConversionService (org.springframework.core.convert.support)
canConvert:145, GenericConversionService (org.springframework.core.convert.support)
canConvert:135, GenericConversionService (org.springframework.core.convert.support)
canConvert:57, SpannerCustomConverter (org.springframework.cloud.gcp.data.spanner.core.convert)
canHandlePropertyTypeForSingularRead:136, ConverterAwareMappingSpannerEntityProcessor (org.springframework.cloud.gcp.data.spanner.core.convert)
getCorrespondingSpannerJavaType:117, ConverterAwareMappingSpannerEntityProcessor (org.springframework.cloud.gcp.data.spanner.core.convert)
getColumnDdlString:188, SpannerSchemaUtils (org.springframework.cloud.gcp.data.spanner.core.admin)
lambda$addColumnDdlStrings$0:239, SpannerSchemaUtils (org.springframework.cloud.gcp.data.spanner.core.admin)
doWithPersistentProperty:-1, 502746837 (org.springframework.cloud.gcp.data.spanner.core.admin.SpannerSchemaUtils$$Lambda$797)
lambda$doWithColumnBackedProperties$1:186, SpannerPersistentEntityImpl (org.springframework.cloud.gcp.data.spanner.core.mapping)
doWithPersistentProperty:-1, 114499348 (org.springframework.cloud.gcp.data.spanner.core.mapping.SpannerPersistentEntityImpl$$Lambda$651)
doWithProperties:329, BasicPersistentEntity (org.springframework.data.mapping.model)
doWithColumnBackedProperties:183, SpannerPersistentEntityImpl (org.springframework.cloud.gcp.data.spanner.core.mapping)
addColumnDdlStrings:230, SpannerSchemaUtils (org.springframework.cloud.gcp.data.spanner.core.admin)
getCreateTableDdlString:124, SpannerSchemaUtils 
...
```

A potential fix might be re-ordering the contents of the `ConverterAwareMappingSpannerEntityWriter.singleItemType2ToMethodMap` such that `Double` comes before `Long`.

I do not know if this would cause any unwanted side effects.

Note that there's no issues with the `Double` type for columns. Only the double primitive.

**Comment by ChengyuanZhao** [comment]
@mattysweeps Thanks much for making this issue! I think re-ordering that map would be the way to go; I'll take a look too and make a PR shortly.

**Comment by ChengyuanZhao** [comment]
I gave the suggested fix a try and due to the same reason (Spring GenericConversionService being able to convert back and forth between integer and floating point number) and now the problem is reversed: `long`, `int`, and `Integer` now get mapped to FLOAT64.

**Comment by meltsufin** [comment]
Is there anyway around this?

**Comment by ChengyuanZhao** [comment]
@meltsufin I believe we have a map (or something close that needs a slight modification) that associates Spanner column types directly with some simple Java types. (For example FLOAT64 with Double and double). I will add a check to see if a direct match exists before testing for can-convert match.

**Comment by ChengyuanZhao** [comment]
@meltsufin  It turns I had that short-cut direct match check already. I just needed to add some entries for the primitive double and long types to some of our type maps.

**Comment by mattysweeps** [comment]
Thanks @ChengyuanZhao for hopping on this so quick! :)
