### ISSUE TITLE
Make tests stricter in DatastoreTemplateTests

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#1089]
Currently, some of the tests in DatastoreTemplateTests have mocks that use ArgumentMatchers.any() matcher. We need to check the actual values of arguments, using ArgumentMatchers.eq() to test more precisely.

**Comment by ChengyuanZhao** [comment]
Just to record some of the things mentioned in in-person discussion: 

- we used findById as an example. Currently because it is using any() as a matcher, it is verify that any given key to datastoreTemplate will result in any arbitrary entity and will result in a final non-null arbitrary object. 
- the proposal is to use the eq() matcher to link these to specific instances of entities, keys, and objects.

- the rebuttal is that it is not the datastoreTemplate's responsibility to guarantee the value of the entity or object corresponding to the given key. It is instead the datastoreEntityConverter and objectToKeyFactory classes' responsibilities to ensure those values, and those are covered by other unit tests. Therefore the only responsibility is that the datastoreTemplate produces a result of the correct type and that the correct instances of the converter and key factory are called.

**Comment by meltsufin** [comment]
I think it's the template's responsibility to ensure that it's calling the client with the correct arguments. Can we have an example here to make this concrete?

**Comment by dmitry-s** [comment]
Sure:
```java
@Test
public void findByIdTest() {
	Key key1 = createFakeKey("key1");
	TestEntity ob1 = new TestEntity();
	Entity e1 = Entity.newBuilder(key1).build();
	when(this.datastore.get(ArgumentMatchers.<Key>any())).thenReturn(e1);
	when(this.datastoreEntityConverter.read(eq(TestEntity.class), any())).thenReturn(ob1);

	assertEquals(ob1, this.datastoreTemplate.findById(key1, TestEntity.class));
}
```

**Comment by meltsufin** [comment]
Here's the actual method you're trying to test:
```java
	@Override
	public <T> T findById(Object id, Class<T> entityClass) {
		Entity entity = this.datastore.get(getKeyFromId(id, entityClass));
		return entity == null ? null
				: this.datastoreEntityConverter.read(entityClass, entity);
	}
```
You really want to verify that `datastore.get()` was called with the passed in `id`. You also want to verify that the entity returned from `datastore.get()` was passed through to conversion. The current test doesn't verify any of that.
It can be implemented simply as:
```java
	@Override
	public <T> T findById(Object id, Class<T> entityClass) {
		return entityClass.newInstance();
	}
```
and the test will still pass.

A better test would be:
```java
	@Test
	public void findByIdTest() {
		// wire up mocks
		String stringKey = "key1";
		Key key = createFakeKey(stringKey);
		TestEntity ob1 = new TestEntity();
		Entity e1 = Entity.newBuilder(key).build();
		when(this.datastore.get(eq(key))).thenReturn(e1);
		when(this.objectToKeyFactory.getKeyFromId(eq(stringKey), any())).thenReturn(key);
		when(this.datastoreEntityConverter.read(eq(TestEntity.class), eq(e1))).thenReturn(ob1);

		// invoke the method under test
		this.datastoreTemplate.findById(stringKey, TestEntity.class);

		// verify
		verify(this.datastore, times(1)).get(eq(key));
	}
```

**Comment by ChengyuanZhao** [comment]
@meltsufin 

Your example is also totally incomplete. It does not verify at any point beyond the client library's datastore.get call. You also need to verify that the converter was given an entity, which is what the original line `assertEquals(ob1, this.datastoreTemplate.findById(key1, TestEntity.class));` did.

In fact asserting this final link in the chain happened necessarily means every previous step also was called.

**Comment by ChengyuanZhao** [comment]
@meltsufin I don't think your counter example would work...

We are verifying that specifically `ob1` is returned, and `ob1` must be returned by the converter mock, and not merely `entityClass.newInstance()`

**Comment by ChengyuanZhao** [comment]
Discussed in person , should add `when(this.objectToKeyFactory.getKeyFromId(eq(stringKey), any())).thenReturn(key);
`

**Comment by ChengyuanZhao** [comment]
However that is altering the test. The definition of `TestEntity` is a part of this test, and intentionally implementing `equals()` to not check by reference is intentionally defeating other parts of the test code that were not expecting this sort of attack.

**Comment by meltsufin** [comment]
If you really want reference equality, there is `assertSame`.

**Comment by ChengyuanZhao** [comment]
The test file in question is being totally re-done as part of the descendants work #1097

**Comment by ChengyuanZhao** [comment]
The tests have been redone in #1097 and are set up to match based on specific objects now. To make them more clear we can add verify calls (though redundant).

**Comment by ChengyuanZhao** [comment]
this class has been totally redone and is now linking together individual entities, objects, and keys.
