### ISSUE TITLE
Look into H2 interoperability with our SQL starter

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#110]
Local dev with H2 is a common use case with the Spring SQL starter, we should give it a go with our starter and see if it plays well, or document if not a good match.

Right off the bat, one difference is H2 asks for "DROP TABLE customer IF EXISTS" and MySQL wants "DROP TABLE IF EXISTS customer"

**Comment by artembilan** [comment]
How about HSQL or Derby instead ?

Although I don't see reason yet in this issue: if you are going to develop locally, without any connection to the Google Cloud, so just rely on the `DataSource` bean and it is already out of scope of this project which embedded (or local) RDBMS is used.

What am I missing otherwise?

Thanks

**Comment by joaoandremartins** [comment]
My main concern is that there is the expectation of using H2 in local development, removing the dependency and the code is now on running on Google Cloud SQL. This is how the Spring SQL starter does it, right?

If they integrate seamlessly, we can close this issue. If they don't and there's a way for us to fix it, we could fix it. Else, could it be worth saying in the documentation that the starter doesn't support local development?

**Comment by meltsufin** [comment]
I agree, I don't fully understand the motivation for this issue. If anything, we should ensure compatibility with connecting to a local MySQL instance. I think that's what MySQL starter does by default when running locally.

**Comment by meltsufin** [comment]
@saturnism WDYT?

**Comment by artembilan** [comment]
The starter does not make sense (or shouldn't ?) if we really deal with any possible (supported) embedded DB, like it really works with the current Spring Boot: http://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/reference/html/boot-features-sql.html#boot-features-sql

I may agree that you are only going to test it and that's all 😄

**Comment by joaoandremartins** [comment]
It seems like @DazWilkin was able to change easily between H2 and Cloud SQL (with that little syntax nuance), so it seems to work fine.
