### ISSUE TITLE
Trace documentation includes unused property

### ISSUE THREAD

**Issue by mtdidexx** [spring-cloud/spring-cloud-gcp#1100]
The documents for trace (trace.adoc) include a reference to the property `spring.cloud.gcp.trace.enabled` which is a property that does not appear to be in `GcpTraceProperties`

Being able to disable Tracing (for example when running locally) would be a great feature.

**Comment by meltsufin** [comment]
The property is used directly in the [StackdriverTraceAutoConfiguration](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/trace/StackdriverTraceAutoConfiguration.java#L71) as `@ConditionalOnProperty`.
