### ISSUE TITLE
Add support @EnableDatastoreAuditing annotation

### ISSUE THREAD

**Issue by sergeymeshkov** [spring-cloud/spring-cloud-gcp#1113]
Please add support of @EnableDatastoreAuditing annotation which simplifies auditing while using Datastore repositories.

**Comment by meltsufin** [comment]
Thank you for the issue submission. Can you please provide some more context on what this annotation would do? Thanks!

**Comment by sergeymeshkov** [comment]
This annotation can be the same as [@EnableJpaAuditing](https://docs.spring.io/spring-data/data-jpa/docs/current/api/org/springframework/data/jpa/repository/config/EnableJpaAuditing.html) or [@EnableMongoAuditing](https://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/config/EnableMongoAuditing.html)

Annotation elements:
**auditorAwareRef** - Configures the AuditorAware bean to be used to lookup the current principal.
**dateTimeProviderRef** - Configures a DateTimeProvider bean name that allows customizing the org.joda.time.DateTime to be used for setting creation and modification dates.
**modifyOnCreate** - Configures whether the entity shall be marked as modified on creation.
**setDates** - Configures whether the creation and modification dates are set.

**Comment by ChengyuanZhao** [comment]
We just implemented this for Spanner so this should be a walk in the park.
