### ISSUE TITLE
Failed conversion for gcs url

### ISSUE THREAD

**Issue by philiplourandos** [spring-cloud/spring-cloud-gcp#1121]
I have a spring batch application I am writing and I have had to change from a FileSystemResource to use GCP storage. I was hoping to use the same functionality where the name of the file to process is a job parameter and the spring framework will create the GoogleStorageResource like it was doing with the FileSystemResource:

```java
@Bean
    @StepScope
    public FlatFileItemWriter merchantUploadFileWriter(
            @Value("#{jobParameters['param.input.file.path']}") final FileSystemResource uploadFile,
            @Value("${bulk.disbursement.gcs.bucket}") final String cloudBucket)
            throws IOException {
        // Code
    }
```

required:

```java
    @Bean
    @StepScope
    public FlatFileItemWriter merchantUploadFileWriter(
            @Value("#{jobParameters['param.input.file.path']}") final GoogleStorageResource uploadFile,
            @Value("${bulk.disbursement.gcs.bucket}") final String cloudBucket)
            throws IOException {
        // Code
    }
```

**Comment by meltsufin** [comment]
Are you using Spring Boot? If so, I would try adding `spring-cloud-gcp-starter-storage`. Otherwise, you need to configure the `GoogleStorageProtocolResolver`  and `Storage` in your application context. See: https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/storage/GcpStorageAutoConfiguration.java.

**Comment by philiplourandos** [comment]
> Are you using Spring Boot?

Yes. 2.0.6.RELEASE

> I would try adding spring-cloud-gcp-starter-storage

I do have that dependency on the Classpath.

> therwise, you need to configure the GoogleStorageProtocolResolver and Storage in your application context

Copy that. Will have a look

**Comment by meltsufin** [comment]
@philiplourandos Please re-open if you're still having the issue. Also, if you have an update, please post here. Thanks!
