### ISSUE TITLE
Spanner change includeColumns param to includeProperties to also apply to interleaved properties

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#1133]

**Comment by ChengyuanZhao** [comment]
@vineela-gampa The PR for this change is now in review. You can now set a Set of properties to include with your queries and reads with the SpannerTemplate.

This way you can selectively load or write some interleaved children properties and not others. This means you can go back to using a simple select query for just the parents and you don't need to build your own nested struct-select queries.

**Comment by vineela-gampa** [comment]
Awesome !! will take a look at the changes done so that i understand.
