### ISSUE TITLE
Moving to Spring Cloud GCP 1.1.0.M2 causes a NPE: remoteServiceName is empty error

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-gcp#1146]
I just updated one of my microservices to use this new version and noticed upon visiting any endpoint the following error:

```text
java.lang.NullPointerException: remoteServiceName is empty at brave.internal.recorder.MutableSpan.remoteServiceName(MutableSpan.java:98) 
~[brave-5.2.0.jar!/:na] at brave.RealSpan.remoteServiceName(RealSpan.java:120) 
~[brave-5.2.0.jar!/:na] at brave.Span.remoteEndpoint(Span.java:123) 
~[brave-5.2.0.jar!/:na] at brave.http.HttpHandler.handleStart(HttpHandler.java:29) 
~[brave-instrumentation-http-5.1.4.jar!/:na] at brave.http.HttpServerHandler.handleReceive(HttpServerHandler.java:75) 
...
```

Removing 

```
  <dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-gcp-starter-trace</artifactId>
  </dependency>

  <dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-gcp-starter-logging</artifactId>
  </dependency>
```

Possibly related to [this](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/handler/MutableSpan.java)?

**Comment by artembilan** [comment]
Would you mind to bring us a stack trace which can be readable?

Please, take a look into GutHub recommendations how to comment code snippets: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by meltsufin** [comment]
@Alos it seems related to this https://github.com/openzipkin/brave/issues/792
Try running with `1.1.0-BUILD-SNAPSHOT` which has the latest version of Brave.

**Comment by Alos** [comment]
Yes, that did the trick! Thanks! :)
