### ISSUE TITLE
Cloud Spanner integration tests are broken due to quota exceeded

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1149]
In Travis log:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.127 s <<< FAILURE! - in org.springframework.cloud.gcp.data.spanner.repository.it.SpannerRepositoryIntegrationTests
[ERROR] queryMethodsTest(org.springframework.cloud.gcp.data.spanner.repository.it.SpannerRepositoryIntegrationTests)  Time elapsed: 0.114 s  <<< ERROR!
com.google.cloud.spanner.SpannerException: 
RESOURCE_EXHAUSTED: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'spanner.googleapis.com/admin_method_quota' and limit 'AdminMethodQuotaPerMinutePerProject' of service 'spanner.googleapis.com' for consumer 'project_number:653574825147'.
links {
  description: "Google developer console API key"
  url: "https://console.developers.google.com/project/653574825147/apiui/credential"
}
Caused by: java.util.concurrent.ExecutionException: 
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'spanner.googleapis.com/admin_method_quota' and limit 'AdminMethodQuotaPerMinutePerProject' of service 'spanner.googleapis.com' for consumer 'project_number:653574825147'.
links {
  description: "Google developer console API key"
  url: "https://console.developers.google.com/project/653574825147/apiui/credential"
}
Caused by: io.grpc.StatusRuntimeException: 
RESOURCE_EXHAUSTED: Quota exceeded for quota metric 'spanner.googleapis.com/admin_method_quota' and limit 'AdminMethodQuotaPerMinutePerProject' of service 'spanner.googleapis.com' for consumer 'project_number:653574825147'.
links {
  description: "Google developer console API key"
  url: "https://console.developers.google.com/project/653574825147/apiui/credential"
}

```

**Comment by ChengyuanZhao** [comment]
Looks like we're gonna need to get in touch with human GCP support. The quota request mechanism for this specific one is broken and links you to increasing the node count quota.

**Comment by ChengyuanZhao** [comment]
In the meantime this quota is a 7-day limit so I believe it is rolling, and we should be OK mostly as I get this resolved.

**Comment by meltsufin** [comment]
What is the exact operation we're exceeded the quota for, and what is the quota?

**Comment by ChengyuanZhao** [comment]
It is the admin API. Creating and deleting tables. It is 300 / 7 days

**Comment by meltsufin** [comment]
The quota isn't that big indeed. How many times approximately are we're doing it per CI build?

**Comment by ChengyuanZhao** [comment]
We do it a fixed number of times per build. I believe it's something like:
- check and create the database if needed
- get the tables that exist so we know if we need to create the table 
- create the table possibly

We haven't run into this limit in the last 8 or 9 months, but I think as our team grew there are more folks submitting PRs that cause builds and we're hitting the limit.

It actually seems pretty hard to get human support for our CI account hmmm..

**Comment by meltsufin** [comment]
It seems like the quota is supposed to be per minute, not per 7 days. So, it's surprising that we would ever exceed it.

**Comment by meltsufin** [comment]
Looks like we're calling `google.spanner.admin.database.v1.DatabaseAdmin.ListDatabases` too much in our integration tests.

**Comment by ChengyuanZhao** [comment]
I'm working with GCP support to try and get this limit raised, though hopefully the problem is mitigated by the PR #1151.
