### ISSUE TITLE
Datastore integration test break into smaller tests and refactor common setup code that would result

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#1154]

**Comment by meltsufin** [comment]
Can you reference the file please?

**Comment by ChengyuanZhao** [comment]
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/it/DatastoreIntegrationTests.java

**Comment by ChengyuanZhao** [comment]
Added link. There is just one integration test file.

**Comment by meltsufin** [comment]
Test seems ok now.
