### ISSUE TITLE
Google Cloud SQL w/ PostgreSQL

### ISSUE THREAD

**Issue by DazWilkin** [spring-cloud/spring-cloud-gcp#116]
The `spring-cloud-gcp-starter-sql` is easily configured for MySQL databases.

I was able to get it working against PostgreSQL too:

pom.xml:
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter-sql</artifactId>
            <version>1.0.0.BUILD-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.1.4</version>
        </dependency>
       <dependency>
            <groupId>com.google.cloud.sql</groupId>
            <artifactId>postgres-socket-factory</artifactId>
            <version>1.0.4</version>
        </dependency>
```
Then, application.properties:
```
spring.cloud.gcp.projectId=[[PROJECT-ID]]
spring.cloud.gcp.sql.instanceName=[[INSTANCE-ID]]
spring.cloud.gcp.sql.jdbcDriver=org.postgresql.Driver
spring.cloud.gcp.sql.jdbcUrl=jdbc:postgresql://google/[[DATABASE-NAME]]?socketFactory=com.google.cloud.sql.postgres.SocketFactory&socketFactoryArg=[[CONNECTION-NAME]]
spring.cloud.gcp.sql.databaseName=[[DATABASE-NAME]]
spring.cloud.gcp.sql.userName=[[DATABASE-USER]]
spring.cloud.gcp.sql.password=[[DATABASE-PASSWORD]]
```

//cc:@joaoandremartins

**Comment by meltsufin** [comment]
This is really really cool, Daz! Thanks for trying it out.

I wonder if we need two different starters for MySQL and PostgreSQL, or just switch auto-configuration based on `org.postgresql.Driver` on the classpath. Or, include both drivers and select based on a user property.

**Comment by DazWilkin** [comment]
It's almost (!) trivial to flip between MySQL and PostgreSQL instances.

The MySQL JDBC URL is the default (not needed) and IIUC takes the form:
```jdbc:mysql://google/[[DATABASE-NAME]]?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=[[CONNECTION-NAME]]```

The PostgreSQL JDBC URL must be specified:
```jdbc:postgresql://google/[[DATABASE-NAME]]?socketFactory=com.google.cloud.sql.postgres.SocketFactory&socketFactoryArg=[[CONNECTION-NAME]]```

and the code currently requires re-stating the following properties even though these are either explicitly or indirectly (in the connection) specified by the URL:
```
spring.cloud.gcp.sql.projectID=[[PROJECT-ID]]
spring.cloud.gcp.sql.instanceName=[[INSTANCE-ID]]
spring.cloud.gcp.sql.databaseName=[[DATABASE-NAME]]
```

Perhaps there should be an additional property:
```
spring.cloud.gcp.sql.databaseType=[MySQL|PostgreSQL]
spring.cloud.gcp.sql.databaseVersion=[[VERSION]]
```
and then it should be possible for it to construct the JDBC URL for all flavors of database that Cloud SQL supports.

Wrote up my (positive) experience on Medium:
https://medium.com/@DazWilkin/google-cloud-sql-4-ways-spring-a4f13ad32714

**Comment by DazWilkin** [comment]
Submitted FR for "Cloud SQL Socket Factory for JDBC drivers" to be consistent in referencing Cloud SQL Connections: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/49

**Comment by joaoandremartins** [comment]
Great stuff! Thanks Daz.

One thing is that if you use `spring.cloud.gcp.sql.jdbcUrl`, spring.cloud.gcp.sql.instanceName` isn't used, along with `region` and `instanceConnectionName`.

It seems that [[CONNECTION_NAME]] is the same as [[INSTANCE_ID]].

I like the databaseType property to distinguish between MySQL and PostgreSQL. However, our starter will only specify one version of a database provider at a time (e.g, MySQL 5.x, not 8).

**Comment by DazWilkin** [comment]
Ah... My mistake. Yes, you are correct on both:

```
spring.cloud.gcp.projectId=[[PROJECT-ID]]
spring.cloud.gcp.sql.jdbcDriver=org.postgresql.Driver
spring.cloud.gcp.sql.jdbcUrl=jdbc:postgresql://google/[[DATABASE-NAME]]?socketFactory=com.google.cloud.sql.postgres.SocketFactory&socketFactoryArg=[[CONNECTION-NAME]]
spring.cloud.gcp.sql.databaseName=[[DATABASE-NAME]]
spring.cloud.gcp.sql.userName=[[DATABASE-USER]]
spring.cloud.gcp.sql.password=[[DATABASE-PASSWORD]]
```

The provider requires `databaseName` even though it's duplicative of  `jdbcURL`.

**Comment by joaoandremartins** [comment]
Yep, that needs to be fixed, too...
