### ISSUE TITLE
PubSubMessageChannelBinder.createConsumerEndpoint ignores passed in group

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1162]
Note that `PubSubChannelProvisioner.provisionConsumerDestination` handles the passed in group.

**Comment by meltsufin** [comment]
@artembilan Could this be causing the problem with multiple consumers used with Spring Cloud Bus?

**Comment by meltsufin** [comment]
So, are we saying that currently the samantics of our binder are incorrect? Meaning that currently if we have multiple consumer destinations with the same name, they are competing for message delivery, whereas with your proposed change they would all receive every message. What are the correct semantics for any binder?

Also, regarding `PubSubMessageChannelBinder.createConsumerEndpoint`, should we be handling the `group` parameter there?

**Comment by meltsufin** [comment]
Thanks for the doc reference. That does clarify that the current semantics are broken according to the specification of Stream binders.

**Comment by artembilan** [comment]
Closed as `Works as Designed` (in part of `PubSubMessageChannelBinder.createConsumerEndpoint()`) in favor of #1162 for the proper anonymous subscription handling.
