### ISSUE TITLE
Pub/Sub Binder does not handle anonymous consumer groups

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1172]
According to [Cloud Stream Docs](https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#consumer-groups):

>  By default, when a group is not specified, Spring Cloud Stream assigns the application to an anonymous and independent single-member consumer group that is in a publish-subscribe relationship with all other consumer groups.

However, in our implementation, we always use the same subscription for all applications that do not specify a consumer group. This causes all consumers to effectively belong to the same consumer group, which is the exact opposite of the specification.

Supersedes #1162

**Comment by artembilan** [comment]
??? Why just not rename that issue?

What is the point to multiply issues around the same problem?

Thanks for understanding!

**Comment by meltsufin** [comment]
Renaming did cross my mind too.

It was my mistake to conflate two different issues in that post. The original issue was really around `createConsumerEndpoint` ignoring the `group` parameter, and the resolution was what you said -- it's as intended.

The discussed there led to the discovery of this issue though. I thought it was not strictly related though. I meant to close that issue.

I'm fine with renaming that issue and closing this one, or just closing that one. Your call.
