### ISSUE TITLE
Replace custom checkstyle config with one in spring-cloud-build

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1195]
See: https://github.com/spring-cloud/spring-cloud-build/blob/master/spring-cloud-build-tools/src/main/resources/checkstyle.xml

This will likely involve some fixes in the codebase to satisfy rules missing in our current checkstyle.xml.

**Comment by romani** [comment]
Ones you finish migration please let me know, I will add your project to checkstyle CI to make sure new releases of checkstyle do not make regression.

**Comment by meltsufin** [comment]
@romani Will do! Is there anything that's preventing you from adding the project to checkstyle CI now? We have checkstyle enabled in the project, it's just that some of these rules are currently commented out.

**Comment by romani** [comment]
Please give me command to run checkstyle on this project, I need to be sure it fails with error, and it can use latest version of checkstyle

**Comment by meltsufin** [comment]
@romani This should do it:
```
./mvnw checkstyle:check@checkstyle-validation
```

**Comment by romani** [comment]
Can you add this command to your CI - https://github.com/spring-cloud/spring-cloud-gcp/blob/master/.travis.yml to let be sure you keep it serious, and we can rely that you do not allow violations in master branch, so we can always use master's HEAD

**Comment by meltsufin** [comment]
This checkstyle execution is already [bound](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/pom.xml#L180) to the `validate` Maven phase.
Since the `validate` phase is the first phase in the Maven lifecycle, we actually run it three times during the build. Once during install phase, once during unit tests, and another time during integration tests. Is running it three times serious enough? :smile:

**Comment by romani** [comment]
>  Is running it three times serious enough?

thanks a lot for hit, https://github.com/checkstyle/checkstyle/issues/6209

**Comment by romani** [comment]
@meltsufin or @elefeint ,
issue is closed but there are bunch of violations in codebase from checkstyle, look at details of our try to hook your project in our no-regression testing - https://github.com/checkstyle/checkstyle/pull/8106 .
Please explain why it happening. We need no violations on each commit to make collaboration efficient. It would be awesome if your CI failing on non-resolved chekcstyle violations.

**Comment by elefeint** [comment]
@romani Your checkstyle rule set seems stricter than the Spring Cloud one. For example, `LineLength` is more of a general suggestion than strict rule in Spring Cloud projects; it's been [disabled](https://github.com/spring-cloud/spring-cloud-build/blob/a2532c63b0668cb49c9ea031aca131282d278c71/spring-cloud-build-tools/src/main/resources/checkstyle.xml#L32) in the build project for a while.

Is it possible to have `spring-cloud-gcp` in the checkstyle CI with our current configured checkstyle and exclusion files?
