### ISSUE TITLE
Log Query times 

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1211]
Hi , we would like to add teh feature to log execution time for each query with the exact SQL its executing. 

@ChengyuanZhao @meltsufin do we already have this feature ?

**Comment by ChengyuanZhao** [comment]
@vineela-gampa If debug mode is on `SpannerTemplate`  will  log the queries (the exact statements) that are executed along with the timestamp the query was completed. Currently it doesn't log the elapsed time, but you can log a timestamp right before the query call.

**Comment by meltsufin** [comment]
@ChengyuanZhao I think we should log the execution time at debug logging level, if the Spanner library doesn't already do that. It seems reasonable to me.

**Comment by ChengyuanZhao** [comment]
@meltsufin  yes sounds good. Please make an issue so we don't lose track of it.

**Comment by meltsufin** [comment]
Why can't we just use this issue?

**Comment by ChengyuanZhao** [comment]
I suppose we could rename it. This issue is more of a question rather than a feature kind of issue.

**Comment by meltsufin** [comment]
Sure, if you can think of a better name, rename it please.

**Comment by vineela-gampa** [comment]
@ChengyuanZhao @meltsufin is this going ot be quick ? we are planniing to play that story as we didnt have this feature.
