### ISSUE TITLE
Trace with X-Cloud-Trace-Context does not match trace with X-B3 header

### ISSUE THREAD

**Issue by dzou** [spring-cloud/spring-cloud-gcp#1212]
I noticed the recorded spans using x-b3 headers do not match traces recorded with x-cloud-trace-context.

In the Trace sample app, if you hit the sample app endpoint,
- with x-b3 you get a trace with 9 spans
- with x-cloud-trace-context you get a trace with 8 spans.

One can confirm this is the case by manipulating the Trace sample app test and running the test using each header.

**Comment by dzou** [comment]
Yeah I'll investigate deeper. My initial gut feeling is this might be a bug - spans have this parent-child relationship and in using the x-cloud-trace-context, it looks like the "root span" is missing; (i.e. there is a span whose `parentSpanId` points to something that doesn't exist).

**Comment by elefeint** [comment]
Might be a bug in propagation. The first time we get a cloud trace header, it gets converted to b3 and sent out.

**Comment by dzou** [comment]
@elefeint I see, which code are you referring to which does that? Is it in zipkin-gcp or in the regular open-zipkin repo?

**Comment by elefeint** [comment]
I was fixing an issue (X-cloud header comes in to an app and gets converted to a B3 header and sent out. The sub-request, when it goes through our proxy, gets another X-cloud header, which is treated as a completely new entity) in openzipkin/zipkin-gcp#97. It's a good place to view the code involved.

I think it's possible that the first hop is still recorded by stackdriver as a separate entry, and after that all headers get propagated as B3 in an orderly manner.

**Comment by dzou** [comment]
Fixed in https://github.com/openzipkin/zipkin-gcp/pull/105

**Comment by meltsufin** [comment]
Do we still need to wait for the new release of `zipkin-gcp` and upgrade to it?

**Comment by dzou** [comment]
Ah yes, good call. Let me reopen this; we can close this once we upgrade the version.

**Comment by dzou** [comment]
Since the Zipkin version has been updated to 0.9.0 (via #1297), this issue is now resolved.
