### ISSUE TITLE
Add executeUpdate method to implementation of Spanner TransactionContext

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#1213]
Spanner API added a new method `executeUpdate` in googleapis/google-cloud-java#3781. As a result, we cannot upgrade to the latest `google-cloud-bom.version` (`0.70.0-alpha`) until we resolve the compilation issue in [`SpannerTransactionManager`](https://github.com/spring-cloud/spring-cloud-gcp/blob/d1c600affb904d45677c87ed0e6ad950822c2c49/spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/SpannerTransactionManager.java#L102).

**Comment by meltsufin** [comment]
@ChengyuanZhao @dmitry-s PTAL
