### ISSUE TITLE
Google Cloud BOM 0.70.0-alpha doesn't work with maven-surefire-plugin:test version 2.22.0

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#1222]
When building spring-cloud-gcp-autoconfigure the maven-surefire-plugin:test fails when using 2.22.0 or newer versions, but it does still work with a slightly older version of the plugin 2.20.

**Comment by amohabir** [comment]
Perhaps could be related to this one: https://issues.apache.org/jira/browse/SUREFIRE-1588
