### ISSUE TITLE
GCP Pubsub broadcast message published to a topic to multiple INSTANCES

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1244]
My usecase:
We have set of data which doesnt change too often where we want to have local cache. When the data changes we want to use event driven mechanism to send the message so that the message gets broadcasted to all the nodes of our application (across multiple regions).
Using GCP pubsub its 1-1 correlation between topic / subscription. i mean for an application we can only have one subscriber per topic. 

How can we achieve broadcasting the message to multiple nodes across different regions of our applicaiton ?

**Comment by vineela-gampa** [comment]
@meltsufin @ChengyuanZhao

**Comment by meltsufin** [comment]
@vineela-gampa Why do you say that you can only have one subscription per topic, if I understood you correctly? A broadcast scenario is achieved where there is a single topic and each node has a separate subscription to that topic. If you are using Spring Cloud Stream, we will even automatically create an anonymous/ephemeral subscription for each of your node/consumers.

**Comment by artembilan** [comment]
This doesn't sound like a bug report or feature request.
All your nodes must have unique subscriptions to the same topic. That's how you can broadcast the same message.

See Pub/Sub docs for more info: https://cloud.google.com/pubsub/docs/overview
