### ISSUE TITLE
Checkstyle: remove checkstyle-header.txt in favor of one provided in the spring-cloud-build

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-gcp#1245]
After fixing https://github.com/spring-cloud/spring-cloud-build/issues/62 we don't need our local `checkstyle-header.txt` any more.

**Comment by meltsufin** [comment]
The [current](https://github.com/spring-cloud/spring-cloud-build/blob/master/spring-cloud-build-tools/src/main/resources/checkstyle-header.txt) copyright header there doesn't allow a single year like:
```
Copyright 2018 original author or authors.
```
It requires 
```
Copyright 2017-2018 original author or authors.
```

**Comment by artembilan** [comment]
That's how it works in Spring Boot: https://github.com/spring-projects/spring-boot/blob/master/src/checkstyle/checkstyle-header.txt#L2

So, I believe for consistency Spring Cloud pulled the same pattern.

I guess the first year means the moment the project has been created. Although it is going to be slightly confusing for new project to follow this *year-year* requirements. So,  we are forced to do something like this `2019-2019`. 😕 

@snicoll , WDYT, please?

**Comment by snicoll** [comment]
> That's how it works in Spring Boot

That's how it is supposed to work across the board in the whole codebase. I'd use `2018-2018` for the time being. What is wrong with that?

**Comment by artembilan** [comment]
Thanks, Stephane, for confirmation!

>  What is wrong with that?

I wonder how do you feel when you have to type `2018-2018` 😄 

I Spring Integration we use this pattern:
```
\E20\d\d(\-20\d\d)?
```
The moment when class has been created. However I believe that policy about the moment when project was created fits this patterns as well. 
Anyway that might be late already to discuss the change in the header pattern...

That's not so big deal, @meltsufin . And that's so trivial task that I marked it with the `good first issue` label. (Maybe it's time to tweet about these issues?..)
After fixing all of this routine our project is going to be aligned with code style standards for the whole Spring portfolio. What is wrong with that?
