### ISSUE TITLE
Framework to connect to https://cloud.google.com/memorystore/docs/redis

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1252]
Its not a bug. 

Does spring have framework to connect to gcp redis memorystore?

**Comment by vineela-gampa** [comment]
@meltsufin

**Comment by meltsufin** [comment]
There is caching support that is [documented in our refdoc](https://docs.spring.io/spring-cloud-gcp/docs/1.1.0.M3/reference/htmlsingle/#_caching_using_cloud_memorystore_for_redis).
