### ISSUE TITLE
Migrate Docs to the Spring Cloud style

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-gcp#1255]
See https://github.com/spring-cloud/spring-cloud-release-tools/issues/113 for more info

**Comment by meltsufin** [comment]
What's the priority on this?

**Comment by artembilan** [comment]
Would be great ti align it with the current Greenwich release train.

**Comment by artembilan** [comment]
See comment from Ryan: https://github.com/spring-cloud/spring-cloud-release-tools/issues/113#issuecomment-442122428.

I guess we need to take some other Spring Cloud project as a sample, e.g. the same Spring Cloud Netflix: https://github.com/spring-cloud/spring-cloud-netflix/tree/master/docs, including its POM

**Comment by artembilan** [comment]
@ryanjbaxter,

We have just moved our docs to Spring Cloud structure.
Can you, please, test what we have so far with Spring Cloud aggregated docs?

Thanks in advance!

**Comment by ryanjbaxter** [comment]
when I build the project with the `docs` profile it fails with
```
[ERROR] Failed to execute goal com.agilejava.docbkx:docbkx-maven-plugin:2.0.15:generate-pdf (pdf) on project spring-cloud-gcp-docs: Error executing ant tasks: Warning: Could not find file /Users/ryanjbaxter/git-repos/spring-cloud/spring-cloud-gcp/docs/target/contents/reference/pdf/index.pdf to copy.
```

**Comment by artembilan** [comment]
Hm... Any idea what are we missing?

Thanks

**Comment by ryanjbaxter** [comment]
Unfortunately not, I have never see it look for a PDF like that....

**Comment by ChengyuanZhao** [comment]
Ah I think I know what's wrong. Will put up a fix PR soon.

**Comment by artembilan** [comment]
Oh, wait!

I think we also need to align plugins for docs in POM similar way you have it in other SC projects, e.g.: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/pom.xml#L32

**Comment by artembilan** [comment]
I think the point is that other Spring Cloud project doesn't build Docbook at all.
Our initial docs approach was borrowed from Spring Cloud Stream, but that one has moved recently to the current Spring Cloud standard and I guess that don't build PDF any more, too.

**Comment by ChengyuanZhao** [comment]
I'm gonna close this one for now. The build issue has been fixed and the generated files are looking like what's needed.

**Comment by ChengyuanZhao** [comment]
#1259
