### ISSUE TITLE
Datastore save is not thread safe

### ISSUE THREAD

**Issue by jroosing** [spring-cloud/spring-cloud-gcp#1260]
Encountered this issue when receiving an initial load of 100k entities that need to be stored. 
Messages can be processed async. 

In my code I have defined a repository as such:
```java
@Repository
public interface MyRepository extends DatastoreRepository<SomeClass, String> {
}
```

I have multiple threads calling this repo's save method. This at some point chains down to a call in the class  "GcpDatastoreAutoConfiguration":

```java	
@Bean
@ConditionalOnMissingBean
public ReadWriteConversions datastoreReadWriteConversions(DatastoreCustomConversions customConversions, ObjectToKeyFactory objectToKeyFactory) 
```

Which then calls "getCustomWriteTarget" in the "TwoStepsConversions" class:

```java	
private Optional<Class<?>> getCustomWriteTarget(Class<?> sourceType) {
		if (DatastoreNativeTypes.isNativeType(sourceType)) {
			return Optional.empty();
		}
		return this.writeConverters.computeIfAbsent(sourceType,
				this::getDatastoreCompatibleType);
	}
```

Note the computeIfAbsent, it may modify the map held in "TwoStepsConversions", which could cause concurrent modification exceptions.;

What would be a good way to go about this? Is this actually intended? Should I make my method synchronized?

**Comment by meltsufin** [comment]
@jroosing It looks like something we should be able to easily fix on our side. Thanks for reporting!
@dmitry-s PTAL.

**Comment by dmitry-s** [comment]
@jroosing 
the fix is in, please reopen if the issue persists
