### ISSUE TITLE
Create a simple Datastore sample app

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1291]

**Comment by ChengyuanZhao** [comment]
Do you mean a codelab ? We have a sample for Datastore in spring-cloud-gcp-data-datastore-sample

**Comment by meltsufin** [comment]
Both actually. We discussed the current sample with @dmitry-s and we thought that it was a bit too complex compared to other samples we have to help people get started. We will rename the current sample to something like "advanced" sample.

**Comment by ChengyuanZhao** [comment]
I see, sounds good.
