### ISSUE TITLE
IAP audience autodetermination does not work on Compute Engine

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#1301]
For AppEngine, IAP autoconfiguration works great.
For Compute Engine and Kubernetes Engine (which runs on Compute Engine), it will fail with message "Service ID expected not to be null". This is because metadata is the wrong place to be getting the Backend Service ID. The right place is...complicated. I've asked IAP team for design guidance.

In the meantime, IAP starter/autoconfig users should provide the correct audience through `spring.cloud.gcp.security.iap.audience` property, overriding automatic determination ([IAP docs](https://cloud.google.com/iap/docs/signed-headers-howto#verify_the_jwt_payload) have guidance on how `aud` claim is composed).

**Comment by meltsufin** [comment]
In the meantime, can we update the refdoc to indicate that the audience determination doesn't work on GCE (App Engine Flex and GKE)?

**Comment by elefeint** [comment]
Removed autoconfig and updated docs in#1293.

**Comment by elefeint** [comment]
Wont-fix; see #1468 for explanation.
