### ISSUE TITLE
JacksonPubSubMessageConverter can't convert Kotlin data class / why I'm receiving empty messages ?

### ISSUE THREAD

**Issue by alexcibotari** [spring-cloud/spring-cloud-gcp#1304]
JacksonPubSubMessageConverter  fail because all fields are mandatory, but sometime I'm receiving empty JSON as message :

``
{}
``

I have 
```
data class AppAction(
  val id: UUID,
  val type: ActionType
) {
}
```

**Comment by meltsufin** [comment]
I guess there are two questions here.

1.  How to handle empty JSON messages.
2.  Why are you getting empty messages in the first place?

For (1), please provide more details on the failure and what you'd prefer to happen instead.
For (2), without having access to the app, it's hard to help. Can you provide a simple example that reproduces the behavior?

**Comment by artembilan** [comment]
I think the point is that provided `ObjectMapper` into the `JacksonPubSubMessageConverter` doesn't support Kotlin.
Please, consider to enable particular module:
```
this.objectMapper.registerModule(new KotlinModule());
```

**Comment by meltsufin** [comment]
@artembilan, how does Spring handle this elsewhere? Can we automatically detect Kotlin in auto-configuration and configure the right module?

**Comment by artembilan** [comment]
We just provide some default customized `ObjectMapper` on the matter.
But the problem here in the `JacksonPubSubMessageConverter` that we can't mutate an external instance. This not what fits a dependency injection rules.

The sample of the proper configuration can be found in the Spring Integration: https://github.com/spring-projects/spring-integration/blob/master/spring-integration-core/src/main/java/org/springframework/integration/support/json/Jackson2JsonObjectMapper.java

So, if @alexcibotari uses Spring Integration  in his project, he can simply call `JacksonJsonUtils.messagingAwareMapper()` and all the modules and other properties are going to be applied to the `ObjectMapper` for the future injections.

Also in Spring Boot the `JacksonAutoConfiguration` does everything for us as well: https://docs.spring.io/spring-boot/docs/2.1.1.RELEASE/reference/htmlsingle/#boot-features-json-jackson

**Comment by meltsufin** [comment]
I forgot that we actually do not autoconfigure the `ObjectMapper`. Our refdoc and examples show something like this:
```java
@Bean
public JacksonPubSubMessageConverter jacksonPubSubMessageConverter() {
    return new JacksonPubSubMessageConverter(new ObjectMapper());
}
```

Maybe, we should instead recommend adding the `spring-boot-starter-json` and relying on the auto-configured `ObjectMapper`?
```java
@Bean
public JacksonPubSubMessageConverter jacksonPubSubMessageConverter(ObjectMapper mapper) {
    return new JacksonPubSubMessageConverter(mapper);
}
```

WDYT?

**Comment by artembilan** [comment]
Yes, that makes sense, but we need to keep in mind that people may use our Pub/Sub module without Spring Boot.
So, we may give a hint that for non-standard behavior the `ObjectMapper` must be supplied with appropriate options or be used from Spring Integration or Spring Boot.

**Comment by alexcibotari** [comment]
I have Jackson-module-Kotlin as dependency in build.gradle
```
implementation "com.fasterxml.jackson.module:jackson-module-kotlin"
```
And I use already existing ObjectMapper
```
@Bean
  fun jacksonPubSubMessageConverter(mapper: ObjectMapper): JacksonPubSubMessageConverter {
    return JacksonPubSubMessageConverter(mapper)
  }
```

**Comment by artembilan** [comment]
Can you confirm that this one is really supplied with the `KotlinModule` during an injection into this `JacksonPubSubMessageConverter`?

**Comment by alexcibotari** [comment]
Hello @artembilan , Yes it is with support of Kotlin

**Comment by alexcibotari** [comment]
I think we can open the issue, maybe it is some strange behavior on my environment.
In case I will fine more details I will open another issue or will reopen the current one.

**Comment by dzou** [comment]
Sounds good. I am currently in the process of writing a Kotlin sample application that uses spring-cloud-gcp as a reference to users. That will likely be able to uncover some problems if any exist with pub/sub + kotlin. I will keep tabs on this issue to see if I can reproduce the problem; let me know if you have additional details.

**Comment by meltsufin** [comment]
@dzou I think it still makes sense to update our documentation to use `spring-boot-starter-json` like I [suggested](https://github.com/spring-cloud/spring-cloud-gcp/issues/1304#issuecomment-445867005). It could be a different issue from this one though.

**Comment by dzou** [comment]
Will do.
