### ISSUE TITLE
Update Pub/sub docs to reference spring-boot-starter-json for Kotlin users

### ISSUE THREAD

**Issue by dzou** [spring-cloud/spring-cloud-gcp#1305]
For users of JacksonPubSubMessageConverter, one must configure the ObjectMapper instance correctly for it to work with Kotlin.

This can be achieved by including spring-boot-starter-json as a dependency and relying on the autowired instance of ObjectMapper when constructing JacksonPubSubMessageConverter.

Details provided in #1304.

**Comment by meltsufin** [comment]
I think it's a good practice, even for Spring Boot applications that don't use Kotlin. So, we should update our Java sample as well to do this.

**Comment by dzou** [comment]
Based on my testing with the Kotlin sample, it turns out Kotlin users do not need to add any special beans to support object serialization with pub/sub. Its likely that the necessary bean is included through some dep.

I will be updating the Kotlin sample to demo this and close this after.
