### ISSUE TITLE
PubSub Protobuf communication example

### ISSUE THREAD

**Issue by alexcibotari** [spring-cloud/spring-cloud-gcp#1309]
Can you please provide examples how to configure PubSub Protobuf communication as alternative for ``JacksonPubSubMessageConverter``

**Comment by meltsufin** [comment]
Pub/Sub uses gRPC which is "Protobuf communication", regardless of the choice of the converter. The converter is only used to convert the message payload, but it still ends up being transferred in a protobuf. If you want to bypass all conversion, just use `ByteString` to represent your payload everywhere.

In any case, the short of it is that you are already using protobufs.
