### ISSUE TITLE
Create profile for Java 11

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#1312]
Per @artembilan's suggestion, create a Java 11 profile in top-level POM.

Changes to make the current codebase work on 11 are in 206422f6b76fefea80b942e0a87764995e75f4a1 .

**Comment by meltsufin** [comment]
@elefeint per conversation with @artembilan, the goal is to leave our source level and compile target at Java 8, but compile with Java 11 JDK. Is this what you were trying to do?

**Comment by elefeint** [comment]
No, I was updating source/target to 11, too. Just compiling with Java 11 is simpler.

**Comment by meltsufin** [comment]
Ok, but apparently that doesn't work either??

**Comment by elefeint** [comment]
Right; because of javac-with-errorprone. Behind that, there is a failing test.

I'll push a fix.

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-cloud/spring-cloud-gcp/commit/07529ad76f056bd20b1007e2cdf666f6e31d1fee
