### ISSUE TITLE
Review and update refdoc for 1.1 release

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1318]
This should be done about a week before the release.

**Comment by ChengyuanZhao** [comment]
check when completing proof reading:

- [ ] cloud foundry
- [ ] config
- [ ] core
- [ ] datastore
- [ ] dependency management
- [ ] getting-started
- [ ] logging
- [ ] memorystore
- [ ] pubsub
- [ ] README 
- [ ] security IAP
- [ ] spanner
- [ ] spring-cloud-gcp / index file
- [ ] spring integration
- [ ] si pubsub
- [ ] si storage
- [ ] spring stream
- [ ] SQL
- [ ] storage
- [ ] trace
- [ ] vision

**Comment by artembilan** [comment]
Re. Cloud Foundry though: https://github.com/spring-cloud/spring-cloud-connectors/issues/248.

The point is to remove remove a `In order for the Cloud SQL integration to work in Cloud Foundry, auto-reconfiguration must be disabled. ` paragraph altogether and don't advertise disabling build-packs.
There might be some other features in the target application, not only just Cloud SQL.

Let's hope that feature is going to be implemented in the Cloud Connectors in time for our 1.1 GA!
