### ISSUE TITLE
Deduplicate content in README.adoc and Refdoc

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1319]
There is a lot of overlap in `/docs/src/main/asciidoc/README.adoc`, which gets used in `/README.adoc`, and the reference document. It should be possible to eliminate most of the content duplication by importing bits of the refdoc into the `README.adoc`.

**Comment by ChengyuanZhao** [comment]
It actually looks like these two files are EXACTLY the same, PR coming soon
