### ISSUE TITLE
Deploying to GAE with properties file containing service account creds file location errors out

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#133]
Caused by: java.io.FileNotFoundException: ***.json (No such file or directory)

If deploying to GAE or GCE, we should probably not use local file system paths. But in theory, we should maybe support creds files on other kinds of resources like classpath files and even GCS?

**Comment by joaoandremartins** [comment]
I'm not too sure what else we should be doing here.

We [already documented](https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-starters/spring-cloud-gcp-starter-core) that in some GCP compute environments, users should rely on the discovered credentials and not use the `credentials-location` property. (Should probably also add something to the reference document)

Should we do anything else to prevent this error?

Magically disregarding user-provided credentials on those environments seems too mystical to me.

OTOH, an error will make it much more visible for users that they must not use the same service account credentials they might have been locally.

I'm tempted to just leave things as-are. @meltsufin @artembilan @saturnism @ludoch WDYT?

**Comment by ludoch** [comment]
What is the context of this error?
Caused by: java.io.FileNotFoundException: ***.json (No such file or directory)
Sample?

**Comment by meltsufin** [comment]
Ultimately we should support classpath and GCS resources for `credentials-location`. Naturally, if you reference a local file, and the file is not there on the server when you deploy, you'll get `FileNotFoundException`.

**Comment by joaoandremartins** [comment]
@ludoch this is related to what you reported the other day. If you deploy a Spring Boot app with a `credentials-location` property to GAE, the credentials won't be found on the GAE instance file system.

@meltsufin indeed, so since we documented this, would you agree no more action is required?

**Comment by meltsufin** [comment]
Correct, the only potential action is to create an issue to track support for other sources besides the local filesystem for `credentials-location`.

**Comment by joaoandremartins** [comment]
That already happens for all the possible [Spring Resource locations](https://docs.spring.io/spring/docs/current/spring-framework-reference/html/resources.html#resources-implementations).

The case with GCS is awkward because the act of getting the credentials from GCS itself requires credentials. If you feel strongly about that use case, feel free to open a new issue.
