### ISSUE TITLE
Add starter to add healthchecks to a webapp

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#134]
This would be especially useful for Spring Boot apps to be deployed in GAE Flex. Currently, if an app doesn't have a healthcheck endpoint set up, Flex deployments will run until they time out, which can take a really long time.

It appears that Spring Actuator might help setting up a healthcheck endpoint on a custom URL (i.e., not the default one).

**Comment by meltsufin** [comment]
I think by default, Spring Boot simply returns HTTP 404 on requests to `/_ah/health`, and that should be OK for health checks, but we might want more meaningful health check responses.

**Comment by joaoandremartins** [comment]
What do you mean 404 should be OK for health checks?

The end goal here would be to come up with an "App Engine-friendly" config that would allow you to deploy a Spring Boot app without having to disable deployment health checks.

**Comment by meltsufin** [comment]
From: https://cloud.google.com/appengine/docs/flexible/python/how-instances-are-managed
> You do not have to do anything special to implement health checking. If your app does not handle health checks, a HTTP 404 response is interpretated as a successful reply.
> 
> You can write your own custom health-checking code. It should reply to /_ah/health requests with a HTTP status code 200. The response must include a message body, however, the value of the body is ignored (it can be empty).

**Comment by joaoandremartins** [comment]
Hmm I was just able to deploy my Spring Boot app to Flex without any special health check treatment, so my initial diagnosis must have been wrong.

At this point, I'll need to look and see if there is any structure to health check responses, or if's just a trivial response. If the latter, this issue can probably be obsoleted.
