### ISSUE TITLE
Datastore findByX always expects a list returned

### ISSUE THREAD

**Issue by JamieCressey** [spring-cloud/spring-cloud-gcp#1350]
Version: 1.1.0.RC2
JDK: 8
Spring Boot Version: 2.1.1.RELEASE
---

I have a repository which looks like;

```
public interface UserRepository extends DatastoreRepository<User, String> {
    Optional<User> findOneByUsername(String username);
}
```

When calling `findOneByUsername` I expect a max of one record to be returned. In actual fact, a list is being returned and I get this error;

```
Unable to convert class java.util.ArrayList to class io.jacent.api.model.User
```

I have also tried `findByUsername` (which the Spring Data docs say should be fine given the return value is singular) with the same results. The expected behaviour is demonstrated when using a JPA repository.

**Comment by JamieCressey** [comment]
Understood. To better match other implementations, should it, or could it,
throw a `IncorrectResultSizeDataAccessException` if the return value is
defined as a singular, or findOneBy is used, in the repository interface
but more than one document is returned from the query?

**Comment by ChengyuanZhao** [comment]
@JamieCressey I think that's a good idea. In fact in the GQL query method (those annotated `@Query`) we do such a check and do throw such an exception. We should add a similar check for this part-tree query method too.
