### ISSUE TITLE
[Spring Integration, PubSub] A lot of expired messages when using Spring Integration with PubSub 

### ISSUE THREAD

**Issue by mikebocian** [spring-cloud/spring-cloud-gcp#1351]
Hi devs!

We decided to use Google PubSub together with Spring Integration in the same way, as it is written here: https://github.com/spring-cloud/spring-cloud-gcp/blob/b5c1fc456fb5af710b5d91c8a40c0d1642eaa9a7/spring-cloud-gcp-samples/spring-cloud-gcp-integration-pubsub-sample/spring-cloud-gcp-integration-pubsub-sample-receiver/src/main/java/com/example/ReceiverApplication.java

Context:
After running an application successfully for over a month (with average message processing ~20msg/s), we had to redeliver ~700k messages to the application. Let's call this operation _a rewind_. So PubSub was populated with 700k of messages and the undelivered message count was pretty big. The whole _rewind_  according to statistics above should lasts ~4h. 

Setup: 
Topic: Simple PubSub topic
Subscription: ackDeadline: 100s
Message retention: 7days
Libs: latest
Configuration: the same as in the sample

Problem:
It turns out, that yes, application processes 50msg/s (which is application max) but PubSub's undelivered messages count melts on average ~15msg/s. When looking on PubSub statistics it can be seen, that there is a lot of expired messages https://imgur.com/a/mvxyrnz but what is interesting, on average they sum to 50msg/s. So it turns out, that the application is processing 50msg/s ( each message is processed within 10s ) but somehow, these messages are not *ack*ed. Only 15msg/s are acked, the rest is expired ( even if the application *ack*ed them ).

In the end, _the rewind_ lasts about much longer, we processed 3.5mln messages instead of 700k and after long debugging I still don't know *_why_*.

 I know, that PubSub can redeliver messages and that the order is not deterministic. I am sure, the situation we experienced is not something usual. 

Do you know what is the reason?

**Comment by elefeint** [comment]
Good catch! That's the greedy subscriber problem -- each subscriber connection gets a buffer of 10Mb messages. It is described in more detail in the PubSub client library project (googleapis/google-cloud-java#3152).
We have a MessageSource for synchronous pull in the works in #1321 ; once it gets submitted, it might come in useful if you want to go back to Spring Integration.

**Comment by mikebocian** [comment]
Ok then! Good to know that this was not our bug. I would be happy to go back to Spring Integration, but knowing the realities of software development, I bet that we will stay with the PubSubTemplate.

**Comment by elefeint** [comment]
That's fair. I'll close this issue; glad that synchronous pull works well for you.
