### ISSUE TITLE
Version conflicts with Lognet grpc-spring-boot-starter

### ISSUE THREAD

**Issue by kbhattac** [spring-cloud/spring-cloud-gcp#1358]
I need to use `@GRpcService` annotation in my application, which also uses `spring-cloud-gcp-starter-trace` `Greenwich.M3` release. When I add the LogNet dependency below, I get the following conflicts when I compile my app:
```
<dependency>
    <groupId>io.github.lognet</groupId>
    <artifactId>grpc-spring-boot-starter</artifactId>
    <version>3.0.0</version>
</dependency>
```
`
Could not resolve version conflict among [org.springframework.cloud:spring-cloud-gcp-starter-trace:jar:1.1.0.M3 -> io.zipkin.gcp:zipkin-sender-stackdriver:jar:0.8.3 -> io.grpc:grpc-core:jar:1.15.1, org.springframework.cloud:spring-cloud-gcp-starter-trace:jar:1.1.0.M3 -> io.zipkin.gcp:zipkin-sender-stackdriver:jar:0.8.3 -> io.grpc:grpc-protobuf:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, org.springframework.cloud:spring-cloud-gcp-starter-trace:jar:1.1.0.M3 -> io.zipkin.gcp:zipkin-sender-stackdriver:jar:0.8.3 -> io.grpc:grpc-protobuf:jar:1.15.1 -> io.grpc:grpc-protobuf-lite:jar:1.15.1 -> io.grpc:grpc-core:jar:1.15.1, org.springframework.cloud:spring-cloud-gcp-starter-trace:jar:1.1.0.M3 -> com.google.cloud:google-cloud-core-grpc:jar:1.56.0 -> io.grpc:grpc-netty-shaded:jar:1.16.1 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1], org.springframework.cloud:spring-cloud-gcp-starter-trace:jar:1.1.0.M3 -> com.google.cloud:google-cloud-core-grpc:jar:1.56.0 -> io.grpc:grpc-stub:jar:1.16.1 -> io.grpc:grpc-core:jar:1.16.1, org.springframework.cloud:spring-cloud-gcp-starter-trace:jar:1.1.0.M3 -> com.google.cloud:google-cloud-core-grpc:jar:1.56.0 -> io.grpc:grpc-auth:jar:1.16.1 -> io.grpc:grpc-core:jar:[1.16.1,1.16.1], io.github.lognet:grpc-spring-boot-starter:jar:3.0.0 -> io.grpc:grpc-netty:jar:1.15.1 -> io.grpc:grpc-core:jar:[1.15.1,1.15.1]]
`
[pom.xml](https://storage.googleapis.com/share-it/pom.xml)

Please suggest how to resolve this.

**Comment by meltsufin** [comment]
The conflict seems to be around the version of `grpc-core`, which is being brought in by lognet through the `grpc-netty` dependency.
Try excluding it:
```xml
                <dependency>
                        <groupId>io.github.lognet</groupId>
                        <artifactId>grpc-spring-boot-starter</artifactId>
                        <version>3.0.0</version>
                        <exclusions>
                                <exclusion>
                                        <groupId>io.grpc</groupId>
                                        <artifactId>grpc-netty</artifactId>
                                </exclusion>
                        </exclusions>
                </dependency>
```

Also, you should be able to use `Greenwhich.RC2` at this point.

Please let us know if this works. Thanks!

**Comment by kbhattac** [comment]
Yes it does! 
I fixed it by adding it to dependency management: 
```
			<dependency>
				<groupId>io.grpc</groupId>
				<artifactId>grpc-core</artifactId>
				<version>1.16.1</version>
			</dependency>
```
https://github.com/kbhattac/CoolRetailer/blob/d3b640ad3bba57c998506658758bcd64960b41f7/src/dataservice/pom.xml#L100

Thanks
