### ISSUE TITLE
Demonstrate use of roles in the IAP sample app

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1371]
Currently, the IAP sample shows how to restrict access to certain URLs based on whether the user is authenticated using IAP. However, in practice, this is not very useful, because IAP will not even let the user access the application if they are not authenticated.

It would be more interesting to show how to extract or assign a role to the user and allow only users with specific roles to access certain areas of the application.

For example, the sample app could have a config property that specifies the user who will be assigned the `ADMIN` role through the `UserDetailsService`, and then an HTTP endpoint that would only be accessible to the admin.

**Comment by elefeint** [comment]
I'll close this issue, and we'll reopen in the new repo if/when IAP supports built-in roles.
