### ISSUE TITLE
Spanner : Trasnactions + updates to table 

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1377]
Hi @ChengyuanZhao  

We have a usecase where we have to read the data and update values on the row. 
1)Can you confirm what kind of locking is done for Read transactions vs update transactions ?
2)Is it possibel to specify for an update to fail if the last updated value on teh current row to update has elapsed teh value the user can provider. It falls in sync with versioning column on db if we use

**Comment by vineela-gampa** [comment]
@meltsufin  @ChengyuanZhao

**Comment by meltsufin** [comment]
@vineela-gampa Have you seen [this](https://cloud.google.com/spanner/docs/transactions) documentation? Does it answer your question?

**Comment by vineela-gampa** [comment]
@meltsufin Yes it does
To retierate 

For read only transactions there are no locks. Its purely used when we need to query data at the same timestamp.

For read-write transactions it does hold lock. For reads it holds shared locks  and upgrades to exclusive lock during write. 

Is it possibel to specify for an update to fail if the last updated value on the current row to update has elapsed the value the user can provider. It falls in sync with versioning column on db if we use ?

**Comment by meltsufin** [comment]
@ChengyuanZhao Do you know? It's more of a Spanner product question, I guess. Probably not the best forum to ask.

**Comment by ChengyuanZhao** [comment]
@vineela-gampa 
For your remaining question 2) you cannot set up some sort of trigger or stored proc to cause a fail or something like that. Instead, in your update transaction you can actually see the live state of that data or versioning column. You will see the newest version of some column even if your update transaction on it started after the start of some other transaction and that other transaction committed sometime during this update transaction.

**Comment by vineela-gampa** [comment]
@ChengyuanZhao Do you mean to check manually on our side to first read and verify ? or spanner framework already supports it ?

**Comment by ChengyuanZhao** [comment]
@vineela-gampa Currently  we leave it to the user to check the version during the transaction. However, I'm currently working on adding entity listeners/callbacks, which I think could be used to reduce some code repetition. #1283

**Comment by vineela-gampa** [comment]
Got it would be helpful.
