### ISSUE TITLE
String type as identity in DataStore is not working correctly

### ISSUE THREAD

**Issue by nickname110** [spring-cloud/spring-cloud-gcp#1390]
String type as identity in DataStore is not working correctly.

> @Entity
> public class Entity {
> 	@Id
> 	private String id;
> }

> Entity entity = new Entity();
> entityRepository.save(entity);
> entityRepository.findById(entity.getId()); //<----- EMPTY!

This is because DatastoreServiceObjectToKeyFactory generate wrong Key!
```
Actual: Key{projectId=myprojectID, namespace=, path=[PathElement{kind=entities, id=null, name=5657818854324128}]}
Expected: Key{projectId=myprojectID, namespace=, path=[PathElement{kind=entities, id=5657818854324128, name=null]}
```

**Comment by dmitry-s** [comment]
Thanks for reporting the issue!

Datastore only supports allocation for Long ids. We will add a check to verify that String ids are not null on save and will throw an exception otherwise.

**Comment by chaurasiyashikhar** [comment]
I am first time using Spring data store, in Entity class i have added @Id annotation in String field, when i am running the application i am getting below issue -
 "message": "Cloud Datastore can only allocate IDs for Long and Key properties. Cannot allocate for type: class java.lang.String",
    "trace": "org.springframework.cloud.gcp.data.datastore.core.mapping.DatastoreDataException: Cloud Datastore can only allocate IDs for Long and Key properties

i am using 1.1.1.RELEASE version for spring-cloud-gcp-starter-data-datastore artifact Id.

**Comment by ChengyuanZhao** [comment]
@chaurasiyashikhar 

We do support string IDs ;  could you share your entity class and some code around your entities and usage?

**Comment by chaurasiyashikhar** [comment]
@Entity(name = "PageData")
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class PageData {
    
    @Id
    private String pageDataKey;
========================
@Component
public class PageDataStoreImpl implements PageDataRepository {

    public PageGcpRepository pageGcpRepository;

    public PageDataStoreImpl(PageGcpRepository pageGcpRepository){
        this.pageGcpRepository = pageGcpRepository;
    }

    @Override
    public PageData save(PageData pageData) {
        return pageGcpRepository.save(pageData);
    }
==========================
PageGcpRepository is interface which is extending DatastoreRepository<PageData, String>

**Comment by ChengyuanZhao** [comment]
@chaurasiyashikhar my apologies, I misread your question. 

Indeed we can only allocate keys for Long and Key types and NOT for string. The reason is that Cloud Datastore only generates Long values when allocating keys. (they look like random numbers). It will not generate a random string for a key.

**Comment by chaurasiyashikhar** [comment]
@ChengyuanZhao 

https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/Singer.java

How this is working ?

**Comment by ChengyuanZhao** [comment]
@chaurasiyashikhar  You can use String IDs if you set it yourself. However if you leave it null we/Cloud Datastore cannot allocate one for you.

**Comment by chaurasiyashikhar** [comment]
@ChengyuanZhao Got it, working now. Thanks
