### ISSUE TITLE
Unable to exclude a list of embedded entities from indexes using the `@Unindexed` annotation

### ISSUE THREAD

**Issue by stevebakh** [spring-cloud/spring-cloud-gcp#1418]
When persisting an entity with a field containing a list of embedded entities, it is not possible to apply the `@Unindexed` annotation. When doing so, the following exception is thrown:

```
...
Caused by: com.google.datastore.v1.client.DatastoreException: Exclude from indexes cannot be set on a list value
...
```

Example entity:

```
@Entity
public class Entity {
    @Id private String id;
    @Unindexed private List<EmbeddedEntity> embeddedEntities;

    public static class EmbeddedEntity {
        private String name;
    }
}
```

I think it would be useful to have the library detect when the annotation is applied to a list value and apply the exclude from indexes property as appropriate to each of the list value's items.

I can achieve what I want by applying the `@Unindexed` annotation to each of the embedded entity's fields, however, this can be a little cumbersome.

**Comment by meltsufin** [comment]
@ChengyuanZhao @dmitry-s PTAL

**Comment by ChengyuanZhao** [comment]
Thank you for this suggestion! We appreciate this and will look into potentially implementing something to make that annotation's behavior on embedded entities more intuitive.

**Comment by ChengyuanZhao** [comment]
It looks like this applies to all ListValue properties and not just embedded entity values. In fact the Datastore/client lib takes care of unindexing everything inside an embedded entity, so from our perspective we just need to go into the ListValue and unindex each item. I'll put up a PR shortly.
