### ISSUE TITLE
Spring boot actuator health end point integration for Datastore - spring-cloud-gcp-data-datastore

### ISSUE THREAD

**Issue by nsrags** [spring-cloud/spring-cloud-gcp#1423]
We have inbuilt support from Spring boot actuator to know health of databases for  Mongo ,Casandra,Redis,Liquibase etc . 

Can you enable health indicator for GCP data store in  Spring boot actuator  project ? 

Project: spring-cloud-gcp-data-datastore 
Reference : https://github.com/spring-projects/spring-boot/tree/master/spring-boot-project/spring-boot-actuator 
Reference Classes of Spring Boot Actuator : LiquibaseEndpoint.java, CassandraHealthIndicator.java, RedisHealthIndicator.java,RedisHealthIndicatorAutoConfiguration.java 

Let me know if any questions from your side.

**Comment by meltsufin** [comment]
@nsrags Thanks for the feature suggestion. Looking at the [Actuator docs](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_writing_custom_healthindicators), it looks like it's just a matter of implementing the `HealthIndicator` for Cloud Datastore and registering the bean in our Datastore auto-configuration `GcpDatastoreAutoConfiguration`.
If you have some code already, we would welcome a pull request. Thanks!

**Comment by nsrags** [comment]
@meltsufin  
 We tried pull tried pull request , couldn't succeed. Please find the attached code for Data store actuator.  
[Cloud_Datastore_Actuator.zip](https://github.com/spring-cloud/spring-cloud-gcp/files/2827194/Cloud_Datastore_Actuator.zip)

**Comment by meltsufin** [comment]
Hi @nsrags, have you tried creating a fork and doing a pull request from there?
See: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by nsrags** [comment]
I am not able format code according to  google check style ( eclipse-java-google-style.xml ) . I tried to format code but couldn't format with in google check style standards. Can you help ? 

spring-cloud-gcp\spring-cloud-gcp-data-datastore\src\main\java\org\springframework\cloud\gcp\data\datastore\core\mapping\DatastoreDataException.java:29: Line has leading space characters; indentation should be performed with tabs only. [RegexpSinglelineJava]
[ERROR] \spring-cloud-gcp\spring-cloud-gcp-data-datastore\src\main\java\org\springframework\cloud\gcp\data\datastore\core\mapping\DatastoreDataException.java:30: Line has leading space characters; indentation should be performed with tabs only. [RegexpSinglelineJava]
[ERROR] \spring-cloud-gcp\spring-cloud-gcp-data-datastore\src\main\java\org\springframework\cloud\gcp\data\datastore\core\mapping\DatastoreDataException.java:31: Line has leading space characters; indentation should be performed with tabs only. [RegexpSinglelineJava]

**Comment by meltsufin** [comment]
This project uses Spring code style. Checkout: https://github.com/spring-cloud/spring-cloud-gcp/blob/master/CONTRIBUTING.adoc.

**Comment by nsrags** [comment]
@meltsufin 
This the pull request. Can your review ?
https://github.com/spring-cloud/spring-cloud-gcp/pull/1457
