### ISSUE TITLE
Async Non IO blocking calls spring-cloud-gcp-data-datastore

### ISSUE THREAD

**Issue by nsrags** [spring-cloud/spring-cloud-gcp#1424]
We enabled Objectify to connect Data store currently. We have plans to migrate spring-cloud-gcp-data-datastore  in the future.

Is there any way to call GCP data store Asynchronously(Non IO blocking calls)  spring-cloud-gcp-data-datastore ?  If no,Can you provide 

Reference : Objectify implementation 
https://github.com/objectify/objectify/wiki/BasicOperations 
ofy().save().entity(thing1);         // asynchronous
ofy().save().entity(thing1).now();   // synchronous

**Comment by meltsufin** [comment]
The Cloud Datastore Client library on which our Spring Data Cloud Datastore integration is built does not seem to support asynchronous operations. See: https://github.com/googleapis/google-cloud-java/issues/493.
Objectify is also built on top of the same library. So, is `ofy().save().entity(thing1)` really asynchronous? @ChengyuanZhao I think you looked into this and it didn't look like it was truly async.

GRPC itself supports non-blocking operations. So, theoretically it's possible to implement. Perhaps, we can add some asynchronous variants to our `DatastoreTemplate` by dropping down to the GRPC level API.

Longer term plan is to support reactive Spring Data APIs which would be non-blocking.

**Comment by ChengyuanZhao** [comment]
I took a look into Objectify's implementation and for example the write-operations ultimately are described in Objecty's  javadoc in `AsyncDatastoreReaderWriterImpl` as a preparation for when the underlying client lib gives real async support. Looking at the code that looks like what is happening (the write is synchronous but given in the facade of a `Future`).

**Comment by eugenekup** [comment]
> The Cloud Datastore Client library on which our Spring Data Cloud Datastore integration is built does not seem to support asynchronous operations. See: [googleapis/google-cloud-java#493](https://github.com/googleapis/google-cloud-java/issues/493).

The GCP Datastore does support async calls (albeit not in the same fashion as e.g. MongoDB driver does) and it is possible to fire multiple async requests and then block on the .get() method later on when you need it: https://cloud.google.com/appengine/docs/standard/java/datastore/async

This is also a recommended way of using Datastore:

> Use asynchronous calls where available instead of synchronous calls. Asynchronous calls minimize latency impact. For example, consider an application that needs the result of a synchronous lookup() and the results of a query before it can render a response. If the lookup() and the query do not have a data dependency, there is no need to synchronously wait until the lookup() completes before initiating the query.

From [Best Practices](url=https://cloud.google.com/datastore/docs/best-practices)

**Comment by ChengyuanZhao** [comment]
@eugenekup We are using the Cloud Datastore API, not the Appengine Datastore API.

**Comment by meltsufin** [comment]
Closing because we currently don't have plans to add async support for Datastore. Instead, we're focusing on adding reactive support for Firestore Native.

**Comment by mmalygin** [comment]
any plans to add this feature?
