### ISSUE TITLE
Datastore template save methods don't need to return entities

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#1427]
Currently `save` and `saveAll` methods return exactly the same entities that are passed as arguments. This might be confusing for users. It seems that the methods should not return anything (for clarity).

**Comment by meltsufin** [comment]
...Or they can return the Datastore `Entity`, if we think it's useful.

**Comment by meltsufin** [comment]
Closing following team discussion.
