### ISSUE TITLE
Travis tests produces errors regarding lack of GOOGLE_APPLICATION_CREDENTIALS but still passes

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#143]
It seems like the unit tests are producing a lot of exceptions due to dependence on Google Credentials.  Yet all the tests are still passing.  Should all of them use mock credentials?

```
Running org.springframework.cloud.gcp.core.autoconfig.GcpContextAutoConfigurationTests
Sep 11, 2017 1:52:10 AM org.springframework.context.annotation.AnnotationConfigApplicationContext prepareRefresh
INFO: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@35851384: startup date [Mon Sep 11 01:52:10 UTC 2017]; root of context hierarchy
Sep 11, 2017 1:52:12 AM org.springframework.cloud.gcp.core.autoconfig.GcpContextAutoConfiguration googleCredentials
SEVERE: No credentials were found.
java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:116)
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:103)
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:76)
	at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:54)
	at org.springframework.cloud.gcp.core.autoconfig.GcpContextAutoConfiguration.googleCredentials(GcpContextAutoConfiguration.java:88)
	...
```

**Comment by meltsufin** [comment]
Our Travis tests don't do any remote API calls. So, they don't need credentials. The problem is probably that we don't catch this `IOException` in the auto-config. @joaoandremartins Can you take a look?

**Comment by artembilan** [comment]
I think some new test doesn't provide `mock(CredentialsProvider.class)`.
Or... there is just need `@SpringBootApplication(exclude = GcpContextAutoConfiguration.class)` do not load default `CredentialsProvider` configuration at all. Because right, Travis can't deal with that.

**Comment by joaoandremartins** [comment]
I don't understand why the tests aren't failing. I suspect it's because the Spring context only logs the exceptions but doesn't actually throw them. Since we never need to use credentials anyway, we never get to a point where the code actually fails.

#144 provides mock credentials so the tests no longer fail.
