### ISSUE TITLE
Clarify naming conventions for Maven artifacts

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1436]
Many developers who are getting started with the project seem to get confused by similarly named Maven artifacts. For example, `spring-cloud-gcp-pubsub` and `spring-cloud-gcp-starter-pubsub`. We should create a list of all published Maven artifacts and what they are in our reference documentation.

**Comment by artembilan** [comment]
For some source of truth https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/htmlsingle/#using-boot-starter

**Comment by dzou** [comment]
I have a good idea where to put this; I am thinking of revamping our [Getting Started](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.1.0.RELEASE/single/spring-cloud-gcp.html#_getting_started) section to be more comprehensive and useful.

**Comment by meltsufin** [comment]
@dzou Sounds good!
