### ISSUE TITLE
Documentation on how to deploy this to App Engine

### ISSUE THREAD

**Issue by connor-mcshane** [spring-cloud/spring-cloud-gcp#1447]
Hi All,

I have been trying to deploy this to App Engine but I am not sure what are the correct build steps to deploy it to GCP.

Does anyone know and would be willing to add some info to the README on how to?

*****edit****
More specifically, it would be beneficial to know the steps on deploying one of the samples to GCP from this repository. E.g cloning the repository, changing application properties, setting up the project in GCP and then running mvn clean package, mvn appengine:deploy etc 

Thanks

**Comment by dzou** [comment]
Hi Connor,

Deploying a Spring Boot Application to App Engine is most easily done with the [App Engine Maven plugin](https://cloud.google.com/appengine/docs/flexible/java/using-maven). You can try following the [codelab here](https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..index#0).

**Comment by meltsufin** [comment]
I think it's actually a fair point that we should have some documentation in our refdoc on how to deploy to GCP, or at least link to the docs that explain it.

**Comment by dzou** [comment]
@meltsufin - Any suggestions for the best place to add the information? I am considering putting it in *Getting Started* section and modifying the doc so it answers how to get started more generally (what dependencies are needed, learning how to use it, deploying, etc.)

**Comment by meltsufin** [comment]
I think it could fit there.

**Comment by connor-mcshane** [comment]
Hi, thanks for you replies. Where I am especially getting stuck is with the parent POMs etc.

So what I have been trying to do is modify the spring-cloud-gcp-data-spanner-sample and deploy it to an app engine flex instance.

When I try to run  mvn appengine:deploy, I get a failure with the checkstyle plugin.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.0.0:check

**Comment by connor-mcshane** [comment]
> Hi Connor,
> 
> Deploying a Spring Boot Application to App Engine is most easily done with the [App Engine Maven plugin](https://cloud.google.com/appengine/docs/flexible/java/using-maven). You can try following the [codelab here](https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/index.html?index=..%2F..index#0).

It seems to be a huge step from the code lab to being able to deploy one of  the sample projects. I am mostly getting confused with the nested Parent POM.xml file references and the dependencies.

**Comment by meltsufin** [comment]
So, yes, the samples in the project are tightly coupled to the project itself and we run checks on the code like checkstyle. The samples are designed more for reading and copying the relevant bits to your own Spring Boot project. You can create your own Spring Boot project using http://start.spring.io and select "GCP Support". For deploying to App Engine, check out this codelab: https://codelabs.developers.google.com/codelabs/cloud-app-engine-springboot/.

**Comment by connor-mcshane** [comment]
Hi @meltsufin , thanks for your reply. Okay yes, my end goal is to have an individual project, with one pom.xml file that has the capabilities of one of the sample projects.

Would it be better to try one of the starter projects? They do still have a parent reference to another pom.xml.

Or 

Try and create a project from scratch using the Spring initializer and adding dependencies to the pom.xml and praying :)

**Comment by dzou** [comment]
Hi @connor-mcshane, I ended up rewriting Getting Started section of our docs (with PR #1463) to help with clarifying this. This will beefs up information about project dependency setup and also references tutorials for deploying Spring applications to GKE and AppEngine. Hopefully starting up a new project with Spring Cloud GCP is clearer with these docs. Let me know if this helps!
