### ISSUE TITLE
Consider making `logging` a separate artifact

### ISSUE THREAD

**Issue by stevenschlansker** [spring-cloud/spring-cloud-gcp#1448]
Currently, if you want to use GCP Stackdriver logging, you must include the whole `autoconfigure` artifact due to https://github.com/spring-cloud/spring-cloud-gcp/pull/346.
It would be nice to be able to use the feature independently, and manually configured.  Forcing users to use autoconfigure and get all the features together is unfortunate.

**Comment by meltsufin** [comment]
Are you using API or JSON-based logging?
You do have the option of disabling the auto-configuration with `spring.cloud.gcp.logging.enabled=false`.
In any case, I think it's a valid suggestion.

**Comment by stevenschlansker** [comment]
I'm trying to do JSON based logging.  I was surprised that the out of the box Google libraries did not have a functioning setup -- the resource labels are not all filled in appropriately on GKE -- so I've been evaluating this code instead.

**Comment by dsyer** [comment]
Autoconfiguration is always optional - you don't have to use it. It's a pretty fine balance, but we prefer usually to keep features together if they are related, even if they are optional. The discussion about programming models not involving autoconfiguration should take place elsewhere really (like with the Spring Boot team), but I'm sure it would be interesting to hear your analysis beyond the throwaway comment.

**Comment by stevenschlansker** [comment]
I don't want to get dragged into a religious war 😸 just want to make sure features work independently as well as together.  For what it's worth, we use Jackson over Gson -- so I ended up just borrowing the code and adapting it directly to my needs.  So if nobody else wants it split out, I consider my needs fulfilled for the moment (although we'd gladly ditch our copy if possible down the road).

**Comment by dsyer** [comment]
There’s nothing religious about autoconfiguration, I promise you. It has always been optional by design, even if it is what most people use in practice. There are a couple of active efforts looking for more convenient “a la carte” programming models even (see this recent [blog](https://spring.io/blog/2019/01/21/manual-bean-definitions-in-spring-boot) and the [Spring Fu](https://github.com/spring-projects/spring-fu) project for instance).
