### ISSUE TITLE
Using Cloud DataStore on AppEngine Standard

### ISSUE THREAD

**Issue by kdabir** [spring-cloud/spring-cloud-gcp#1458]
Using `spring-cloud-gcp-data-datastore` in a Spring Boot based AppEngine Standard project requires us to specify `project-id` and credentials file, which is redundant for AppEngine Standard environment. 

Further when developing locally, I really want to connect to local datastore emulator (that comes with appengine-sdk java8) rather than having to connect to DataStore over network.

This issue is a request to provide a more convenient way to use `spring-cloud-gcp-data-datastore` under AppEngine Standard.

**Comment by ChengyuanZhao** [comment]
@kdabir The module is intended for Cloud Datastore (the stand-alone service) instead of the legacy app-engine Datastore. 
We actually recently implemented emulator support: https://github.com/spring-cloud/spring-cloud-gcp/pull/1445

**Comment by dzou** [comment]
Yes indeed, if you build off our latest snapshot (1.2.0), you can connect to emulator by adding the `spring.cloud.gcp.datastore.emulator-host` property to your `application.properties` file - i.e. `spring.cloud.gcp.datastore.emulator-host=localhost:8081`.

Our snapshots are published to the Spring Snapshots repo: https://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-gcp/1.2.0.BUILD-SNAPSHOT/

@ChengyuanZhao as far as the AppEngine support, is there a way we can infer credentials on our end for convenience? Or is it not really possible?

**Comment by meltsufin** [comment]
We do not plan to support the App Engine Datastore. Closing.
