### ISSUE TITLE
Add more examples to spring-cloud-gcp-examples

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#146]
- [x] Trace
- [x] CloudSQL
- [ ] Pub/Sub
- [x] Spring Integration w/ Pub/Sub

**Comment by meltsufin** [comment]
Let's create separate issues for the remaining ones and just close this one.

**Comment by joaoandremartins** [comment]
After #168 which should be very close to be merged, this issue can be for the last Pub/Sub code sample, which I'm planning to finish today!
