### ISSUE TITLE
Create a sample app that exposes a GRPC service

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1462]

**Comment by elefeint** [comment]
[Sample app](https://github.com/spring-cloud/spring-cloud-gcp/tree/grpc-spanner-sample/spring-cloud-gcp-samples/spring-cloud-gcp-grpc-spanner-sample) available on `grpc-spanner-sample` branch.

Putting this issue on hold for now.

**Comment by meltsufin** [comment]
Leaving the sample app in a branch and closing this for now.
