### ISSUE TITLE
SingleUse reads causes a session leak

### ISSUE THREAD

**Issue by damjan-gjurovski** [spring-cloud/spring-cloud-gcp#1474]
Using the `findById` method of the spring data spanner project causes the app to block after the method has been called the same time as the maximum number of spanner sessions. Upon further investigations, it looks like the problem is in the `org.springframework.cloud.gcp.data.spanner.core.SpannerTemplate`,  where a session is opened on line 414 and another session is opened on line 417. Further method calls only use the second session, which is closed properly after the read is completed, but the first session leaks and is never closed, causing the app to exhaust the session pool.

To recreate the problem, set the `maxSessions` to 100 (or even lower) and call the `findById` 101 times

The spring-cloud-gcp-data-spanner version in use is 1.1.0.RELEASE

**Comment by damjan-gjurovski** [comment]
I just took a look at the code on master and, without testing it, it seems that the problem still persists (line 445-450)

**Comment by ChengyuanZhao** [comment]
@damjan-gjurovski thank you for this issue! looking into it now
