### ISSUE TITLE
Consider to use java-cfenv for better responsibility distinguishing when we parse VCAP_SERVICES

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-gcp#1479]
The logic is handled in the `GcpCloudFoundryEnvironmentPostProcessor`.

See more info in the https://spring.io/blog/2019/02/15/introducing-java-cfenv-a-new-library-for-accessing-cloud-foundry-services

**Comment by meltsufin** [comment]
This is nice!
