### ISSUE TITLE
spanner array(struct) vs regular query performance

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1487]
HI  @meltsufin  @ChengyuanZhao we want to hear your inputs on is using array efficient for high perofrmance vs regular query ?
Recently i heard that array(struct) shouldnt be used and its memory intensive. Can you confirm ?

**Comment by ChengyuanZhao** [comment]
@vineela-gampa I can definitely see that being the case. I would check with the client library team (available here https://github.com/googleapis/google-cloud-java). 

Just wanted to add that we have lazy-loading interleaved child properties now for performance, so perhaps that can offset some of the joining-and-selecting-children-as-structs that you mentioned in the past .

**Comment by vineela-gampa** [comment]
@ChengyuanZhao  thanks for confirming. Would it be the case where parent has only one level child and each there are no more than 10 childs at any point of time ?

**Comment by ChengyuanZhao** [comment]
I am closing this issue; please direct this question about query performance on spanner to Cloud Spanner directly if this is still ongoing.
