### ISSUE TITLE
this.datastoreTemplate.findById not finding the descendent child record 

### ISSUE THREAD

**Issue by Vinooj** [spring-cloud/spring-cloud-gcp#1488]
I have a Parent/Child relationship modeled as follows using @Descendants

@Entity(name = "parent")
public class Parent {
        @Id
        Long id;

        @Descendants
        Set<Child> children;

        public void setChildren(Set<Child> child) {
                this.children = child;
        }
}

@Entity(name = "child")
public class Child {
        @Id
        Key id;

        String name;
}

I first create a parent and then create a child using the following service 
Note: This works. I am able to create the Child record.

@RequestMapping(value = "/parents/{id}/children/{childId}", method = RequestMethod.POST)
public ResponseEntity<Subject> saveChild(@PathVariable Long id, @PathVariable Long childId,
                                             @Valid @RequestBody Child child) throws URISyntaxException {
        Parent parent = this.datastoreTemplate.findById(id, Parent.class);
        parent.setChildren(new HashSet<>(Arrays
                .asList(new Child(child.getName()))));
        parent = parentRepository.save(parent);
}

I'm able to see the Child record created above using childRepository.findAll();

ISSUE: However I'm not able to query the Child record using 
-------------------------------------------------------------
Child child = this.datastoreTemplate.findById(childId, Child.class); //Null or empty
where childId is a long.

Appreciate any help.

Thanks

**Comment by ChengyuanZhao** [comment]
@Vinooj Child ID **must** be a Key instead of a long. The reason is that a plain long child ID (without the ancestor parent specified in the Key) is considered a distinct key from full Key ID value (that does refer to the parent's id value). They are two separate entities with different key values from Datastore's perspective.

**Comment by meltsufin** [comment]
@ChengyuanZhao Can we do this kind of validation automatically when one uses `@Descendants` to provide a helpful error message?

**Comment by ChengyuanZhao** [comment]
@meltsufin  we currently disallow storing any child descendants with a non-Key ID type.

However the question here is about going back completely unaware of the original child instance and looking it up with any given key value. Remember in Datastore the entire Kind is not subjugated to being a descendant of another Kind. Descendant relationships are by-entity/row and can even occur between entities of the same kind or between two kinds in opposite directions.

**Comment by Vinooj** [comment]
@ChengyuanZhao 

I'll try passing Key instead of the id(long).

**Comment by ChengyuanZhao** [comment]
@Vinooj the key you use must refer to the parent key as an ancestor. To Datastore the entire key includes all ancestor values.

**Comment by Vinooj** [comment]
Thanks for your quick response @ChengyuanZhao

I did spend some time researching trying to figure out how to do it
1. docs
2. https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/it
3. https://cloud.google.com/appengine/docs/standard/java/datastore/creating-entity-keys

Can you please provide some sample code.

**Comment by ChengyuanZhao** [comment]
@Vinooj You can use the client lib's key factory `com.google.cloud.datastore.KeyFactory` to construct new keys with the components and ancestors you need. It's a "builder" style class, and you can create a new instance of that factory to construct a key.

**Comment by Vinooj** [comment]
Thanks @ChengyuanZhao

I got it to work with the following code,

`Key parentKey = Key.newBuilder("my-project-id", "parent", id).build();
 Key childKey = Key.newBuilder(parentKey, "child", childId ).build();
 
Child existingChild= this.datastoreTemplate.findById(childKey, Child.class);
 existingChild.setName("Name - 1");
 existingChild = childRepository.save(existingChild);`
