### ISSUE TITLE
feat(sql): support third party parameters in url

### ISSUE THREAD

**Issue by davinkevin** [spring-cloud/spring-cloud-gcp#1489]
Hi, 

I'm using the Spring Cloud GCP SQL to configure my app with a CloudSQL Postgresql database. But, I need to use a specific `schema`. 
This need is linked to a limitation of Spring-Batch which will create its metadata-table inside the public schema by default and can't be overridden. 

So, one solution is to add a parameter in the JDBC url to add `currentSchema=mycustomschema`. This leads to a string like this in case of CloudSQL for PostgreSQL:

```
url:url: jdbc:postgresql://google/dbname?cloudSqlInstance=my-project-id:zone:instance-name&socketFactory=com.google.cloud.sql.postgres.SocketFactory&currentSchema=mycustomschema 
```

I've looked into the source code of the autoconfigure part and I think, for now, this can't be done with Spring Cloud GCP => https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/sql/DefaultCloudSqlJdbcInfoProvider.java

For now, I choose to use the `url` of the datasource and not relying on the autoconfiguration, but I would like to fit best into Spring Cloud GCP logic. What is your opinion about this ?

Then, I would like to do a PR about this to allow custom parameters. Is it a good idea from your point of view?

**Comment by elefeint** [comment]
I like the idea of supporting configurable properties; this will likely need to be done in `DatabaseType`.

For your immediate problem of reusing database URL creation logic while still passing the extra schema parameter, you could provide a `CloudSqlJdbcInfoProvider` bean in your own configuration as an extension of `DefaultCloudSqlJdbcInfoProvider` that calls super.getJdbcUrl() to get the base and then appends the extra parameter. This will suppress the autoconfigured plain `DefaultCloudSqlJdbcInfoProvider`  and use your composite URL when autoconfiguring `DataSourceProperties`.

**Comment by meltsufin** [comment]
Re-open if the answer is not satisfactory.
