### ISSUE TITLE
Get Cursor from DatastoreRepository Response

### ISSUE THREAD

**Issue by nabilnasri** [spring-cloud/spring-cloud-gcp#1490]
Hello, 

I have a custom `Query` on my Repository method. This is what it looks like
```
public interface PostReplyRepository extends DatastoreRepository<PostReply, Long> {
	@Query("SELECT * FROM postReply WHERE __key__ HAS ANCESTOR @parentPostKey")
	List<PostReply> getRepliesForPostWithId(@Param("parentPostKey") Key parentPostKey);
}
```
It works so far, but i would like to have the Cursor included in the Response. Am I using the wrong return value with a `List` or is it not supported?

**Comment by dmitry-s** [comment]
@nabilnasri This feature is currently unsupported, but we might implement it in the future.

**Comment by nabilnasri** [comment]
Thanks for the quick response! This feature would be very useful for us. Do you have any alternative idea on how to accomplish this?

**Comment by dmitry-s** [comment]
Could you provide more details on that? Why do you need the cursor?

Thanks

**Comment by nabilnasri** [comment]
The official Google Docs say that one should avoid using offset with integers.

> Although Datastore mode databases support integer offsets, you should avoid using them. Instead, use cursors. 

https://cloud.google.com/datastore/docs/concepts/queries?hl=en#datastore-datastore-cursor-paging-java

**Comment by dmitry-s** [comment]
Thanks for clarification. I don't think that's achievable in current implementation. But it looks like it shouldn't be hard to implement - most likely with `Page` return type.

**Comment by nabilnasri** [comment]
Sounds good! 
Maybe it is something for another issue, but when using pageable with a method annotated with @Query it throws an exception because the PageRequest can not be converted to a Datastore-compatible type.
I can provide a stacktrace once I am on my notebook again.

**Comment by dmitry-s** [comment]
That's a limitation of `@query` methods. We can't modify the provided query. Page return types work only with methods that generate queries (e.g. `findByColor(..)`)

We'll need to invent something new for `@query` annotated methods.

**Comment by meltsufin** [comment]
@mp911de It seems like there is a lot of interet in this feature. Can you recommend something? Thanks!

**Comment by mp911de** [comment]
The typical scheme for paging is by returning `Page<T>` and accepting `PageRequest` as in:

```java
public interface MyRepository<T, ID>
  extends CrudRepository<T, ID> {

  Page<T> findAll(Pageable pageable);
}
```

Alternatively, use `Stream` for transparent paging:

```java
public interface MyRepository<T, ID>
  extends CrudRepository<T, ID> {

  Stream<T> findAllBy();
}
```

See also `PagingAndSortingRepository`. Do not return technology specific types in repositories as they are a technical aspect, not a domain aspect.

**Comment by meltsufin** [comment]
@mp911de This questions is specifically about the use of a custom query (`@Query`). Do Spring Data implementations typically support returning a `Page` for these scenarios?

**Comment by mp911de** [comment]
Yes, typically we have this feature. It's easier to implement for stores that accept a notion of limit/offset parameters additional to a query string or the predicate definition. In some case (e.g. Cassandra) we need to amend the actual query string. Not sure this applies for Datastore as well.

**Comment by meltsufin** [comment]
@dmitry-s @ChengyuanZhao We don't want to modify the GQL query string, but we can expose [Cursors](https://cloud.google.com/datastore/docs/concepts/queries#datastore-datastore-limit-java) somehow. One option is to just allow an optional `CursorHolder` parameter for `@Query` annotated methods. The other, more idiomatic way would be to seamlessly use cursors for `@Query` methods that declare `Stream<T>` return type. WDYT?

**Comment by dmitry-s** [comment]
@meltsufin My plan was to expose cursor and allow it as a parameter, similar to your suggestion. But the other way seems reasonable too.

**Comment by kwiesmueller** [comment]
As long as the cursor is accessible directly when needed, any of those option sounds good.

**Comment by mp911de** [comment]
@meltsufin @dmitry-s please do not return a `Cursor` object directly. Rather provide a wrapper that makes it usable with `PageRequest` (see [`CassandraPageRequest`](https://docs.spring.io/spring-data/cassandra/docs/current/api/org/springframework/data/cassandra/core/query/CassandraPageRequest.html), Cassandra uses an opaque paging state object that must be passed on the next request).

This way, you can navigate through pages (`Slice.nextPageable()`,`Slice.previousPageable()`,  `Page.nextPageable()`) without using driver-specific API.

**Comment by meltsufin** [comment]
Thanks @mp911de! This sounds like a great direction. @dmitry-s Can you please see how difficult it would be to implement?

**Comment by dmitry-s** [comment]
It looks like it shouldn't be too hard.
