### ISSUE TITLE
Spring Security with GCP IAP on GAE Flex fails with "Project expected not to be null"

### ISSUE THREAD

**Issue by dvdgsng** [spring-cloud/spring-cloud-gcp#1493]
Deploying to GAE Flex with spring-cloud-gcp-starter-security-iap fails to automatically determine the GCP project.

> ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt:
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'audienceValidator' defined in class path resource [org/springframework/cloud/gcp/autoconfigure/security/IapAuthenticationAutoConfiguration.class]:
>Invocation of init method failed; nested exception is java.lang.IllegalArgumentException:
> **Project expected not to be null.**

Few lines earlier the log states:

> o.s.c.g.a.c.GcpContextAutoConfiguration  : The default project ID is MY_CORRECT_GCP_PROJECT_ID

The configuration is unset, meaning none of properties for `spring.cloud.gcp.security.iap.*` have been specified in the application.properties (registry, algorithm, header, issuer, audience). According to the docs, this should work since the defaults are used and audience is not required in GAE.

Related env vars are set properly by GAE and available to the application: GOOGLE_CLOUD_PROJECT, GCLOUD_PROJECT. Not sure if they are used, though.

Am I missing something?

Do you require more information?

**Comment by elefeint** [comment]
Most likely, the account does not have GCP's `resourcemanager.projects.get` IAM permission, so IAP is unable to retrieve project details.

Could you check what permissions are available to the account being used?

**Comment by dvdgsng** [comment]
Thanks for the quick reply.

I've checked the permissions. We've not configured any additional service accounts, so the default service accounts should be used to run our services.:

* The "App Engine default service account" (...@appspot.gserviceaccount.com) has the "Editor" role assigned, which includes `resourcemanager.projects.get` permissions.
* The "App Engine Flexible Environment Service Agent" (...@gae-api-prod.google.com.iam.gserviceaccount.com) had only "App Engine flexible environment Service Agent" assigned, which is not listed in IAM->Roles so I can not check what permissions it actually has (most likely because it's a Google managed SA). I've added the "Editor" role and redeployed the service, but unfrot. without any change, the error persists.

**Comment by elefeint** [comment]
Could you check that [Cloud Resource Manager API](https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com) is enabled?

**Comment by dvdgsng** [comment]
It was not enabled indeed. I enabled it and after redeploying the application was able to access the required information. 👍 Would be nice if this was hinted in the docs, though.

Thank you! Very helpful. :)

**Comment by elefeint** [comment]
I'll update the docs; I definitely missed the important setup bits!
