### ISSUE TITLE
Add checkstyle file to the project

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-gcp#15]

**Comment by joaoandremartins** [comment]
I'm trying to enable [eclipse-code-formatter](https://github.com/spring-cloud/spring-cloud-build/blob/master/spring-cloud-dependencies-parent/eclipse-code-formatter.xml) following [these instructions](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/appendix-contributing.adoc), but the Eclipse Code Formatter Plugin is clashing with another plugin I've got installed, which I don't want to uninstall.

I filed an [issue](https://github.com/krasa/EclipseCodeFormatter/issues/140) in the plugin's Github page, but I'm not sure it's going to be resolved. Would be cool to have a Spring format file that I could use.

**Comment by viniciusccarvalho** [comment]
We unfortunately use that file as the base for our formatting rules. I never had issues with the plugin before, so I can't really help there, I'm sorry.

I don't know if I can export Intellij format options after importing the eclipse format file, let me check that.
