### ISSUE TITLE
@Transactional annotaton is not working with GCP Datastore !

### ISSUE THREAD

**Issue by ayushj158** [spring-cloud/spring-cloud-gcp#1501]
While using spring integration for GCP data store , We have noticed couple of issues with @Transactional annotation. 

1. @Transactional annotation is not respected at all i.e. if i call respostiroy.save(entity) , the transaction is immediately committed instead of committing it after the method(annotated with @Transactional ) is finished.   
- I did verify data was updated in  cloud itself before method was finished.
- Spring documentation suggests transactional annotation is supported.
- https://cloud.spring.io/spring-cloud-static/Greenwich.RC2/multi/multi__spring_data_cloud_datastore.html

```
@Autowired
 private CustomerCommPrefRepository repository;

 @GetMapping("/test/save")
 @Transactional
  public void save() {
                 Entity entity = new Entity(composeEntity());
                 repository.save(entity ); //on this step itself transaction is getting committed, and i can see the updated results in cloud.
                 Optional<Entity > cm = repository.findById("test");
     }
```

2.  Spring documentation suggests that performTransaction cannot be used in @Transactional annotated methods . 
- I did a sample code and did not see any errors reported(compile as well as run-time) when i used an performTransaction in an @Transactional annotated methods . 
- https://cloud.spring.io/spring-cloud-static/Greenwich.RC2/multi/multi__spring_data_cloud_datastore.html
 
What the reason ? is the issue 1 related to it, maybe @Transactional  annotation is not working at all in case of datastore

#### Code Snippet

```
   @Autowired
   private CustomerCommPrefRepository repository;

    @Autowired
    DatastoreOperations myDatastoreOperations;

    @GetMapping("/test/save")
    @Transactional
    public void save(){
        myDatastoreOperations.performTransaction(datastoreTemplate -> {
          Entity entity = new Entity(composeEntity());
            return  datastoreTemplate .save(entity , null);
        });
        Entity entity = new Entity();
        repository.save(entity );
    }

```

Can you please help us here as we are planning to use data store integration for production?

**Comment by ChengyuanZhao** [comment]
@ayushj158 

Is this code snippet located in an object itself and that object being autowired to where you finally use it? 

Take a look at our tests that try to cover that the several operations (including save) hit the transaction context. https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTransactionTemplateTests.java 

This test class also has the example in `TransactionalService` about how to set everything up.

**Comment by ayushj158** [comment]
Here is the actual code with class names. 
- @Trasactional is annotated on a service class which calls an repository interface to save/read the data.


#### Repository 

```
import org.springframework.cloud.gcp.data.datastore.repository.DatastoreRepository;
import org.springframework.stereotype.Repository;
@Repository
public interface SampleDatastoreRepository extends DatastoreRepository<SampleEntity, String> {
}

```


#### Service 
```
 @Service
public class SampleDatastoreService {
    @Autowired
    private SampleDatastoreRepository repository;

    @Transactional
    public void save() {
        SampleEntity entity = new SampleEntity("ayush-test", composeCommPref("ayush557@gmail.com"));
        repository.save(entity);
        repository.findById("ayush-test").ifPresent(i -> System.out.println(i));
    }
}
```
Behavior i see : I can see updated entity in cloud data-store just after the execution of  repository.save() ,whereas if it was working in a transaction it should have been committed after execution of method "save" completes !

**Comment by ChengyuanZhao** [comment]
@ayushj158 just to confirm, your config is annotated with `@EnableTransactionManagement`?

**Comment by ayushj158** [comment]
It worked what i needed to do was add @EnableTransactionManagement and add below bean to config 

```
@Bean
    DatastoreTransactionManager datastoreTransactionManager(Datastore datastore) {
        return new DatastoreTransactionManager(datastore);
    }
```

Why not add default DatastoreTransactionManager bean (just like DatastoreTemplate and Datstore beans) and @EnableTransactionManagement to GcpDatastoreAutoConfiguration.class ? 

Also i think if it is possible we can update the spring documentation to define these steps to enable @Transaction . For me i had the assumption just like @EnableDatastoreRepositories  , @EnableTransactionManagement will also be auto-configured.


https://cloud.spring.io/spring-cloud-static/Greenwich.RC2/multi/multi__spring_data_cloud_datastore.html

Thanks for your help :) :+1:

**Comment by ChengyuanZhao** [comment]
@ayushj158 good to hear ! 
We actually do provide the transaction manager if using our auto config ( https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/datastore/DatastoreTransactionManagerAutoConfiguration.java ) 

(However we do require you to add the `@EnableTransactionManagement` yourself. I think we got that from some other Spring Data modules that seem to have the user adding it. )
