### ISSUE TITLE
Project Build Error

### ISSUE THREAD

**Issue by Mustafa-Hafeez** [spring-cloud/spring-cloud-gcp#1502]
Fairly new to maven, but I have pulled the code and have an error in my pom.xml fir for spring-cloud-gcp-data-spanner-sample. 
Project build error: Non-resolvable parent POM for com.example:spring-cloud-gcp-data-spanner-sample:[unknown-version]: Could not find artifact org.springframework.cloud:spring-cloud-gcp-samples:pom:1.2.0.BUILD-SNAPSHOT and 'parent.relativePath' points at wrong local POM

**Comment by meltsufin** [comment]
What is the build command you're running and from which directory?

**Comment by Mustafa-Hafeez** [comment]
I am running mvn package in this directory:
spring-cloud-gcp-master\spring-cloud-gcp-samples\spring-cloud-gcp-data-spanner-sample

**Comment by meltsufin** [comment]
You'd want to first build from the root directory `spring-cloud-gcp-master\`.

**Comment by Mustafa-Hafeez** [comment]
Thanks for the replies, I'm very new to all of this, so I greatly appreciate any help you can provide. When I try to build from the root, I get a bunch of warnings, should I be worried & how can I fix them exactly? I don't clearly understand how to.. thanks!
![image](https://user-images.githubusercontent.com/7739079/54851084-4618b680-4cbf-11e9-833a-616df930287c.png)

**Comment by meltsufin** [comment]
No need to worry about warnings for your purposes. We do need to take care of them at some point though. You can also skip tests to make the build faster with `mvn clean install -DskipTests`.

**Comment by ChengyuanZhao** [comment]
Closing this one now. Please feel free to reopen if there is an error.
