### ISSUE TITLE
spring-cloud-gcp-starter-pubsub not shutting down

### ISSUE THREAD

**Issue by danneville** [spring-cloud/spring-cloud-gcp#1503]
Hi,

I'm experiencing some issues using spring-cloud-gcp-starter-pubsub where the application hangs on shutdown. It sounds the same as this issue https://github.com/spring-cloud/spring-cloud-gcp/issues/60 which was closed when it wasn't able to be reproduced.

I have created a Spring CommandLineRunner Application that will publish messages to PubSub and then shutdown however it does not. I've provided the bare minimum to reproduce here [https://github.com/danneville/spring-gcp-pub-sub-issue](https://github.com/danneville/spring-gcp-pub-sub-issue) . Just the inclusion of the spring-cloud-gcp-starter-pubsub dependency causes the application to hang on shutdown. If you remove the dependency it shuts down immediately as expected.

This happens both when running the application in IntelliJ and on the command line.

I've provided the [thread dump](https://github.com/danneville/spring-gcp-pub-sub-issue/blob/master/thread-dump.txt) in the repo if this helps.

Please can you confirm if this is an issue or if I should be specifying something to gracefully shutdown?

Many thanks

**Comment by dmitry-s** [comment]
Thanks for reporting the issue! 
I was able to reproduce it using your sample app. We will take a look.

**Comment by dmitry-s** [comment]
We identified the issue, will push a fix shortly.

**Comment by elefeint** [comment]
@danneville This has been fixed in _1.2.0.BUILD-SNAPSHOT_, but if using a snapshot version is not an option, you can close the thread pool like this:

```
@SpringBootApplication
public class SampleApplication implements CommandLineRunner {

    @Autowired
    @Qualifier("subscriberExecutorProvider")
    ExecutorProvider subscriberExecutorProvider;

    @PreDestroy
    public void shutdownExecutor() {
        this.subscriberExecutorProvider.getExecutor().shutdown();
    }

    public static void main(String[] args) {
        // ... original logic
    }
}
```

**Comment by danneville** [comment]
Excellent thank you @elefeint amd @dmitry-s for you quick responses.

I can confirm that this worked for me. I did also have to add the publisherExecutorProvider to get it to work for when I'm publishing messages.

```
    @Autowired
    @Qualifier("subscriberExecutorProvider")
    private ExecutorProvider subscriberExecutorProvider;

    @Autowired
    @Qualifier("publisherExecutorProvider")
    private ExecutorProvider publisherExecutorProvider;

    @PreDestroy
    public void shutdownExecutor() {
        this.subscriberExecutorProvider.getExecutor().shutdown();
        this.publisherExecutorProvider.getExecutor().shutdown();
    }
```

Thanks again
