### ISSUE TITLE
Consider naming our thread pools for ease of troubleshooting

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#1506]
Issues such as #1503 will be easier to troubleshoot if we can easier identify which thread pool failed to close.

**Comment by meltsufin** [comment]
Do we have more examples of thread pools that we create without explicitly naming them?
I think to make this issue actionable, we need some pointers to those.

**Comment by elefeint** [comment]
After the three in Pub/sub (publisher, subscriber, ack), I think there is only the one left in `traceExecutorProvider` in `StackdriverTraceAutoConfiguration` left. Looking at it, it also needs to become a Spring-managed bean, like the ones in #1505.
