### ISSUE TITLE
Firestore Native Mode support

### ISSUE THREAD

**Issue by dlinsin** [spring-cloud/spring-cloud-gcp#1507]
Is there any plan to add support for [Cloud Firestore](https://firebase.google.com/docs/firestore/) ?

**Comment by meltsufin** [comment]
Firestore in Datastore mode is already supported.

**Comment by ChengyuanZhao** [comment]
I assume this is talking about Firestore in "native" mode? There are some differences in the data model that seem pretty different from Datastore so that it doesn't seem like our module can work in "native" mode   ( even when the relevant client lib classes or dependencies are switched out)
