### ISSUE TITLE
Update docs to mention that we support Firestore in Datastore mode

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1508]
Existing projects that use Datastore are starting to be automatically [upgraded](https://cloud.google.com/datastore/docs/upgrade-to-firestore) to Firestore in Datastore mode. We should update our documentation to mention that Spring Data Datastore supports Firestore in Datastore mode.

Related to question in #1507.

**Comment by meltsufin** [comment]
@dmitry-s Can you take care of this please?

**Comment by dmitry-s** [comment]
Yes, I'll do that.
