### ISSUE TITLE
CloudSQL starter should default to InnoDB dialect

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#1510]
CloudSQL 2nd generation only supports InnoDB (https://cloud.google.com/sql/faq).
The starter should autoconfigure that has the dialect to use.

**Comment by saturnism** [comment]
Related: https://github.com/spring-projects/spring-boot/issues/15342

**Comment by meltsufin** [comment]
Duplicate of #392?

**Comment by saturnism** [comment]
ah yes, definitely a duplicate. can close this one and keep the other one. thnx!
