### ISSUE TITLE
Spanner/Datastore - unable to use both Spring Data Spanner & Datastore in the same app 

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#1512]
Added both Spanner & Datastore starters to the same application, and tried to use both repositories.
The application failed to start.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'personRepositiory', defined in null, could not be registered. A bean with that name has already been defined in null and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

```

**Comment by ChengyuanZhao** [comment]
Is this supposed to be possible ? @saturnism I was under the impression this wasn't supposed to be possible given the way the Spring Data Common works.

**Comment by meltsufin** [comment]
@mp911de Is it true that two Spring Data implementation could not co-exist?

**Comment by mp911de** [comment]
You can run multiple modules in the same application. You need to provide either entity annotations, repository subtypes or filtered/scoped base packages so that a module knows which repositories it should implement. Take a look at the docs https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.multiple-modules and https://github.com/spring-projects/spring-data-mongodb/blob/master/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/repository/config/MongoRepositoryConfigurationExtension.java#L76

**Comment by ChengyuanZhao** [comment]
@saturnism could you provide the sample you're trying this with? I'll see if I can get it working

**Comment by saturnism** [comment]
@ChengyuanZhao I'll try to get the full source into github. in the mean time, it's pretty straight forward. Please see the following. Thanks for taking a look!

```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-data-datastore</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-data-spanner</artifactId>
		</dependency>
```

(kotlin code)
```
@RepositoryRestResource
interface BookRepository : SpannerRepository<Book, Key>

@RepositoryRestResource
interface PersonRepository : DatastoreRepository<Person, Long>

@Entity
data class Person(
		@Id
		var id: Long? = null,
		var name: String? = null,
		var age: Int? = null
)

@Table
data class Book(
        @PrimaryKey
		var id : String? = UUID.randomUUID().toString(),
		var isbn : String? = null
)
```

**Comment by meltsufin** [comment]
@ChengyuanZhao Can you please follow-up on this one?

**Comment by ChengyuanZhao** [comment]
@meltsufin will take a look now.

**Comment by ChengyuanZhao** [comment]
@mp911de I'm wondering if there is some place in a config/registrar class I missed. I'm reproducing this error myself and it looks like Datastore and Spanner repositories are attempted to be created for the user's repo interface. 

For example, I have `TraderRepository extends SpannerRepository<Trader, String> ` specifically extending only the SpannerRepository type. The `Trader` type is also annotated with `@Table` for Spanner and not `@Entity` for Datastore.

I have the following set in my Spring Data Spanner config classes:

```
// in EnableSpannerRepositories annotation class
Class repositoryBaseClass() default SpannerRepository.class;
Class repositoryFactoryBeanClass() default SpannerRepositoryFactoryBean.class;

// in SpannerRepositoryConfigurationExtension
public String getRepositoryFactoryBeanClassName() {
		return SpannerRepositoryFactoryBean.class.getName();
	}

protected Collection<Class<? extends Annotation>> getIdentifyingAnnotations() {
		return Collections.singleton(Table.class);
	}

protected Collection<Class<?>> getIdentifyingTypes() {
		return Collections.singleton(SpannerRepository.class);
	}
```

I have the same settings in the Datastore module referring to the Datastore-specific classes/types. 

Is there another setting that I am missing that would prevent both modules from trying to create repos for TraderRepository?

**Comment by mp911de** [comment]
My bad, I missed that we switched multi-store detection from pattern-based class names to `spring.factories`. You need to provide a `META-INF/spring.factories` file with an entry pointing to your `…RepositoryFactor` for each store to tell Spring Data there are multiple store modules.

See [Spring Data JPA](https://github.com/spring-projects/spring-data-jpa/blob/master/src/main/resources/META-INF/spring.factories#L1) as example. [Here's also a link](https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/repository/config/RepositoryConfigurationDelegate.java#L238-L247) to the code that detects multi-store presence.

Without detecting that multiple stores are on the classpath, Spring Data does not enter strict mode and so all repositories are picked up by both store modules.
