### ISSUE TITLE
Re-enable GcpStorageAutoConfigurationTests and StackdriverLoggingIntegrationTests after fixing or refactoring them

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1521]
After upgrading to Spring Boot 2.2 the `GcpStorageAutoConfigurationTests` and `StackdriverLoggingIntegrationTests` tests fails because of the login screen put up in front of the REST controller. Ideally, the fix would allow us to remove all of the auto-configuration exclusions.

**Comment by dzou** [comment]
What are your thoughts on just deleting the tests? Since we have integration coverage from integration tests in their modules as well as from samples, I think they may be redundant.

**Comment by meltsufin** [comment]
The advantage of these is that they run as unit tests with each PR, rather than integration tests that only run post-merge on master.

**Comment by dzou** [comment]
> The advantage of these is that they run as unit tests with each PR, rather than integration tests that only run post-merge on master.

Hmm, I don't agree that this is an advantage. The two tests listed are integration tests, and we could just as easily remove the Dit.storage/Dit.logging requirement on the integration tests in storage/logging if we wanted to do that.

Also the [Logging tests are not being run as a unit test](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/test/java/org/springframework/cloud/gcp/autoconfigure/logging/it/StackdriverLoggingIntegrationTests.java#L88).

**Comment by meltsufin** [comment]
What I meant to say is that they run locally without invoking GCP. For integration tests that are guarded with flags, we can only run them on master, (1) because they're slow, and (2) because we don't have the encrypted credentials in the case of external pull requests.

**Comment by dzou** [comment]
I see, in that case the storage test is fine, but `StackdriverLoggingIntegrationTests` definitely invokes GCP.

**Comment by dzou** [comment]
Actually I think I understand the full story now. Looks like the logging IT was put here before you split out a logging module. Perhaps the logical solution is to just move that test to the newly created logging project which does not yet have an integration test.

**Comment by dzou** [comment]
Turns out this is resolved.

GcpStorageAutoConfigurationTests fixed by Elena in #1638.
Logging integration tests consolidated to the trace sample sample test in #1676.
