### ISSUE TITLE
Repositories are polluted in downstream project by default

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-gcp#1522]
This project has a `spring` profile that is enabled by default and contains references to several repositories: https://github.com/spring-cloud/spring-cloud-gcp/blob/23664c6958b1cf0bea121c4e6c83338b94be9db4/spring-cloud-gcp-dependencies/pom.xml#L195 

A BOM should never have that for a start, it should only contain dependency management and nothing else. You can also use the flatten maven plugin to "clean" published POM and remove build specific setup. 

Somewhat related but I can see this list is copy/pasted in the root pom and the number of repositories is quite large (that should slow down the build).

Please make sure to backport that for every supported version

**Comment by snicoll** [comment]
Note that the spring cloud build parent will remove those automatically, see https://github.com/spring-cloud/spring-cloud-build/issues/89 - I still recommend removing that profile from the BOM (do you need it?)

**Comment by meltsufin** [comment]
We can probably remove it. I think the rationale was to make it easier for users to start using the project by just importing the BOM and not having to configure the repositories.
@markfisher I see that you made the profile active by default back in 2017. WDYT?
