### ISSUE TITLE
Add spring-cloud-gcp-logging

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#154]
Log correlation w/ Spring Cloud Sleuth and GCP Trace IDs
Automatic log module configuration depending on the environment (GCE, GAE Flex, GAE Standard, & Kubernetes)

**Comment by meltsufin** [comment]
Related [issue](https://github.com/spring-projects/spring-boot/issues/8933) being discussed on spring-boot.
