### ISSUE TITLE
Move properties from starter module and autoconfig to core module

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#155]
E.g., PubSub autoconfiguration currently lives in the starter module, but shouldn't it be in the core module?

Most of the autoconfig checks for .enabled flag in properties to offer the user to turn it off. 
Starters only manages the default dependencies

**Comment by joaoandremartins** [comment]
`@ConfigurationProperties` is a Boot concept. I don't think we would want the core module to depend on Boot, but let me know if I'm missing anything @saturnism

**Comment by joaoandremartins** [comment]
#262 captures this requirement in more detail. Let's follow up there.
