### ISSUE TITLE
Automatically capture GCP Trace IDs in Sleuth integration

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#156]
Add a filter to automatically capture GCP trace IDs (e.g., from HTTP LB), and also set LB trace propagation response header.

**Comment by meltsufin** [comment]
This may also apply to logging support that we're planning. We need to capture the HTTP request header `x-cloud-trace-context` and group request logs by trace ID.

**Comment by joaoandremartins** [comment]
@saturnism @meltsufin is this already done?

**Comment by joaoandremartins** [comment]
`x-cloud-trace-context` is being intercepted according to our [refdoc](https://docs.spring.io/spring-cloud-gcp/docs/1.0.0.M3/reference/htmlsingle/#_stackdriver_logging_support).
