### ISSUE TITLE
BigQuery integration

### ISSUE THREAD

**Issue by sergeymeshkov** [spring-cloud/spring-cloud-gcp#1568]
Hi,
Is it possible to implement Big Query integration to Spring?
1. BigQuery repository settings (like @ EnableDatastoreRepositories) 
2. BigQuery autoconfiguration
3. Object mapping
4. Object relationships
5. Query methods, native SQL
6. Audit integration (@ CreatedDate, @ LastModifiedDate, @ CreatedBy, @ LastModifiedBy)
7. REST repositories
8. Database Schema Admin, Migrations

**Comment by meltsufin** [comment]
@sergeymeshkov BigQuery is not designed for OLTP. It's used mostly as a data warehouse. So, I wonder what is your use-case such that you need ORM for BigQuery.

That aside, there seems to be a [JDBC driver](https://cloud.google.com/bigquery/providers/simba-drivers/) for BigQuery. So it might be fairly easy to make it work with Spring Data JPA / Hibernate and/or Spring Data JDBC.

**Comment by sergeymeshkov** [comment]
@meltsufin thank you, I understand that BigQuery designed as a data warehouse. 
In our case, we save a large amount of analytical data in BigQuery and sometimes we need to display it (we use https://mvnrepository.com/artifact/com.google.cloud/google-cloud-bigquery). To do this, we have to write SQL queries, retrieve data and transform them into data models, which increases the amount of boilerplate code. In addition, most developers will still write their own abstractions for integration with BigQuery. I understand that some concepts like the stream insets, jobs and etc. not supported by Spring Data, however, at least some 'SELECT' queries can be supported.

**Comment by meltsufin** [comment]
I see. Do you think Spring Data JDBC or Hibernate would be appropriate for your usecase? I know that neither is supported currently though.

**Comment by ChengyuanZhao** [comment]
From reading about BigQuery it sounds like these were the important points
-  the documentation encourages denormalized data
-  tables don't have keys (and no relationship mechanisms) 
-  loading data is primarily in batch jobs,
- stream inserting has significant waiting periods 

It sounds like Spring Data isn't a good fit since BQ isn't a good way to store and reflect a bunch of related entities. But it sounds like the request here is just to run queries and convert rows into POJOs, which sounds a lot like what the simpler JDBC driver is there for.

**Comment by sergeymeshkov** [comment]
@meltsufin  I have no specific expectations regarding the framework. Both of those solutions might work, but personally, I prefer approaches which were designed by you guys in Spanner and Datastore.  Anyway, @ChengyuanZhao is right - actual request is " is just to run queries and convert rows into POJOs". However, I still think that Spring Data framework should support BigQuery. Yes, some concepts don't match with popular OLTP solution, but those concepts might be hidden under the hood. Regarding DX - if the developer uses BigQuery, it is his responsibility to understand the concepts of a streaming insert, jobs, and denormalization. If Spring Data doesn't provide some functionality - he can use already existed library.

**Comment by sergeymeshkov** [comment]
Are there any plans for this feature?

**Comment by meltsufin** [comment]
It might be in the future, but we're not currently prioritizing it.

**Comment by meltsufin** [comment]
Closing since we're still don't think an ORM for BigQuery is appropriate.
However, we are planning some support in terms of a `BigQueryTemplate` implementation coming.
