### ISSUE TITLE
Issue if SLF4J dependencies

### ISSUE THREAD

**Issue by Andyccs** [spring-cloud/spring-cloud-gcp#1574]
I was trying to use the datastore dependency. I found out that if one project decided to use `log4j-slf4j-impl` as one of its dependency, then the project can't depends on `spring-cloud-gcp-data-datastore` because the datastore dependency use `log4j-to-slf4j`.

References:

- https://logging.apache.org/log4j/2.0/log4j-slf4j-impl/
- https://logging.apache.org/log4j/2.0/log4j-to-slf4j/index.html
- https://stackoverflow.com/questions/32366586/using-log4j2-with-slf4j

**Comment by meltsufin** [comment]
Spring Data Datastore doesn't seem to depend on `log4j-to-sl4j`. What makes you say that it does?
Here's my test:
```
spring-cloud-gcp/spring-cloud-gcp-data-datastore$ mvn dependency:list | grep slf4j
[INFO]    org.slf4j:slf4j-api:jar:1.7.26:compile
[INFO]    org.apache.logging.log4j:log4j-to-slf4j:jar:2.11.2:test
[INFO]    org.slf4j:jul-to-slf4j:jar:1.7.26:test
```
You can see that the dependency is in the `test` scope only, and should not make it into your application.

**Comment by Andyccs** [comment]
Your comment seems to be valid. I am not sure why I got the problem in the first place, but I wasn't able to reproduce it. Sorry for the false signal.
