### ISSUE TITLE
How to customize trace attributes/tags?

### ISSUE THREAD

**Issue by rajivml** [spring-cloud/spring-cloud-gcp#1604]
I have created a question on stackoverflow tagging spring-cloud-gcp but I didn't got any reply, so that's why re-posting it here again.
https://stackoverflow.com/questions/55320822/gke-stack-driver-trace-reporting-by-cluster-by-environment-by-service-by-service

We have multiple spring boot apps running on top of GKE and for spring boot applications am using spring-cloud-gcp-starter-trace to log traces to stack driver so that I can debug those traces via the stack driver UI.

Am not able to figure out how to add labels like service_name, service_version and cluster_name so that I can filter out only those traces for reporting purposes because right now we have istio configured on one cluster and even with one percent sampling rate it's generating tons of telemetry data and with UN-availability of filters or am missing some configuration, the trace UI has almost become useless for me

I had a look at the documentation for spring-cloud-gcp-starter-trace, they don't have any properties through which I can set these fields/tags.

Does spring-cloud-gcp-tracing library and stack driver tracing service support adding such tags and if yes, what are the touch points where I should add these tags and what are the list of valid tags applicable for GKE environment

Some references on what am talking about:
https://github.com/googleapis/cloud-trace-nodejs/issues/455
https://github.com/googleapis/cloud-trace-nodejs/issues/306

Can some one please let me know how can I achieve this.

**Comment by rajivml** [comment]
I just now went through the documentation and found this property to set the name of the service. 

Similarly, am expecting few of other tags to be associated with these traces and stack driver tracing UI should honor these tags i.e allow me to filter the data based on these tags

Already Present:
spring.zipkin.service.name: foo

Expected Tags:
spring.zipkin.service.environment: prod/dev/qa
spring.zipkin.service.version: v1/v2/v3

**Comment by meltsufin** [comment]
Hi @rajivml. Thanks for the question. We will look into it shortly. Currently, we're blocked due to another issue with Trace. #1608 

cc/ @saturnism

**Comment by meltsufin** [comment]
@rajivml You can add custom tags using the `brave.SpanCustomizer`. Just autowire it in as the bean already exists in the application context.
You can then add tags, like this:
```
@Autowired
SpanCustomizer spanCustomizer;

...

spanCustomizer.tag("my-tag", "my tag value");
```
These will turn into labels on you traces in Stackdriver Trace, on which you can [search](https://cloud.google.com/trace/docs/trace-filters).

**Comment by rajivml** [comment]
@meltsufin thanks for looking into this.

may be a very novice question, right now I don't have any custom code written for generating the traces am using out of box functionalities provided by spring-cloud-gcp library. So, what are the touch points where this change has to be done, can you point to an example in case if any?

**Comment by rajivml** [comment]
The Filter based approach isn't working, will try hardcoding at each API end point and see if it's working 

```
nField customizer in com.uipath.ml.controller.RequestHeaderFilter required a bean of type \u0027brave.SpanCustomizer\u0027 that c ould not be found.\r\n\r\nThe injection point has the following annotations:\r\n\t- @org.springframework.beans.factory.annotation.Autowired(required\u003dtrue)\r\n\r\n\r\nAction:\r\n\r\nConsider defining a bean  of type \u0027brave.SpanCustomizer\u0027 in your configuration.\r\n","context":"default"}
--
```

**Comment by meltsufin** [comment]
@rajivml I'm a little confused about the problem you're facing. Do you have multiple `SpanCustomizer` beans in the application context? Or, are you unable to add new beans to the application context?
Using the Spring MVC interceptors seems appropriate. I added it to our Trace example. See: #1619.

**Comment by rajivml** [comment]
Thank you very much @meltsufin . I have just now tested it and it's working fine and I can see the tags in stackdriver trace UI.

You can resolve the issue. Appreciate the support !!

**Comment by meltsufin** [comment]
I'm glad it worked for you! Thanks for the update.
