### ISSUE TITLE
Flyway with Google Cloud Spanner new Project

### ISSUE THREAD

**Issue by Mustafa-Hafeez** [spring-cloud/spring-cloud-gcp#1612]
Hi, so I have been working with this example project: https://github.com/olavloite/spanner-flyway-example

The problem I'm facing is trying to create a new project based off this one to fit my needs. However, when I try changing the migration files, I get many different errors, an example being InvocationTargetException. I am assuming I cant just be changing the files like that, but how can I create a replica to fit my needs. I am new to all of this so it is difficult for me to understand what to do. Thanks!

**Comment by meltsufin** [comment]
Can you describe your problem in more detail? This project is not associated with the one you link to. I'm confused as to what you're asking.

**Comment by ChengyuanZhao** [comment]
@Mustafa-Hafeez 
We are a separate and unrelated project to the one you linked. I see you already made an issue there asking about it so I will close this onie.
