### ISSUE TITLE
Stack Driver Propagate traceId From Upstream Apps

### ISSUE THREAD

**Issue by rajivml** [spring-cloud/spring-cloud-gcp#1621]
We have some upstream apps which are coded in Dot Net and we have some other services coded in Spring Boot which runs on top of GKE.

Now the users will interact with Upstream Apps coded in dotnet which in-turn rely on Spring Boot Services for the task to complete.

For Spring boot Apps, am using Spring Cloud Sleuth tracing to trace the service calls flow/journey, but how do I stitch the entire journey right from the users interaction with Dot Net Apps till the final request is complete.

Say for example, if the dotnet apps are using this library https://cloud.google.com/trace/docs/setup/aspnet to instrument tracing and push the same to stackdriver , when the dot net service hit our Spring Boot service, does the trace_id/parent_id will remain the same or since the apps are coded in different languages and are using different client libraries , a new trace_id will be generated when the Spring boot service is called ?

And if yes, how do I avoid this scenario and propagate the same trace_id so that I can see the entire service call journey in stack driver trace UI irrespective of language barrier

**Comment by meltsufin** [comment]
The stitching is done via trace propagation in the HTTP headers.
We rely on Zipkin with Brave (B3-) headers.
Take a look at https://github.com/openzipkin/zipkin4net to make your .NET application use Zipkin for trace propagation.

**Comment by rajivml** [comment]
@meltsufin Any idea, If this library http://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Diagnostics.AspNet/index.html internally uses the one you are suggesting https://github.com/openzipkin/zipkin4net , so that by using the google-cloud-dotnet library we can push all the traces to stackdriver

**Comment by meltsufin** [comment]
The library you're referring to doesn't seem to be using Zipkin. Nonetheless, depending on how it propagates traces across requests, it may interoperate with Zipkin GCP.

cc: @SurferJeffAtGoogle
