### ISSUE TITLE
Clarify Spring Cloud GCP SQL support for Kubernetes

### ISSUE THREAD

**Issue by nealeu** [spring-cloud/spring-cloud-gcp#1627]
I've gone around in circles a lot in this area and still stuck (and trial and error in something as complex as K8s in GCP is not fun)

I would love to be deploying just as AppEngine Custom, but that doesn't give me the ability to do request and limit for vCPUs on many apps on the same node.

However, I'm targetting Kubernetes and it's not clear what Spring Cloud GCP features work in Kubernetes vs in App Engine.

Could the documentation be made clearer here (happy to do a PR if I knew what the actual situation was).
e.g. in K8s, do we need to specify the hostname via a URL instead of the instance-connection-name?

or, is the situation that Spring Cloud GCP is really Spring Cloud Google App Engine?

Perhaps something like https://codelabs.developers.google.com/codelabs/cloud-spring-petclinic-cloudsql/index.html but with deploy to GKE would be more useful as an example.

**Comment by meltsufin** [comment]
Although we do not have extensive testing on K8, the project is designed to run on it. We do have some special handling for App Engine standard in the project, but it's very limited, and all features are designed to be independent of the execution environment.
If you find any problems with any of the features on K8, please file a specific bug.

**Comment by nealeu** [comment]
That was what I guessed with there being AppEngine and default impls.  I'll press on.
