### ISSUE TITLE
Upgrade cloud-sql-socket-factory to 1.0.13

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#1633]
1) `SslSocketFactory` got renamed to `CoreSocketFactory`.
2)  Depending on the outcome of GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#131, either skip a version and depend on the constant exposed in the next version, or hardcode the user token property name in `GcpCloudSqlAutoConfiguration`.

**Comment by elefeint** [comment]
Verified that using CoreSocketFactory.setApplicationName() works in version `1.0.14-SNAPSHOT`.

**Comment by meltsufin** [comment]
Completed.
