### ISSUE TITLE
Cloud Spanner Session leaks

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1637]
Customer reports:

> We still continue to experience the session leak issue. In our the application starts working once you restart. However, if application is on for couple of hours.
> 
> Spanner will not throw any error, but it simply timeouts getting the connection. We do not even an error being throwed. It is very difficult to drill down what

**Comment by ChengyuanZhao** [comment]
Awaiting more detail. This is unexpected since tests now cover a known issue in the template's `read` method.

**Comment by meltsufin** [comment]
We should try to understand how big is the connection pool and whether the connections are properly returned to the pool after use.

**Comment by meltsufin** [comment]
It looks like the default pool size is 400. I suspect that the sessions are not being returned to the pool after use. This would cause the pool to be exhausted after a while, but not immediately. We can try to force it by configuring the maximum pool size to something really small, like "1".

**Comment by ChengyuanZhao** [comment]
@meltsufin Hmm trying that with our existing integration tests doesn't cause an issue (we do dozens of operations in quick succession). 

I think we'll need to get more detail from the user; the number of operations and places to look is pretty large without a hint.

**Comment by meltsufin** [comment]
Also, could be related to https://github.com/googleapis/google-cloud-java/issues/3616

**Comment by meltsufin** [comment]
Unable to reproduce.
