### ISSUE TITLE
Subscribing to multiple subscriptions from different Project IDs

### ISSUE THREAD

**Issue by don-mayur** [spring-cloud/spring-cloud-gcp#1639]
Spring Cloud GCP doesn't provide(or I am not aware of) option/configuration to subscribe to two different subscriptions which belong to two individual and separate Google Cloud Project with respective Project IDs.

Right now we use Google Cloud Pub-Sub library to do it but would like to use Spring GCP PubSub for this scenario.

**Comment by elefeint** [comment]
It's possible to do, with some custom configuration. You'll need to define a separate [subscriber factory](https://github.com/spring-cloud/spring-cloud-gcp/blob/72d746486fedd19b16ead3cdbbcfb48c3e90c3a9/spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/support/DefaultSubscriberFactory.java#L78) and [PublisherFactory](https://github.com/spring-cloud/spring-cloud-gcp/blob/72d746486fedd19b16ead3cdbbcfb48c3e90c3a9/spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/support/DefaultPublisherFactory.java#L70) for each project, passing a custom `GcpProjectIdProvider`, like this:

```
DefaultSubscriberFactory factory1 = new DefaultSubscriberFactory(() -> "PROJECT1");
DefaultSubscriberFactory factory2 = new DefaultSubscriberFactory(() -> "PROJECT2");
PubSubSubscriberTemplate subscriberTemplate1 = new PubSubSubscriberTemplate(factory1);
PubSubSubscriberTemplate subscriberTemplate2 = new PubSubSubscriberTemplate(factory2);
// same for publisher template
```

You can rely on the rest of autoconfiguration for plugging into Spring Integration and Spring Cloud Stream if you provide an implementation of `PubSubOperations` that delegates to the right `PubSubSubscriberTemplate` and `PubSubPublisherTemplate` based on the subscription name.

**Comment by elefeint** [comment]
As of #1678, it is now possible to publish/subscribe to topics in different projects with a fully qualified topic/subscription name.

**Comment by arghyadeysodepur** [comment]
How do we pass keys for these two project-ids?

**Comment by meltsufin** [comment]
> How do we pass keys for these two project-ids?

Whatever credentials you set up using `spring.cloud.gcp.pubsub.credentials` is what will be used. So, those credentials must have permissions to access both projects.
