### ISSUE TITLE
[Question] Uploading files to GCS and correlating logs with traces

### ISSUE THREAD

**Issue by korrawit** [spring-cloud/spring-cloud-gcp#164]
Hello,

1. About  spring-cloud-gcp-storage
As my understanding, only read and update file are supported.
I'm just curious that now current spring-cloud-gcp-storage support for uploading file yet?

2. About spring-cloud-gcp-trace
I couldn't find log that related with trace from Trace List.
Does spring-cloud-gcp-trace has put log into Stackdriver Logging as well?

BR,

**Comment by joaoandremartins** [comment]
Hi @korrawit , thanks for your question!

1) GCS file creation through the Resource abstraction isn't supported. We'll open an issue to consider supporting file creation on `((WritableResource) file).getOutputStream()` if the file still doesn't exist on GCS.

2) You can see the logs associated to a trace by going to the Google Cloud Console Trace section, opening a trace and opening the link in Details -> Log -> "View"

**Comment by meltsufin** [comment]
Regarding `spring-cloud-gcp-storage`, our implementation of the `WritableResource` (`GoogleStorageResource`) doesn't currently auto-create the file when you call `getOutputStream()`. However, I created an issue to add that capability. See #165.
For now, you can inject the `com.google.cloud.storage.Storage` bean, which the starter auto-configures and use its API which includes `create(...)` methods.

Regarding `spring-cloud-gcp-trace`, correlating logs with traces is not supported yet. See: #154. (cc @saturnism )

**Comment by joaoandremartins** [comment]
Questions answered, please reopen if anything missed.
