### ISSUE TITLE
Spring Sleuth: How to Trace Long Running Methods Within a Service

### ISSUE THREAD

**Issue by rajivml** [spring-cloud/spring-cloud-gcp#1640]
HI,

Right now am able to track response time across the services and I would like to extend or break down the response time within a service so that I can track response times of some long running methods within a service like DB calls, external service calls like S3/GCS uploads/downloads, docker builds etc kind of long running methods.

can you please let me know how can I achieve this, I tried annotating these methods with @NewSpan somehow it didn't worked. 

If possible, can you please extend the gcp-trace-example to demonstrate this, Thanks

**Comment by meltsufin** [comment]
@rajivml The Trace sample already has an example of `@NewSpan` in the `WorkService` class. Is it different from what you're trying to do?

**Comment by rajivml** [comment]
apologize for the late response, I just now tried with @NewSpan Annotation and am able to see response times at an Method level.  I think some rogue dependency or dependency mismatch was causing an issue earlier.

You can resolve it

**Comment by meltsufin** [comment]
Thanks for the update! Glad it worked for you!
