### ISSUE TITLE
Support auto-configuration of the Datastore emulator

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1642]
Currently, we support the Datastore emulator by allowing the client to configure host and port via the `spring.cloud.gcp.datastore.emulator-host` property. However, it remains the user's responsibility to start and stop the emulator.

The proposal is to add the `spring.cloud.gcp.datastore.emulator=true` property to automatically configure the emulator, start, and stop it. `LocalDatastoreHelper` from `google-cloud-java` can be used to accomplish it.

See discussion [here](https://github.com/spring-cloud/spring-cloud-gcp/issues/1430#issuecomment-481429999).

**Comment by lucasoares** [comment]
I created the issue on google github [here](https://github.com/googleapis/google-cloud-java/issues/4933) and I will submit the PR accepting a custom port.

**Comment by lucasoares** [comment]
@meltsufin google cloud lauched the release if my modification accepting port on the datastore emulator:
https://github.com/googleapis/google-cloud-java/releases/tag/v0.88.0

**Comment by meltsufin** [comment]
@lucasoares Would you be interested in a contributing a PR for it?

**Comment by lucasoares** [comment]
@meltsufin I can help with that but I'm not a spring contributor.. To do that I will need to change datastore client's version, but spring use the google client BOM in `spring-cloud-gcp-dependencies` and it will not let me change only the datastore version. What I should do in this case?

After that will be the easy part :)

If I continue with this contribution I will try to enter in some community chat to ask ppl questions like that. Thank you.
