### ISSUE TITLE
Make samples standalone 

### ISSUE THREAD

**Issue by ludoch** [spring-cloud/spring-cloud-gcp#1643]
The samples are in the same repo as the libraries...
If I check out the entire repo it is not clear how do I use a given sample with a given release (HEAD is not released)

The pom refers to the parent sample that refers to the parent...
This would not be the case for real customers apps, and they are struggling to adapt to a correct pom with the correct references to a released version of SpringBoot and the GCP integration.

**Comment by meltsufin** [comment]
I think it's a fair criticism, as more people are trying to use the samples directly rather than just looking at the code.

**Comment by dzou** [comment]
@meltsufin, what's your recommendation to begin starting work on this? I guess we first have to figure out where to first create a new repository?

**Comment by meltsufin** [comment]
I would disconnect the samples from the project parent.
Make the parent of each sample the spring boot parent.
```xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>...</version>
</parent>
```
