### ISSUE TITLE
Reenable tests affected by multiple DestinationResolver beans

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#1648]
When Spring Cloud Stream is compatible with Spring Integration 5.2:
* `PubSubExtendedBindingsPropertiesTests`
* `SampleAppIntegrationTest` in `spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample`
*  `SampleAppIntegrationTest` in `spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-polling-binder-sample`
* `LocalSampleAppIntegrationTest` in `spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-bus-config-sample`

**Comment by artembilan** [comment]
The fix is here: https://github.com/spring-cloud/spring-cloud-stream/pull/1690

**Comment by elefeint** [comment]
There is now a new failure: ```Caused by: java.lang.NoClassDefFoundError: org/springframework/integration/endpoint/Pausable```.

I'll look into that.

**Comment by meltsufin** [comment]
Same as here: https://github.com/spring-cloud/spring-cloud-gcp/issues/1715

**Comment by elefeint** [comment]
Mm, moved packages in https://github.com/spring-projects/spring-integration/commit/2fb7554dcfd7c585eabfbeb9f4069ad307a2c028. Must be a dependency version issue somewhere.

**Comment by elefeint** [comment]
PEBCAK. I thought I pulled the latest master, but I was missing the PR that fixed this issue.
