### ISSUE TITLE
Auto-create blob in Storage with GoogleStorageResource.getOutputStream()

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#165]
Our implementation of the `WritableResource` (`GoogleStorageResource`) doesn't currently auto-create the file when you call `getOutputStream(`), but it would be useful to automatically create it if it doesn't exist. This behavior would mirror the `FileSystemResource`.

**Comment by markfisher** [comment]
Should it be enabled/disabled by a boolean property?

**Comment by joaoandremartins** [comment]
That's something we considered. Maybe add flag protection and make it `true` by default?
However, it's not clear when a user would want this off. (Maybe unexpected quota/billing protection?)
Also, file creation on `getOutputStream()` is also always enabled for `FileSystemResources`..
