### ISSUE TITLE
Spanner session pooling - min/max sessions along with grpc channel configuration -recommendation needed

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1652]
Hi @meltsufin @ChengyuanZhao 

I want to know whats the recommended configuration required for min / max sessions on spanner. whats the ideal count of grpc channels to be configured?
Current defaults used in cloud spanner code min =10 sessions max=400 
and grpc channels defaults to 10.

Inorder to handle 100 TPS with spanner node count=2  what is the recommended min / max sessions to be configured and channel count ? Assuming most of our queries finish <50ms .

Any suggestion would greatly help.

**Comment by vineela-gampa** [comment]
@ChengyuanZhao @meltsufin  any update on this ?

**Comment by ChengyuanZhao** [comment]
@vineela-gampa Please direct query and Spanner performance questions to Cloud Spanner support. We focus on the integration with Spring Data and aren't the best source of advice on this question.

**Comment by vineela-gampa** [comment]
Sure got it.
