### ISSUE TITLE
Spanner taking longer to respond sometimes -Intermittently

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1653]
Hi @meltsufin  @ChengyuanZhao 

I observed spanner takes quite long sometimes to respond. It doesnt happen always but on some requests reads on a table (which has 200 records ONLY) took >2s .

i dont see any CPU Spike on spanner ?Unable to figure out why only few calls have that issues. If you have any insights to share where to start looking would greatly help. 

![image](https://user-images.githubusercontent.com/2513330/56251916-04d7b480-607b-11e9-968d-c97b47560b00.png)

**Comment by vineela-gampa** [comment]
@ChengyuanZhao @meltsufin do you guys have any update to share?

**Comment by ChengyuanZhao** [comment]
@vineela-gampa Is it apparent where the hang-up is? Is it possible to debug and step through the operation to see where the time is taken? You may want to direct this question to Cloud Spanner support , as Spring Data Spanner merely sends the query to Spanner using the client lib and doesn't participate in executing it.

**Comment by vineela-gampa** [comment]
No its not apparent. Sure will take it up there.
