### ISSUE TITLE
Datastore template and converter/mapper produces fluxes 

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#1659]
In effort to provide reactive repositories for Datastore we need to modify the converter/mapper to produce a flux from result set instead of doing the row-by-row iteration itself. 

The standard template can then also use this converter and simply consumes the entire flux before returning.

**Comment by meltsufin** [comment]
Closing, since we decided not to pursue reactive datastore.
