### ISSUE TITLE
Explore Spanner converter/mapper produces flux

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#1660]
This is the same effort as described for datastore in #1659

**Comment by ChengyuanZhao** [comment]
After much progress and discussion for our work in https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc it appears that we cannot use the client library's existing functionality for the Flux and Mono results. 

We may end up using the grpc layer directly for the reactive support while also using the client lib for the existing non-reactive functionality ?

**Comment by elefeint** [comment]
Superceded by Cloud Spanner R2DBC implementation.
