### ISSUE TITLE
spring.cloud.gcp.sql.credentials.location does not get picked up by runtime.

### ISSUE THREAD

**Issue by tafypz** [spring-cloud/spring-cloud-gcp#1679]
Using `org.springframework.cloud:pring-cloud-gcp-starter-sql-mysql:1.1.1.RELEASE` (same problem with 1.2.0.BUILD-SNAPSHOT)
While passing the property **`spring.cloud.gcp.sql.credentials.location`**, the default service account for the machine gets picked up instead of the account specified in the json file.
Using **`spring.cloud.gcp.credentials.location`** works fine and the account is picked up from the json file.

**Comment by meltsufin** [comment]
I'm not able to reproduce this problem. I just tried using `spring.cloud.gcp.sql.credentials.location` in the [MySQL sample](https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-sample) and when I put an invalid file in there, it fails. So, it's clearly being picked up.

Can you try to reproduce your issue on the sample?

**Comment by tafypz** [comment]
@meltsufin The sample code works however it is not using the property specified in the [documentation](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.1.0.RELEASE/single/spring-cloud-gcp.html#_spring_boot_starter_for_google_cloud_sql):
documentation mentions **`spring.cloud.gcp.sql.credentials.location`** but the sample code uses **`spring.cloud.gcp.credentials.location`**

**Comment by meltsufin** [comment]
How does it fail? Both properties are valid options. The first one just applies to all services vs. the second just for Cloud SQL. I tried `spring.cloud.gcp.sql.credentials.location` and it worked for me.

**Comment by tafypz** [comment]
@meltsufin My apologies, I misread the logging statement that came from the default credentials provider as a statement about the SQL credentials being used.

**Comment by sparmboy** [comment]
In case anyone still gets this issue, `CloudSqlEnvironmentPostProcessor` only logs an info message if it fails to find the file specified by `spring.cloud.gcp.sql.credentials.location`, and will proceed to use the default after that without failing.

`LOGGER.info("Error reading Cloud SQL credentials file.", ioe);`
