### ISSUE TITLE
Update App Engine app.yaml to use App Engine Java 11

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#1682]
There are currently some examples that are using App Engine Flex for deployment. App Engine Java 11 can deploy fat JARs going forward. It would be great to update & test the samples to use App Engine Java 11 when it's beta.

https://github.com/spring-cloud/spring-cloud-gcp/search?q=flex&unscoped_q=flex

**Comment by ttomsu** [comment]
Clarified with Ray: the request is also to move from GAE _Flex_ on Java 8 to GAE _Standard_ on Java 11.
