### ISSUE TITLE
Unable to convert class java.time.OffsetDateTime to Datastore supported type

### ISSUE THREAD

**Issue by chaurasiyashikhar** [spring-cloud/spring-cloud-gcp#1695]
In my Pojo class i have start date and end date field which is having OffsetDateTime data type, but i am not able to save in data store. getting below exception -

"Unable to write ExperienceFragmentData.startDateTime; nested exception is org.springframework.cloud.gcp.data.datastore.core.mapping.DatastoreDataException: Unable to convert class java.time.OffsetDateTime to Datastore supported type.

ExperienceFragmentData is extending ExperienceFragment and startDateTime field is present in ExperienceFragment parent class.

**Comment by dmitry-s** [comment]
java.time.OffsetDateTime type conversion is not supported out of the box, you would need to provide custom converters to and from Datastore supported type.

See [this section](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.1.0.RELEASE/single/spring-cloud-gcp.html#_custom_types_2) for details.

**Comment by meltsufin** [comment]
@mp911de Does Spring Data Commons support or have plans to support `java.time`?

**Comment by mp911de** [comment]
Spring Data has support for `java.time`. Specifically `OffsetDatetime` requires an offset to be provided along with the time date/time value and a mechanism in Datastore to store the offset in the same field.

You _could_ register a `Converter` to map `OffsetDateTime` to `String` if you think that's useful.
