### ISSUE TITLE
pom file forcing external repositories into a private build system

### ISSUE THREAD

**Issue by abgm** [spring-cloud/spring-cloud-gcp#1698]
This is a transitive dependency of my project that is built with a private nexus.
Build output : 
```
Downloading from gcs-mirror: https://maven-central.storage-download.googleapis.com/repos/central/data/io/grpc/grpc-core/maven-metadata.xml
[WARNING] Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to spring-snapshots (https://repo.spring.io/libs-snapshot-local): Connect to repo.spring.io:443 [repo.spring.io/35.241.58.96] failed: Connection timed out: con
nect
[WARNING] Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to spring-milestones (https://repo.spring.io/libs-milestone-local): Connect to repo.spring.io:443 [repo.spring.io/35.241.58.96] failed: Connection timed out: c
onnect
[WARNING] Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to spring-releases (https://repo.spring.io/release): Connect to repo.spring.io:443 [repo.spring.io/35.241.58.96] failed: Connection timed out: connect
[WARNING] Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to gcs-mirror (https://maven-central.storage-download.googleapis.com/repos/central/data): Connect to maven-central.storage-download.googleapis.com:443 [maven-c
entral.storage-download.googleapis.com/74.125.136.128] failed: Connection timed out: connect
```
https://github.com/spring-cloud/spring-cloud-gcp/blob/18778f5e77690a7038dfac9436e1b4fec3e0b388/pom.xml#L231

I already tried to turn off the spring profile via maven option but without success.
`mvn -U -V clean compile -P !spring`

related to : https://github.com/spring-cloud/spring-cloud-gcp/issues/1522

**Comment by meltsufin** [comment]
It looks like your private Nexus doesn't have some of the required dependencies for Spring Cloud GCP, like `io.grpc:grpc-core`.
Which version of Spring Cloud GCP are you using?

**Comment by abgm** [comment]
I can build with success.
But because this repositories are defined on this pom, maven try to get the maven-metadata.xml for them... 
This repositories definitions shouldn't be done on the pom file but on the maven setting...

**Comment by meltsufin** [comment]
The repositories are defined in the `spring` profile.
Try running `mvn package -P '!spring'`.

**Comment by abgm** [comment]
> The repositories are defined in the `spring` profile.
> Try running `mvn package -P '!spring'`.

`
C:\dev\my-services\service>mvn package -P '!spring'
[INFO] Scanning for projects...
[INFO]
[INFO] ----------< org.my:my-services >-----------
[INFO] Building my-services 0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from my-releases: https://nexus.tt.my.com/repository/my-releases-maven-proxy/io/grpc/grpc-core/maven-metadata.xml
Downloading from mavenlibrary: https://nexus.tt.my.com/repository/mavenlibrary/io/grpc/grpc-core/maven-metadata.xml
Downloading from mavenspringmilestone: https://nexus.tt.my.com/repository/mavenspring-milestone/io/grpc/grpc-core/maven-metadata.xml
Downloading from mavenspring: https://nexus.tt.my.com/repository/mavenspring/io/grpc/grpc-core/maven-metadata.xml
Downloading from my-other-releases: https://nexus.tt.my.com/repository/my-other-releases-maven2-nexus2-proxy/io/grpc/grpc-core/maven-metadata.xml
Downloading from my-commons: https://nexus.tt.my.com/repository/my-commons-maven-hosted/io/grpc/grpc-core/maven-metadata.xml
Downloaded from mavenlibrary: https://nexus.tt.my.com/repository/mavenlibrary/io/grpc/grpc-core/maven-metadata.xml (1.9 kB at 1.2 kB/s)
Downloaded from mavenspring: https://nexus.tt.my.com/repository/mavenspring/io/grpc/grpc-core/maven-metadata.xml (1.9 kB at 1.2 kB/s)
Downloading from my-releases-maven-hosted: https://nexus.tt.my.com/repository/my-releases-maven-hosted/io/grpc/grpc-core/maven-metadata.xml
Downloading from nexus: https://nexus.tt.my.com/repository/mavenlibrary/io/grpc/grpc-core/maven-metadata.xml
Downloading from spring-snapshots: https://repo.spring.io/libs-snapshot-local/io/grpc/grpc-core/maven-metadata.xml
Downloading from spring-milestones: https://repo.spring.io/libs-milestone-local/io/grpc/grpc-core/maven-metadata.xml
Downloaded from nexus: https://nexus.tt.my.com/repository/mavenlibrary/io/grpc/grpc-core/maven-metadata.xml (1.9 kB at 3.6 kB/s)
Downloading from spring-releases: https://repo.spring.io/release/io/grpc/grpc-core/maven-metadata.xml
Downloading from gcs-mirror: https://maven-central.storage-download.googleapis.com/repos/central/data/io/grpc/grpc-core/maven-metadata.xml
[WARNING] Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to spring-snapshots (https://repo.spring.io/libs-snapshot-local): Connect to repo.spring.io:443 [repo.spring.io/35.241.58.96] failed: Connection timed out: con
nect
[WARNING] Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to spring-milestones (https://repo.spring.io/libs-milestone-local): Connect to repo.spring.io:443 [repo.spring.io/35.241.58.96] failed: Connection timed out: c
onnect
[WARNING] Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to spring-releases (https://repo.spring.io/release): Connect to repo.spring.io:443 [repo.spring.io/35.241.58.96] failed: Connection timed out: connect
[WARNING] Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to gcs-mirror (https://maven-central.storage-download.googleapis.com/repos/central/data): Connect to maven-central.storage-download.googleapis.com:443 [maven-c
entral.storage-download.googleapis.com/64.233.185.128] failed: Connection timed out: connect
[INFO]
`

**Comment by abgm** [comment]
> It looks like your private Nexus doesn't have some of the required dependencies for Spring Cloud GCP, like `io.grpc:grpc-core`.
> Which version of Spring Cloud GCP are you using?
1.16.1 
`
[INFO] +- org.springframework.cloud:spring-cloud-gcp-pubsub-stream-binder:jar:1.1.0.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.1.3.RELEASE:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-gcp-pubsub:jar:1.1.0.RELEASE:compile
[INFO] |  |  +- com.google.cloud:google-cloud-pubsub:jar:1.59.0:compile
[INFO] |  |  |  +- com.google.cloud:google-cloud-core:jar:1.59.0:compile
[INFO] |  |  |  |  +- com.google.guava:guava:jar:26.0-android:compile
[INFO] |  |  |  |  |  +- org.checkerframework:checker-compat-qual:jar:2.5.2:compile
[INFO] |  |  |  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
[INFO] |  |  |  |  |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |  |  |  |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] |  |  |  |  +- joda-time:joda-time:jar:2.10.1:compile
[INFO] |  |  |  |  +- com.google.http-client:google-http-client:jar:1.27.0:compile
[INFO] |  |  |  |  +- com.google.api:api-common:jar:1.7.0:compile
[INFO] |  |  |  |  +- com.google.api:gax:jar:1.35.1:compile
[INFO] |  |  |  |  +- com.google.protobuf:protobuf-java-util:jar:3.6.1:compile
[INFO] |  |  |  |  |  \- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] |  |  |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.12.0:compile
[INFO] |  |  |  +- com.google.cloud:google-cloud-core-grpc:jar:1.59.0:compile
[INFO] |  |  |  |  +- com.google.auth:google-auth-library-credentials:jar:0.12.0:compile
[INFO] |  |  |  |  +- com.google.protobuf:protobuf-java:jar:3.6.1:compile
[INFO] |  |  |  |  +- io.grpc:grpc-protobuf:jar:1.16.1:compile
[INFO] |  |  |  |  |  \- io.grpc:grpc-protobuf-lite:jar:1.16.1:compile
[INFO] |  |  |  |  \- io.grpc:grpc-context:jar:1.16.1:compile
[INFO] |  |  |  +- com.google.api.grpc:proto-google-cloud-pubsub-v1:jar:1.41.0:compile
[INFO] |  |  |  +- com.google.api.grpc:grpc-google-cloud-pubsub-v1:jar:1.41.0:compile
[INFO] |  |  |  +- io.grpc:grpc-netty-shaded:jar:1.16.1:compile
[INFO] |  |  |  |  \- io.grpc:grpc-core:jar:1.16.1:compile (version selected from constraint [1.16.1,1.16.1])
[INFO] |  |  |  |     +- io.opencensus:opencensus-api:jar:0.12.3:compile
[INFO] |  |  |  |     \- io.opencensus:opencensus-contrib-grpc-metrics:jar:0.12.3:compile

`

**Comment by meltsufin** [comment]
You're actually using `1.1.0.RELEASE`.
In any case, I'm not sure why `!spring` is not working, but you should make sure that you actually have `grpc-core` in your private repository. If it was there, maven would not attempt to look elsewhere.

**Comment by abgm** [comment]
we have the jar on our nexus ... in more that one proxy for a public maven repo..
for  example:
```
Downloaded from mavenlibrary: https://nexus.tt.my.com/repository/mavenlibrary/io/grpc/grpc-core/maven-metadata.xml (1.9 kB at 1.2 kB/s)
 Downloaded from mavenspring: https://nexus.tt.my.com/repository/mavenspring/io/grpc/grpc-core/maven-metadata.xml (1.9 kB at 1.2 kB/s)
```

**Comment by meltsufin** [comment]
Interesting. I'm out of ideas here. Maybe someone else could help. @artembilan ?

**Comment by artembilan** [comment]
I'm not so good with Maven to determine the issue.

@abgm ,

If you think there is a problem in our project, feel free to raise a Pull Request with the fix and we will revise the final solution together with you.

Thank you for understanding.

**Comment by abgm** [comment]
Hi guys,

If I have time I will make a pull request for a possible solution.

I leave here some interesting links to create a solution.

https://github.com/takari/maven-wrapper/issues/4
https://github.com/gzm55/project-settings-maven-extension#example
> @Randgalt project-settings-extension fits corporate environment very well, it just loads the project-level settings at .mvn/settings.xml

https://blog.sonatype.com/2009/02/why-putting-repositories-in-your-poms-is-a-bad-idea/

> Each of these entries will end up in your consumer's builds since Maven needs to check them all for missing dependencies. Maven currently isn't able to tell when you introduce a repository which dependencies are supposed to be found there (and it gets worse when you consider transitivity).

**Comment by abgm** [comment]
You should remove the activeByDefault=true. You have this option force on .mvn/maven.config
I find an ugly solution for me, I'm putting mirrors to the repos I'm inheriting 
example
```
 [DEBUG] Using mirror mirror-spring-snapshots (https://nexus.tt.my.com/repository/spring-snapshots-libs-snapshot-local) for spring-snapshots (https://repo.spring.io/libs-snapshot-local).
```

https://github.com/spring-cloud/spring-cloud-gcp/blob/master/pom.xml#L228
```
 <profile>
	<id>spring</id>
	<activation>
	     <activeByDefault>true</activeByDefault>
	</activation>
	<repositories>
```

https://github.com/spring-cloud/spring-cloud-gcp/blob/master/.mvn/maven.config
``` 
-DaltSnapshotDeploymentRepository=repo.spring.io::default::https://repo.spring.io/libs-snapshot-local -P spring
```
**The spring-cloud-build don't have the activeByDefault=true**
https://github.com/spring-cloud/spring-cloud-build/blob/master/pom.xml#L675
```
<profile>
     <id>spring</id>
     <repositories>
```

**Comment by meltsufin** [comment]
Related to #1522 which was not resolved completely.
We need to apply the same fix to `pom.xml` as well.

**Comment by vincenzo-mazzotta** [comment]
I have below error the same that I see here:
`Downloading from spring-releases: https://repo.spring.io/libs-release/io/grpc/grpc-core/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/io/grpc/grpc-core/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/io/grpc/grpc-core/maven-metadata.xml (3.3 kB at 9.9 kB/s)
**[WARNING] Could not transfer metadata io.grpc:grpc-core/maven-metadata.xml from/to spring-releases (https://repo.spring.io/libs-release): Authentication failed for https://repo.spring.io/libs-release/io/grpc/grpc-core/maven-metadata.xml 401 Unauthorized**`

**Comment by elefeint** [comment]
@vincenzo-mazzotta Please open a new issue if you believe a Spring Cloud GCP dependency is adding Spring repos into your project. As it is currently, this project only activates the Spring repositories if a profile named "spring" is activated during build.
