### ISSUE TITLE
Release 1.0.0.M1 

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#170]
A tracking issue to capture MVP requirements 1.0 M1 release and to pushing M1 to Maven Central.

Current list: https://github.com/spring-cloud/spring-cloud-gcp/milestone/2

**Comment by saturnism** [comment]
should some of the 1.0.0.M1 issues be moved to M2?

**Comment by joaoandremartins** [comment]
Updated https://github.com/spring-cloud/spring-cloud-gcp/milestone/2 with what I think is remaining for an M1 release.
Most of it is already in-flight work in the form of PRs, we should be able to tackle the remaining ones in a day or two.

**Comment by joaoandremartins** [comment]
@sobychacko after #129, #178 and #183 are in, we are ready for our M1 release!

Are you able to help us, or point us to anyone who can?

How do we articulate to make this happen? Are you available any time this week to run the necessary scripts?

I imagine we'd need to temporarily change the version to 1.0.0.M1 for the deployment. It'd be preferable to do this with you on the line, so we can get on with the release and then roll back the version immediately after.

Thanks!

**Comment by saturnism** [comment]
also, if pub/sub client library is beta, can we GA the spring adapter? :/

**Comment by artembilan** [comment]
> if pub/sub client library is beta, can we GA the spring adapter?

No, we can't. Indeed.
But the story is about *milestone* and this is already fine to release.

When we are ready for GA, we definitely should ensure that client lib is GA as well.

**Comment by joaoandremartins** [comment]
We are now ready for an M1 release after merging #198.

@artembilan do you know who is able to run the scripts on your end?

**Comment by artembilan** [comment]
Sure! 
Let's ping @sobychacko !
He is a Build Master in our Lego City 😉 

Soby, let us know when you are able to release the `1.0.0.M1` for this project and what you need on the matter yet.

Thanks in advance!

**Comment by sobychacko** [comment]
@artembilan @joaoandremartins let me know when you are ready. I can push the release.

**Comment by markfisher** [comment]
is anyone planning a blog post? 😉

**Comment by joaoandremartins** [comment]
I'll be doing smoke tests on the current version. We should be all set on Tuesday to make the release, if nothing big comes up. @sobychacko I'll reach out to you through here on Tuesday!

@markfisher were you thinking of a blog post for the milestone or for the GA?

**Comment by markfisher** [comment]
a sneak preview (with a pointer to the getting started guide) plus 1.0 roadmap blog might be a nice way to attract some users to the milestone release

**Comment by joaoandremartins** [comment]
There are two things I see missing:
1) Service-specific project ID missing from Cloud SQL and Cloud Storage,
2) Reference document lacks a Spring Cloud Config section.

First one should be an easy fix. As for the second, I'll try to write something up until Tuesday.

**Comment by joaoandremartins** [comment]
Turns out that neither GCS nor SQL need the project ID, so disregard 1.

**Comment by joaoandremartins** [comment]
@artembilan @sobychacko can we do the release today?

**Comment by artembilan** [comment]
I don't have objections, but I'm afraid only @sobychacko is able to press the big red button.
So, let's wait from him!
Thanks

**Comment by joaoandremartins** [comment]
Alright, @sobychacko let me know when you're able to run the release scripts and if you need anything from us.

Off the top of my head, we would need to replace any `1.0.0.BUILD-SNAPSHOT` references in the whole project by `1.0.0.M1`. Let me know if the scripts can do this.

**Comment by sobychacko** [comment]
@joaoandremartins We can update the versions through maven. We will do the release tomorrow (11/2).

**Comment by joaoandremartins** [comment]
@sobychacko thanks a mil!

**Comment by sobychacko** [comment]
@joaoandremartins is it ready to start the `1.0.0.M1` release?

**Comment by joaoandremartins** [comment]
@sobychacko yes.

**Comment by sobychacko** [comment]
ok, I will ping here, once done.

**Comment by sobychacko** [comment]
@joaoandremartins why is the `spring-cloud-build` parent is kept at `1.3.3.BUILD-SNAPSHOT`. https://github.com/spring-cloud/spring-cloud-gcp/blob/master/pom.xml#L9
That needs to updated to a non snapshot version. Then need to test for another round.

**Comment by joaoandremartins** [comment]
Good catch! Please approve #228

**Comment by joaoandremartins** [comment]
@sobychacko the parent's version was changed, you're free to proceed with the release.

**Comment by sobychacko** [comment]
@joaoandremartins Could you make sure that no more commits to upstream/master until after the `1.0.0.M1` release?

**Comment by sobychacko** [comment]
@joaoandremartins could you merge pr https://github.com/spring-cloud/spring-cloud-gcp/pull/229?

**Comment by joaoandremartins** [comment]
@sobychacko no worries on the code freeze.

Regarding #229, do we want to clarify what will happen to the `examples` before we merge?

**Comment by sobychacko** [comment]
@joaoandremartins thanks for merging - starting the release.

**Comment by sobychacko** [comment]
@joaoandremartins @artembilan Release is completed. All the artifacts are available in the milestone repository at: http://repo.spring.io/libs-milestone-local/org/springframework/cloud

Repository is tagged with `v1.0.0.M1` here: https://github.com/spring-cloud/spring-cloud-gcp/releases/tag/v1.0.0.M1

https://github.com/spring-cloud/spring-cloud-gcp/pull/230 is issued to update the versions back to 1.0.0.BUILD-SNAPSHOT. Once that's merged, this issue can be closed.

**Comment by joaoandremartins** [comment]
Thanks a lot @sobychacko !

**Comment by joaoandremartins** [comment]
Do you know if the release table on the right in http://cloud.spring.io/spring-cloud-gcp/ will update automatically, or if we need to do anything to update it?

**Comment by artembilan** [comment]
I will update that page for us, @joaoandremartins !

Well, I would consider to exclude http://repo.spring.io/libs-milestone-local/org/springframework/cloud/spring-cloud-gcp-docs/ from the release as well. There is nothing in that jar for end-users...

**Comment by sobychacko** [comment]
docs are sync'd here: https://docs.spring.io/spring-cloud-gcp/docs/1.0.0.M1/

**Comment by artembilan** [comment]
Thank you @sobychacko !

@joaoandremartins , the project page has been updated. Now we have there `1.0.0 M1` bullet!

The question for everybody: where are our JavaDocs ?

Also some bug in the doc: there is no version mentioned on the first page. See Spring Kafka for example: https://docs.spring.io/spring-kafka/docs/2.0.0.RELEASE/reference/html/

**Comment by joaoandremartins** [comment]
@artembilan it isn't clear to me what's adding the version to your refdoc from https://raw.githubusercontent.com/spring-projects/spring-kafka/master/src/reference/asciidoc/index.adoc

The release commit isn't helpful either https://github.com/spring-projects/spring-kafka/commit/f68cdb6c1ed83304b7d84d19dc914c5b90e4faf4

I'm wondering if there is a script ran e.g., for spring-kafka and not for spring-cloud-gcp that adds the version to the refdoc?

**Comment by joaoandremartins** [comment]
@sobychacko do you know how we can publish the most recent layout of the refdoc?

e.g., when I build the document locally, I get this generated under `target/generated-docs`

![screenshot from 2017-11-03 12 06 39](https://user-images.githubusercontent.com/3290856/32383892-9ebd2c3e-c08f-11e7-84a5-980cd5dba559.png)

**Comment by artembilan** [comment]
@joaoandremartins ,

there is this one: https://github.com/spring-projects/spring-kafka/blob/master/src/reference/asciidoc/index-docinfo.xml

And pay attention to the `{spring-kafka-version}` placeholder which is populated from the Gradle task:
```
asciidoctor {
	sourceDir file("$docsDir")
	sourceDocumentNames = files("$docsDir/index.adoc") // Change in >= 1.5.1
	outputDir file("$buildDir/html")
	backends = ['html5', 'docbook']
	logDocuments = true
	options = [
		doctype: 'book',
		attributes: [
			docinfo: '',
			toc2: '',
			'compat-mode': '',
			imagesdir: '',
			stylesdir: "stylesheets/",
			stylesheet: 'golo.css',
			'spring-kafka-version': "$version",
			'source-highlighter': 'highlightjs'
		]
	]
}
```

Although I guess we can use existing `{project-version}` pretty well.

**Comment by joaoandremartins** [comment]
@artembilan do you know what reads `index-docinfo.xml`? Is it your docs scripts?

I tried to copy that approach and stage locally using `mvn clean install -P full`, but I'm not able to see the changes..

**Comment by artembilan** [comment]
Yeah... I think that is what done by this beast in Gradle:
```
apply plugin: DocbookReferencePlugin

reference {
	sourceFileName = 'index.xml'
	sourceDir = file("$buildDir/html")
	pdfFilename = 'spring-kafka-reference.pdf'
	expandPlaceholders = ''
}

reference.dependsOn asciidoctor
```

However I see that Spring Cloud Stream uses something similar for its Maven facet: https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-docs.

Sorry, I'm out of help here on the matter. Maybe @sobychacko can share the light how to be with docs? He is a one of contributors to that project.

Thanks

**Comment by joaoandremartins** [comment]
@sobychacko your help would be invaluable regarding the best way to add the project version to the reference document AND how to publish the reference document in the newer format I pasted above.

Thanks!
