### ISSUE TITLE
Spring Data Spanner Repositories `In` clause queries support

### ISSUE THREAD

**Issue by don-mayur** [spring-cloud/spring-cloud-gcp#1701]
Spring data spanner gives `java.lang.UnsupportedOperationException: The statement type: IN (1): [IsIn, In] is not supported.` when trying to use `IN` for selecting columns  part of a composite key in a SpannerRepository interface
`@Query("select * from <TableName> t where t.<columnName1>= @param1 AND t.columnName2 IN (@param2)")`
```Set<OnHandInventory> findBy<ColumnName1>And<ColumnName2>In(@Param("param1") String columnOneValue,@Param("param2") Set<Long> column2Values);```

Note: Exception being thrown at [SpannerStatementQueryExecutor.java](https://github.com/spring-cloud/spring-cloud-gcp/blob/72d746486fedd19b16ead3cdbbcfb48c3e90c3a9/spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/repository/query/SpannerStatementQueryExecutor.java#L399)

**Comment by ChengyuanZhao** [comment]
@don-mayur  

By the way it looks like your example method name is actually a `@Query` annotated SQL string, which means Spring Data Spanner wouldn't be aware of the contents of the string and the IN clause at all. 

It is only if you part-tree/name-convention query method like "findByCol1AndCol2In" without `@Query` annotation that the parsing would hit on that IsIn/In keyword  keyword.

**Comment by don-mayur** [comment]
@ChengyuanZhao Thanks for taking up on this issue, I have tried using method name such as findByCol1AndCol2In and then using some different name with `@Query` on top of it by referring some of Spring Data JPA examples. Unfortunately, none of the approaches worked.

**Comment by ChengyuanZhao** [comment]
@don-mayur  I added support in the referenced PR.
