### ISSUE TITLE
Maven cannot find artifact spring-cloud-gcp-starter-config

### ISSUE THREAD

**Issue by laszlocsontos** [spring-cloud/spring-cloud-gcp#1704]
**Description**

After adding `org.springframework.cloud:spring-cloud-gcp-starter-config` to `pom.xml` project fails to build. The [reference documentation states](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.1.1.RELEASE/single/spring-cloud-gcp.html#_spring_cloud_config), the coordinates for that starter, but it [doesn't seem to exist](https://search.maven.org/search?q=spring-cloud-gcp-starter-config). 

**Steps to reproduce**

1. Generate a new project on start.spring.io.

- Project: Maven
- Lang: Java
- Spring Boot: 2.1.6
- Dependencies: GCP Support

2. Add the following dependency to `pom.xml`

```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-gcp-starter-config</artifactId>
</dependency>
```

3. Try to compile the project

```
% ./mvnw package                                                                                                                 :(
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< com.example:demo >--------------------------
[INFO] Building demo 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.springframework.cloud:spring-cloud-gcp-starter-config:jar:1.1.1.RELEASE is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.817 s
[INFO] Finished at: 2019-06-19T16:29:24+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project demo: Could not resolve dependencies for project com.example:demo:jar:0.0.1-SNAPSHOT: Failure to find org.springframework.cloud:spring-cloud-gcp-starter-config:jar:1.1.1.RELEASE in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
./mvnw package  6.06s user 0.28s system 329% cpu 1.920 total
```

Am I doing something wrong?

I don't know if it's related, but `spring-cloud-gcp-starter-bus-pubsub` and `spring-cloud-gcp-starter-firestore` are also missing.

Thanks for your help!

- Laszlo

**Comment by meltsufin** [comment]
Config has not been released to Maven Central because it's still in Beta.
It's Spring Cloud policy not to publish modules to Maven Central which are not GA.
You can get it from the Spring Snapshots repository.

**Comment by meltsufin** [comment]
The other modules are not part of the 1.1 tack. They're available in 1.2 snapshots.

**Comment by laszlocsontos** [comment]
Looks this this in intentional: https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-starters/spring-cloud-gcp-starter-config/pom.xml#L31

A possible workaround might be to enable the milestones repo and specify the latest milestone manually.

```
  <repositories>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
    </repository>
  </repositories>

  <dependencies>
    ....
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-gcp-starter-config</artifactId>
      <version>1.1.0.M3</version>
    </dependency>
    ....
  <dependencies>
```

I don't know yet however if that has any undesirable side effects.

**Comment by meltsufin** [comment]
That works. You can also just use the latest build snapshot version.
`1.1.2.BUILD-SNAPSHOT`.
The 1.1.x tack is very stable because it's in maintenance mode.
