### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#171]
Integration tests for each service that we have local emulators for is a good start. e.g., Pub/Sub
This should also allow us to detect issues with our configuration property setup (e.g., detect when property names change).

**Comment by ChengyuanZhao** [comment]
Is the above check marks accurate so far?

**Comment by joaoandremartins** [comment]
We do have logging integration tests ready, too.
In terms of SQL, I think unit tests are enough? All our action is contained to prior to connecting to a database, we don't really have to talk to any other systems, so I would tick that one, too.

**Comment by ChengyuanZhao** [comment]
@meltsufin if you're fine with that for the SQL then we can do that last check mark.

**Comment by meltsufin** [comment]
I'm not sure I agree because we do generate the JDBC url and configure scopes. An integration test for that could be useful. #705 might be a substitute for a specific integration test though.
