### ISSUE TITLE
Credential passed from database at runtime for send data in pub sub / Set credential at runtime in PubSubTemplete or PubSubAdmin 

### ISSUE THREAD

**Issue by himanshukumar-ayla** [spring-cloud/spring-cloud-gcp#1711]
Spring boot provide feature to pass credential like : cloud.gcp.auth.location=file:/usr/local/...
i have all credential detail in my database , with multiple GCP account , i want to decide at runtime which google account i will use based on some condition.

Is there any option to pass credential at run time in PubSubAdmin or PubSubTemplete .

Thanks

**Comment by meltsufin** [comment]
`PubSubAdmin` constructor takes in a `CredentialsProvider`. You just have to create your own `PubSubAdmin` bean in your application context instead of the default one.
It's similar for `PubSubTemplate`, although there the beans are a bit more nested.

**Comment by meltsufin** [comment]
Please reopen if this didn't answer your question.
