### ISSUE TITLE
GCP PubSub Publisher retry settings issues

### ISSUE THREAD

**Issue by VenkataKrishnaVarmaPenumatsa** [spring-cloud/spring-cloud-gcp#1712]
We have the below configuration for the GCP PubSub publisher retry settings and on the GCP DEADLINE_EXCEEDED/NOT_FOUND/UNAVAILABLE exceptions the retry settings are not being considered and no attempt is made to republish the message to topic.
retry:
           max-attempts: 2
           total-timeout-seconds: 120
           initial-rpc-timeout-seconds: 60
           max-rpc-timeout-seconds: 120

spring-cloud-gcp-starter-pubsub version : 1.0.0.RELEASE
google-cloud-pubsub version: 1.54.0

**Comment by dzou** [comment]
Thanks for the report. Could you post your application config file so I can take a look?

**Comment by VenkataKrishnaVarmaPenumatsa** [comment]
Here are the properties config for the GCP:
spring:
 cloud:
    gcp:
      pubsub:
        project-id: test_Id
        publisher:
         executor-threads: 10
         batching:
          enabled: true
          element-count-threshold: 100
          flow-control:
             max-outstanding-element-count: 100
         retry:
           max-attempts: 2
           total-timeout-seconds: 120
           initial-rpc-timeout-seconds: 60
           max-rpc-timeout-seconds: 120
        subscriber:
          parallel-pull-count: 10
          max-ack-extension-period: 3600
          flow-control:
             max-outstanding-element-count: 100
      credentials:
        location: classpath:test.json

**Comment by dzou** [comment]
I did some experimentation locally and I was able to confirm that the settings are being processed/propagated by us correctly. 

Unfortunately, I was unable to reproduce an error condition in order to trigger a retry to occur and verify that it is being done.

Do you have instructions for how to reproduce this problem locally? Also, what environment are you running your application in?

**Comment by dzou** [comment]
Hey I was doing some more digging and I found where the retry settings are propagated to: https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java#L143

You can see this class is consuming the retry settings we provide and also provide a set of retryable codes:

```
StatusCode.Code.ABORTED,
StatusCode.Code.CANCELLED,
StatusCode.Code.DEADLINE_EXCEEDED,
StatusCode.Code.INTERNAL,
StatusCode.Code.RESOURCE_EXHAUSTED,
StatusCode.Code.UNKNOWN,
StatusCode.Code.UNAVAILABLE
```

I noticed one of the codes you listed `NOT_FOUND` is not in the list.

Do you have some error stack traces we can look at? Maybe the first thing we can do is to confirm that the error codes which are not being retried fall under this list.

**Comment by dzou** [comment]
Closing since there has been no response. Please reopen if the issue is still unresolved.
