### ISSUE TITLE
Extract roles from IAP access level claims

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#1716]
IAP JWK tokens now contain access level claims that can be used to provide role information used for authorization.

https://cloud.google.com/iap/docs/signed-headers-howto#verify_the_jwt_payload, https://cloud.google.com/access-context-manager/docs/overview#access-levels

**Comment by meltsufin** [comment]
Closing due to lack of demand from customers. Re-open if you're interested.
