### ISSUE TITLE
Error with compound repository method finding for ID and another field.

### ISSUE THREAD

**Issue by lucasoares** [spring-cloud/spring-cloud-gcp#1720]
Hello.

I found an issue with the data respository interface method construction probably caused after the closure of the issue #1683 

I created this repository:
```java
@Repository
public interface RoleRepository extends DatastoreRepository<Role, Long> {
  Role findByIdAndCompanyId(long id, long companyId);
}
```

This method doesn't works anymore if the object is also inserted with the new version of Spring Cloud GCP like this:

```java
    Role role = new Role();
    role.setId(123L);
    role.setCompanyId(444L);
    this.datastoreTemplate.save(role);
```

The id field is an `@Id`.

Even with the object on datastore, the repository interface method is not matching any object.

**Comment by dmitry-s** [comment]
@lucasoares could you provide the source code for Role so we can try to reproduce the issue?

Thanks

**Comment by lucasoares** [comment]
Here you are:

```java
@Data
@NoArgsConstructor
@Entity(name = "Role")
@Accessors(chain = true)
public class Role {
  @Id private Long id;
  private String name;
  private Long companyId;
}
```

**Comment by meltsufin** [comment]
Why aren't you just searching by ID? The ID is already unique. Try using `findById`.

**Comment by ChengyuanZhao** [comment]
Just to add some more detail @lucasoares , the change happened because we now store the ID directly in the Datastore Key for that entity and not as a separate field/property/column. As a result, it cannot appear in the GQL queries we generate for these query methods because there simply isn't a column name to refer to in the query. The only way to query using the ID property is to do a key-query via the findById method that works only on the key and no other conditions or columns.

**Comment by dmitry-s** [comment]
@lucasoares just to clarify: if you would like to find an entry and you have the ID, you do not need any extra conditions in the query, because ID is unique and entries can be uniquely identified by ID. Therefore, `findById` method should be used in that case.

Re-open the ticket if you still have questions.

**Comment by lucasoares** [comment]
@dmitry-s I have a specific product rule on my application that I will need to manually check the `companyId` field since the `id` field has nothing to do with the company itself. Its a security check.

Previously I was using this method to query for both properties at the same time to save some code and deal with security checks directly in the database. Now I will need to get the document to my application memory to validate the second attribute.

The issue #1683 is a breaking change then, because it can break production codes :P

**Comment by meltsufin** [comment]
@lucasoares Agreed that it's a breaking change, although we didn't think anyone was relying on the behavior where we were seemingly unnecessarily storing the id in a column. Our goal with the change was to remove the redundancy in storing the id and avoid the potential of the ids getting out of sync, which is possible, and given that it's a version jump from 1.1 to 1.2, we thougth it's an acceptable change.

That being said maybe @dmitry-s can recommend a workaround. You can add an additional id column, but maybe keeping it in sync with the actual id would be tricky.

**Comment by dmitry-s** [comment]
@lucasoares There is a workaround. You could use a `@Query` annotated method with a custom query, but you would need to convert your `id` to `Key` type. Something like this should work.

In the repository interface:
```
@Repository
public interface RoleRepository extends DatastoreRepository<Role, Long> {
  @Query("select * from |com.fully-qualified-name.Role|  where companyId=@compId and __key__ = @id")
  Role findByIdAndCompanyId(@Param("id") Key id, @Param(compId) long companyId);
}
```
In the class where you use this method you'll need to autowire ObjectToKeyFactory and DatastoreMappingContext to convert `long` to `Key`:
```
@Autowired
private ObjectToKeyFactory objectToKeyFactory;

@Autowired
private DatastoreMappingContext datastoreMappingContext;

....
Key key = this.objectToKeyFactory.getKeyFromId(123L,
    this.datastoreMappingContext.getPersistentEntity(Role.class).kindName());
this.testEntityRepository.getOneTestEntity(key, 2L);
....
```

I tested this approach and it worked for me. Let us know if you have questions.

**Comment by meltsufin** [comment]
Based on this workaround, it looks like we can just add support for it.

**Comment by lucasoares** [comment]
Interesting! I will try that approach and yes @meltsufin its an acceptable change!!

Thank you guys.
