### ISSUE TITLE
RW Transaction across schemas

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1721]
Hi @meltsufin @ChengyuanZhao 

Our current instance has 2 schemas defined on it.
Instance : core-inst 
                        -schema1
                        -schema2
Does spring cloud data spanner allow to have RW transaction across schemas in an instance ? An application 1 on schema 1 wants to update a row in table in schema 2 to maintain data consistency .

**Comment by ChengyuanZhao** [comment]
@vineela-gampa by "schema" do you mean database? Spanner only has transactions on single databases.

**Comment by meltsufin** [comment]
Assuming that schema and database are used as synonyms, the connection and hence the transactions are bound to a particular schema/database.

**Comment by vineela-gampa** [comment]
sorry about the mixup yes as schema i meant database.
