### ISSUE TITLE
Regarding org.springframework.cloud version1.2.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by srivraokp** [spring-cloud/spring-cloud-gcp#1722]
Hi,

When will version 1.2.0.BUILD-SNAPSHOT will available in Release Version, we are planning to use interleaved lazy feature which is not yet available in Greenwich version.

Thanks
Sri

**Comment by meltsufin** [comment]
1.2 is part of the Hoxton Spring Cloud release train. So, it will follow the release schedule for Hoxton.
See here: https://github.com/spring-cloud/spring-cloud-release/milestones.
