### ISSUE TITLE
Spanner Template :: Is there a way to read Bounded Staleness

### ISSUE THREAD

**Issue by srivraokp** [spring-cloud/spring-cloud-gcp#1723]
In SpannerTemplate is there a way to read records with bounded staleness instead of exact staleness

**Comment by meltsufin** [comment]
@ChengyuanZhao Do we support bounded staleness reads?

**Comment by ChengyuanZhao** [comment]
There is not. We only have the option to use exact staleness.

**Comment by srivraokp** [comment]
@ChengyuanZhao 
Thanks for taking up this fix,
The Scenario we have is while retrieving e-com orders we want to give a range of 5 to 10 seconds so that we get the latest modified record, instead of always going for exact
