### ISSUE TITLE
Cloudfoundry autoconfiguration for cloudsql is broken when java-cfenv is on the classpath

### ISSUE THREAD

**Issue by KamikaZeeFu** [spring-cloud/spring-cloud-gcp#1732]
Hi, 
when using spring-cloud-gcp in cloudfoundry in combination with java-cfenv, the integration is broken and no connection to bound cloudsql instances can be established.
The root cause is that `GcpCloudFoundryEnvironmentPostProcessor` is not setting `spring.datasource.url`, which means this property is set by cfenv.
Cfenv does not know about the special format the cloudsql socketfactory needs, so no connection can be established.

**Comment by meltsufin** [comment]
Is it possible to override `spring.datasource.url` to be an empty string with java-cfenv so that it's ignored?
How does it determine `spring.datasource.url` anyway?
@artembilan Anyone working on CF can advise us here?

**Comment by KamikaZeeFu** [comment]
cfenv-java is parsing VCAP_SERVICES, which contains the url to the instances public ip address.
java-cfenv is working on a feature to disable certain bindings, but that is yet to be merged.
Setting spring.datasource.url via the property source in `GcpCloudFoundryEnvironmentPostProcessor` would be the correct thing to do IMHO, since `@ConfigurationProperties` are populated from the environement's propertysources.

**Comment by artembilan** [comment]
I also don't see any problems with overriding it with the `GcpCloudFoundryEnvironmentPostProcessor`. Not sure though why VCAP_SERVICES doesn't provide a proper JDBC url in GCP environment...

I see there is an `AbstractJdbcUrlCreator` abstraction. So, maybe in case of GCP we need to introduce our own implementation and expose it as a `services`?..
See this module: https://github.com/pivotal-cf/java-cfenv/tree/master/java-cfenv-jdbc

**Comment by meltsufin** [comment]
Our auto-configuration for Cloud SQL works on the assumption that if `spring.datasource.url` is provided by the user or whatever is upstream, in this case CF, that's what the application wants to use to connect.
I think the onus is on whoever is specifying the URL to get it right, or just not specify it.
I'm confused as to why the URL specified doesn't work. If it's a public IP, it should just work. You don't need anything else. In fact, you don't need this module at all in that case. I would set `spring.cloud.gcp.sql.enabled=false`.

**Comment by meltsufin** [comment]
@KamikaZeeFu Can you please comment on why the URL with the public IP doesn't work? Or, if you've resolved the problem, please close this issue.

**Comment by KamikaZeeFu** [comment]
Hello, sorry for replying so late. In order to connect through the public IP one has to configure the cloudsql instance to allow the source IP range. Since IP addresses are not known beforehand in a dynamic platform such as cloud foundry, the range if possible addresses would be quite large.
That's why so far, we've been using spring-cloud-gcp resp. the cloudsql socket factory

**Comment by meltsufin** [comment]
@KamikaZeeFu I opened a PR that should resolve your issue and applies a more general change to the behavior of Cloud SQL auto-config.
