### ISSUE TITLE
Convertor for Key to String & vice versa

### ISSUE THREAD

**Issue by sumitkanoje** [spring-cloud/spring-cloud-gcp#1773]
Problem: Unable to convert String to Key while using `spring-cloud-gcp-data-datastore-sample`

Basically I'm writing `InstrumentRepository` as below

```
public interface InstrumentRepository extends DatastoreRepository<Instrument, Key> {

}
```

which will allow datastore operations on Instrument Entity. 
https://github.com/spring-cloud/spring-cloud-gcp/blob/8f233f616e4647403177e49549e6aa081b108b8b/spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/main/java/com/example/Instrument.java#L32-L35

But, Instrument entity has Key as type of `@Id` (shown above) since it is `@Descedent` of `Singer` Entity (Only Key types are allowed for descendants id)

So whenever I try to access/update using REST endpoint I get 

```
{
  "timestamp": "2019-07-27T10:03:44.846+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "No converter found capable of converting from type [java.lang.String] to type [com.google.cloud.datastore.Key]",
  "path": "/api/instruments/Key%7BprojectId=demo-app,%20namespace=,%20path=%5BPathElement%7Bkind=instruments,%20id=5673082664517632,%20name=null%7D%5D%7D"
}
```

I thought of writing `CustomConvertor` which will implement `keyToString` & `stringToKey` methods from `com.google.appengine.api.datastore.KeyFactory` like below

```
    static final Converter<String, Key> STRING_TO_KEY_CONVERTER =
            new Converter<String, Key>() {
                @Override
                public Key convert(String s) {
                    return KeyFactory.stringToKey(s);
                }
            };
```

But then I come to know that `stringToKey` is not available in `com.google.cloud.datastore.KeyFactory`

Shall I add dependency for `com.google.appengine.api.datastore.KeyFactory` into my project? Will this be a good approach? 

Am I doing it wrong? Can someone suggest approach to get it done?

**Comment by meltsufin** [comment]
@dmitry-s @ChengyuanZhao

**Comment by ChengyuanZhao** [comment]
I see the error when trying to read an instrument in the browser. 

```
@RepositoryRestResource(collectionResourceRel = "instruments", path = "instruments")
public interface InstrumentRepository extends DatastoreRepository<Instrument, Key> {

}
```

![image](https://user-images.githubusercontent.com/29288945/62059787-ddec5b00-b1f1-11e9-802c-e46ffe3bcb2f.png)



I'll try to figure it out.

**Comment by ChengyuanZhao** [comment]
What's happening is Spring Data REST repo stuff will read the Instrument entities available in the database and will parse the Key values and gives you these URLs you can visit , such as 

```
http://localhost:8080/instruments/Key%7BprojectId=amp-demo-landing-page,%20namespace=spring-demo,%20path=%5BPathElement%7Bkind=singers,%20id=3,%20name=null%7D,%20PathElement%7Bkind=instrument,%20id=5757334940811264,%20name=null%7D%5D%7D
```

If you try to visit that URL then Spring Data REST will parse that URL into this:
```
Key{projectId=amp-demo-landing-page, namespace=spring-demo, path=[PathElement{kind=singers, id=3, name=null}, PathElement{kind=instrument, id=5757334940811264, name=null}]}
```

Notice how all the ancestors and such are in that string. But this is just a JSON representation of the original Key object or something. Spring Data REST then tries to see if there's a converter to convert this JSON back into a Key to do the read for you. 

There isn't a JSON-to-Key converter defined anywhere, so this causes the error. 

@meltsufin @dmitry-s 

I wanna note that we can't just simply write a JSON-to-Key converter either. such a converter would have the type `Converter<String,Key>` but that conflicts with another possible meaning of that type where the string contents aren't parsed as JSON but simply refer to the Key's base value/name.

**Comment by ChengyuanZhao** [comment]
Wait! actually looks like we solved this issue in the Spanner module. 

We just need to make a bean that is  `ConditionalOnClass({BackendIdConverter.class,`

**Comment by sumitkanoje** [comment]
Hi @ChengyuanZhao, thanks for the prompt reply,

tried to figure out how this can be achieved with `ConditionalOnClass({BackendIdConverter.class,`
Can you please come up with an example to show its usage?

Also I came across a spring technique for handling such scenarios but not sure if it's applicable here,

I found someone writing a `SingerController` which can expose more endpoints for updating/adding new instruments as follows,

As shown in below controller
https://github.com/spring-projects/spring-petclinic/blob/master/src/main/java/org/springframework/samples/petclinic/owner/PetController.java

I was thinking if I can write such endpoint created in above `PetController` as follows

```
@Controller
@RequestMapping("/singers/{singerId}")
class InstrumentController {

    @Autowired
    private final SingerController singer;
    
    @Autowired
    private final InstrumentRepository instrument;

    constructor....

    @GetMapping("/instruments")
    public List<Instrument> findAll() {
        .....
    }

    @GetMapping("/instruments/{instrumentId}")
    public List<Instrument> findOne() {
        .....
    }

    @PostMapping("/instruments")
    public void createInstrument(Instrument instrument) {
        .....
    }

    @PostMapping("/instruments/{instrumentId}")
    public void updateInstrument(Instrument instrument) {
        .....
    }

}
```

**Comment by ChengyuanZhao** [comment]
@sumitkanoje I'll make the fix to the repo. I'll let you know when it's up.

**Comment by sumitkanoje** [comment]
Hi @ChengyuanZhao 

After I upgraded my codebase to `1.2.0.BUILD-SNAPSHOT` (latest one),
I was forced to change `@Reference` type from `org.springframework.cloud.gcp.data.datastore.core.mapping.Reference` to `org.springframework.data.annotation.Reference` due to which `@Reference` properties of any entity are not getting exposed in REST response, which was happening earlier,

Also whenever I post JOSN body with `@Reference` properties all the properties after `@Reference` property are stored as `null` in datastore.

In our case for Singer Entity, properties `personalInstruments, lastModifiedTime & albums` are saved as null in datastore, can you help how can I achieve updating `@Reference` from REST api?
Also how can we expose `@Reference` entity in JSON response of REST?

**Comment by dmitry-s** [comment]
Hi @sumitkanoje 

Could you provide the JSON that you post? I'll try to replicate the issue.

Thanks

**Comment by dmitry-s** [comment]
@sumitkanoje I suspect that the issue is not related to `@Reference`. Could you try removing that annotation and see if it works as expected?

**Comment by meltsufin** [comment]
Note that properties annotated with `@Id` are by default ignored by Spring Data REST. Also, please make sure that all other properties in the entity have public accessors.
