### ISSUE TITLE
Implement save/saveAll for firestoreTemplate

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#1779]

**Comment by ChengyuanZhao** [comment]
Regarding saveAll there are actually 2 cases in ReactiveCrudRepository.

- saveAll of a publisher 
- saveAll of an iterable 

The first case of the publisher I think we should just be reusing the singular save method we already have since we have no idea how long we would need to buffer the incoming entities before saving. We might as well save as we go. 

The second case I think we should be using the write(WriteRequest) batch save. 

We should do these in separate PRs. 

@dmitry-s @meltsufin  FYI

**Comment by meltsufin** [comment]
I think we should use `write(WriteRequest)` in both cases. It's just that for iterable, you'll only have to make a single call. For the publisher, you would send a series of batches, each one of size 1.
It's a streaming RPC. So, it should be pretty efficient.
```
  // Streams batches of document updates and deletes, in order.
  rpc Write(stream WriteRequest) returns (stream WriteResponse) {
    option (google.api.http) = {
      post: "/v1/{database=projects/*/databases/*}/documents:write"
      body: "*"
    };
  }
```

**Comment by ChengyuanZhao** [comment]
sorry if this is a dumb question, but are you saying that calling `write` with WriteRequests that have an array of only 1 document (https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1#google.firestore.v1.WriteRequest) repeatedly is automatically very efficient?

**Comment by meltsufin** [comment]
Right, I don't see a problem with that. The reason it should be efficient is because it's streaming. The fact that there's only one document in the array should not matter much. The point is that the series of `WriteRequest`s is streamed.

**Comment by ChengyuanZhao** [comment]
@meltsufin  For my curiosity: what does it mean that it's "streaming" ? 
From the docs it looks like they give you back a token/id you pass back and forth with each subsequent request. They look like just regular discrete requests physically and that the "streaming" part of it is more of abstract meaning given by one of the parameters (the stream token/id) .

**Comment by meltsufin** [comment]
Although the explanations are not very deep, GRPC docs describe streaming here: https://grpc.io/docs/guides/concepts/.
The idea is that backpressure is supported and there is no need for a round-trip for each request.

**Comment by dzou** [comment]
I believe this is now resolved.
