### ISSUE TITLE
Add feature to read datastore entity name from application.properties/external files with @Entity annotation

### ISSUE THREAD

**Issue by swathi-Hv** [spring-cloud/spring-cloud-gcp#1788]
While using the @Entity annotation for defining the kind in datastore, the "name" field as part of the annotation only accepts on constants. Is there a possibility to add a feature where this "name" can be read from a config file? Right now this support doesn't exist. 
The query to the datastore just returns empty values.

**Comment by ChengyuanZhao** [comment]
We can implement SpEL for the entity name so anything in the application context can be used in the kind name.

**Comment by meltsufin** [comment]
Please re-open if the suggestion didn't answer your question.
