### ISSUE TITLE
Firestore update/updateAll

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#1796]

**Comment by dzou** [comment]
@ChengyuanZhao - Is this just the same as saveAll()?

**Comment by ChengyuanZhao** [comment]
@dzou 

The updateall portion is done. However the update is not done because `save` needs to be rewritten to use saveall. Right now `save` uses the separate createdocumentrequest that is create-only. I don't think it works as an update-or-insert.

**Comment by dzou** [comment]
Ohh ok. I can take this task then - (if you are not goign to work on this)

**Comment by ChengyuanZhao** [comment]
It is yours my friend
