### ISSUE TITLE
Change Spring Integration module group

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-gcp#18]
The SI module is currently a child of the parent spring-cloud pom. We need to look in a way to make it more consistent with other SI modules and probably let it live on it's own pom.

Here's some things to keep in mind:

1. Doing this and leaving the module on this repo will cause issues on build process, as it would not be built with mvn commands
2. We will need a separate BOM to make sure that we are pulling and syncing the right libraries from spring-cloud-gcp

**Comment by meltsufin** [comment]
What if we stick with the same maven `groupId`, but name the module `spring-integration-gcp`? I understand that it would still require a `groupId` change when/if it moves out of `spring-cloud-gcp`, but at this point it doesn't seem likely, and even if it does happen, it wouldn't catastrophic.

**Comment by artembilan** [comment]
That's the plan, @meltsufin , at least in my feeling.

It will catastrophic because changing the group cause changing the Maven coordinates.
So, we should do that as soon as possible do not confuse external world.

At least in my understanding how we go...

**Comment by garyrussell** [comment]
I feel quite strongly that all SI modules should have consistent groupid/artifactids.

I don't really understand the issue - we can have a separate build plan for the SI module.

However, the consensus seems to feel differently so I will defer to the majority.

**Comment by joaoandremartins** [comment]
Is now a good time to revisit this? We should start seeing customers soon, hopefully.

**Comment by meltsufin** [comment]
After #360 is merged, we won't have a separate spring integration module.
