### ISSUE TITLE
Filter on Referenced entities

### ISSUE THREAD

**Issue by sumitkanoje** [spring-cloud/spring-cloud-gcp#1806]
I was trying to implement filter on referenced entities like below

```
class SingerRepository extends DatastoreRepository<Singer, String> {
    @Query("select * from singers where firstBand = @firstBand")
    filterSingersByfirstBand(@Param("firstBand") Band firstBand);
}
```
Above function throws `Unable to convert class Band to Datastore supported type` exception

So I changed type of `@Param` to `String` & wrote below query which will filter Singers based on Band id

```
@Query("select * from  singers where firstBand = :#{ 'key(bands,'''.concat(#firstBandId).concat(''')') }")
filterSingersByfirstBand(@Param("firstBand") String firstBandId);
```

After going through logs it show `@SpELtag1` is correctly calculated as key literal ex. `key(bands, 'General Band')`

But still the output of this function is an empty array, Can someone explain how can I filter on referenced entity?

If manually write query as `select * from  singers where firstBand = key(bands, 'General Band')` function returns filtered singers.

**Comment by dmitry-s** [comment]
In order to make it work you could convert the object id to a key and make your method param `Key`:
```java
@Query("select * from  |com.example.Singer| where firstBand = @firstBandKey")
List<Singer> filterSingersByfirstBand(@Param("firstBandKey") Key firstBandKey);
```
You would need to autowire `DatastoreTemplate` into the class where you use this query method:
```java
@Autowired
DatastoreTemplate datastoreTemplate;
```
After that you can use it like this:
```java
singerRepository.filterSingersByfirstBand(datastoreTemplate.createKey(Band.class, band.getName())
```
I created an issue for making object to key conversion automatic: #1810 

Please reopen if that doesn't help.

**Comment by sumitkanoje** [comment]
Working, thanks 👍
