### ISSUE TITLE
Modify Documentation to reuse spring-cloud-build

### ISSUE THREAD

**Issue by dzou** [spring-cloud/spring-cloud-gcp#1812]
It was recommended to us on gitter by Spring folks that we ought look into reusing spring-cloud-build for our documentation.

See: https://github.com/spring-cloud/spring-cloud-build#reusing-the-documentation

Reusing the Spring docs infrastructure should make our lives easier ? Or be better ? Investigate what this means exactly.

Followup to #1811

**Comment by meltsufin** [comment]
Obsolete.
