### ISSUE TITLE
Docs Page is Broken

### ISSUE THREAD

**Issue by averikitsch** [spring-cloud/spring-cloud-gcp#1814]
Link to [spring-cloud-gcp](https://cloud.spring.io/spring-cloud-gcp/reference/html/) gives a 404.

**Comment by meltsufin** [comment]
Yep, https://github.com/spring-cloud/spring-cloud-gcp/pull/1811

**Comment by dzou** [comment]
Just in case you were looking for the docs, you can try this link which works: https://spring.io/projects/spring-cloud-gcp#overview

**Comment by dzou** [comment]
Ok, the link should be working now: https://cloud.spring.io/spring-cloud-gcp
