### ISSUE TITLE
Performance of firestoreTemplate.saveAll() seems slower than Client Libraries

### ISSUE THREAD

**Issue by dzou** [spring-cloud/spring-cloud-gcp#1827]
I noticed while testing firestoreTemplate.saveAll changes, it seems like client libraries are much faster at performing a saveAll() than the reactive pattern.

See experiments: https://github.com/spring-cloud/spring-cloud-gcp/pull/1826

**Comment by meltsufin** [comment]
This is possibly caused by our write batch always being of size 1.

**Comment by dzou** [comment]
Resolved after implementing batching.
