### ISSUE TITLE
Can not write to local datastore emulator

### ISSUE THREAD

**Issue by vtnlinh95** [spring-cloud/spring-cloud-gcp#1828]
Hi,
I am trying to save an entity to the local datastore emulator but there is nothing happen when I use Postman sending a request to my REST API. I have debugged the API and I could see that the entity is created and my datastore is my localhost:8081. 
There is no error log and the local_db.bin is not created.
I try to query the datastore and there is nothing.

One more point: I can access to localhost:8081 (my datastore emulator host) but I get 404 when I get access to localhost:8081/datastore.

**Comment by dmitry-s** [comment]
@vtnlinh95 
Was the issue resolved? If not, please provide more details on how to replicate the issue.

Thanks!

**Comment by vtnlinh95** [comment]
Yes, the problem is resolved because the datastore has option not to write on disk. That is the reason why I can not find the local_db.bin file
