### ISSUE TITLE
Batch processing of stores

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#1842]
Hi @ChengyuanZhao / @meltsufin 

We have a blocker where we are currently processing an excel - which attributes to 60000 mutations. Ask from business is do a flush and fill. (so we are using deleteAll and insertAll as part of RW transaction by chunking 20,000 each) due spanner limitation.

> com.google.cloud.spanner.SpannerException: INVALID_ARGUMENT: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: The transaction contains too many mutations. Insert and update operations count with the multiplicity of the number of columns they affect. For example, inserting values into one key column and four non-key columns count as five mutations total for the insert. Delete and delete range operations count as one mutation regardless of the number of columns affected. The total mutation count includes any changes to indexes that the transaction generates. Please reduce the number of writes, or use fewer indexes. (Maximum number: 20000)
links {
  description: "Cloud Spanner limits documentation."
  url: "https://cloud.google.com/spanner/docs/limits"

> }

If multiple people are using our application at the same time its possible 
Thread T1 deleted and started processing inserts an excel. 
Thread T2 started deleting after inserts on T1 started .

One way is to maintain a lock in a table if one thread is updating and reject the other request when another thread is doing it. 

Do you have any recommendations for this problem ?

**Comment by ChengyuanZhao** [comment]
If I'm understanding your situation correctly I think you can simply have T1 and T2 both operate in their own transactions  (either by submitting the chunking work all within an anonymous function or using the Transactional annotation). 

If you are deleting and inserting those 60k rows from both threads and T2 starts its transaciton before T1 closes its transaction then  any of the rows touched by T1 cannot be touched by T2 (T2 will fail). 

However if T1 might commit before T2 then you'll simply have the work performed twice without any exceptions.
