### ISSUE TITLE
PubSub creating consumer group and not picking existing subscription

### ISSUE THREAD

**Issue by turboT4** [spring-cloud/spring-cloud-gcp#1844]
Been trying to deploy my service recently and just noticed that I may be not understading some concepts well...

`spring.cloud.stream.bindings.output.destination=output-topic
spring.cloud.stream.bindings.output.binder=pubsub
spring.cloud.stream.bindings.input.destination=input-topic
spring.cloud.stream.bindings.input.group=input-subscription
spring.cloud.stream.bindings.input.binder=pubsub`

I have just created all those queues and the mentioned `input-subscription` which points to `input-topic`. However, with this config, a new subscription called `input-topic.input-subscription` is created by Spring, and right now its failing because of the policy (the service shouldn't be able to create any queue or subscription)

Is there any config or concept that I'm missing out?

**Comment by meltsufin** [comment]
Please see [this section](https://cloud.spring.io/spring-cloud-gcp/reference/html/#_consumer_destination_configuration) in the reference documentation.
There is a note there clarifying it:

> If you are manually creating Pub/Sub subscriptions for consumers, make sure that they follow the naming convention of `<destinationName>.<consumerGroup>`.


If you want to make sure that resources are not created automatically, set this property:

```
spring.cloud.stream.gcp.pubsub.bindings.events.consumer.auto-create-resources=false
```

**Comment by turboT4** [comment]
My bad for not looking enough into the docs! Going fast while developing is clearly not the solution :)

Just a quick doubt  @meltsufin regarding the conversion, and being a conversion wouldn't make much of a point to ask this but... Is there any option to change the delimiter so that the `.` becomes a `-` or any other char?

**Comment by meltsufin** [comment]
There isn't really an easy way to override it. You'd have to extend `PubSubChannelProvisioner` and make the changes there.

**Comment by turboT4** [comment]
Got you @meltsufin , thanks a lot!
