### ISSUE TITLE
Support PubSub topic resolution from message header

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#19]
Header would have precedence over `PubSubTemplate`'s `topic` field.

Some good examples are the Kafka and Kinesis adapters:
https://github.com/spring-projects/spring-integration-aws/blob/master/src/main/java/org/springframework/integration/aws/outbound/KinesisMessageHandler.java#L93
https://github.com/spring-projects/spring-integration-kafka/blob/master/src/main/java/org/springframework/integration/kafka/outbound/KafkaProducerMessageHandler.java#L147

More discussion [here](https://github.com/spring-cloud/spring-cloud-gcp/pull/14/files/a379cc599773c86a402b0a6b365331c8bdc39e7f#diff-b9e1539c9f93aaee09ea016f3c777faa).

**Comment by artembilan** [comment]
The `topicExpression` should be as an option as well. The same Kinesis and Kafka sample.
All that is based on the [SpEL](http://docs.spring.io/spring/docs/4.2.9.RELEASE/spring-framework-reference/html/expressions.html) and its support in [Spring Integration](http://docs.spring.io/spring-integration/reference/html/spel.html).
