### ISSUE TITLE
Please provide a changelog

### ISSUE THREAD

**Issue by honnel** [spring-cloud/spring-cloud-gcp#1907]
Is there any way to see the differences between released versions?
Additionally whats the current stable version? 
https://spring.io/projects/spring-cloud-gcp says 1.2.0
https://github.com/spring-cloud/spring-cloud-gcp/releases says 1.1.3

**Comment by meltsufin** [comment]
You're right we need to do better with release notes.
The current GA (stable) version is `1.1.3`.
Version 1.2.0 is not GA yet, but it's close. If you want the latest changes, use `1.2.0.M2`.
We'll work on the release notes. I believe we can just generate them from the closed issues list.
