### ISSUE TITLE
Pub/Sub documentation for polling is wrong.

### ISSUE THREAD

**Issue by lucasoares** [spring-cloud/spring-cloud-gcp#1910]
The [PubSubReactiveFactory](https://github.com/spring-cloud/spring-cloud-gcp/blob/v1.2.0.M2/spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/reactive/PubSubReactiveFactory.java) doesn't have the method createPolledFlux like documented [here](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.0.M2/reference/html/spring-cloud-gcp.html#_reactive_stream_subscription).

It should be just `poll`.

**Comment by elefeint** [comment]
Good catch, thank you!

**Comment by lucasoares** [comment]
I'm going to fix this right now!
