### ISSUE TITLE
missing artifact "spring-cloud-gcp-logging" in "spring-cloud-gcp-starter-logging"

### ISSUE THREAD

**Issue by praveen4463** [spring-cloud/spring-cloud-gcp#1915]
I am using spring-cloud-gcp's **stackdriver logging** component. After adding the following starter, it turned out that one of the artefact `spring-cloud-gcp-logging` is missing as maven couldn't find and download it.

Due to this, the resource like `org/springframework/cloud/gcp/logging/logback-appender.xml`is missing. I believe the artefacts published to maven central needs to be fixed.

spring cloud gcp BOM version - `1.1.3.RELEASE`
starter used - `spring-cloud-gcp-starter-logging`

More clearly, the second artefact `<artifactId>spring-cloud-gcp-logging</artifactId>` from starter [spring-cloud-gcp-starter-logging](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-starters/spring-cloud-gcp-starter-logging/pom.xml) wasn't found by maven.

**Comment by meltsufin** [comment]
@praveen4463 Spring Cloud GCP version `1.1.x` doesn't have the `spring-cloud-gcp-logging` module. It was introduced in `1.2.x`. Please refer to the [version-specific documentation](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.1.3.RELEASE/multi/multi__stackdriver_logging.html#_log_via_api), which explains that you should use `org/springframework/cloud/gcp/autoconfigure/logging/logback-appender.xml`.
