### ISSUE TITLE
Support for Cloud Tasks?

### ISSUE THREAD

**Issue by johkin** [spring-cloud/spring-cloud-gcp#1917]
Do you have any plans of adding support for the Cloud Tasks service? In that case, when could that be expected?

**Comment by meltsufin** [comment]
@johkin Can you please provide more details on what kind of support for Cloud Tasks you have in mind? Are you using Spring Batch, Spring Cloud Stream, or Spring Cloud Task?

**Comment by johkin** [comment]
Sorry, didn't think of the ambiguity. I'm interested in using GCP Cloud Tasks (https://cloud.google.com/tasks/).
I guess the implementation could be somewhat similar to PubSub?

**Comment by meltsufin** [comment]
We also have several integrations for Pub/Sub. I guess the more basic one would be `CloudTasksTemplate` and the Spring Integration channel adapter built on top of that.

**Comment by meltsufin** [comment]
Closing in favor of https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/156.
