### ISSUE TITLE
Remove custom brave version

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#1932]
This is follow up to #1870 
Related: openzipkin/zipkin-gcp#146

Needs to be done in both 1.2 and 1.1 branch.

**Comment by meltsufin** [comment]
I don't think we'll be upgrading in the 1.1.x branch.

**Comment by elefeint** [comment]
This was done in #2019.
We should keep the `brave` [exclusion](https://github.com/spring-cloud/spring-cloud-gcp/blob/c4c3256be7da01e0800bae14239ab981df9cdb3e/pom.xml#L128) in `brave-propagation-stackdriver` because the version should consistently come from `spring-cloud-sleuth`.
