### ISSUE TITLE
Documentation question for Pub/Sub of `spring.cloud.gcp.pubsub.subscriber.parallel-pull-count`

### ISSUE THREAD

**Issue by lucasoares** [spring-cloud/spring-cloud-gcp#1933]
Hello.

The documentation says that the number of parallel-pull-count for Subscriber is the number of available cores:
![image](https://user-images.githubusercontent.com/10624972/65621376-04343a00-df9a-11e9-8180-c4664f529156.png)

Looking at the code the default number for Google's Subscriber lib is 1.
![image](https://user-images.githubusercontent.com/10624972/65621400-0eeecf00-df9a-11e9-9865-d42451ce7f80.png)

I didn't found the default value being set to the number of available cores anywhere on Spring GCP code. Is this still true?

**Comment by meltsufin** [comment]
Spring Cloud GCP simply doesn't set this parameter, when it's not specified in configuration. So, it relies on the default in the Google Cloud Java Pub/Sub client library.
It used to be the number of cores, but has changed [here](https://github.com/googleapis/google-cloud-java/pull/3147/files#diff-5c59d3b131c625ad32cdcbf7e4b3ea53L452).
We just need to update our documentation.

@lucasoares Thanks for bringing this to our attention. PRs are always welcomed. :wink:
