### ISSUE TITLE
Spring cloud GCP should use plainText to communicate with a PubSub emulator

### ISSUE THREAD

**Issue by lucasoares** [spring-cloud/spring-cloud-gcp#1955]
Hello.

I'm getting lots of errors trying to use the PubSub emulator with Spring Cloud GCP lib.

For example trying to use the `PubSubAdmin` to check if a topic exists, I get this message:
```Status{code=UNIMPLEMENTED, description=Method not found: google.pubsub.v1.Publisher/GetTopic, cause=null}```

Apparently the PubSub emulator can't receive all gRPC messages correctly.

Google's example of PubSub emulator usage are using plainText in the channel to communicate with the emulator: https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-examples/src/main/java/com/google/cloud/examples/pubsub/snippets/UsePubSubEmulatorSnippet.java#L42

With some research I didn't found any way to change the communication with the Spring Cloud GCP lib. There is any way to do that or we need to implement this?

**Comment by lucasoares** [comment]
I created this question on StackOverflow: https://stackoverflow.com/questions/58204646/error-using-pubsub-emulator-with-spring-cloud-gcp-unimplemented-method-not-fou because I'm having big issues trying to use the Spring Cloud GCP PubSub to connect to an emulator.

**Comment by dzou** [comment]
Hey @lucasoares, could you provide a reproducible sample for us?

**Comment by lucasoares** [comment]
Hello @dzou 

I executed the same test today and it passes without any error.
I really don't know if it was my environment or any dependency issue.

I will close this issue now and re-open if necessary. Sorry for the inconvenience.

**Comment by dzou** [comment]
No worries, thanks for asking; we really appreciate users posting issues and asking questions.
