### ISSUE TITLE
Firestore implement/document emulator support

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#1956]

**Comment by eddumelendez** [comment]
@dmitry-s shall we expect something like `LocalDatastoreHelper` from https://github.com/googleapis/google-cloud-java?

**Comment by p595285902** [comment]
Wondering if the test in the [sample](https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample) is using the real database.

**Comment by meltsufin** [comment]
@p595285902 Yes it does. Are you looking for instructions on how to run it with an emulator?

**Comment by p595285902** [comment]
Yeah, or something guide on how to run my end to end tests without impacting the real data. Was thinking if I need set the `spring.cloud.gcp.firestore.project-id` to a test only project.

**Comment by meltsufin** [comment]
You can definitely set a different project id for the tests, until we add the emulator support/documentation.
