### ISSUE TITLE
DatastoreHealthIndicator.doHealthCheck should throw a checked exception

### ISSUE THREAD

**Issue by elharo** [spring-cloud/spring-cloud-gcp#1976]
Running tests I noticed this in the logs:
```
2019-10-09 09:14:35.659 [main] WARN  o.s.c.g.a.d.h.DatastoreHealthIndicator - Datastore health check failed
java.lang.RuntimeException: Cloud Datastore is down!!!
	at org.springframework.cloud.gcp.autoconfigure.datastore.health.DatastoreHealthIndicator.doHealthCheck(DatastoreHealthIndicator.java:57)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
```

This is exactly the case for which checked exceptions were designed, an external condition that cannot be prevented in the project's code. 

The `doHealthCheck` method that this method overrides is declared to throw java.lang.Exception  so there's no problem with the signature here.

**Comment by elharo** [comment]
Stackdriver AsyncReporter seems to have the same issue, probably elsewhere too


on - Error when performing Stackdriver AsyncReporter health check.
java.lang.RuntimeException: null
	at org.springframework.cloud.gcp.autoconfigure.trace.StackdriverTraceAutoConfigurationTests.testAsyncReporterHealthCheck(StackdriverTraceAutoConfigurationTests.java:152)

**Comment by meltsufin** [comment]
> Running tests I noticed this in the logs:
> 
> ```
> 2019-10-09 09:14:35.659 [main] WARN  o.s.c.g.a.d.h.DatastoreHealthIndicator - Datastore health check failed
> java.lang.RuntimeException: Cloud Datastore is down!!!
> 	at org.springframework.cloud.gcp.autoconfigure.datastore.health.DatastoreHealthIndicator.doHealthCheck(DatastoreHealthIndicator.java:57)
> 	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
> ```
> 
> This is exactly the case for which checked exceptions were designed, an external condition that cannot be prevented in the project's code.
> 
> The `doHealthCheck` method that this method overrides is declared to throw java.lang.Exception so there's no problem with the signature here.

I don't see any point in wrapping the runtime exception produced by the datastore client library into a checked exception because `doHeathCheck` is a protected method and is only used internally by `AbstractHealthIndicator.health()`. All exceptions get swallowed and turned to a "down" status there anyway. See [source](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/AbstractHealthIndicator.java).

**Comment by meltsufin** [comment]
> Stackdriver AsyncReporter seems to have the same issue, probably elsewhere too
> 
> on - Error when performing Stackdriver AsyncReporter health check.
> 
> ```
> java.lang.RuntimeException: null
> 	at org.springframework.cloud.gcp.autoconfigure.trace.StackdriverTraceAutoConfigurationTests.testAsyncReporterHealthCheck(StackdriverTraceAutoConfigurationTests.java:152)
> ```

I think this has more to do with the mocks in the test. @elefeint @dzou WDYT?

**Comment by elharo** [comment]
No, I don't think the mocks are at issue here. The problem I'm reporting is not that an exception is thrown but that the wrong exception is thrown. Looking at the signature of these methods they aren't declared to throw any checked exception. Unless the health checks always pass (in which case why perform them)  a failing health check for an external service should be a checked exception, not a runtime exception.

**Comment by meltsufin** [comment]
The public API of the health indicator does not throw any exceptions. Instead it returns a `Health` object that indicates whether the service is `UP` or `DOWN`. See: https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/AbstractHealthIndicator.java#L79

The exception, whether checked or not, is an internal implementation detail used [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/health/AbstractHealthIndicator.java#L84).
Am I missing something?

**Comment by elharo** [comment]
`DatastoreHealthIndicator.doHealthCheck` is a protected method in a public class, so it's part of the published API. Thus the exceptions it throws are not internal implementation details.

Even if they were internal implementation details, though, it's still useful to use checked exceptions for external sources of error to guarantee that handlers are in place where they need to be. Internal code is just as susceptible to missing a needed exception handler as external code.

**Comment by meltsufin** [comment]
Agreed regarding the general case. However, the source of the exception is the Datastore API and the exception is unchecked there. Furthermore, there are dozens of other `AbstractHealthIndicator` implementations in Spring, and not one that I looked at uses a checked exception. So, I assume that's a stylistic choice that Spring made, which we may disagree with but should probably still follow.

**Comment by elharo** [comment]
Possibly a bug in the datastore API too then. What's the call?

AbstractHealthIndicator itself does use a checked exception.

**Comment by meltsufin** [comment]
`Datastore.run()` [method](https://github.com/googleapis/google-cloud-java/blob/master/google-cloud-clients/google-cloud-datastore/src/main/java/com/google/cloud/datastore/Datastore.java#L446).
The `DatastoreException` is not checked.

**Comment by dzou** [comment]
> > Stackdriver AsyncReporter seems to have the same issue, probably elsewhere too
> > on - Error when performing Stackdriver AsyncReporter health check.
> > ```
> > java.lang.RuntimeException: null
> > 	at org.springframework.cloud.gcp.autoconfigure.trace.StackdriverTraceAutoConfigurationTests.testAsyncReporterHealthCheck(StackdriverTraceAutoConfigurationTests.java:152)
> > ```
> 
> I think this has more to do with the mocks in the test. @elefeint @dzou WDYT?

Yeah, the tests will always produce these logs because the test intentionally produces a failure condition and verifies that a warning was indeed logged if the health check failed.

We did things this way because this is like a Spring convention/style to log things like this rather than throw checked exception; like the main guy working on Spring Cloud Sleuth told us to implement the stackdriver health check in that way. Yeah, I see your logic justifying the CheckedException; however I think we are just trying to match the existing conventions/expectations in Spring framework... which may not be the optimal convention outside this context
