### ISSUE TITLE
CONTRIBUTING.adoc incomplete

### ISSUE THREAD

**Issue by elharo** [spring-cloud/spring-cloud-gcp#1977]
It seems there's a gap between CONTRIBUTING.adoc and getting `mvn test` to pass. At a minimum, one also needs to install the Cloud SDK and the cloud datastore emulator. There might well be other setuup steps to perform. We should document these in sufficient detail that a developer can go from `git clone` to `mvn test` passing without having to contact the development team.

**Comment by meltsufin** [comment]
Ah, yes, we have neglected that document and need to bring it up to date. We should make sure that all emulator tests can be easily disabled so that gcloud would not be required for unit tests.
Thanks for reporting this!
