### ISSUE TITLE
@Transactional not rolling back Spanner Transactions

### ISSUE THREAD

**Issue by srivraokp** [spring-cloud/spring-cloud-gcp#1980]
@Transactional is not rolling back the transaction

Attached is the code,

[Code.txt](https://github.com/spring-cloud/spring-cloud-gcp/files/3715887/Code.txt)

@ChengyuanZhao @meltsufin can you please help me on this

**Comment by srivraokp** [comment]
This is working fine in 1.1.3.RELEASE but failing in 1.2.0.M3

**Comment by meltsufin** [comment]
@srivraokp We have [an integration test for rollback](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-spanner/src/test/java/org/springframework/cloud/gcp/data/spanner/repository/it/SpannerRepositoryIntegrationTests.java#L269), and it seems to be passing.

I find the code you use to create `SpannerTransactionManager` problematic:

> ```java
>         @Bean
> 	public SpannerTransactionManager transactionManager() {
> 		SessionPoolOptions sessionPoolOptions = SessionPoolOptions.newBuilder()
> 				.setFailIfPoolExhausted()
> 				.setMinSessions(0)
> 				//.setMaxSessions(2)
> 				.build();
> 		SpannerOptions options = SpannerOptions.newBuilder()
> 				.setSessionPoolOption(sessionPoolOptions)
> 				.build();
> 		Spanner spanner = options.getService();
> 		DatabaseId db = DatabaseId.of(options.getProjectId(), spannerInstance, spannerdatabase);
> 		DatabaseClient dbClient = spanner.getDatabaseClient(db);
> 		return new SpannerTransactionManager(() -> dbClient);
> 	}
> ```

You are basically binding the transaction manager to a new instance of the Spanner `DatabaseClient`, but it's not the same `DatabaseClient` that will be available in the Spring application context and used by Spring Data.

In your code, you're only customizing the `SessionPoolOptions`. So, you really only need to override that bean in your configuration.

try:
```java
        @Bean
	public SessionPoolOptions sessionPoolOptions() {
		return SessionPoolOptions.newBuilder()
				.setFailIfPoolExhausted()
				.setMinSessions(0)
				//.setMaxSessions(2)
				.build();
	}
```

In fact, you don't even need to do that. All of these options can be configured via `spring.cloud.gcp.spanner.*` properties in your `application.config`.

I'm not sure why your code would work in `1.1.3.RELEASE` though.

**Comment by srivraokp** [comment]
@meltsufin 
I tried the same but it does not work, the first update is done DB and the second one failed

@Bean
	public SessionPoolOptions sessionPoolOptions() {
		return SessionPoolOptions.newBuilder()
				.setFailIfPoolExhausted()
				.setMinSessions(0)
				//.setMaxSessions(2)
				.build();
	}

I am using .setFailIfPoolExhausted() as I noticed spring.cloud.gcp.spanner.failIfPoolExhausted=true
is not working

This code was working till we upgraded to 1.2.0.M3

**Comment by meltsufin** [comment]
Can you share your `pom.xml`? Can you reproduce the issue within the integration test I pointed to?

**Comment by srivraokp** [comment]
@meltsufin 
Please find attached pom

[pom.txt](https://github.com/spring-cloud/spring-cloud-gcp/files/3718611/pom.txt)

I have to try the integration test cases,

**Comment by meltsufin** [comment]
I don't see anything obviously wrong in the `pom.xml`. Please let us know how the integration test repro goes.

**Comment by srivraokp** [comment]
@meltsufin 

in 1.2.0.M3

private TransactionContext getTransactionContext() {
		if (TransactionSynchronizationManager.isActualTransactionActive()) {
			SpannerTransactionManager.Tx tx = (SpannerTransactionManager.Tx) TransactionSynchronizationManager
					.getResource(this.databaseClientProvider.get());
			if (tx != null && tx.getTransactionContext() != null) {
				return tx.getTransactionContext();
			}
		}
		return null;
	}

tx is coming null always but in older version it is picking the existing Transaction

**Comment by meltsufin** [comment]
We did change how we manage transactions in 1.2.0.M3, but we didn't observe any of our tests failing. I wonder what exactly in your setup is causing the transaction holder to not work.
Is there any other transaction management in the app besides Spanner?

If you're debugging your application, can you put a breakpoint [here](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/SpannerTransactionManager.java#L171) and see what happens when the transaction starts?

**Comment by srivraokp** [comment]
@meltsufin 
no we are just using spanner and the code is pretty straight forward
Controller --> Service --> DAO

Service has @Transactional and calls 2 different methods on DAO

As I debugged it does not pick the existing transaction when it calls the second method on DAO, where as in older versions the same is retained

[Screen.docx](https://github.com/spring-cloud/spring-cloud-gcp/files/3719155/Screen.docx)

**Comment by meltsufin** [comment]
@srivraokp Thanks for the screenshots!
The transaction should be picked up as long as the key is the same in both places.
`TransactionSyncrhonizationManager.getResource(this.databaseClientProvider.get())` is returning null. This makes me suspect that the value returned by `this.databaseClientProvider.get()` is not the same as `tx.getDatabaseClient()` in the begin transaction. Can you verify that by evaluating `this.databaseClientProvider.get()` in the second screenshot, and comparing to the ref value in the first?

**Comment by srivraokp** [comment]
@meltsufin 
It is different, I was trying to say the same in my earlier post too

Attached is the screen
[Screen2.docx](https://github.com/spring-cloud/spring-cloud-gcp/files/3719416/Screen2.docx)

**Comment by srivraokp** [comment]
@meltsufin 
Thanks for your inputs, I was able to find the defect in my code corrected and it is working fine

The way SpannerTransactionManager  was created in my code was the problem, I will close this issue

**Comment by meltsufin** [comment]
Hi @srivraokp. Thanks for the update.
Can you share more about what was the mistake, so that others would know how to fix it, if they make the same one?

**Comment by srivraokp** [comment]
Below is the corrected code
@meltsufin 
Please find below corrected code, Thanks again

@Autowired
private Supplier<DatabaseClient> databaseClientProvider;

@Bean
public SpannerTransactionManager transactionManager() {		
	return new SpannerTransactionManager(databaseClientProvider);
}

Rollback and Commits are working fine

**Comment by YashJainSC** [comment]
Is there any documentation on how to use declarative transactions for spanner ? Do we need to define bean for spannerTransactionManager or is it created automatically ?

**Comment by elefeint** [comment]
@YashJainSC The transaction manager is created automatically when you pull in the `spring-cloud-gcp-starter-data-spanner` ([documentation](https://googlecloudplatform.github.io/spring-cloud-gcp/2.0.5/reference/html/index.html#declarative-transactions-with-transactional-annotation)).

**Comment by YashJainSC** [comment]
@elefeint yes I went through this but in my case it is not getting created.

This is my pom
[pom.docx](https://github.com/spring-cloud/spring-cloud-gcp/files/7555244/pom.docx)

**Comment by elefeint** [comment]
@YashJainSC Please create a minimal reproducer project demonstrating the problem and open a new issue in the new repo https://github.com/GoogleCloudPlatform/spring-cloud-gcp

The most common reasons for transactions to silently not be created are:
1) [method annotated as `@Transactional` is required to be public](https://docs.spring.io/spring-framework/docs/current/reference/html/data-access.html#transaction-declarative-annotations-method-visibility) but is not
2) `@EnableTransactionManagement` annotation must be present on some `@Component` class in your application but is not

**Comment by YashJainSC** [comment]
@elefeint seems like I had earlier 1.1.1.RELEASE for spring-cloud.version and had upgraded to 1.2.8.RELEASE. And auto configuration was added after 1.1.1.RELEASE. After I update maven project with 1.2.8.RELEASE the bean spannerTransactionManager is getting created

**Comment by YashJainSC** [comment]
@elefeint Thanks!
