### ISSUE TITLE
PubSub: cannot cast AckReplyConsumer with 'ORIGINAL_MESSAGE' header

### ISSUE THREAD

**Issue by johannesgiani** [spring-cloud/spring-cloud-gcp#1981]
Since `GcpPubSubHeaders.ACKNOWLEDGEMENT` is deprecated, messages should not be acknowledged anymore using this peace of code, which is used also in the documentation:
```
AckReplyConsumer consumer = message.getHeaders().get(GcpPubSubHeaders.ACKNOWLEDGEMENT, AckReplyConsumer.class);
consumer.ack();
```
Now when casting the `ORIGINAL_MESSAGE` header there is an exception thrown, so none of these two approaches work:
```
AckReplyConsumer consumer = (AckReplyConsumer) message.getHeaders().get(GcpPubSubHeaders.ORIGINAL_MESSAGE);
```
```
AckReplyConsumer consumer = message.getHeaders().get(GcpPubSubHeaders.ORIGINAL_MESSAGE, AckReplyConsumer.class);
```

Please update the documentation and provide a solution not using the deprecated header

**Comment by meltsufin** [comment]
Our current documentation doesn't mention `GcpPubSubHeaders.ACKNOWLEDGEMENT` header at all. Which version of the docs are you looking at and which version of the project are you using?

Here's [the documentation](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.0.M3/reference/html/#inbound-channel-adapter-using-pubsub-streaming-pull) on how to use `GcpPubSubHeaders.ORIGINAL_MESSAGE`:

Example given in the docs:
```java
@Bean
@ServiceActivator(inputChannel = "pubsubInputChannel")
public MessageHandler messageReceiver() {
    return message -> {
        LOGGER.info("Message arrived! Payload: " + new String((byte[]) message.getPayload()));
        BasicAcknowledgeablePubsubMessage originalMessage =
              message.getHeaders().get(GcpPubSubHeaders.ORIGINAL_MESSAGE, BasicAcknowledgeablePubsubMessage.class);
        originalMessage.ack();
    };
}
```

Does this not work?

**Comment by johannesgiani** [comment]
Thank you, perfect 👌 

It is stated in the getting started guide: https://spring.io/guides/gs/messaging-gcp-pubsub/

**Comment by meltsufin** [comment]
Thanks! I filed an issue under the quick start guide.
