### ISSUE TITLE
Duplicate records returned across pages in Spring Data Spanner

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#1982]
Example of the problem:

> ```java
> Pageable pageable = PageRequest.of(pageNbr>0?(pageNbr-1):0, config.getPageSize())
> optional = repository.getAll(pageable);
> ```
> 
> Specific example of duplicates. Lets say the query returns 20 rows ids 1-20, and I have set the pagesize as 5, each page is supposed to have 5 items. When the client calls with pageNbr=1, we see the response has 5 items-  id 1-5, pageNbr=2, will have ids 6-10, pageNbr =3 can have items with id 7,8,9,10,11,12, instead of having 11-15, ids 7,8,9,10 get repeated in pageNbr3. Although the pagesize is honored, the items returned in each page is not unique.  I would expect each new page to give me new result set.

What's probably going on:

Every time you request a new page, it's a completely new query and the results are not guaranteed by Spanner to be the same every time. For example, new records might be added. However, in this case, more importantly, the order of the results is not guaranteed, unless a sort is specified.
Something like this should resolve the issue:

```java
Pageable pageable = PageRequest.of(pageNbr>0?(pageNbr-1):0, config.getPageSize(), Sort.by(Order.asc("id"));
```

This may still have issues occasionally if new records are inserted into the table between page requests. For that, you would need to use staleness configuration. However, this may not be a real problem for most users.

Since our default is no sort for Spanner Pageable, we should update our documentation to warn about this situation. Alternatively, we can try to change the default to use the Entity id as the default sort order.

**Comment by dmitry-s** [comment]
Enabling default sort order might have performance drawbacks.

**Comment by meltsufin** [comment]
Right, but why would you ever do pagination without a sort when duplicates can happen? I guess only if you care about one page of results.

**Comment by RonaldLaeremans** [comment]
We might investigate adding a more automated way to support a stale read at a timestamp similar to how we use UrlSafeCursor for the Datastore Pageable support. For the use cases that want a guaranteed consistent resultset.

**Comment by meltsufin** [comment]
Closing, in favor of #1998.
