### ISSUE TITLE
No 1.2.0.M3 spring-cloud-gcp-data-firestore on Spring Milestone repository

### ISSUE THREAD

**Issue by lucasoares** [spring-cloud/spring-cloud-gcp#1988]
Hello.

I was trying to use Spring Cloud GCP for Firestore with this dependency management:
```xml
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-gcp-dependencies</artifactId>
        <version>1.2.0.M3</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

Looking at spring milestone repository I was unable to find the 1.2.0.M3 version for `spring-cloud-gcp-data-firestore` artifact. The repository have only the version 1.2.0.M2.

**Comment by dmitry-s** [comment]
It was removed by mistake. We'll put it back in so it's available in the next release.

**Comment by lucasoares** [comment]
Thanks!
