### ISSUE TITLE
Add the ability to pass enums to @DiscriminatorValue

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-gcp#1993]
Currently there is a way to use annotations to handle [inheritance with Datastore](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/docs/src/main/asciidoc/datastore.adoc#inheritance-hierarchies). One of the annotations allows you to pass a String to act as the discriminator. Instead of accepting only Strings, I wish I can pass an enum:

```java
public enum AnimalType {
  CAT,
  DOG,
  RAT
}
```

and then

```java
@DiscriminatorValue(AnimalType.CAT)
public class Cat extends Animal {
...
}
```

**Comment by meltsufin** [comment]
What we have is consistent with `javax.persistence.DiscriminatorValue`, which also works with `String`.
How would we implement what you're proposing?

**Comment by Alos** [comment]
I guess its infeasible :(
