### ISSUE TITLE
Provide auto/manual acknowledgement mode

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#20]
Right now, we're sending PubSub's `AckReplyConsumer` back to the user so they can ack/nack the message.
We should provide the option to ack messages automatically, and use a sensible default.

**Comment by artembilan** [comment]
Also consider to rename ` CONSUMER = PREFIX + "pub_sub_consumer"` to the ` ACKNOWLEDGEMENT = PREFIX + "pub_sub_acknowledgement"` since that reflects reality better.

**Comment by joaoandremartins** [comment]
I was just preparing a PR for that :)

**Comment by artembilan** [comment]
OK. I place the merge of the #17 to my highest priority to unblock that super-active PR'ing 😄 

And yes, with all that activity I need someone else for review. I'm not so fast reading English especially if I'm  not familiar with the subject like GCP 😉

**Comment by joaoandremartins** [comment]
It sounds like this is a dupe of https://github.com/spring-cloud/spring-cloud-gcp/issues/8
