### ISSUE TITLE
Declarative Reactive transactions in Firestore

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#2004]
Implement `@Transactional` support for reactive template and repositories.

**Comment by dmitry-s** [comment]
I looked at spring-data-mongodb but I'm not sure how exactly it supports declarative transactions.
In https://github.com/spring-projects/spring-data-mongodb/blob/master/spring-data-mongodb/src/test/java/org/springframework/data/mongodb/ReactiveTransactionIntegrationTests.java

I see this:
```
		@Transactional
		public Flux<Person> declarativeSavePerson(Person person) {

			TransactionalOperator transactionalOperator = TransactionalOperator.create(manager,
					new DefaultTransactionDefinition());

			return transactionalOperator.execute(reactiveTransaction -> {
				return operations.save(person);
			});
		}
```
Do you have to use `TransactionalOperator` even if the method is annotated with `@Transactional`?
I wasn't able to find any cases where `@Transactional` is used without `TransactionalOperator`.

@mp911de do you have any recommendations? Also, could you point me to the code that handles declarative transactions? thanks

**Comment by mp911de** [comment]
Once a `ReactiveTransactionManager` bean is available, you don't have anything to do to make reactive `@Transasctional` work.

> Do you have to use TransactionalOperator even if the method is annotated with @Transactional?

Not in the first place. You could start the transaction via `TransactionalOperator` and then you call somewhere in the call chain a `@Transactional` method to propagate the transaction to another method that wants to participate in the same transaction (or open a new one).

Regular Spring transaction propagation apply for reactive transactions as well.

**Comment by meltsufin** [comment]
Thanks @mp911de! This great. It means we just need to document the usage.
