### ISSUE TITLE
Move to SF 5.0 and SB 2.0 when they're GA

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#201]

**Comment by artembilan** [comment]
I would say not a fact that we need their GA for our development.
That really might be just enough to rely on the same `spring-cloud-dependencies-parent:2.0.0.BUILD-SNAPSHOT` during development phase.
The Milestones can be released with appropriate Milestones from there.

If you definitely have plans to go GA for `1.0.0` before appropriate GAs for our `Spring Cloud 2.0` dependencies (including Spring Cloud Stream 2.0 for Binder), than let's post-pone this task to the next year for our version `2.0`.

But still we need keep in mind: even if Google release its `alpha` and `beta` into Maven Central, that wouldn't  be good to release our GA based on them. So, we definitely need GA for all our dependencies.
