### ISSUE TITLE
Pub/Sub newly daemonized thread pools shut down too well

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2015]
After #2010, the Pub/Sub subscriber thread pool no longer keeps an application alive. This is good, expected behavior for simple `PubSubTemplate` users, but it results in very unintuitive behavior for Spring Cloud Stream sinks and (haven't tested it, but pretty sure) Spring Integration apps with service activators. Basically, if a Spring application is not a web application, it starts up, looks around, finds nothing interesting to do, and shuts down.

@artembilan What is expected behavior of a non-web Spring Integration application that subscribes to a queue? Intuitively, it seems that such an application should stay up waiting for data to come in.

One possible solution is to provide a daemon thread pool by default, but to override it with a non-daemon thread pool if both Pub/Sub and Spring Integration are detected on the classpath.

@artembilan @meltsufin WDYT?

**Comment by artembilan** [comment]
This is not something what has to be the framework responsibility.

In our samples we use a trick like this:
```
public static void main(String[] args) throws Exception {
	ConfigurableApplicationContext ctx = SpringApplication.run(Application.class, args);

        ...

	System.out.println("Hit 'Enter' to terminate");
	System.in.read();
	ctx.close();
}
```

That's all: I wouldn't abuse non-managed threads in the framework.

**Comment by meltsufin** [comment]
I agree with @artembilan. If we need to keep any of our console apps from shutting down in this scenario, the trick above would be totally fine. I think most developers have encountered this kind of thing before.

**Comment by elefeint** [comment]
Sounds good; I'll update the samples then.
