### ISSUE TITLE
Several daemon threads getting created

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#2018]
Hi @ChengyuanZhao  @meltsufin 

Recently we are observing several GAX- threads are getting created. We didn't have this issue before but have hit this issue with recent changes. Do you happened to know why these threads are getting created ?

Daemon Thread [Gax-138] (Suspended (breakpoint at line 53 in InstantiatingExecutorProvider))	
	InstantiatingExecutorProvider$1.newThread(Runnable) line: 53	
	ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor, Runnable) line: 619	
	ScheduledThreadPoolExecutor(ThreadPoolExecutor).addWorker(Runnable, boolean) line: 932	
	ScheduledThreadPoolExecutor(ThreadPoolExecutor).ensurePrestart() line: 1603	
	ScheduledThreadPoolExecutor.reExecutePeriodic(RunnableScheduledFuture<?>) line: 350	
	ScheduledThreadPoolExecutor$ScheduledFutureTask<V>.run() line: 296	
	ScheduledThreadPoolExecutor(ThreadPoolExecutor).runWorker(ThreadPoolExecutor$Worker) line: 1149	
	ThreadPoolExecutor$Worker.run() line: 624	
	Thread.run() line: 748

**Comment by ChengyuanZhao** [comment]
@vineela-gampa Could you provide more detail about what operations you're doing that cause these threads to be created that weren't before? Any idea which update in version caused these? GAX threads come from the underlying grpc layer under the client lib, so they're a few layers removed from Spring Data Spanner.

**Comment by elefeint** [comment]
Do you only use Spanner, or also Pub/Sub, by any chance?
Are you on the snapshot versions of spring-cloud-gcp?
Also, could you qualify "recent" - days/weeks/months?

Thanks!

**Comment by vineela-gampa** [comment]
we use spanner, pubsub (sync/async) pull subscribers.

**Comment by vineela-gampa** [comment]
@ChengyuanZhao we are using latest released milestone of spanner
with session (min : 10 max `10) and channels : 35

**Comment by ChengyuanZhao** [comment]
@vineela-gampa please share the operations you're using. Please also
isolate the usage from the pubsub usage to confirm it is from Spring Data
Spanner.

**Comment by meltsufin** [comment]
Obsolete.
