### ISSUE TITLE
disable checkstyle for sample apps 

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2028]
Working with someone on setting up a sample app, and import order is tripping us up. Sample apps don't need to follow the strict spring style.

**Comment by elefeint** [comment]
We'd still want checkstyle when writing code and creating PRs... Not sure how to combine usability and quality here.

**Comment by meltsufin** [comment]
I don't think we should disable checkstyle for sample apps. We want to maintain some level of style consistency even in the sample apps. However, some rules can be relaxed for sample apps, as we've already done. See [checkstyle-suppressions.xml](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/src/checkstyle/checkstyle-suppressions.xml). It should be possible to automatically fix imports if you've got everything setup following [CONTRIBUTING.adoc](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/CONTRIBUTING.adoc).

**Comment by elefeint** [comment]
Right, but potential contributors are a small subset of the people who copy sample apps.
