### ISSUE TITLE
Spanner REST Repo PUT operation not supported

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#2044]
I think this is actually similar to the Datastore issue we encountered a few months ago: 
https://github.com/spring-cloud/spring-cloud-gcp/issues/1773

The source is this SO issue : https://stackoverflow.com/questions/58815607/setting-the-primary-key-directly-via-the-key-id-property-is-not-supported-span

In there the user is doing a PUT request to write a new entity to Spanner, but because the new ID is contained as a string in the URL, it's not converted properly to the Spanner Key.java type. So this needs to be supported.

**Comment by meltsufin** [comment]
Thanks, @ChengyuanZhao!

**Comment by dmitry-s** [comment]
The conversion works just fine. The real issue is ConvertingPropertyAccessor tries to set SpannerCompositeKeyPropert on the entity object instead of setting the String Id field.
