### ISSUE TITLE
Figure out how an old version of Guava crawled back in

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2052]
Noticed it tripping checks on #2051 
It seems that the latest version of com.google.cloud:google-cloud-core is bringing in an ancient evil that is Guava 20.

 https://app.snyk.io/org/artembilan/project/1a2faade-6eb3-4e42-9835-80ac62d68a1c/pr-check/5817bf53-c12b-436a-9250-5ee82448e794?refs=b3b24486af9d45a2ee05b048092920fe37a6c9d7..600626f32ea52c6c8cf013dc97148d69f6c16c50&fromGitHubAuth=true

**Comment by meltsufin** [comment]
com.google.protobuf:protobuf-java:jar:3.10.0:compile

**Comment by meltsufin** [comment]
I think this is yet another bug in Snyk. I'm only seeing guava version `28.1-android` when running `mvn dependency:tree`. I think it's a fairly recent version of Guava.

**Comment by elefeint** [comment]
Closing the false positive.
