### ISSUE TITLE
com.google.cloud.firestore.annotation.DocumentId class not found

### ISSUE THREAD

**Issue by gautamdey** [spring-cloud/spring-cloud-gcp#2056]
when I am trying to use the example for firestore with spring data spring boot we are running into issue  
com.google.cloud.firestore.annotation.DocumentId class not found

gradle 
 firestoreMilestoneVersion = '1.2.0.RC2'

  implementation "org.springframework.cloud:spring-cloud-gcp-starter-firestore:${firestoreMilestoneVersion}"
    implementation "org.springframework.cloud:spring-cloud-gcp-data-firestore:1.2.0.RC2"

if we remove the @DocumentId annotation we start getting error 
   app_name=unknown thread=main location=o.s.b.SpringApplication line=823 Application run failed
   2019-11-25T21:45:18.56-0800 [APP/PROC/WEB/0] OUT org.springframework.dao.InvalidDataAccessApiUsageException: Reactive Repositories are not supported by JPA. Offending repository is com.stubhub.tns.evaluation.repository.EvaluationPayloadRepository!

**Comment by meltsufin** [comment]
Hi @gautamdey! Can you please provide more details about which example you're running? All of our samples are automatically tested.
Also, `1.2.0.RELEASE` is now available. So, give it a try.

**Comment by gautamdey** [comment]
Hi @meltsufin  I am trying out the example 
https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample

I have updated to 1.2.0 release still same error . 
Just for information the project where iam using this is webflux and it also uses postggres for which I am using non-rx driver .

**Comment by meltsufin** [comment]
Have you tried running the example separately to see if it works for you?
If it does, then we need another way to reproduce your issue.
cc/ @dmitry-s

**Comment by indian9** [comment]
@meltsufin we are checking as requested.
