### ISSUE TITLE
Update storage starter ref docs to showcase creating relative paths

### ISSUE THREAD

**Issue by jabubake** [spring-cloud/spring-cloud-gcp#206]
https://docs.spring.io/spring-cloud-gcp/docs/1.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#_google_cloud_storage

**Comment by meltsufin** [comment]
The write operation is already documented there, just not the relative paths.

**Comment by jabubake** [comment]
Sorry, missed that.

**Comment by joaoandremartins** [comment]
We were actually thinking whether it's necessary to highlight the relative path feature?
It should be easily discoverable through Javadoc or looking at the class..

**Comment by jabubake** [comment]
You're right, i think that's a fair point.
