### ISSUE TITLE
java.util.Date should not be converted to spanner Date type

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#2067]
java.util.Date represents an instant in time, with millisecond precision, while Spanner Date represents a date without time.

**Comment by ayancancode** [comment]
> java.util.Date represents an instant in time, with millisecond precision, while Spanner Date represents a date without time.

So, we have to use Timestamp as a column  in spanner Database and we are forced to use com.google.cloud.Date as a type in Entity if we want to put column type as Date. Please let me know if my understanding is correct.

**Comment by meltsufin** [comment]
`LocalDateTime` seems to be the perfect match for the Spanner `DATE`. Both are just dates with no timezone.

**Comment by ayancancode** [comment]
Thanks @meltsufin . I guess that makes sense.

**Comment by meltsufin** [comment]
@ayancancode You're absolutely right, I meant to say `LocalDate`.
