### ISSUE TITLE
`createRelative` works incorrectly if bucket name does not have a trailing slash

### ISSUE THREAD

**Issue by jabubake** [spring-cloud/spring-cloud-gcp#207]
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResource.java#L145

expects a trailing slash, which breaks if the resource is initialized without a trailing '/'.
```
@Value("gs://[YOUR_GCS_BUCKET]")
private Resource gcsResource;
```

**Comment by jabubake** [comment]
@meltsufin FYI

**Comment by ChengyuanZhao** [comment]
This one is fixed here: https://github.com/spring-cloud/spring-cloud-gcp/pull/239

At the time this didn't work because we didn't actually support buckets as resources, but now we do.
