### ISSUE TITLE
Add Firestore support mention to landing pages

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#2071]
Firestore support is currently not listed on the `README.md`, [project site](https://spring.io/projects/spring-cloud-gcp), and [refdoc intro](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.0.RELEASE/reference/html/#introduction).

**Comment by dmitry-s** [comment]
It is listen on refdoc info:  https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.0.RELEASE/reference/html/#spring-data-reactive-repositories-for-cloud-firestore

**Comment by meltsufin** [comment]
I meant the Introduction section.
