### ISSUE TITLE
Spring context shuts down after context startup in pubsub 1.2.0

### ISSUE THREAD

**Issue by joris-desmedt** [spring-cloud/spring-cloud-gcp#2077]
When using the spring-cloud-gcp-starter-pubsub dependency if your on version 1.1.3 and have set up a method of receiving messages the context keeps running and listening for messages, even if you don't have the web dependency (important since I'm creating a non webApp for processing messages). Which is what you want, I think.
But if you go to 1.2.0 it shut down immediately after startup.

Create the getting started project form https://spring.io/guides/gs/messaging-gcp-pubsub/ without web dependency, output and controller. Then change the versions between 1.1.3 and 1.2.0 to see that in 1.1.3 the context keeps running while in 1.2.0 it gets shut down immediately.

**Comment by joris-desmedt** [comment]
I suspect the reasons is the use of daemon threads in pubsub 1.2.0
https://stackoverflow.com/questions/37754410/how-to-prevent-spring-app-context-shutdown-until-shutdown-hook-is-fired

**Comment by elefeint** [comment]
You are correct about the causes. The new behavior is intentional, though -- it's described in the [changelog](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/CHANGELOG.adoc):

> This is a change in behavior for non-web applications that subscribe to a Cloud Pub/Sub topic. The subscription threads used to keep the application alive, but will now allow the application to shut down if no other work needs to be done.

There is more detail on how we came to this decision in #2015.

**Comment by joris-desmedt** [comment]
@elefeint ok thanks
