### ISSUE TITLE
DatastoreTemplate#convertEntitiesForRead very slow (17 second delay)

### ISSUE THREAD

**Issue by BenDol** [spring-cloud/spring-cloud-gcp#2083]
**Version:** 1.2.0.RC2
I am making a call with the DatastoreTemplate that freezes for ~17 seconds every call.

EDIT: Removed the code, the issue is that I have a lot of recursive references in some of my table definitions. What I would like to know is if there is a way to tell Spring not to do a deep search for every reference on an entity. I haven't been able to find one and projection still seems to take a long time to execute (though I need to dig into this a little more).

Any help is greatly appreciated.

**Comment by BenDol** [comment]
Actually this might not work since I removed all the references, I will need to include all the references from these entities in an archive.

**Comment by BenDol** [comment]
Is there a way to exclude deep entity references being pulled in a query? I'm looking at Projection atm, but it would be nice if it was possible to ignore deep References on a given call.

**Comment by meltsufin** [comment]
We support [projections](https://cloud.spring.io/spring-cloud-gcp/reference/html/#projections-2) and that's probably the most appropriate solution at the moment.
The performance you're quoting still sounds pretty bad. Are there many roundtrips to the database? @dmitry-s Any thoughts on this?

**Comment by dmitry-s** [comment]
Yes, there are additional database calls for entity reference resolution. Let me see if there is a way to workaround that.

**Comment by dmitry-s** [comment]
Lazy loading could help with that issue. 
@meltsufin what do you think?

**Comment by meltsufin** [comment]
Sure, it makes sense. We already have an issue for it: #1101.
