### ISSUE TITLE
Spring Cloud version for 1.2.x branch seems wrong

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2094]
The Spring Cloud Build parent version [on 1.2.x branch](https://github.com/spring-cloud/spring-cloud-gcp/blob/b90faa3527d79f4c138532cc81e97e198199bf61/pom.xml#L9) is the same as on [master](https://github.com/spring-cloud/spring-cloud-gcp/blob/6c029b249a567f39063cb45fe947a6381b99eb6a/pom.xml#L9) -- `2.2.1.BUILD-SNAPSHOT`.

It should probably be Greenwich `spring-cloud-build:2.1.10.BUILD-SNAPSHOT` on the 1.2.x branch.

**Comment by meltsufin** [comment]
Spring Cloud Build 2.2.x corresponds to the Hoxton release AFAIK, which is aligned with our 1.2.x release. We should probably just upgrade to 2.2.2 snapshots.

**Comment by elefeint** [comment]
[spring-cloud-release wiki](https://github.com/spring-cloud/spring-cloud-release/wiki/Supported-Versions) says that Hoxton will support both Spring Boot 2.2.x and 2.3.x. So I spring-cloud is not doing a version bump...

Here is my current understanding:

|spring-cloud-gcp|spring cloud release train|spring-cloud-build|spring-boot
|---|---|---|---|
|1.2.x|Hoxton|2.2.1|2.2.x and 2.3.x
|1.3.x|Ilford|2.2.2.BUILD-SNAPSHOT|2.4.x

So the reason I was confused is that `spring-cloud-build` in `Hoxton` release train has nowhere to grow. I would have expected the current snapshot to have been updated to `2.3.0.BUILD-SNAPSHOT`.

But anyway, our versioning seems reasonable.

For future reference: https://spring.io/blog/2019/12/23/spring-cloud-roadmap-and-hoxton-and-greenwich-maintenance-and-eol-announcements
