### ISSUE TITLE
Storage integration should provide ability to provide initial file contents

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2097]
To fit into Spring Resource idiom, `GoogleStorageResource` [creates a new file](https://github.com/spring-cloud/spring-cloud-gcp/blob/72d746486fedd19b16ead3cdbbcfb48c3e90c3a9/spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResource.java#L306) before returning the output stream to a now-existing file.

But GCP Storage treats the act of overwriting a file as requiring both a _delete_ and a _create_ permission, so if the service account only has the _create_ permission, it actually cannot use the output stream provided by `GoogleStorageResource`, failing with `[account] does not have OBJECTS_DELETE access to [bucket/file]` error.

We should provide ability to create and write a resource in one go, using the overloaded `Storage.create(BlobInfo, byte[])` method.

**Comment by meltsufin** [comment]
> But GCP Storage treats the act of overwriting a file as requiring both a delete and a create permission

What does it look like in the client library code? Can we configure the append mode so that it doesn't view it as "overwriting"?

> We should provide ability to create and write a resource in one go, using the overloaded `Storage.create(BlobInfo, byte[])` method.

Although useful for the `GoogleStorageResource` abstraction, I'm not sure if this really addresses the issue, since the problem is in the `getOutputStream()` method which is part of the `WritableResource` abstraction.

**Comment by meltsufin** [comment]
Never mind about the "append" idea, since Google Cloud Storage treats all objects as immutable.
See: https://cloud.google.com/storage/docs/key-terms#immutability.
Thanks @elefeint for the pointer!
