### ISSUE TITLE
Add Continuous Integration to GitHub repo

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#21]
We've been using self hosted Jenkins in other neighbour projects and I think it's been good so far.

**Comment by viniciusccarvalho** [comment]
We have a hosted jenkins (https://jenkins.spring.io) that we can configure to build and publish artifacts

**Comment by artembilan** [comment]
Even if we have already added Travis to PR's, we still need CI to publish snapshots and releasing eventually.

**Comment by meltsufin** [comment]
@mbogoevici You mentioned you know someone who might be able to help us get this set up. Can you please point them here? Thanks!

**Comment by markfisher** [comment]
I've added @sobychacko to the dev team here.

**Comment by meltsufin** [comment]
Hi Soby! Thanks for volunteering to help us! Please let us know what you need from us to get the CI setup started.

**Comment by sobychacko** [comment]
@meltsufin I will set it up soon.

**Comment by sobychacko** [comment]
@meltsufin here is the URL for the Jenkins build: https://jenkins.spring.io/job/spring-cloud-gcp-master-ci/

**Comment by meltsufin** [comment]
That was really fast! Thanks! I don't have read permissions though, it looks like.

**Comment by sobychacko** [comment]
hmm - I thought everyone has read access with the GitHub logins. @trevormarshall can help with that.

**Comment by meltsufin** [comment]
We now have access and the snapshots are published! Thanks guys!
@joaoandremartins I think you can close this issue now.

**Comment by artembilan** [comment]
I'm reopening this issue because I see this in the PR:

![travis](https://user-images.githubusercontent.com/1071590/28464149-eb23e82e-6df1-11e7-9231-b28e4809ca47.png)

Can some one explain why do we we have two of them?
Plus that looks like they both perform the same task.
So, in my feeling we have to wait twice more time to determine that PR is OK.

Thanks

**Comment by meltsufin** [comment]
One build is for the branch and another for the PR merge into master. [See this explanation on stackoverflow](https://stackoverflow.com/questions/34974925/travis-ci-creates-two-buids-for-each-github-commit-push/).
I think one way to disable the "useless" push build is to limit to master branch:
```yaml
branches:
  only:
    - master
```
Also, can we get the newly setup Jenkins CI to report build status to GitHub?

**Comment by artembilan** [comment]
OK. Thank you, @meltsufin !

I think I'm fully satisfied with only the auto-merge option. This way, if it fails, you'd be forced to rebased your branch to the `master` for cleaner merge in the future.
