### ISSUE TITLE
.exists() throws exception for existing GCS buckets

### ISSUE THREAD

**Issue by jabubake** [spring-cloud/spring-cloud-gcp#210]
https://github.com/spring-cloud/spring-cloud-gcp/blob/9debe0aff000396f67045c17e3b70fc056ebcd3c/spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResource.java#L109

throws ``java.lang.StringIndexOutOfBoundsException: String index out of range: -1``

when used with a bucket name that exists.

**Comment by ChengyuanZhao** [comment]
Could you give the full cloud storage path you were using?

**Comment by ChengyuanZhao** [comment]
I was able to see the same error when using just a path to a bucket (not any specific object within a bucket existing or not). 

At the moment the GoogleStorageResource only works if the path is for an object, and not a bucket as a whole. Some functionality of a Resource like the reading and writing streams don't have an obvious meaning with a path to just a bucket as a whole, but other functionality from Resource make sense. 

We can extend the functionality here to support bucket paths too. I'll work on something and put up a PR.

**Comment by ChengyuanZhao** [comment]
@artembilan Could I be added as a contributor to this repository? I'd like to assign this issue to myself and also make branches for PRs.

**Comment by artembilan** [comment]
I think we need to ask @markfisher .

I don't have admin permissions to modify the project collaborators.
