### ISSUE TITLE
spring-cloud-gcp doesn't appear to work with Workload Identity

### ISSUE THREAD

**Issue by AClarkie** [spring-cloud/spring-cloud-gcp#2107]
Workload Identity is the recommended way to access Google Cloud services from within GKE due to its improved security properties and manageability:
https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

Has anyone tested that this feature works with Spring Boot applications

**Comment by AClarkie** [comment]
Can confirm it does work, so ignore this request

**Comment by devil47sid** [comment]
Not working for me. The service account not being used deployed pod
