### ISSUE TITLE
user & password field information missing in the SQL starter ref docs and README.md

### ISSUE THREAD

**Issue by jabubake** [spring-cloud/spring-cloud-gcp#211]

**Comment by artembilan** [comment]
Not sure what properties you are talking about.
There is a phrase:

> This starter is configured through `DataSourceProperties`.

So, user & password come to the service from there.

Elaborate, please, more what we are missing.

Thanks

**Comment by joaoandremartins** [comment]
@artembilan the issue is that it's not well discoverable. We came across the same issue on a hackathon. Thanks for filing, @jabubake 

Btw, happy birthday @artembilan !

**Comment by joaoandremartins** [comment]
Fixed by #218.
