### ISSUE TITLE
Add support for Google Cloud Secret Manager

### ISSUE THREAD

**Issue by rohanliston** [spring-cloud/spring-cloud-gcp#2115]
**Is your feature request related to a problem? Please describe.**

Google Cloud have recently added a service called [Secret Manager](https://cloud.google.com/secret-manager), which provides secure, centralised storage for application-level secrets such as API keys, DB credentials, and so on. This service is comparable to [AWS Secrets Manager](https://aws.amazon.com/secrets-manager/).

It is currently in beta, but will apparently be [officially announced](https://www.reddit.com/r/googlecloud/comments/ebmd5z/google_clouds_new_secrets_manager_secret_manager/fb7srv4/) sometime this month (Jan 2020).

Using a managed service like this would be much more convenient for some users than setting up Vault instances or managing Spring Cloud Config Server. 

**Describe the solution you'd like**

Add support for using Google Cloud Secret Manager as a bootstrap property source, similar to Spring Cloud AWS Secrets Manager.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by meltsufin** [comment]
@rohanliston Thanks for the feature request. I'ts been on our radar and we're planning to start working to implement Spring Cloud Vault support for the GCP Secret Manager.

**Comment by sethvargo** [comment]
Hi @meltsufin - let us (Secret Manager) know if we can help. I just published some Java samples at: https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/secretmanager

**Comment by eddumelendez** [comment]
Hi, I will be glad to help too :)

**Comment by meltsufin** [comment]
This is great! Thanks for volunteering to help. We can definitely benefit from some suggestions and code reviews from the community.
cc/ @dzou

**Comment by dzou** [comment]
Hey thanks for the interest and support all, I'll be starting work on this shortly and keep you updated on progress along the way.

**Comment by meltsufin** [comment]
Question for those of you asking for this support:
Are you looking to use HashiCorp’s Vault with GCP Secrets Manager as a backend or do you just need a bootstrap property source that will load secrets into the `Environment`?

**Comment by rohanliston** [comment]
@meltsufin We would prefer to use GCP Secret Manager as a bootstrap property source directly.

**Comment by mikkelbd** [comment]
Same use case here. Would be nice to use GCP Secret Manager directly to load secrets into the `Environment` without having to setup and manage Vault.

**Comment by dzou** [comment]
> Same use case here. Would be nice to use GCP Secret Manager directly to load secrets into the `Environment` without having to setup and manage Vault.

Thanks for flagging this, we'll be prioritizing this work in the next couple of weeks; will get this out shortly.

**Comment by dzou** [comment]
Hey guys, I have sent out PR #2168 which does the initial work of loading secrets from secret manager into the environment at bootstrap time.

At present, this implementation will load the _latest version_ of all the secrets in your GCP project in the environment.

Are there additional features that would interest you? I.e:
- Do you want to be able to specify by secret ID which secrets you want to load into the environment? Perhaps filter secret IDs by regex?
- Sometimes you'll update your secrets or create multiple versions of the same secret (like version 1, 2, 3, latest, etc.). These versions are accessible by the API. Do you want to have an option to load all versions of all your secrets as well?

**Comment by rohanliston** [comment]
@dzou I can't think of an instance where we would want to load different versions of the same secret. Others may have a use case for it, though.

My assumption is that updating a secret in GCP would require a restart of the application for the change to take effect locally. Is that correct? Is there any way to detect changes and reload without restarting? It's not an issue if not, I'm just curious.

Having not used anything but `.properties` files and environment variable overrides before, I don't have a clear picture of what the usage looks like from a user's perspective. Do we specify some mapping from secret name to property name in `bootstrap.properties`?

If you can provide a brief usage example, I can let you know my thoughts on additional features.

**Comment by meltsufin** [comment]
> My assumption is that updating a secret in GCP would require a restart of the application for the change to take effect locally. Is that correct? Is there any way to detect changes and reload without restarting? It's not an issue if not, I'm just curious.

Typically that would be the case, but Spring supports refreshing without restart too with `@RefreshScope`. See: https://spring.io/guides/gs/centralized-configuration/. @dzou This is something we should test with our implementation.
Alternatively, we're thinking of providing a `SecretManagerTemplate.getSecret()` which you can then use to directly retrieve secret values at any time and get the latest.

Regarding usage, stay tuned for the sample app. You can follow along in the PR #2168.

**Comment by dzou** [comment]
Hey all, if you want to start experimenting with this, you can try the feature of using secret manager as a bootstrap property source on the `1.3.0.BUILD-SNAPSHOT`.

Here is a sample we wrote: https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample

Let us know if there's any adjustments or features you think make sense. Tracking these here: #2176.

**Comment by dzou** [comment]
With the completion of https://github.com/spring-cloud/spring-cloud-gcp/pull/2302, this is done.

**Comment by vieirajluis** [comment]
I apologize to post it here, but was the only support that I had found so far.
I have tried providing it directly on my bootstrap file, but seems that its not working as expected. The account service (Compute Engine default service account) has Secret Manager Secret Accessor permission granted. However, seems that is unable to read the secret value.

spring 
   datasource:
       username: ${sm://projects/MY_PROJECT_ID/secrets/dbusername}
       password: ${sm://projects/MY_PROJECT_ID/secrets/dbpassword}

After deploying it on Cloud Run:
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "//projects/MY_PROJECT_ID/secrets/dbusername"

Thanks, for any help.

**Comment by dzou** [comment]
@vieirajluis - No problem, thank you for asking.

This feature right now is only available in the 1.2.3.BUILD-SNAPSHOT version. Are you using the snapshot version?

To use this version you'll need to add the repository to your project as well:

```
<repository>
	<id>spring-snapshots</id>
	<name>Spring Snapshots</name>
	<url>https://repo.spring.io/libs-snapshot-local</url>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
```

**Comment by vieirajluis** [comment]
Thank you vert much for reply.
 <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.2.6.RELEASE</version>
    <relativePath/> 
  </parent>
  <groupId>myappgroup</groupId>
  <artifactId>myappartifactId</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>myappname</name>
  <description>myappdescription</description>

  <properties>
    <java.version>11</java.version>
    <spring-cloud.version>Hoxton.SR3</spring-cloud.version>
  </properties>
  
   <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-gcp-starter-secretmanager</artifactId>
    </dependency>
Thanks for help.

**Comment by dzou** [comment]
I'm not 100% sure what version hoxton.SR3 maps to, but you can try setting the version number for `spring-cloud-gcp-starter-secretmanager` to `1.2.3.BUILD-SNAPSHOT` and also make sure you add that snapshot repository I mentioned. See if that works for you.

**Comment by vieirajluis** [comment]
Ill give a try. Thank you very much.

**Comment by vieirajluis** [comment]
Thanks, once again Daniel. We have decided to go for Vault with GCP Secrets Manager as a backend, for now. This will let GCP to manage the infrastructure.

**Comment by dzou** [comment]
@vieirajluis - Thanks, good to know. Please feel free to ask questions if you have any in the future - we're reachable via Gitter https://gitter.im/spring-cloud-gcp/Lobby or you can post a question as an Issue on Github.

**Comment by kioie** [comment]
@dzou added the repo and dependency, and got the following error

`Could not resolve dependencies for project com.gcp.springboot:inventorymanagement:jar:1.0.0.0: Failed to collect dependencies at org.springframework.cloud:spring-cloud-gcp-starter-secretmanager:jar:1.2.3.BUILD-SNAPSHOT: Failed to read artifact descriptor for org.springframework.cloud:spring-cloud-gcp-starter-secretmanager:jar:1.2.3.BUILD-SNAPSHOT: Failure to find org.springframework.boot:spring-boot-dependencies:pom:2.3.0.M4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

**Comment by johannesgiani** [comment]
When will this be available in a Service Release?

**Comment by dzou** [comment]
@kioie - Sorry for the confusion on this. You also need an additional spring milestones repository. The following pom.xml snippet should work:

```
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter-secretmanager</artifactId>
            <version>1.2.3.BUILD-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/libs-snapshot-local</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
        </repository>
    </repositories>
```

@johannesgiani - We follow the Spring Cloud release train, and I believe the next scheduled release for our 1.2.3 will be in Hoxton SR5, [tenatively scheduled for May 18](https://github.com/spring-cloud/spring-cloud-release/milestones).

**Comment by vieirajluis** [comment]
Hello everyone,

Any news about org.springframework.cloud 1.2.3 release?

Thanks.

**Comment by elefeint** [comment]
It's in process.

**Comment by elefeint** [comment]
Release was postponed to Monday, May 25.

**Comment by peterwmwong** [comment]
Any updates on when 1.2.3 will be released?

Thanks.

**Comment by elefeint** [comment]
@spencergibb What is the latest plan for the Hoxton SR?

**Comment by breun** [comment]
I generally check https://github.com/spring-cloud/spring-cloud-release/milestones but currently the entry for Hoxton.SR5 says "Past due by 1 day". Should be soon then, I guess.

**Comment by elefeint** [comment]
1.2.3 is out!

**Comment by kioie** [comment]
Congratulations guys!! We've waited for this!

**Comment by dzou** [comment]
> Congratulations guys!! We've waited for this!

Thanks for your interest! Please feel free to post an issue if you run into problems or have feature requests.

**Comment by vieirajluis** [comment]
How do you guys manage to change the order of precedence (Order of precedence: container vs service variables). Or even change a Cloud Run environment variable previously set as super_secret=secrets.mysecret on a **Running Container**, if Cloud Run keeps it [precedence?.](https://cloud.google.com/run/docs/configuring/environment-variables) I have tried this, from a container, and also from the service. The secrets are loaded. Could see after print the env variables. However, it does not affect/changes what was set on the container. [(Secret Manager: Improve Cloud Run security without changing the code)](https://medium.com/google-cloud/secret-manager-improve-cloud-run-security-without-changing-the-code-634f60c541e6)
Thanks.

**Comment by dzou** [comment]
@vieirajluis - Hmm not a Cloud Run expert - though I would imagine if you redeploy the new config it should override the previous default value in the environment : https://cloud.google.com/run/docs/configuring/environment-variables#setting

Not sure why it wasn't changing the default values though.

You can also try asking: https://stackoverflow.com/questions/tagged/google-cloud-run

**Comment by vieirajluis** [comment]
Thanks for reply. Actually, when you redeploy the new config is also setting a static new value (super_secret =sm://application-secret or super_secret=secrets.application-secret). It cannot be changed after the container is deployed/service starts. So, spring gcp secrets manager will work only if you apply the secret access/load within the spring code, and do the configuration/set properties (db_password) within a config class instead of a property file.

Thanks.

**Comment by dzou** [comment]
@vieirajluis - I see. Hey sorry for the delayed response - If this is still an issue for you, can you post a separate issue to [our issuetracker](https://github.com/spring-cloud/spring-cloud-gcp/issues) with more details and some reproduction instructions. We can make sure it doesn't get dropped from our radar.

**Comment by vieirajluis** [comment]
Hi Daniel,

Cloud Run **fully-managed** doesn't supports resetting environment variables on a running container. Also, I did check it with Google Cloud  folks, and for now to use the secrets from secrets manager on Cloud Run **fully-managed** you must use spring-cloud-gcp-starter-secretmanager dependency and on your application property file (Spring: application.yml) you should config your secret as following:

db_password: sm://my_secret_password, until Google releases a new version that will support secrets manager configuration similar to Cloud Run for Anthos something like that. I am using like I just explained and its is working. 

Thanks.

**Comment by dzou** [comment]
@vieirajluis - I see, thank you for the clarification!
