### ISSUE TITLE
it's not possible to pass comparator to GcsStreamingMessageSource

### ISSUE THREAD

**Issue by lukasGemela** [spring-cloud/spring-cloud-gcp#2117]
**Is your feature request related to a problem? Please describe.**
we would like to process files in defined order

**Describe the solution you'd like**
see https://github.com/spring-cloud/spring-cloud-gcp/pull/2116

**Comment by dzou** [comment]
Fix is provided by #2116; I will add the unit test and doc update to close out this issue.
