### ISSUE TITLE
Structured JSON logging doesn't work on Cloud Run (managed)

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#2122]
It mostly works. However, `TRACE` and `WARN` severity levels are not recognized correctly.

The reason for this seems to be the fact that Cloud Run doesn’t actually use `fluent-plugin-google` to do severity level [translation](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/ed11fb17beaa129910e60308011c8be93d31e830/lib/fluent/plugin/out_google_cloud.rb#L1851). Instead it does its own parsing of structured JSON logs and only allows the severity levels listed [here](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogSeverity).

One way around it could be to do severity level translation ourselves in the `StackdriverJsonLayout` class.

**Comment by steren** [comment]
Can you open an internal bug for the severity levels that are not recognized? We could easily accept `WARN` in addition to `WARNING`, especially if this makes Cloud Run behaves more like the fluentd agent. This work is related to internal bug 146219077

**Comment by meltsufin** [comment]
@dzou Did you test these levels? Do they still not work?

**Comment by dzou** [comment]
They work now! I've updated the friction log that you wrote linked in our Spring on Cloud Run document with the updated screenshots.

Here is a screenshot showing that the TRACE and WARN levels are recognized with the `CONSOLE_JSON` logging appender:

![image](https://user-images.githubusercontent.com/3209274/83781196-2c615600-a65c-11ea-9d6c-a46254c3b431.png)

Going to close this bug.
