### ISSUE TITLE
Update Spring Cloud GCP Home Page

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#2125]
**Describe the bug**
https://spring.io/projects/spring-cloud-gcp can use an update to document the newest modules. 

**Sample**
E.g., Firestore is missing.

**Comment by meltsufin** [comment]
@artembilan We have already updated this in our source. Can we run the update on the web site? Thanks!

**Comment by artembilan** [comment]
Sure! Give me a text and I'll post it on the project page!

**Comment by dmitry-s** [comment]
@artembilan the updated text is here: https://github.com/spring-cloud/spring-cloud-gcp/blob/master/docs/src/main/asciidoc/sagan-index.adoc

**Comment by artembilan** [comment]
Fixed: https://spring.io/projects/spring-cloud-gcp
