### ISSUE TITLE
Projection and Slice return type

### ISSUE THREAD

**Issue by Flexy-recruitment-backend** [spring-cloud/spring-cloud-gcp#2133]
Hello, 
I am trying to use projection in order to query an entity in the datastore. I don't manage to use Slice as return type with my projection. The same thing works fine with a Page return type :

My entity is called "Customer" and have a lot of fields.
I have created a projection interface called CustomerProjection  : 

`public interface CustomerProjection {
    String getLastName();
}`

And in my repository, I have the following request : 

`public interface CustomerRepository extends DatastoreRepository<Customer, Long> {
    Page<CustomerProjection> findByIsActiveAndIsDeleted(boolean isActive, boolean isDeleted, Pageable pageable);
}`

This request work well, but when I change the return type in "Slice", I constat at runTime that I obtain a `Slice<Customer>` in place of `Slice<CustomerProjection>`

Is that a bug? is this problem due to some mistake from me?
Regards
CG

**Comment by dmitry-s** [comment]
It looks like a bug, I'll take a look.

**Comment by Flexy-recruitment-backend** [comment]
I confirm that the correction of the issue #2146 solve the problem!
Thank you.
Regards
CG
