### ISSUE TITLE
How to set attributes on pubsub message using gcp cloud project

### ISSUE THREAD

**Issue by mickeyadlg87** [spring-cloud/spring-cloud-gcp#2134]
Hi,

I created a producer application to send messages to a topic on pubsub, I followed the outbound channel adapter approach you show here https://spring.io/guides/gs/messaging-gcp-pubsub/ and it works fine, but I'm not sure how to set attributes and not only the payload on the data message element.

`
    @MessagingGateway(defaultRequestChannel = "pubsubOutputChannel")
    public interface PubsubOutboundGateway {
        void sendToPubsub(String text);
    }`

the sendToPubsub method only populates 'data' attribute on Message, but I'm not sure how can I populate the attributes key:

`
Received message: Message {
  data: b'{"document_id":"doc","correlationId":"uno","oldCor...'
  attributes: {}
}`

Thanks !

**Comment by meltsufin** [comment]
@mickeyadlg87 Try switching the gateway to `Message<string>`.

```java
	@MessagingGateway(defaultRequestChannel = "pubSubOutputChannel")
	public interface PubSubOutboundGateway {

		void sendToPubSub(Message<String> text);
	}
```

```java
	@PostMapping("/postMessage")
	public RedirectView postMessage(@RequestParam("message") String message, @RequestParam("times") int numTimes) {
		for (int i = 0; i < numTimes; i++) {
			MessageHeaders messageHeaders = new MessageHeaders(ImmutableMap.of("my-header", "my-header-value"));

			Message<String> msg = MessageBuilder.createMessage(message + "(" + i + ")", messageHeaders);

			this.messagingGateway.sendToPubSub(msg);
		}
		return new RedirectView("/");
	}
```

**Comment by elefeint** [comment]
Spring Integration gives you a lot of options -- @meltsufin 's approach give you the most flexibility over the message you are sending, but there are also some shortcuts if you want to add only a single header, or a known [map of headers](https://docs.spring.io/spring-integration/reference/html/gateway.html#gateway-mapping).

[This example](https://github.com/elefeint/examples/tree/master/pubsub-with-attributes) shows the automatic `@Header` conversion into a Pub/Sub attribute:
```
@MessagingGateway(defaultRequestChannel = "pubsubOutputChannel")
public interface PubsubOutboundGateway {

  void sendToPubsub(String text, @Header("custom-header") String header);
}
```

Invocation then looks like this:
```
messagingGateway.sendToPubsub(message, "custom header value");
```

**Comment by mickeyadlg87** [comment]
Thanks a lot, it works pretty well, now I'm using `@Headers` tag to pass attributes in the message :D
