### ISSUE TITLE
Performance fetch 4000 entities

### ISSUE THREAD

**Issue by Flexy-recruitment-backend** [spring-cloud/spring-cloud-gcp#2137]
Hello,
We have to fetch a great number of entities of one kind in the datastore. Actually we have performance problem because it seems that a query which return 4000 entites take about between 4 and 5 seconds to return the list of java objects. Moreover we could have to request more entities (max 35 000 entites)
Here is the repository which execute the request : 

```
public interface CustomerRepository extends DatastoreRepository<Customer, Long> {
    Slice<Customer> findByIsActiveAndIsDeleted(boolean isActive, boolean isDeleted, Pageable pageable);
}
```

Is it a normal time? or is it technics to improve this time?

**Comment by meltsufin** [comment]
This may be normal, but we want to make sure that our Spring Data Datastore code is not adding additional overhead. So, it would be interesting to see how this compares to fetching the same 4000 entities directly through the Datastore Client Library.

cc/ @dmitry-s

**Comment by dmitry-s** [comment]
@Flexy-recruitment-backend 
could you clarify what kind of objects you are working with? Is every individual record large in size? Do they have related entities/descendants?

**Comment by Flexy-recruitment-backend** [comment]
Hello, here is the code of the entity.
As you can see, we have several "descendants" but I have linked them with the Key type in order to avoid that Spring plays two queries each time I want to fetch a Customer

```
@Data
@Entity(name = "Customer")
public class Customer {

    @Id
    private Long id;
    private String firstName;
    private String lastName;
    private String email;
    private String hashedPassword;
    private String phone;
    private String landline;
    private String salt;
    private boolean isVerified;
    private Role role;
    @Field(name = "companies")
    protected List<Key> companyKeys = new ArrayList<>();
    @Field(name = "sessions")
    protected List<Key> sessionKeys = Collections.emptyList();
    private Date lastConnexionDate;
    private String lastUserAgent;
    private String idReserveWithGoogle;
    private String country;
    private String region;
    private Gender gender;
    private String address1;
    private String address2;
    private String city;
    private String postCode;
    private String comment;
    private Date birthDate;
    private String origin;
    private String paymentUserId;
    private Online online = ACTIVE;
    private Boolean isCGVAccepted;

    //Warning : be carrefull to the value of this field with the legacy code
    //if this field should be false, see the index rules in the VersionableEntity.java
    @Setter(NONE)
    private boolean isActive = true;
    private boolean isDeleted = false;

    private String requestId;

    //same warning for isActive field
    @Setter(NONE)
    private Date timeModified;

    @Setter(NONE)
    private Date timeCreated;
    protected Key optInOut;
    protected List<Key> optInOutReminders;

	public Customer() {
		super();
        salt = randomUUID().toString();
	}
}
```

**Comment by Flexy-recruitment-backend** [comment]
Hello,
We have made a test with the native cloud datastore API and we have about the same performance time. I think the overhead added by Spring data is limited.
However do you have any idea to optimize this type of request?
Regards
CG

**Comment by meltsufin** [comment]
@Flexy-recruitment-backend thanks for the clarification!

There are some general Datastore performance tips [here](https://cloud.google.com/datastore/docs/best-practices), but I would recommend contacting GCP Support regarding the performance question. They should be able to take a close look at your Datastore configuration and give advice on query performance.

cc/ @eddavisson

**Comment by dmitry-s** [comment]
I ran my own tests and got identical results. There is very small difference between client and spring-data-gcp-data-datastore.
One thing to try is using projections if you don't need all the fields, but currently projections fetch all fields anyway (we are working to resolve the issue).
