### ISSUE TITLE
@Transactional don't work

### ISSUE THREAD

**Issue by Flexy-recruitment-backend** [spring-cloud/spring-cloud-gcp#2144]
Hello,
I am trying to use transaction in a service class with spring cloud gcp and the datastore. It seems that transaction is "understood" by Spring-data because I constat that we pass in the the DatastoreTemplateManager doRollback method when a runtimeException is thrown in my code. Unfortunately, the entity doesn't go back to its old state (the one before the transaction) after the rollback..

I think my project is well configured : 
I use the starter dependency : 
```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter-data-datastore</artifactId>
        </dependency>
```

My Service function is annotated with @Transactional. I throw voluntarily a RuntimeException at the end in order to provoque a Rollback.
```
@Transactional(rollbackFor = RuntimeException.class)
    public void restore(Long id) {
        LOGGER.log(INFO, "Restoring deleted customer of id {0} ...", id);
        Optional<Customer> optionalCustomer = customerRepository.findByIdAndIsDeleted(id, true);
        if (optionalCustomer.isPresent()) {
            Customer customer = optionalCustomer.get();
            customer.setDeleted(false);
            customerRepository.save(customer);
            LOGGER.log(INFO, "Customer of id {0} restored", id);
            throw new RuntimeException("Test");
        }
    }
```
My "customerRepository" is simple : 
```
@Repository
public interface CustomerRepository extends DatastoreRepository<Customer, Long> {
    Optional<Customer> findByIdAndIsDeleted(Long id, boolean isDeleted);
}
```
One more detail, I used AOP in the repository in order to use a specific namespace.
So, I have a pointcut in the application class and a Bean to give a DatastoreNamespaceProvider

```
@SpringBootApplication
@ServletComponentScan
public class SpringbootApplication implements WebMvcConfigurer {

    public static void main(String[] args) {
        SpringApplication.run(SpringbootApplication.class, args);
    }

    @Bean
    public DatastoreNamespaceProvider getNamespaceProvider() {
        return DatastoreNamespaceContextHolder::get;
    }

    @Pointcut("execution(* com.flexycorp.customer.repository.CustomerRepository.*(..))")
    public void customerRepositoryPointcut() {}
    
}
```

Do you think this detail is the origin of the transaction problem? 
Do you understand why the transactions don't work fine on my system?
Regards
CG

**Comment by dmitry-s** [comment]
Spring uses AOP internally for transactions handling. I suspect that your pointcut might be affecting this behavior. 
Could you try your method without the pointcut?

**Comment by Flexy-recruitment-backend** [comment]
I have tried the transaction without the poincut and the problem is still present.
In order to make the test, I have to keep the DatastoreNamespaceProvider. Maybe, the behavior could be linked to this settings?

**Comment by Flexy-recruitment-backend** [comment]
Do you have any news on this subject?

**Comment by dmitry-s** [comment]
Hi @Flexy-recruitment-backend,
 
we have a test for `@Transactional`  in the `DatastoreIntegrationTests` class and it works as expected. Could you try and see if it works for you?

Thanks

**Comment by meltsufin** [comment]
Please re-open if you're still having this issue.
