### ISSUE TITLE
Datastore Projections should restrict query to contain only the necessary fields

### ISSUE THREAD

**Issue by dzou** [spring-cloud/spring-cloud-gcp#2145]
When a user creates a Datastore query using a Projection object, the underlying query should contain only the necessary fields to satisfy the projection. 

I think this should be done using the Projection Query: https://cloud.google.com/datastore/docs/concepts/queries#projection_queries

First determine if this being done right now (I think not..)? If not, we can investigate if this is possible.

**Comment by Flexy-recruitment-backend** [comment]
Thanks for the merge!! how can I test the change without waiting for a release?

**Comment by dzou** [comment]
No problem -

Just add the Spring Snapshots repo to your POM:

```
<repository>
	<id>spring-snapshots</id>
	<name>Spring Snapshots</name>
	<url>https://repo.spring.io/libs-snapshot-local</url>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
```

Then you can depend on the `1.3.0.BUILD-SNAPSHOT` version of this project.

**Comment by dzou** [comment]
So the solution of this should also allow users to not have to create object-only constructors for their entities; see this: https://github.com/spring-cloud/spring-cloud-gcp/issues/2139#issuecomment-581588585

**Comment by dmitry-s** [comment]
That isn't so. Object-only constructors will be required anyway.

**Comment by dzou** [comment]
@dmitry-s - I don't quite agree. I think it's possible to not have object-only constructors if we simply convert `nulls` to sensible values for primitives (like `false`, `-1`, etc.). These placeholder values will not matter since the projection proxy prevents users from accessing them.

**Comment by dmitry-s** [comment]
@dzou what I meant is it is not related to  this issue. This issue is about querying only the fields used in the projection interface.

**Comment by dmitry-s** [comment]
Since Datastore projection queries require all properties specified in the projection to be included in an index, this feature is not backwards compatible. 
We would have to introduce some way to switch it on and off.

**Comment by meltsufin** [comment]
As you can see we downgraded the priority of this. If we ever decide to do this, we will want to make it a configurable option because setting up indexes for each projection could be quite unfriendly to the users.

**Comment by meltsufin** [comment]
@dmitry-s What about the note in this issue regarding this not being backwards compatible??

**Comment by dmitry-s** [comment]
@meltsufin while it is true, the error message is clear and suggests the index that needs to be created, so all you have to do is to copy the index definition and deploy it.
