### ISSUE TITLE
Add @ConditionalOnProperty to GcpContextAutoConfiguration

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2147]
**Is your feature request related to a problem? Please describe.**

@ssoydan-strands reported not being able to fully turn off pubsub starter on Gitter

> I have a java-maven project which has a dependency - "spring-cloud-gcp-starter-pubsub"
I want to disable/enable pubsub with a property (not with a profile) but even when I think it is disabled, I see "failed to detect whether we are running on Google Compute Engine" info log.
I tried different properties like below but none of them seems to work. Do you know if any exist? With the dependency added, it always tries to connect.

**Describe the solution you'd like**
We should add a flag to turn off either common concerns (`GcpContextAutoConfiguration`) or a kill switch to disable all `spring-cloud-gcp` integrations. The former is sufficient, but for someone using several of our modules it's a hassle to turn them off one-by-one.

**Describe alternatives you've considered**
There are workarounds for the issue
1) explicitly specify credentials through properties or by registering your own bean of type `CredentialsProvider` ([docs](https://github.com/spring-cloud/spring-cloud-gcp/blob/b2811f70908ecf54c897475ab0b2874e0079e861/docs/src/main/asciidoc/core.adoc#credentials ))
2) continue relying on autodiscovery, but specifically turn off the GCE check with an environment variable `NO_GCE_CHECK=true` ([docs](https://github.com/googleapis/google-auth-library-java/blob/master/README.md#application-default-credentials))

But neither of those is intuitive to someone seeing a GCE warning in the logs.

**Comment by meltsufin** [comment]
Have you considered using the [built-in mechanism in Spring Boot to disable specific auto-configuration classes](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-disabling-specific-auto-configuration)?

```java
@EnableAutoConfiguration(exclude={GcpContextAutoConfiguration.class})
```
or in `application.properties`:
```
spring.autoconfigure.exclude=org.springframework.cloud.gcp.autoconfigure.core.GcpContextAutoConfiguration
```

**Comment by elefeint** [comment]
We don't make our users exclude on per-class basis in our scenarios and instead provide a documented property; why is this different?

**Comment by meltsufin** [comment]
Yes.
Let's add `spring.cloud.gcp.core.enabled`.

**Comment by ssoydan-strands** [comment]
@elefeint Thanks for the feedback and creating the issue. The second workaround only clears the "Failed to detect whether we are running on Google Compute Engine" log but I can see some more logs like below. I would like to disable them all with a property.

WARN  (1)main [DefaultCredentialsProvider.java:128]: No core credentials are set. Service-specific credentials (e.g., spring.cloud.gcp.pubsub.credentials.*) should be used if your app uses services that require credentials.
INFO  (1)main [GcpContextAutoConfiguration.java:75]: The default project ID is ****

**Comment by ssoydan-strands** [comment]
@meltsufin Thank you also for the feedback. The workaround works with the property below but it is obvious that there should be a specific property which disables them all.

spring.autoconfigure.exclude=org.springframework.cloud.gcp.autoconfigure.core.GcpContextAutoConfiguration
