### ISSUE TITLE
Document core properties

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2151]
`spring.cloud.gcp.credentials.location`, `spring.cloud.gcp.credentials.encoded-key`, `spring.cloud.gcp.project-id`, and `spring.cloud.gcp.credentials.scopes`

Follow up to #2150

**Comment by chaudharydeepak** [comment]
Hi @elefeint , if this issue is still open, I will be more then happy to help out. Let me know. Thank you.

**Comment by elefeint** [comment]
Go ahead, thank you!

**Comment by meltsufin** [comment]
Already done.
