### ISSUE TITLE
Allow `projectId` override in Firebase authentication

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2178]
The new Firebase authentication should allow users to override the default `projectId`, similarly to [Pub/Sub](https://github.com/spring-cloud/spring-cloud-gcp/blob/8d8adbe6a1fa32a17058ad9e45f22e3bb15c7018/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/pubsub/GcpPubSubProperties.java#L50), since it's possible to need Firebase in one project and, say, Datastore, in another (since they can't live in the same project).

Follow up to #2157.

**Comment by femrtnz** [comment]
Hi All, 

Can I work on this issue?

**Comment by meltsufin** [comment]
@femrtnz Sure!
