### ISSUE TITLE
Add refdoc for Firebase authentication

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2182]
Follow up to #2111, #2157.

Some of the contents can be derived from README on the sample app.

**Comment by meltsufin** [comment]
@elefeint What should be the priority on this?

**Comment by elefeint** [comment]
I bumped it to P2. We ought to have documentation.

**Comment by ssm951** [comment]
Any updates on documentation for this? I was trying to use this functionality but am getting stuck. Documentation and samples would help.
