### ISSUE TITLE
Firestore Data reactive support for query method naming for nested properties

### ISSUE THREAD

**Issue by alok-prasad** [spring-cloud/spring-cloud-gcp#2198]
I am trying to use query method naming to access nested property and query back the results. But I only get back an empty array. Below is an example of spring data 

Person -> Address -> ZipCode

findByNameAndAddress_ZipCode()

findByAddressZipCode()

findByAddress_ZipCode()

I tried this but its not working. Please help.

**Comment by dmitry-s** [comment]
@alok-prasad 
This feature is currently not supported. Our team needs to discuss if and when we want to implement it.
We will let you know!

cc/ @meltsufin
