### ISSUE TITLE
PlatformTransactionManager for GCP PubSub

### ISSUE THREAD

**Issue by michael-mcgovern-greater-com-au** [spring-cloud/spring-cloud-gcp#2199]
** Does a PlatformTransactionManager make sense for GCP PubSub? **

We're looking at RabbitMQ versus GCP PubSub.

Spring AMQP/RabbitMQ impl has a PlatformTransactionManager that allows the channel to be transacted and commit/rollbacks to ack/nack the channel.

I'm not aware of GCP Pub Sub having one and so am wondering if a PlatformTransactionManager for GCP PubSub make sense? 

Given Pubsub appears to need ack/nack at the message level it is more complex to hold a reference to all messages received/published so they can be ack/nack at commit/rollback.

Any other reasons there isn't one?

Thanks
Michael

**Comment by meltsufin** [comment]
Cloud Pub/Sub does not support the concept of transactions. Once a message is published to a topic, Pub/Sub guarantees at-least-once delivery to the subscribers. On the receiving side, you can think of ack as a commit, and nack as a rollback. Note that acking and nacking can be done in a [batch](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/core/subscriber/PubSubSubscriberOperations.java#L136).

So, as a whole I don't think `PlatformTransactionManager` makes sense for Pub/Sub, but the question you should ask is whether your use case really requires it.

**Comment by michael-mcgovern-greater-com-au** [comment]
Thanks meltsufin

I understand it is not transactional as such but doing Spring transaction synchronisation would allow ack/nack in commit/rollback processing such that there would only a small chance that a database update commits and a message is not published or consumed.

Does the AcknowledgeablePubsubMessage allow for ack/nack of published messages in commit/rollback processing?

Does the AcknowledgeablePubsubMessage mean I can have

**Comment by meltsufin** [comment]
Once it's published, it's published and can be already processed by a subscriber before you even commit your database transaction.
One thing you can do is delay publishing the message until you commit the db transaction.
Another thing to consider, is to have an "undo" message in case of a rollback.

**Comment by michael-mcgovern-greater-com-au** [comment]
@meltsufin thanks - delay publish until commit looks like something for us to try.
