### ISSUE TITLE
Optimize GoogleStorageResource

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-gcp#22]
The `blob` property must be `volatile`.
The `resolve()` method should not be `synchronized` from the first row.
We can use " Double-Checked Locking" pattern do not block all the threads if `blob` is already initialized:
```
  class Foo {
        private volatile Helper helper = null;
        public Helper getHelper() {
            if (helper == null) {
                synchronized(this) {
                    if (helper == null)
                        helper = new Helper();
                }
            }
            return helper;
        }
    }
```

https://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html

**Comment by meltsufin** [comment]
I think caching should be remove altogether because the `blob` can be modified from an external source. In addition, since blobs are immutable, if you write to it, you will get into a situation where your `blob` object actually points to an non-existing resource.

**Comment by artembilan** [comment]
Closing according @meltsufin 's comment about `Blob` immutability. So, caching even can be evil in this case.

See linked #73 for more information.
