### ISSUE TITLE
Enhance support of the PENDING_COMMIT_TIMESTAMP 

### ISSUE THREAD

**Issue by s13o** [spring-cloud/spring-cloud-gcp#2203]
The support of "PENDING_COMMIT_TIMESTAMP" is enough primitive in SpringData for Spanner today. We actually can't use it with only a Spring Data in a business logic when we need to have several timestamp fields in different objects be consistently filled by an actual commit timestamp value on reaching some business condition. It is possible only with DML statements like `UPDATE Singers SET LastUpdated = PENDING_COMMIT_TIMESTAMP() WHERE SingerId = 1` or Mutations like 
```java
Mutation.newInsertBuilder("Performances")
            .set("SingerId")
            .to(performance.singerId)
            .set("VenueId")
            .to(performance.venueId)
            .set("EventDate")
            .to(performance.eventDate)
            .set("Revenue")
            .to(performance.revenue)
            .set("LastUpdateTime")
            .to(Value.COMMIT_TIMESTAMP)
            .build());
```
A simple solution might be to declare a constant value like the `Value.COMMIT_TIMESTAMP` does. Unfortunately. It is impossible today because the 3-party developer can't overwrite some "default converters" like `JavaToSpannerTimestampConverter` used at `SpannerConverters#JAVA_SQL_TO_SPANNER_DATE_CONVERTER`.

**Comment by meltsufin** [comment]
Have you tried passing in epoch for the timestamp? It looks like that's what `Value.COMMIT_TIMESTAMP` is.

**Comment by s13o** [comment]
> Have you tried passing in epoch for the timestamp? It looks like that's what `Value.COMMIT_TIMESTAMP` is.

I did my investigation a half of year ago. I know that `SpannerConverters` has been changed since that. Even when the option to use `Value.COMMIT_TIMESTAMP` exists now it is still not clear, undocumented and untrivial I believe.

If I'm wrong (it will be nice btw), please, close this issue and provide a link on the documentation or some example how to use it.

**Comment by s13o** [comment]
I think I can do a PR for it enough fast at least to discuss what I'm talking about but, please, after the merge of #2165 :)
