### ISSUE TITLE
DataStore - Dynamic Namespace

### ISSUE THREAD

**Issue by marcosstefani** [spring-cloud/spring-cloud-gcp#2204]
I can't use the library even though I consider it fantastic. I definitely need the namespace to be dynamic. My need is to deal with immense volumes of data and the variable namespace helps a lot in that sense. I believe that if we put some kind of field with a specific annotation (like @Id for example, it could be @Namespace) it would facilitate and assist in the development of those who depend on this dynamic.

**Comment by meltsufin** [comment]
@marcosstefani Are you accessing entities from different namespaces in the same project? Notice that we do allow the default namespace to be changed via a property or the `DatastoreNamespaceProvider`.

**Comment by dmitry-s** [comment]
@marcosstefani could you describe your use case in more details?

**Comment by marcosstefani** [comment]
My scenario is as follows:

Google Cloud has a limited resource per project. And one of the limitations is the number of composite indexes allowed within a namespace. To address this limitation, we have the alternative of creating a different namespace for each of our clients. So, we have one namespace per customer but they all have the same tables. I did not find in the documentation a more precise detail on how to use different namespaces within the same Entity. As I read in the documentation I need to put the namespace in the properties file, so I only have 1 namespace for my application. I needed to have a field within the Entity so that I can say that it is the namespace.
Thank you for the questions.

**Comment by meltsufin** [comment]
I think a custom `DatastoreNamespaceProvider` is exactly what you need. You can write is such that it produces a different namespace name depending on the user state. See a similar discussion in #1289.

**Comment by marcosstefani** [comment]
obrigado, verei sim

**Comment by marcosstefani** [comment]
Thank you, I saw what you sent. Answer it, but it's not automatic. I always need a command to change the namespace. I would really like it to be dynamic, passing through only one property of my class, just as the ID is.

**Comment by meltsufin** [comment]
If I understand you correctly, you would like something like this?

```java
class User {
  @namesapce
  String namespace;
  @Id
  String id;
  ...
}
```

This might be feasible on the write side, but how will we know which namespace to read from when you call something like `userRepository.getAll()`?

The approach I've seen before is to use a thread-local to store the namespace, if all access should be bound to the same namespace depending on which customer is logged in.

You situation might be different though.

**Comment by marcosstefani** [comment]
That is exactly the point. I believe that anyone using this approach will not be able to use getAll in this way, but passing the namespace as a parameter.

**Comment by meltsufin** [comment]
Which approach are you referring to? The `@namespace` in the entity or the `DatastoreNamespaceProvider`?

**Comment by dmitry-s** [comment]
@marcosstefani do you suggest we introduce `userRepository.findAll(String namespace)` method?

**Comment by meltsufin** [comment]
Please re-open if you have further feedback on this issue.

**Comment by amiyalenka82** [comment]
@meltsufin DatastoreNamespaceProvider only overrides the namespace provided in application.properties file. So, at a particular time, you have only one namespace available. How can I actually work on multiple namespaces? I can have multiple threads running in the same application and using different namespaces simultaneously.

**Comment by artemptushkin** [comment]
The problem here that `DatastoreNamespaceProvider #get` is called during the configuration start, but the application might be not ready for this, i.e. doesn't have a namespace, it fails with NPE on `keySupplier.get()` in:
```java
GcpDatastoreAutoConfiguration
return () -> store.computeIfAbsent(keySupplier.get(), this::getDatastore);
```

Thus, the current configuration forces developers to put some namespace as a default one

**Comment by artemptushkin** [comment]
And it is dynamic already if I get you @marcosstefani , just extend to like this

```java
@Component
public class UserContextProvider implements DatastoreNamespaceProvider, Consumer<UUID> {
    private static final ThreadLocal<UUID> USER_CONTEXT = new ThreadLocal<>();

    @Override
    public String get() {
        return ofNullable(USER_CONTEXT.get())
                .map(UUID::toString)
                .orElse(null);
    }

    @Override
    public void accept(UUID uuid) {
        USER_CONTEXT.set(uuid);
    }
}
```

And call accept once in each trace

**Comment by dzou** [comment]
Thanks @artemptushkin -- This is a great solution; we will document this better.

**Comment by amiyalenka82** [comment]
@artemptushkin To set the namespace into ThreadLocal, I need to retrieve the value from somewhere. How to get the namespace value in UserContextProvider (the custom NamespaceProvider) ?

**Comment by artemptushkin** [comment]
@amiyalenka82 I would say, as soon as you get it. I share a cooler class for a case if your trace starts in Spring Rest Controller, classic web servlet

```java
@Component
@RequiredArgsConstructor
@Scope(proxyMode = ScopedProxyMode.TARGET_CLASS)
public class HeaderValueProvider implements Supplier<String>, DatastoreNamespaceProvider {
	private final HttpServletRequest httpServletRequest;

	@Override
	public String get() {
		return httpServletRequest.getHeader("someHeader");
	}
}
```

You don't even need to set anything. @dzou consider this as also a sample
