### ISSUE TITLE
consumer.concurrency setting is a no-op in cloud streaming with Pub/Sub

### ISSUE THREAD

**Issue by dmccobra** [spring-cloud/spring-cloud-gcp#2209]
My application is receiving messages using Spring Cloud Stream bound to GCP pubsub. I'm experimenting with the following configuration parameters:

spring.cloud.gcp.pubsub.subscriber.executor-threads
spring.cloud.stream.bindings.<channelName>.consumer.concurrency

The application has 3 different channels, each of which has a consumer group defined. Multiple instances of the application will be running in production (on kubernetes). The app uses spring-cloud-gcp-core version 1.1.1.RELEASE and spring-cloud-gcp-pubsub version 1.1.1.RELEASE

I'm trying to find the right settings to configure to determine how many messages can be processed in parallel in each app instance. I've been experimenting on my local machine tweaking both of the above parameters, but only executor-threads seems to have any effect. If I set it to say 5, and pump a bunch of messages into the system, I see 5 threads in my message handling logs. If I bump it up to 10, I see 10 threads there. The concurrency parameter, however, doesn't seem to do anything, no matter if it's set to 1 or 10 or whatever.

What is the relationship between these parameters, if any? Is the concurrency parameter only used for other binders like Rabbit or Kafka?

Thanks.

**Comment by elefeint** [comment]
You are correct -- we never implemented the stream binder property handling, relying on application-global [Pub/Sub properties](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/docs/src/main/asciidoc/pubsub.adoc#configuration) instead. This is simpler but limits ability to adjust these settings per-consumer.

There is one more Pub/Sub property you may be interested in -- `spring.cloud.gcp.pubsub.subscriber.parallel-pull-count` that determines how many pullers (each with an executor with `spring.cloud.gcp.pubsub.subscriber.executor-threads` number of threads) will be created.

The global Pub/Sub properties likely meet your current requirement, but it's a good feature request to provide per-consumer flexibility.

**Comment by meltsufin** [comment]
@dmccobra May I ask you, why aren't you using the 1.2.x version of the project?

**Comment by dmccobra** [comment]
@meltsufin 1.1.1 is what we have running in production. We are using Bigtable, spanner and pubsub and if I recall correctly we were having problems with getting all three of these to work correctly when updating everything to latest versions. Another group is responsible for some of these areas - I'm not sure when the last time they tried an updgrade was.

**Comment by dmccobra** [comment]
@elefeint Thanks for the insight and for information on `spring.cloud.gcp.pubsub.subscriber.parallel-pull-count`

**Comment by meltsufin** [comment]
Please re-open if you have further questions/comments.
