### ISSUE TITLE
Did checkstyle stop enforcing `this.` prefix on class members?

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2231]
Make sure checkstyle is not borked in general. If only `this.` enforcement got relaxed, can't say I'll miss it.

**Comment by meltsufin** [comment]
Are you saying checkstyle checks are not working anymore?

**Comment by elefeint** [comment]
Checkstyle definitely works in general. It just got me on a non-standalone-brace in a catch block, which is good.

**Comment by elefeint** [comment]
So, `this.` enforcement on class members was disabled a [loooong time ago](https://github.com/spring-cloud/spring-cloud-build/commit/58cbac5e860713bf9b3462fc6da019cc0bc007b5) in Spring Cloud.
