### ISSUE TITLE
CNF: sun.security.tools.keytool.CertAndKeyGen that RSAKeyGeneratorUtils uses

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#2240]
`sun.security.tools.keytool.CertAndKeyGen` might have been removed in JDK 11?
This is only affecting `FirebaseJwtTokenDecoderTests`.

cc/ @viniciusccarvalho

**Comment by elefeint** [comment]
This is crimping my style; tired of switching to 8. I'm going to fix the test.

**Comment by viniciusccarvalho** [comment]
Sorry did not had any spare cycles to look at it. It should be very simple to just load a cert in memory, one that has already been pre created. I was just avoiding that approach (lots of people use) just to avoid cert expiration issues on tests, but I guess we could set it to a very long time in the future.

**Comment by elefeint** [comment]
@viniciusccarvalho I'm too lazy; found an MIT-licensed library that required minimal changes to your code.
Could you take a look at #2249 when you get a chance? I can't set you as an official reviewer because of project settings.

**Comment by viniciusccarvalho** [comment]
LGTM, thank you @elefeint
