### ISSUE TITLE
Consider removing the custom `Scheduler` from `PubSubReactiveFactory`

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2246]
After #2227 is merged, the scheduler will only be used to trigger `Flux.interval()`, which already uses `Schedulers.parallel()` by default. The chained operations are an async call to Pub/Sub and a flat map, but these are executed on `PubSubSubscriberTemplate.asyncPullExecutor`.

`GcpPubSubReactiveAutoConfiguration` after #2227 would use `Schedulers.parallel()` unless a custom `pubSubReactiveScheduler` bean is provided through user configuration.

The question is, would anyone ever actually want to override the default Reactor-wide parallel scheduler.

[PR thread with more context](https://github.com/spring-cloud/spring-cloud-gcp/pull/2227/files#r389870557)

**Comment by meltsufin** [comment]
Decided not to do this.
