### ISSUE TITLE
Spring Cloud GCP/Serverless/Google Cloud Run - https://cloud.google.com/run

### ISSUE THREAD

**Issue by sb-cloudscience** [spring-cloud/spring-cloud-gcp#2253]
### Spring Cloud GCP and Google Cloud Run Abstractions

**Google Cloud Run Serverless Platform builds on KNative to run stateless containers on a fully managed environment.**

Spring Cloud GCP should be able to provide the abstractions to the Cloud Run for Spring Cloud runtime on Cloud Run.

- [ ] Spring Cloud Observability with CloudRun
- [ ] Spring Cloud Function Composition with CloudRun
- [ ] Spring Initializr https://start.spring.io/ for CloudRun
- [ ] Spring Boot Maven and Gradle Plugins for CloudRun

**Comment by meltsufin** [comment]
@sb-cloudscience Please add more context.

**Comment by sb-cloudscience** [comment]
> @sb-cloudscience Please add more context.
Please see the context added. Thank you.

**Comment by meltsufin** [comment]
Please re-open if you have more specifics.
