### ISSUE TITLE
FirestoreReactiveRepository yields GRPC-errors after enabling Trace

### ISSUE THREAD

**Issue by olssonoskar** [spring-cloud/spring-cloud-gcp#2254]
**Describe the bug**
Spring boot version: 2.2.5
Spring Cloud version: Hoxton.SR3

Queries via FirestoreReactiveRepository results in error with root cause "UNIMPLEMENTED: GRPC target method can't be resolved" if using trace. Enabling/disabling trace in configuration will change between expected/normal behavior and this error. 

Expected behavior would be to get the document back and tracing-information to be present on the google cloud project. 

**Sample**
Simple sample included, hopefully all that is needed to reproduce.
[tracingfirestore.zip](https://github.com/spring-cloud/spring-cloud-gcp/files/4349732/tracingfirestore.zip)

**Comment by dmitry-s** [comment]
It fails on google.firestore.v1.Firestore/RunQuery request.
@meltsufin @elefeint any ideas why it would fail when tracing is enabled but works otherwise?

**Comment by elefeint** [comment]
Certainly a trace issue, based on this (the new reactor stack traces are awesome):
`checkpoint ⇢ org.springframework.cloud.sleuth.instrument.web.TraceWebFilter [DefaultWebFilterChain]`

Likely something with stream instrumentation in Zipkin GCP. Let me dig into that.

**Comment by meltsufin** [comment]
I don't really have any ideas without looking deeper into this. The first thing I would try would be to update to the latest versions of everything and make sure there are no diamond dependency issues.
@elefeint Thanks for helping out.

**Comment by olssonoskar** [comment]
Thanks @elefeint for resolving this issue!
Anyway to use a snapshot just to verify that this solves our issue as well? 
I tried to use the one from spring snapshot repo but seems some dependencies are not available and I'm uncertain if this is on my side or not. 
I'd just like to know that everything works as intended in the next release!

**Comment by elefeint** [comment]
You should be able to use the snapshots repository by adding the following repo to the pom file, and setting the spring-cloud-gcp dependency version to `1.2.3.BUILD-SNAPSHOT`.
```
<repositories>
				<repository>
					<id>spring-snapshots</id>
					<name>Spring Snapshots</name>
					<url>https://repo.spring.io/libs-snapshot-local</url>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
					<releases>
						<enabled>false</enabled>
					</releases>
				</repository>
</repositories>
```

**Comment by elefeint** [comment]
Let us know which dependencies are having trouble!

**Comment by olssonoskar** [comment]
The problem was on my side, the build snapshot included a milestone dependency, so i had to add the milestone repository as well.
But this seems to be working just fine now. 👍 
Thanks again to all of you!
