### ISSUE TITLE
SecretManager - ability to configure version/label to select

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#2260]
**Is your feature request related to a problem? Please describe.**
SecretManager allows me to create a key/value pair but with different versions. I'd like to be able to be explicit to which version to use in case I need to rollback my application to a previous configuration.

**Describe the solution you'd like**
in bootstrap.properties, ability to configure `...secretmanager.version`?

Secret Manager also allows users to label each key, can labels be selected?

**Comment by dzou** [comment]
Thanks for the request Ray, yes will definitely look into this.

Just as a first thought, would it be reasonable to allow users to specify the version they want for each secret individually and default to latest if not specified? I.e. something like:

```
spring.cloud.gcp.secretmanager.versions.<YOUR_SECRET_ID>=3
```

**Comment by saturnism** [comment]
thnx @eddumelendez!

btw, for labels, is there a way to limit the secrets using labels as well?

**Comment by dzou** [comment]
Oh yes, that is a good idea; we can definitely add a label filter to filter only adding secrets with a certain label.

**Comment by meltsufin** [comment]
Obsolete.
