### ISSUE TITLE
Whitelisted MDC keys in Sleuth are not present when Trace is enabled

### ISSUE THREAD

**Issue by olssonoskar** [spring-cloud/spring-cloud-gcp#2268]
**Describe the bug**
Cloud version: Hoxton.SR3
Boot version: 2.2.5

We configure Sleuth to include request headers in the mdc (for logs). It works well with the StackdriverJsonLayout by default, but after enabling trace, these headers are not populated anymore.

The expected behavior is that the population of MDC should work and be included in logging statements no matter if trace is enabled or not. 

Including sample project with a test to verify the behavior. Enabling/disabling trace will make the test pass or fail.

[demo.zip](https://github.com/spring-cloud/spring-cloud-gcp/files/4369124/demo.zip)

**Comment by dzou** [comment]
Thanks for the report and the reproducible example @olssonoskar . I will take a look at this for you and hope to followup shortly.

**Comment by dzou** [comment]
@meltsufin - Some initial first thoughts after debugging - I think this might be related to zipkin code since the traces bring in Zipkin; maybe there is some code in our Zipkin dependencies that is not forwarding the MDC headers correctly.

**Comment by meltsufin** [comment]
@adriancole Do you have hints for us on how to investigate this?

**Comment by adriancole** [comment]
@olssonoskar can you make a fork of this branch and add your changes to it (without gcp in use) I'd like to see if this is sleuth in general or specifically when -gcp is involved https://github.com/openzipkin/sleuth-webmvc-example#spring-webflux-tracing

when done, post your fork back here which has a commit of your changes. it makes it really easy to validate. cheers!

**Comment by adriancole** [comment]
@meltsufin first trying to see if this has to do with the assembly hooks added by sleuth

**Comment by meltsufin** [comment]
I tried `spring.sleuth.log.slf4j.whitelisted-mdc-keys=req-id` instead of `log.slf4j.whitelisted-mdc-keys=req-id` as recommended in the [documentation](https://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/2.1.0.RELEASE/single/spring-cloud-sleuth.html) and it worked for me.

See: https://github.com/openzipkin/sleuth-webmvc-example/pull/34

@olssonoskar Can you give a try?

**Comment by meltsufin** [comment]
Never mind, my mistake. You actually have the right property in your example.
Continuing to investigate...

**Comment by meltsufin** [comment]
The difference I'm seeing is in the default extractor in the `HttpServerHandler`.

`ExtraFieldPropagation$ExtraFieldExtractor`
vs.
`CompositeExtractor` with `B3Propagation` and `XCloudTraceContextExtractor`.

**Comment by meltsufin** [comment]
I guess we need to add  `ExtraFieldPropagation` extractor [here](https://github.com/openzipkin/zipkin-gcp/blob/8b2462c054737259bdd707de49da0cc32aaa6806/propagation-stackdriver/src/main/java/zipkin2/propagation/stackdriver/StackdriverTracePropagation.java#L86).

**Comment by meltsufin** [comment]
It looks like the same issue as https://github.com/openzipkin/zipkin-gcp/issues/167.
cc/ @elefeint @adriancole

**Comment by adriancole** [comment]
should be a bit easier to workaround as this has come up before.

From TraceAutoConfiguration
```java
		ExtraFieldPropagation.FactoryBuilder factoryBuilder;
		if (this.extraFieldPropagationFactoryBuilder != null) {
			factoryBuilder = this.extraFieldPropagationFactoryBuilder;
		}
		else {
			factoryBuilder = ExtraFieldPropagation
					.newFactoryBuilder(B3Propagation.FACTORY);
		}
```

So, if you provide a bean like this.

```java
@Bean ExtraFieldPropagation.FactoryBuilder() {
  return ExtraFieldPropagation.newFactoryBuilder(YOUR_FACTORY);
}
```

should work I think

**Comment by adriancole** [comment]
because you just need to wrap your factory. I wouldn't do any more engineering than this because the concept of how correlation fields work is likely to change anyway at some point.

**Comment by meltsufin** [comment]
@adriancole Thanks for the suggestion! This is perfect because we would no longer skip all of the logic in `TraceAutoConfiguration.sleuthPropagation()`.

**Comment by meltsufin** [comment]
@olssonoskar We're waiting for the next Brave release to be added to Sleuth, but in the meantime, you can just add this bean to your application configuration to get the extra fields working.
```java
	public ExtraFieldPropagation.FactoryBuilder extraFieldPropagationFactoryBuilder() {
		return ExtraFieldPropagation.newFactoryBuilder(StackdriverTracePropagation.FACTORY);
	}
```

**Comment by olssonoskar** [comment]
I see, still great that the issue was resolved!
Any possibility that this will not be included in the release of 1.2.3 since awaiting brave release?

**Comment by meltsufin** [comment]
`1.2.3` is currently scheduled for March 11 along with the rest of the Spring Cloud release train.
It should make it in. We're waiting for the next Brave release and the Sleuth release that would follow.

**Comment by adriancole** [comment]
fyi for the moment, 2.x sleuth will stay with ExtraFieldPropagation eventhough it is deprecated. made changes here in brave 5.11 https://github.com/spring-cloud/spring-cloud-sleuth/pull/1595

3.x sleuth will move to the new BaggageField type for configuration, including BaggagePropagation. This is a lot more flexible, but the main difference for you is using that builder as an entrypoint instead of ExtraFieldPropagation.FactoryBuilder


 In both cases you can use BaggageField to get values (even if configured implicitly with ExtraFieldPropagation.FactoryBuilder) we might make some backwards safe trick for sleuth 2.x who supply BaggagePropagation.FactoryBuilder, though.. will keep you posted.

**Comment by meltsufin** [comment]
Is Sleuth 2.2.x going to move to Brave 5.11.1? If so, are you expecting to release it soon? Thanks!

**Comment by adriancole** [comment]
It is already 5.11.1 I'm not sure the next release of 2.2.x. I know 3.0 milestone (boot 2.3.x) seems to be blocking on me for monday.

https://github.com/spring-cloud/spring-cloud-release/milestones

@marcingrzejszczak do you know?
