### ISSUE TITLE
Exception from the Google credential lib is been lost on a try catch

### ISSUE THREAD

**Issue by abgm** [spring-cloud/spring-cloud-gcp#2272]
**Describe the bug**
I'm using spring cloud lib on a GKE cluster with workload identity. And I have a issue that I can debug correctly because the important exception for me is been lost by this lib. See commit below.

The application fail on the context initialization... The the only information is that log that is changed on this commit

Will be great have this fixed on the new version of this lib. 

Thanks

**Commit causing**
https://github.com/spring-cloud/spring-cloud-gcp/commit/dcce3c60f58149bc5008272e2068a4c98205ad15

**Comment by meltsufin** [comment]
Are you asking to include the exception in the log message like it was before this commit?

**Comment by abgm** [comment]
Yes please.
