### ISSUE TITLE
Add annotation which bring support to test against spanner

### ISSUE THREAD

**Issue by eddumelendez** [spring-cloud/spring-cloud-gcp#2281]
**Is your feature request related to a problem? Please describe.**

Make easy to test using spanner

**Describe the solution you'd like**

Looking into [testing-code-that-uses-cloud-spanner](https://github.com/googleapis/google-cloud-java/blob/master/TESTING.md#testing-code-that-uses-cloud-spanner) I think the project can provide the infrastructure with `@DataSpannerTest` annotation. There are similar annotation for `neo4j`, `jdbc`, `jpa` and so on in the spring-boot project

**Describe alternatives you've considered**

* Add documentation related to it
* Provide an `AbstractSpanner` class

**Comment by meltsufin** [comment]
We are already developing support for testing with Spanner emulator.
See: #2357 
Do you still think we need to add support for `@DataSpannerTest`?

**Comment by eddumelendez** [comment]
[this](https://gist.github.com/eddumelendez/2a305ea223b4fd34aa69a27d667f4678) is what we currently should do in order to test the repositories.

With the `@SpannerTest` or `@DataSpannerTest` we can provide the right dependencies via `spring.factories` and drop the config to detect repositories. However, the properties need to be set.

I am wondering how the amazing work #2357 can also help this approach too! I am also thinking about testing the emulator not only against localhost but also include testcontainers.

**Comment by meltsufin** [comment]
Closing in favor of: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/159
