### ISSUE TITLE
Allow Language to be added in CloudVisionTemplate

### ISSUE THREAD

**Issue by santpandey123** [spring-cloud/spring-cloud-gcp#2282]
**Is your feature request related to a problem? Please describe.**
We are actually using SpringCloud to use GoogleVision for OCR(Optical Character Recognition) purpose. We are using  CloudVisionTemplate to interact with Google's OCR.

However there is a limitation in analyzeImage method in CloudVisionTemplate. The limitation is:
1. We can't pass ImageContext object to analyzeImage method.

Sometimes we need to OCR to return only English alphabets in response. We can achieve this using ImageContextObject like this:

 ImageContext imageContext = ImageContext.newBuilder().addLanguageHints("en").build();

And setting imageContext in the request like:
AnnotateImageRequest.newBuilder().setImageContext(imageContext)

**Describe the solution you'd like**
I would like the analyzeImage and extractTextFromImage to accept an additional optional parameter of ImageContextType.

**Describe alternatives you've considered**
Sadly, I was not able to figure out how to pass ImageContext object to both of the above methods. So I ended up not using CloudVisionTemplate class at all and wrote similar code in my method itself

**Additional context**
We came across this issue because we were persisting OCR response in a MYSQL table in seperate String columns. We had written logic to reject non English words prior to saving to Mysql.
But we could see that there were encoding issues at OCR's end for English words which caused write failure for English words.
Refer this article for more info:
https://medium.com/@santosh.pandeyy/limitation-of-springs-google-vision-client-b1ac2f6ba2b1?sk=39d12cf6adf3ab5180978dc8701f9452

**Comment by dzou** [comment]
Thanks for the report!

Yes, we can definitely add this in, I'll share with you a PR shortly.

**Comment by dzou** [comment]
Hey, just made a PR to add this in; let me know if you have any comments: https://github.com/spring-cloud/spring-cloud-gcp/pull/2286
