### ISSUE TITLE
Consider using underscores to be the namespace-separating character in Secret Manager

### ISSUE THREAD

**Issue by dzou** [spring-cloud/spring-cloud-gcp#2285]
If users are interested in naming their secret id's to match the property keys used in Spring, they need a workaround solution since periods are not allowed to be in the secret ID in secret manager.

We can consider offering the option of converting underscores to periods in the secret ID.

**Comment by avdLuna** [comment]
Hello, i want to contribute with this issue. There`s something i should know first besides Google Cloud and Springboot ?

**Comment by dzou** [comment]
Hey @avdLuna - Thanks for your interest!

Unfortunately this issue might not be a good one to start with; we're actually starting new work for [building a new way of specifying secrets](https://github.com/spring-cloud/spring-cloud-gcp/issues/2283#issuecomment-608619326) which may make this feature obsolete.
I think it will be more clear in the next week or two whether we still want to pursue this or not after we commit the new secret manager code.

We are very excited to have external contributors though, if there is another issue that might interest you, please don't hesitate to ask.

**Comment by dzou** [comment]
Gonna close this; I think it will be obsolete with #2302 in.
