### ISSUE TITLE
Refactor HealthIndicator autoconfiguration

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2292]
For 1.3.x, as this is a backwards-incompatible change.
Follow up to #2280.

`PubSubHealthIndicatorAutoConfiguration` and `DatastoreHealthIndicatorAutoConfiguration` ought to be embedded in the overall product autoconfig.

See [discussion](https://github.com/spring-cloud/spring-cloud-gcp/pull/2040#discussion_r347659326) in original PubSub implementation for background.

This refactoring for Pub/Sub has been done in branch `health-indicator-autoconfig-for-1.3` (the test was incorporated as `PubSubHealthIndicatorTests.healthIndicatorDisabledWhenPubSubTurnedOff`

**Comment by meltsufin** [comment]
Obsolete.
