### ISSUE TITLE
Secret Manager: Useful sample files?

### ISSUE THREAD

**Issue by guillaumeblaquiere** [spring-cloud/spring-cloud-gcp#2299]
Not a bug, more a question.

In my tests, I removed the file [MyApplicationProperties](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/java/com/example/MyAppProperties.java) and [this line](https://github.com/spring-cloud/spring-cloud-gcp/blob/820a5dcd0f7e1c0937958ac8c14bfc30072950c0/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/java/com/example/SecretManagerApplication.java#L24) and all work correctly.

Do I miss or not understand something? Or the files are legacy and not useful today?

**Comment by dzou** [comment]
Ah, that field was just used to demonstrate you can also `@Autowire` a properties class if needed. But that is a good point; I guess because the field is not being used that no error was produced.

**Comment by guillaumeblaquiere** [comment]
Anyway, it's a good example, I didn't know this capability! But not really in relation with secret manager!!
