### ISSUE TITLE
CSRF protection with Secret Manager

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#2308]
We should provide an implementation of `CsrfTokenRepository` that would allow developers to use CSRF tokens generated by the Secret Manager. We have to also think about token rotation. A sample application should also be provided.

cc/ @sethvargo @saturnism

**Comment by sethvargo** [comment]
Ping @tam7t

**Comment by meltsufin** [comment]
Closing due to lack of demand.
Please re-open in the new repo, if you're interested: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues.
