### ISSUE TITLE
Getting a single entry findBy... results in EmptyResultDataAccessException

### ISSUE THREAD

**Issue by mirjalal** [spring-cloud/spring-cloud-gcp#2316]
Hi *.

**Version: 1.2.2.RELEASE
JDK: 8
Spring Boot Version: 2.2.6.RELEASE
Kotlin: 1.3.71**

I have a simple repository like this:

```
interface ApiUserRepository : DatastoreRepository<ApiUser, Long> {
    fun findByUsername(username: String): ApiUser? // notice that return type is nullable
}
```

But when that method called (**AND** there is **no data** related with the username in datastore) the exception thrown:
`org.springframework.dao.EmptyResultDataAccessException: Expecting at least 1 result, but none found`

The exception message comes from [here](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/repository/query/PartTreeDatastoreQuery.java#L179). 

I also tried to change repository function return type to non-nullable, but it didn't help.

**Comment by dmitry-s** [comment]
Hi @mirjalal, 

It works as expected. In order to allow find method to return `null` you need to annotate it with `@Nullable` annotation. 

Example from our docs:
```
  //throws an exception if no results
  Trader findOneByAction(String action);

  //because of the annotation, returns null if no results
  @Nullable
  Trader getByAction(String action);
```

Feel free to reopen if that didn't help.

Thanks,
Dmitry

**Comment by mirjalal** [comment]
Hi @dmitry-s 

I am so sorry but I should reopen the issue. 

I have already marked find method as nullable. The function return type is `ApiUser?` which `?` symbol stands for nullable type.

I hope I gave clear explanation.

p.s. The same code works well with `JpaRepository`.

Thanks,
Mirjalal

**Comment by meltsufin** [comment]
@dmitry-s Can you look into how Spring Data JPA supports this in Kotlin?
