### ISSUE TITLE
Create a test rule for Spanner emulator

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#2318]
The rule should automatically start and stop the emulator.

**Comment by eddumelendez** [comment]
@dmitry-s have a few quesitons regarding to this. As far as I can see, there is `PubSubEmulator`. So,

* Can we use this existing rule to create `SpannerEmulator`?
* `ExternalResource` is based on JUnit 4 but I can see that `spring-cloud-gcp` is supporting `2.3.x`, have you considered moving this to JUnit 5 or support both?
* At the beginning, I though there should be a auto-configuration class to start spanner or pubsub like currently firestore or datastore do.

**Comment by dmitry-s** [comment]
Hi @eddumelendez ,

At this point, Cloud Spanner Emulator set up and start is a multi step process, as it requires installing components of gcloud, installing docker, and also configuring gcloud and creating instances. Because of that I am not sure if we can/should create a rule for  Cloud Spanner Emulator.

@meltsufin what do you think?

**Comment by meltsufin** [comment]
@dmitry-s Docker is only required on Mac and Windows.
Assuming that all of the components are installed, what are your concerns?
Does it make sense to just focus on starting and stopping the emulator, as the issue originally intended.

**Comment by saturnism** [comment]
can we/combine this work w/ @eddumelendez 's Testcontainer modules? https://github.com/eddumelendez/testcontainers-java/tree/gcloud/modules/gcloud/src/main/java/org/testcontainers/containers

**Comment by meltsufin** [comment]
@saturnism The test containers look pretty cool! However, we're providing emulator support here without the use of containers (except for Spanner).
Maybe there is still some code we can reuse, I don't know.

**Comment by elefeint** [comment]
Testcontainers is the way to go for all emulators. We should not be providing separate support; the way I did it for Pub/Sub is more fragile (relies on finding PID, keeps track of subprocesses. meh.)
