### ISSUE TITLE
Pub/Sub Asynchronous pull retry mechanism for failure handling

### ISSUE THREAD

**Issue by sxg370** [spring-cloud/spring-cloud-gcp#2326]
We have spring application consumes messages from a pubsub topic through asynchronous pull subscription and makes REST(post) call to a target application. For the happy path scenario, flow is working as expected. But we want to have more control over resent messages because of any failures, for that we wanted to use retry configurations. Failed messages come back within 10 sec as per acknowledgment deadline. We want to postpone the repeated consumption of these messages and set limit on maximum retries. In case of any failures like target application down or any network connectivity issues between spring application and target application, without maximum retries limit, spring application is continuously retries to receive messages from pubsub and make post calls to target application. Also it sends logs to stack driver, which can make the app to hang up. We thought the below retry setting are designed to handle such cases.

According to this document https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-pubsub-integration/#5 we have defined beans and as per this https://docs.spring.io/spring-cloud-gcp/docs/1.1.0.M1/reference/html/_spring_cloud_gcp_for_pub_sub.html I have set retry configuration in application profile config. like this:
spring.cloud.gcp.pubsub.subscriber.retry.initial-retry-delay-second: 4
spring.cloud.gcp.pubsub.subscriber.retry.max-attempts: 5
spring.cloud.gcp.pubsub.subscriber.retry.max-retry-delay-seconds: 7
spring.cloud.gcp.pubsub.subscriber.retry.total-timeout-seconds: 3000

but it had no effect on the reoccuring of the messages.

Does spring-cloud-gcp-pubsub supports retry config? Do we set the retry configurations correctly? If it won't support, then how to solve this issue?

Thanks for any suggestions!

**Comment by meltsufin** [comment]
See similar question here: https://stackoverflow.com/questions/54534403/what-are-the-retry-settings-for-subscriber-in-pubsub-and-how-to-set-them-correct

These retry settings are low level GRPC retry settings. They do not relate to the actual behavior of Pub/Sub. What you are describing sounds more like a need for a dead-letter queue which is not currently supported by Pub/Sub. You can implement it yourself by acking the messages that fail and publishing them to another queue. Of course this can be a bit cumbersome to do reliably.

The somewhat promising news is that Dead Letter Queue support is coming to Pub/Sub and is currently in Alpha. See here: https://cloud.google.com/sdk/gcloud/reference/alpha/pubsub/subscriptions/create

**Comment by elefeint** [comment]
The retry settings' naming is a bit misleading here -- they refer to the retries performed when a gRPC call to the Pub/Sub service fails for a retryable reason (such as network timeout).

To implement a "please do not redeliver this message, as it cannot be processed due to a downstream issue" strategy, you'd need to programmatically extend the acknowledgement deadline.

To extend the deadline on a single message, use `AcknowledgeablePubsubMessage.modifyAckDeadline()`.
To extend the deadline on a known collection of messages, use `PubSubTemplate.modifyAckDeadline()` method.

**Comment by elefeint** [comment]
If you'd like to do exponential backoff on your HTTP application (and perhaps only ack the Pub/Sub message when the HTTP call succeeds), this helper library might be of use: http://googleapis.github.io/google-http-java-client/exponential-backoff.html

**Comment by sxg370** [comment]
@meltsufin @elefeint Thanks for the quick response! 

> See similar question here: https://stackoverflow.com/questions/54534403/what-are-the-retry-settings-for-subscriber-in-pubsub-and-how-to-set-them-correct
> 
> These retry settings are low level GRPC retry settings. They do not relate to the actual behavior of Pub/Sub. What you are describing sounds more like a need for a dead-letter queue which is not currently supported by Pub/Sub. You can implement it yourself by acking the messages that fail and publishing them to another queue. Of course this can be a bit cumbersome to do reliably.
> 
> The somewhat promising news is that Dead Letter Queue support is coming to Pub/Sub and is currently in Alpha. See here: https://cloud.google.com/sdk/gcloud/reference/alpha/pubsub/subscriptions/create

Thanks for the quick response! That is great to know. Do you have any idea when it will be released? Even we can start using it if it is in beta.

**Comment by sxg370** [comment]
> If you'd like to do exponential backoff on your HTTP application (and perhaps only ack the Pub/Sub message when the HTTP call succeeds), this helper library might be of use: http://googleapis.github.io/google-http-java-client/exponential-backoff.html

@elefeint Thanks for the details! I will try implementing these and once Dead Letter Queue support is added then I will switch to using that .

**Comment by meltsufin** [comment]
> > The somewhat promising news is that Dead Letter Queue support is coming to Pub/Sub and is currently in Alpha. See here: https://cloud.google.com/sdk/gcloud/reference/alpha/pubsub/subscriptions/create
> 
> Thanks for the quick response! That is great to know. Do you have any idea when it will be released? Even we can start using it if it is in beta.

Apparently it's GA as of yesterday. So, feel free to start using it.

**Comment by meltsufin** [comment]
Closing in favor of #2328.

**Comment by dzou** [comment]
@sxg370 - Hey we're interested in adding support for deadletter queues (tracking here #2328). Just to understand more your use pattern - Are you using Pub/Sub template through Spring Integration or Spring Cloud Stream? Or just through standard PubSubTemplate usage?

**Comment by sxg370** [comment]
We are using the Spring cloud stream followed this [example](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/java/com/example/SinkExample.java) to implement. To make our app resilient, we have two requirements 1) Dead letter support 2) add retry delay. So along with the spring cloud stream, I tried other patterns also, but nothing worked. To answer your question, we are using the Spring cloud stream.

**Comment by dzou** [comment]
I see, thank you for letting us know. Yes we definitely will look into both areas you mentioned.

As a temporary solution for now - if you're interested in trying the dead letter queues I went through these instructions yesterday and it works as expected: https://cloud.google.com/pubsub/docs/dead-letter-topics

Basically if a message is sent through the topic and it gets nacked 5 times (this is configurable) Pub/Sub will not try to keep redelivering the message but forward this to the dead letter queue.

Using the [example](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/java/com/example/UserMessage.java#L34) you linked, you can try this out by starting the app up (which I think is configured to auto-create a subscription to the topic). Then find this subscription in Cloud Console and then follow the instructions to add the dead letter queue topic to this subscription. Then try sending a message through the app and set the `throw error` option to true to see what happens.

We're going to try to make this process more seamless... some ideas might be to automatically configure this dead letter topic correctly in spring cloud stream so you don't have to worry about it. And we'll look into the retry delay issue, I wonder if there is something we can do there. Maybe you can let us know if you find a particularly interesting feature you want implemented.

**Comment by elefeint** [comment]
Cloud Pub/Sub now has native support for exponential backoff: https://cloud.google.com/pubsub/docs/admin#using_subscription_properties
