### ISSUE TITLE
Find a way to augment DataSourceProperties after GcpCloudSqlAutoConfiguration 

### ISSUE THREAD

**Issue by johannesgiani** [spring-cloud/spring-cloud-gcp#2330]
In GCP CloudSQL postgres, a password for the user has to be provided. A way to handle credentials like this password when running on App Engine is to use KMS to get an encrypted credential from somewhere and decrypt it at runtime. It would be cool to find a solution to augment the properties provided by the auto configuration like this, which is not possible right now because `GcpCloudSqlAutoConfiguration` already exposes `DataSourceProperties` as primary.

```
@Bean
public DataSourceProperties dataSourceProperties(DataSourceProperties dataSourceProperties) {
    dataSourceProperties.setPassword("myDecryptedPasswordFromSomewhere");
    return dataSourceProperties;
}
```

I already asked that question on stackoverflow but without a satisfying answer: https://stackoverflow.com/questions/57824017/enhance-datasourceproperties-configuration-bean-with-kms-provided-secret/57857437?noredirect=1#comment102410137_57857437

**Comment by meltsufin** [comment]
@johannesgiani You should be able to provide your own bootstrap property source that contains a value for `spring.datasource.password`. In fact, this is something we do for our Secret Manager integration.

See: https://cloud.spring.io/spring-cloud-commons/multi/multi__spring_cloud_context_application_context_services.html#customizing-bootstrap-property-sources

**Comment by meltsufin** [comment]
[Here's an example](https://github.com/spring-cloud/spring-cloud-gcp/pull/2331/commits/ac7394f4dfae9ea801e0fb8281147926ba755b8b).

**Comment by johannesgiani** [comment]
Awesome, many thanks. I wasn't aware of those bootstrapping capabilities.
