### ISSUE TITLE
Separate credentials per PubSub topic or subscription

### ISSUE THREAD

**Issue by jed-meyer** [spring-cloud/spring-cloud-gcp#2353]
We got two separate credentials for two pubsub topics of the same project-id and there doesn't seem to be an obvious way to provide credentials per topic/subscription.

Is this possible using Spring Boot with Spring Cloud GCP?

**Comment by meltsufin** [comment]
`DefaultSubscriberFactory` has a setter for `CredentialsProvider`. That might help depending on your specific use case. Are you using the `PubSubTemplate` directly? It's bound to a single `CredentialsProvider`. So, it's not going to be super straightforward.

Have you considered creating a service account that has permissions on both topics? GCP IAM is very flexible that way.

**Comment by jed-meyer** [comment]
Yes, we currently use `PubSubTemplate` directly.

A single service account with all needed permissions is something we asked for in the first place but since it's an _ultraflexible_ microservices approach we are coding against the other party is very reluctant to provide any.

Will head over to SO for further help, might need some more kickstart to get things rolling.

Thank you very much for your efforts and clarification!

**Comment by elefeint** [comment]
It seems that you've worked it out, but in case it helps: you'd need to create two separate `PublisherTemplate` objects, similar to how we create the default one in the [autoconfiguration](https://github.com/spring-cloud/spring-cloud-gcp/blob/2adf4328c819a634a3ad7a1627426badf198c4fb/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java#L150), and pass it two custom `PublisherFactory` objects like [this one](https://github.com/spring-cloud/spring-cloud-gcp/blob/2adf4328c819a634a3ad7a1627426badf198c4fb/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java#L317), using the factory's `.setCredentialsProvider()` method to inject custom credentials.

**Comment by jed-meyer** [comment]
Thank you for your help! Kind of eager to try that out, but since we'll need at least four different credentials with more on their way, this will probably make some nasty code. We finally convinced the other party to provide us with a single account solving our issue.

Feature request, though: let users pass pubsub credentials per topic

**Comment by elefeint** [comment]
Since credentials are tied to a gRPC stub, this would require creating a separate publisher/subscriber factory equivalent in autoconfiguration code. So this code duplication would have to exist somewhere, and since it's not the most typical usecase, we are unlikely to add multiple objects for each topic to the context...

**Comment by jed-meyer** [comment]
Fine with me, had to ask nevertheless :) Thanks again @elefeint and @meltsufin, keep up with your great work!
