### ISSUE TITLE
spring.cloud.gcp.pubsub.emulator-host doensn't work

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#2367]
Failed w/ URI exception, i don't know if we needed to prefix w/ `dns:///`. I can create it w/o the prefix.

Secondly, the `transportChannelProvider` is pretty generic, if we configure pubsub to use the emulator host, shouldn't this be scoped only to pub/sub? in case there are others expecting a `transportChannelProvider` too?

Lastly, `CredentrialsProviderrs` should default to `NoCredentialsProvider` for this one.

/cc @eddumelendez

**Comment by dmitry-s** [comment]
`spring.cloud.gcp.pubsub.emulator-host` works  for me.

@saturnism could you provide a sample app so I can replicate the issue?

Thanks!

**Comment by meltsufin** [comment]
This might be somewhat unrelated, but we should consider adding a `spring.cloud.gcp.pubsub.emulator.enabled` property to be consistent with other emulator support configs.

**Comment by saturnism** [comment]
@dmitry-s i wsa getting a URI exception Let's schedule some time to see this on gvc.

**Comment by saturnism** [comment]
also, what value did you set it?

**Comment by dmitry-s** [comment]
@saturnism I set it to "localhost:8085"

**Comment by saturnism** [comment]
I think the difference is I used an IP address.  Do we really need the dns:/// prefix?

**Comment by elefeint** [comment]
For emulator, likely not.
This was added to production services in #2085, and emulators most likely just got mopped up for consistency.

**Comment by dmitry-s** [comment]
@saturnism you don't need to use dns:/// prefix, we add it automatically.

**Comment by saturnism** [comment]
> you don't need to use dns:/// prefix, we add it automatically

I know - and it's causing the issues when the host is not a dns name, but an ip

**Comment by dmitry-s** [comment]
Oh I see. I'll check if that works.

**Comment by dmitry-s** [comment]
The prefix is required for dns names. I don't think we can switch to requiring users to append it to the host name (breaking change).
Instead, if we want to support ip-addresses we could try to detect them and don't add prefix in that case.

@meltsufin what do you think?

**Comment by eddumelendez** [comment]
> The prefix is required for dns names. I don't think we can switch to requiring users to append it to the host name (breaking change).

@dmitry-s throw a warning when the prefix is not used, wdyt? and let people know that in future versions they need to prepend dns:// and to keep backward compatibility.

**Comment by saturnism** [comment]
It’s so weird that, for hostnames we need to use dns:/// but for IP, it’s be something else different :/

**Comment by dmitry-s** [comment]
@eddumelendez that makes sense. Actually since it's only used for testing we can just throw exception with a message that we now require dns:/// to be present.

**Comment by saturnism** [comment]
My bad - the code works as-is. I misconfigured it from the test, where the correct way is:
```
TestPropertyValues.of("spring.cloud.gcp.pubsub.emulator-host=" + PUBSUB_HOST)
          .applyTo(ctx);
```

I made the mistake of:
```
TestPropertyValues.of("spring.cloud.gcp.pubsub.emulator-host", PUBSUB_HOST)
          .applyTo(ctx);
```

apologies!

**Comment by saturnism** [comment]
Also, prefer _not_ having to specify the dns prefix.
