### ISSUE TITLE
Secret Manager - ability to load secrets based on application name / profile

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#2368]
**Describe the solution you'd like**
In Runtime Config, config k/v for a single app are grouped under a namespace, so that it can all be loaded for an app.

For Secret Manager, add ability to refer to secrets based on a prefix, such as application.name

For example
`spring.cloud.gcp.secret-manager.prefix=myapp`

And when referring to `${database_password}, it loads `myapp_database_password`, or delimited w/ something more special

**Comment by saturnism** [comment]
secret manager doesn't support '.' at the moment, so we can't do `myapp.database.password

**Comment by dzou** [comment]
To support the Runtime-config use-case we'll see what the results of adding in the '.' names are. Hopefully the additional context you provided on that issue thread will be a good motivator.

But yeah let's wait to see what happens with the `.` discussion, if that doesn't go through we can consider the converting `_` to `.` feature.

**Comment by dzou** [comment]
Unfortunately we haven't gotten through with allowing the usage of `.` in secret manager so going to close this.

I think it may be infeasible to pursue this; so far creating the mappings manually via `some.property={sm://...}` seems to be the only way of doing things. It probably makes secret manager unfit as a candidate to replace runtime config.
