### ISSUE TITLE
Add starters to start.spring.io

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#237]
Would help adoption greatly, especially because currently, for M1, we also need to add Pivotal's milestone repo.

Bonus points for adding an [App Engine Standard Spring Boot app](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/springboot-appengine-standard) too.

**Comment by joaoandremartins** [comment]
@artembilan @sobychacko would any of you know what the right procedure for adding things to start.spring.io is?
Or do you know who I should speak with?

The [website](http://start.spring.io/) doesn't cover that anywhere that I can find.

**Comment by artembilan** [comment]
I think you need to go here https://github.com/spring-io/initializr.

Although I wouldn't be so paranoiac about "Pivotal's milestone repo".
This project is under Spring IO umbrella and there are a lot of Open Source projects.
And that's pretty natural for all the Spring users to follow our recommendations about artifacts.
Even if you worry about some Google users to adopt here they first of all should become familiar with Spring Boot and Spring Framework per se. And for this reason they definitely will come to our milestone repo some way.

More better for the promotion would help something like Release Blog post, like I did recently for Spring Kafka: https://spring.io/blog/2017/11/09/spring-for-apache-kafka-2-1-rc1-and-2-0-1-1-3-1-available. Or  Oleg for the Spring Cloud Stream Elmhurst.M3: https://spring.io/blog/2017/11/09/spring-cloud-stream-elmhurst-m3-2-0-0-m3-release-announcement

Hope that explains a bit.

**Comment by joaoandremartins** [comment]
@artembilan just to clarify, I'm very fine with using Pivotal's MS repo.
I just want to make user experience better by adding the repo declaration to the `pom.xml` directly, so users don't have to copy and paste it.
That's where I think start.spring.io could provide great value!

Side note, it would also help me a lot on my talk if I could specify our starters in start.spring.io instead of copying and pasting them from our refdoc/READMEs :smile:

**Comment by joaoandremartins** [comment]
Fixed by https://github.com/spring-io/initializr/pull/539 (after it gets merged)

**Comment by joaoandremartins** [comment]
Duplicate of #181
