### ISSUE TITLE
PubSubHealthIndicator reported false alarm when pubsub was actually UP

### ISSUE THREAD

**Issue by Will1229** [spring-cloud/spring-cloud-gcp#2374]
PubSubHealthIndicator reports DOWN but pubsub is actually UP in some situations. Error message:

`pubSub: {
status: "DOWN",
details: {
error: "com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action."
}
},`

According to the code here:
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/pubsub/health/PubSubHealthIndicator.java#L56

The health indicator only reports UP if pubsub returns 404 NOT_FOUND when the indicator tries to pull an non-existing subscription id.

It worked before however it failed from yesterday probably because of a recent GCP pubsub change. So now it instead of returning 404, returns a PERMISSION_DENIED 403 for a non-existing subscription. Therefore health check failed. But the connection to pubsub is actually UP.

The fix could be expanding the checking boundary so that all 4xx response codes are considered pubsub UP.

**Comment by elefeint** [comment]
Is it possible that the permissions for the account your application is using have changed?

**Comment by Will1229** [comment]
Not as I know. The application is still able to receive pubsub messages so I believe the permissions are still enough there for a message subscriber.

**Comment by elefeint** [comment]
I've tested it with an admin account, as well as with an account that only has a Pub/Sub Subscriber role, and in both cases 404 is correctly returned from the pull call to a nonexistent subscription.

Part of the health check's usefulness is in verifying credentials, so interpreting 403 Access Denied as being normal would lead to a false positive successful healthcheck but failed actual application requests.

What happens when you use gcloud to pull from a nonexistent subscription with the same credentials used in the health check?

```
gcloud pubsub subscriptions pull exampleSubscription123 
```

For me it returns `NOT_FOUND: Resource not found (resource=exampleSubscription123).`

**Comment by Will1229** [comment]
As I tested with gcloud it also returned 404 NOT_FOUND.

However when my application did this with a service account it returned 403 ACCESS_DENIED.
The service account inherits Cloud Functions Service Agent role which has pubsub roles by default.

Also tried to manually add pubsub admin role into this service account but still didn't work.

I assume you have tested with a service account?

**Comment by Will1229** [comment]
And another thinking: would it be better if we can make the health check subscription-id configurable so that instead of expecting a 404 with a random subscription we can actually check the existence of a real subscription, which guarantees it's healthy.

**Comment by elefeint** [comment]
Could you check if the service account has the Pub/Sub Viewer role?

Making subscription ID configurable is an interesting idea, however that will also require the Viewer role -- the health check should not be pulling messages from a real subscription.
Another option is to make "UP" error codes configurable -- this way, the common use (404 means up, 403 means down for current configuration) is supported, but a variation without Viewer role is also allowed.

**Comment by Will1229** [comment]
Yes. Pubsub Viewer role is included in my service account. It feels strange that given the same service account my application is able to pull messages with an existing subscription id but not a random one.

Not sure if this is a common issue or just because some special config which I'm not aware of in my GCP environment setup.

**Comment by ashukla-noon** [comment]
I have got same issue. It started on May 20, '20 16:01 IST, Issue is still going on. We didn't make any changes from our application side.

"pubSub":{"status":"DOWN","details":{"error":"com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action."}}}}

Please help

**Comment by amitshukla90** [comment]
I have got same issue. It started on May 20, '20 16:01 IST, Issue is still going on. We didn't make any changes from our application side.

"pubSub":{"status":"DOWN","details":{"error":"com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action."}}}}

Please help

**Comment by elefeint** [comment]
1.2.3 release is going out on Monday; we'll get a workaround or extra flexibility in by then.

**Comment by elefeint** [comment]
The actual permission required to make this work as before is `pubsub.subscriptions.list`. It is included in Pub/Sub Viewer role.

I'll set up ability to customize "successful" statuses through properties in Spring Cloud GCP, so that if it's not feasible to add the extra permission to the account, applications can mark 403 as indicating Pub/Sub being up.

**Comment by elefeint** [comment]
`PubSubHealthIndicator` will now accept both 404 and 403 as valid actuator `UP` status codes. This change will go into version 1.2.3, which is getting released Monday. 

In the meantime, you can disable the pubsub healthcheck manually by seting `management.health.pubsub.enabled=true` in the application properties. For more custom logic, your application can provide it's own bean extending `org.springframework.boot.actuate.health.AbstractHealthIndicator`.

If you are interested in further customizing this logic within Spring Cloud GCP, vote and comment on #2386.
