### ISSUE TITLE
Allow users to specify PubSub's subscriber callback

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#24]
Right now we set the callback for the user, `PubSubInboundChannelAdapter.receiveMessage()`.

We should add in a functional interface in the constructor to allow users to specify a callback.

There were also talks of specifying a MessageListenerContainer (?), but I haven't looked into this.

**Comment by artembilan** [comment]
That's not correct.
The `PubSubInboundChannelAdapter` is an start of the integration flow, which is based on the message channel communication. So, letting end-user to inject his own callback eliminates the `PubSubInboundChannelAdapter` purpose.

The current solution is absolutely right where we receive a PubSub message, convert it into the SI Message and send to the configured channel. That is how SI works.

What you suggest makes sense outside of the SI. That is what we call `MessageListenerContainer`. The good sample of that is Spring Kafka: https://github.com/spring-projects/spring-kafka/tree/master/spring-kafka/src/main/java/org/springframework/kafka/listener
and the Inbound Channel Adapter for it: https://github.com/spring-projects/spring-integration-kafka/blob/master/src/main/java/org/springframework/integration/kafka/inbound/KafkaMessageDrivenChannelAdapter.java

I find this PubSub `Subscriber` as pretty straightforward API that we even don't need that `MessageListenerContainer` (at least for now).
The good sample for similar approach is `MqttPahoMessageDrivenChannelAdapter`: https://github.com/spring-projects/spring-integration/blob/master/spring-integration-mqtt/src/main/java/org/springframework/integration/mqtt/inbound/MqttPahoMessageDrivenChannelAdapter.java. Where we don't have any containers and just subscribe to the topics (`this.client.subscribe(topics, grantedQos);`) and register ourselves as callback - `this.client.setCallback(this);`.

**Comment by joaoandremartins** [comment]
That's great! Yes, that makes sense.

I filed this issue after a conversation with @viniciusccarvalho yesterday, but I might have failed to understand what was actually being talked.
We spoke about this in the scope of the auto/manual PubsubMessage ack/nack. However, it seems like this isn't a good way of getting there.
