### ISSUE TITLE
Refdoc has CSS issues where some code is invisible

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#2412]
See: https://cloud.spring.io/spring-cloud-gcp/reference/html/

![image](https://user-images.githubusercontent.com/17732492/83711863-5f6eff80-a5f2-11ea-8fc2-239911dfc180.png)

Credits for reporting: @Alos.

**Comment by dzou** [comment]
Looks like this is a problem with how spring manages all documents across their site - you can see the same problem for other projects:

https://cloud.spring.io/spring-cloud-gateway/2.2.x/reference/html/#tls-and-ssl
https://cloud.spring.io/spring-cloud-netflix/2.2.x/reference/html/#using-eureka-on-aws
https://cloud.spring.io/spring-cloud-security/2.2.x/reference/html/#_oauth2_single_sign_on

**Comment by dzou** [comment]
I think this is fixed now (at least for us): 

![image](https://user-images.githubusercontent.com/3209274/85041092-787dc180-b157-11ea-960c-c3bdcf7daee0.png)

**Comment by dzou** [comment]
Gonna close since this appears to be fixed for us: https://cloud.spring.io/spring-cloud-gcp/reference/html/#stackdriver-logging
