### ISSUE TITLE
Implement subcollection support in Firestore

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#2415]
User request: https://stackoverflow.com/questions/62043573/how-to-fetch-documents-from-subcollection-in-firestore-using-spring-data/

Currently we support embedded collections, but Firestore has one more type of associated collections, called [subcollections](https://firebase.google.com/docs/firestore/data-model#subcollections).  That feature allows loading the collection independently from the parent document.

**Comment by theHilikus** [comment]
Is the only way today to use firestore subcollections to use `FirestoreTemplate` or is it possible to create a Repository extending `FirestoreReactiveRepository` that supports subcollection documents?
Looking at the sample code and the PR, it seems the answer is the former, but i want to confirm if i'm missing something

**Comment by dmitry-s** [comment]
@theHilikus you are right, currently we only support `FirestoreTemplate` way. Please create a ticket if you are interested in an alternative way of accessing subcollections, so we can discuss it. 

And also, contributions are welcome!

Thanks

**Comment by meltsufin** [comment]
Partially fixed in #2415. Please re-open if needed.
