### ISSUE TITLE
Spring Cloud GCP's BOM (via Hoxton.SR5) using Guava (Android version) by default

### ISSUE THREAD

**Issue by donbeave** [spring-cloud/spring-cloud-gcp#2419]
**Describe the bug**
The problem with dependency management. After creating a new project by using Spring Initializr (https://start.spring.io) and adding Spring Cloud to it (in my case Hoxton.SR5), after adding `implementation("com.google.guava:guava")` to the dependency block Gradle will resolve `29.0-android` version instead of `29.0-jre`, which is expected. The problem came after I have added `mavenBom("org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR5")` to the `dependencyManagement` `imports` block, which means this dependency resolved by BOM settings in `spring-cloud-dependencies` project.

**Sample**
To reproduce it, just create a new empty project with the following `build.gradle` file:

```groovy
plugins {
    id 'org.springframework.boot' version '2.3.0.RELEASE'
    id 'io.spring.dependency-management' version '1.0.9.RELEASE'
    id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
    mavenCentral()
}

ext {
    set('springCloudVersion', "Hoxton.SR5")
}

dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter'
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
    implementation("com.google.guava:guava")
}

dependencyManagement {
    imports {
        mavenBom(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES)
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}")
    }
}

test {
    useJUnitPlatform()
}
```

After that execute `./gradlew dependencies` in the terminal, the dependency report will print the issue:

<img width="929" alt="image" src="https://user-images.githubusercontent.com/139017/84027958-6c10a080-a9c2-11ea-8d14-1124394bec9b.png">

**Comment by suztomo** [comment]
The reason GCP Libraries BOM uses "-android" is to support Java 7. (Google cloud Java libraries support Java 7)

To override the guava flavor, here is the documentation:
https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM#guava-versions--jre-or--android

This can be done at @donbeave 's project. If spring-cloud-gcp is ok to dismiss Java 7, then it makes sense to override it at spring-cloud-gcp.

**Comment by elefeint** [comment]
Spring requires Java8+; IMHO it makes sense to override at `spring-cloud-gcp`.
@meltsufin What do you think?

**Comment by meltsufin** [comment]
+1 Spring Cloud GCP should not worry about Java 7, since Spring itself is on Java 8+.
Let's update our BOM.

**Comment by suztomo** [comment]
@elefeint Thank you
