### ISSUE TITLE
google cloud storage ignore spring.cloud.gcp.credentials.location and use the machine credentials

### ISSUE THREAD

**Issue by esoni** [spring-cloud/spring-cloud-gcp#2422]
**Describe the bug**
Hi,
i m working in my locale machine that have OS windows. On my local machine i m logged with my user: dario.frongillo@gmail.com; I run my Spring App with property
spring.cloud.gcp.credentials.location=file:D:\\keys\\key.json
spring.cloud.gcp.storage.credentials.location=file:D:\\keys\\key.json

In order to run my application using a service account created with a key contained in the path above. However my spring app not use the service account to save and download the object of my cloud storage.
The expected behavior is to use to  interact with google cloud storage using the account service configured with the key provided in spring.cloud.gcp.credentials.location

**Comment by meltsufin** [comment]
@esoni The code you shared demonstrates that you're not relying on our Storage autoconfiguration, which these properties are part of.
You should not create your own instance of `Storage` by calling `StorageOptions.getDefaultInstance().getService()`, but rather use the one that is auto-configured for you.
First make sure that you have the starter in your `pom.xml`.
```xml
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-storage</artifactId>
		</dependency>
```
Then simply autowire the `Storage` object that is configured with the credentials you specify in your `application.properties`

```java
@Autowired
Storage storage;
```

**Comment by esoni** [comment]
I confirm as reported by @meltsufin .
Thanks for the support you can close the ticket.
thanks
