### ISSUE TITLE
The Spring Initializr in spring.start.io tells you that Spring Cloud GCP does not work with Spring Boot 2.3.0

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-gcp#2423]
**Describe the bug**

1. Visit https://start.spring.io/
2. Create a project with Java 11
3. Spring Boot 2.3.0
4. JAR
5. Click on the button to add dependencies and then search for GCP.

The user gets a message saying that GCP does not work with this version:

`Requires Spring Boot >= 2.0.0.RELEASE and < 2.3.0.M1.`

**Comment by dzou** [comment]
@Alos - Thanks for reporting, I filed https://github.com/spring-io/start.spring.io/pull/472 which I think should address this issue.

**Comment by meltsufin** [comment]
Fixed by https://github.com/spring-io/start.spring.io/pull/472.
