### ISSUE TITLE
Could not autowire. No beans of 'SpannerTemplate' type found.

### ISSUE THREAD

**Issue by borzhao-sh** [spring-cloud/spring-cloud-gcp#2431]
**Describe the bug**
IDEA says `Could not autowire. No beans of 'SpannerTemplate' type found. ` when I'm injecting `SpannerTemplate`.

Also there is no `@Component` or equivalent annotation on the class declaration statement, so IDEA thinks that `SpannerTemplate` is not a bean managed by Spring, I guess that's the reason why the `No beans of 'SpannerTemplate' type found` message shows up. 

Spring Cloud GCP version: 1.1.3.RELEASE

**Sample**
Write following code in Intellij IDEA.

```java
@Autowired SpannerTemplate spannerTemplate;
```

And then an inspection error says `Could not autowire. No beans of 'SpannerTemplate' type found. ` shows up.

**Comment by meltsufin** [comment]
Do you have this dependency in your `pom.xml`?

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-data-spanner</artifactId>
</dependency>
```

Also, the version of Spring Cloud GCP you're using is very old. Can you upgrade to 1.2.3?

**Comment by borzhao-sh** [comment]
Yes, we have that dependency. 
I tried to update Spring Cloud GCP to 1.2.3.RELEASE, but the warning still exists. 

Actually this warning doesn't affect our program. The `SpannerTemplate` can be successfully injected during runtime and everything works fine. It's just a little bit annoying and I think maybe we can make some improvement.

**Comment by meltsufin** [comment]
So is this a warning that you only see in the IDE when it does some static analysis, not when you run the app?
Can you share a screenshot?

**Comment by borzhao-sh** [comment]
Yes, it's just a warning from static analysis. 

![Screen Shot 2020-06-17 at 1.43.22 PM.png](https://i.loli.net/2020/06/17/VSYqn6oRL4wAdTO.png)

**Comment by meltsufin** [comment]
This seems more like an issue with IntelliJ IDEA than this project itself.
See some potential workarounds [here](https://stackoverflow.com/questions/21323309/intellij-idea-shows-errors-when-using-springs-autowired-annotation).

**Comment by borzhao-sh** [comment]
The root cause I think is that the `SpannerTemplate` doesn't have the `@Component` annotation, which makes IDEA think the `SpannerTemplate` is not a Spring managed bean. 
When IDEA performing the static analysis, it can't find any Spring managed bean with type `SpannerTemplate`, so IDEA warns us about that. 

Anyway, it's not a big issue but annoying. And I just wanting you to know this.
