### ISSUE TITLE
Use DatastoreOperations instead of DatastoreTemplate 

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-gcp#2436]
I was trying to proxy the DataStoreOperations by using kotlin delegate "by" method. But I found out that in several places on the DataStoreRepositoryFactory and associated classes they use a DatastoreTemplate and not the interface DatastoreOperations.

I started a refactor to push a PR, but noticed there are several methods that only exist on `DatastoreTemplate` it wasn't clear why those methods are not also present on the interface as many of them use the same types as the ones present on DataStoreOperations.

Is there a reason why all the classes are using an implementation instead of the interface contract?

Any chances this could be changed to use DataStoreOperations?

**Comment by viniciusccarvalho** [comment]
I actually finished a PR, all tests are green but checkstyle is failing without writing anything to checkstyle-result.xml, that makes a bit painful trying to figure out why is it complaining about

**Comment by meltsufin** [comment]
@viniciusccarvalho Can you elaborate on the problem that this is trying to solve in Kotlin?

**Comment by viniciusccarvalho** [comment]
Sure @meltsufin. Well its usually a good practice to have the dependencies be interfaces rather than implementations anyways. In this case all the beans that depends on DatastoreOperations are actually dependent on the implementation. This reduces the possibility of someone providing a different implementation.

That was my case, I was using kotlin delegation just because I find it to be much simpler, but anyone who tries to implement DataStoreOperations (maybe via a Proxy for example) would find out that the Beans that generate the repositories implementations would all fail.

I had to give up on the datastore repository approach and use my own DatastoreTemplate instead for my demo, but it would be nice to enable this kind of extension possibility.

Low priority, not a deal breaker, but seems as a good practice anyway that would not hurt to have in place.

Let me know if you want more info on this.

**Comment by dmitry-s** [comment]
@viniciusccarvalho makes sense. Thanks for your contribution!
