### ISSUE TITLE
Unable to specify default value with Secret Manager 

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#2444]
**Describe the bug**
In Spring, when using a property, like `${greeting}`, you can also specify a default value in case the property is not configured, `${greeting:Hi}`.

However, this no longer works with Secret Manager properties, such as: `${sm://greeting}`, it cannot have a default value of `${sm://greeting:Hi}`.

**Comment by dzou** [comment]
Hmm I looked into this a bit; we kind of co-opted the meaning of the `:` by incorporating it into the protocol syntax (`sm://`). So it just means that we won't be able to rely on Spring's default handling of the `:` to handle default values. We could probably implement our own code to handle default values by parsing the expression but it's gonna be a little more work.

Curious from your perspective - is reliance on the default value a common use-case for customers and what situations might they need the feature?

**Comment by dzou** [comment]
@meltsufin - I can implement something where we use a  `|` character as a default value separator.

So basically if a user provides `${sm://xxxx|default-value}` and `xxxx` is not a valid secret we can return `default-value`? What do you think?

This would be some custom logic that lives in the secret manager property source. Currently the problem is we can't rely on the Spring Framework to do this work for us because Spring sees the first `:` in `sm://` and thinks that is the default value separator, so it will just return everything after the first `:` as the default value if we return `null`.

**Comment by meltsufin** [comment]
Does Spring allow customization of the default value separator? If not, then like you said, we have no choice but to roll our own. Let's vet this with the Secret Manager team though.

**Comment by dzou** [comment]
@sethvargo - Hey Seth, it's been a while! We have a question about this new feature we're considering adding for our SecretManager integration for Spring.

We're considering adding this `|` syntax operator so if a user specifies `${sm://xxxx|default-value}` in their configuration file and `xxxx` is not a valid secret, it will return the string `default-value` instead.

Is this inline with the best practices for what the Secret Manager recommends? I would guess that the primary use-case of this would be in development scenarios when the user has not yet put all their secrets in secret manager, so they can rely on a fallback value. Though I could also see this being an anti-pattern as well if this encourages the user to store some password as plaintext in their file as a 'fallback' value. Curious about your thoughts.

**Comment by sethvargo** [comment]
While I'm not sure familiar with all the use cases for Springboot (and I like @saturnism to tell us more about his use case), it does seem odd that you'd want to specify a default value for a secret.

I think people would expect an error if they ask for a secret and it doesn't exist.

**Comment by sethvargo** [comment]
Also, I think we can maintain the spring pattern of using a `:`, we just have to be a bit more clever in counting the number of `:` 😄

**Comment by saturnism** [comment]
i don't think we should use `|`. The `:` is spring idiomatic way for all default values. If ppl want to have a default value, that would be the way to specify it. we may need to look for the additional ':' it in our layer. since it's also possible to specify something like `${someconfig:default has : as well}`

**Comment by dzou** [comment]
Ok sounds good, we can go with the second `:` approach.

@saturnism - Just curious what would you say is the primary use-case of the default value; is it to store a static default value during development? Or did you set something more complex as a default value?

Reading through the Spring code, I see they do some recursive parsing of the stuff after the colon (i.e. if the default value is also a SPEL expression that needs to be parsed), but maybe we don't need to do that depending on the use-case.

**Comment by dzou** [comment]
Tracking this here: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/213
