### ISSUE TITLE
spring-cloud-gcp-data-spanner Avoid from aborting due to idle transaction specification of Spanner

### ISSUE THREAD

**Issue by katynnek** [spring-cloud/spring-cloud-gcp#2453]
## BackGround
There is a specification of Spanner which is the so-called "Idle Transaction".
It says; after 10 seconds from when a transaction becomes idle, the transaction will be aborted in any case.
https://cloud.google.com/spanner/docs/reference/rest/v1/TransactionOptions#idle-transactions

Like when debugging or calling external API in one transaction, it tends to occur and it's a typical problem.
I need the feature to avoid this specification.

## Possible Solution
Spanner document says if this behavior is undesirable, we can periodically execute a simple query like `select 1` to sustain the transaction.
And I think this is the most feasible way to do it.

Ideally, when I annotate a method with `@Transactional`, the query like above is executed in the background or another thread so that we don't have to concern about it.

It's also no problem when it comes that we have to code some configuration.

I would really appreciate it if you take it consideration.
It already supported I also want to know about it.
Thanks

**Comment by elefeint** [comment]
@kennyTakimura The property you are looking for is `spring.cloud.gcp.spanner.keepAliveIntervalMinutes`. This property will be passed to the Cloud Spanner client library, which will keep the session active for you.

Idle sessions are cleaned up after an hour, so any value under 60 should work to keep sessions from being closed.

**Comment by dmitry-s** [comment]
@elefeint the documentation that @kennyTakimura  is referring to says:

> Idle Transactions
> A transaction is considered idle if it has no outstanding reads or SQL queries and has not started a read or SQL query within the last 10 seconds. Idle transactions can be aborted by Cloud Spanner so that they don't hold on to locks indefinitely. In that case, the commit will fail with error ABORTED.
> 
> If this behavior is undesirable, periodically executing a simple SQL query in the transaction (e.g., SELECT 1) prevents the transaction from becoming idle.

@kennyTakimura could you clarify what is the use case for such long transactions with no interaction with the database within 10 seconds? It seems very unusual.


Thanks

**Comment by meltsufin** [comment]
If we wanted to support this, the best place for it would probably be in the [Spanner client lib](https://github.com/googleapis/java-spanner).
cc/ @olavloite

**Comment by kennyTakimura** [comment]
@dmitry-s Yes, it doesn't happen frequently.

- A typical and critical use case which is what I faced is like below.
In a transaction, our system calls an API provided an external organization responsible for the user billing process and it must be proceeded in serial and synchronously.
Because of the high latency, I received the response after more than 10 seconds

- Productivity-related case but it will be very helpful if this is supported
When debugging the system, the query is frequently aborted because it takes some time for the investigations.

**Comment by olavloite** [comment]
@meltsufin I took a quick look in the code of `spring-cloud-gcp-data-spanner` and if I'm not mistaken, you are using both the `TransactionManager` [here](https://github.com/spring-cloud/spring-cloud-gcp/blob/f45d4be12d2848a775b5b28f8e763b725959aed7/spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/SpannerTransactionManager.java#L166) and `TransactionRunner` [here](https://github.com/spring-cloud/spring-cloud-gcp/blob/f45d4be12d2848a775b5b28f8e763b725959aed7/spring-cloud-gcp-data-spanner/src/main/java/org/springframework/cloud/gcp/data/spanner/core/SpannerTemplate.java#L399) to create and manage transactions. Is that correct? And am I also correct to assume that you are currently not using the Connection API in the client library?

The reason I'm asking is to check where this should preferably be added.

I do have a concern regarding this, though, as it could possibly cause one transaction to silently hold on to locks on the backend for an unreasonable amount of time. This again will cause other transactions to abort. So it should be a background process that does stop after a certain amount of time, and this timeout should also be configurable to allow users to set a different timeout in `DEBUG` mode than in `PROD` mode. That would mean adding a configuration option like this:
* `SpannerOptions.transactionKeepAliveSeconds`:
  * Default is 0, which means it is disabled and the backend will abort the transaction after 10 seconds.
  * Anything above 10 seconds would mean that the client library will send a ping for an active transaction every ~8 seconds to keep it alive. When the timeout has been reached, the client library will stop sending pings and let the transaction be aborted by the backend to prevent it accidentally keeping locks for too long.
  * Values between 1 and 10 (inclusive) do not make any sense and should be rejected.

@skuruppu Any thoughts on this?

**Comment by elefeint** [comment]
@olavloite 0 vs 10+ almost sounds boolean. If we don't want users to set their own timeout between 1 and 10 seconds, perhaps just provide a flag that's off by default?

**Comment by olavloite** [comment]
> @olavloite 0 vs 10+ almost sounds boolean. If we don't want users to set their own timeout between 1 and 10 seconds, perhaps just provide a flag that's off by default?

That was my initial thought as well, but I think we would want to let a user to set different values for the two different cases that @kennyTakimura mentioned above:
1. For production use: Some transactions may need to stay active for more than 10 seconds while waiting for some external service. This should however in normal use not exceed something like 60 seconds.
1. For debug purposes: When setting a breakpoint and stepping through transaction code, you want to be able to set a longer timeout to prevent your transaction from timing out while you are inspecting variable values etc.

We could use two different flags or options to achieve the above, but I'm not sure that would provide a better user experience than just allowing the user to determine the timeout value themselves.

**Comment by elefeint** [comment]
Makes sense! I mis-read the property intent as being for "ping interval" vs "total transaction timeout allowed".

**Comment by meltsufin** [comment]
@olavloite You're right that we don't use the Connection API yet and we use both `TransactionRunner` and `TransactionManager`.
I think your suggestion with the background ping process that is configurable makes sense. Nonetheless, I think this should primarily be a product decision first. For example, would this be supported across all languages? Does it make sense to implement on the back-end instead?

**Comment by skuruppu** [comment]
This is always an interesting one and it has come up a few times before. I think the general consensus from the Spanner team is that we don't want to automatically refresh transactions behind the scenes in the client library because we don't want users to unintentionally hold onto transactions that they're not using. If users need this behavior, it's better for them to add some logic in their own applications since then they would understand the reasons why they're doing this.

However, we do understand that this behavior might be necessary for ORM and driver implementations where the end user might not have enough control to implement this logic. So I would be open to us providing this support at the connection API level or at the JDBC driver level.

For reference, the [same issue](https://github.com/googleapis/python-spanner/issues/12) came up during the Django implementation as well so we asked them to add this functionality at the dbapi or Django layer.

**Comment by olavloite** [comment]
I've added a feature request to the Spanner client library specifically for the Connection API.

**Comment by elefeint** [comment]
The Spanner team consensus was that building auto-extending transactions would cause problems more frequently than it would solve them. Spring Cloud GCP's goal is to integrate the existing GCP client libraries with the Spring ecosystem, but not to change their behavior. As such, we won't consider adding this feature.
