### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#2458]
- [ ] create `main` branch
- [ ] protect `main` branch the same as `master` currently
- [ ] update CI/CD scripts and config to refer to the new branch
- [ ] update links in documentation that reference `tree/master`
- [ ] [Switch GitHub default branch](https://docs.github.com/en/github/administering-a-repository/setting-the-default-branch)
- [ ] delete `master`

Anything else we would need to do?

**Comment by elefeint** [comment]
[Switch default branch](https://docs.github.com/en/github/administering-a-repository/setting-the-default-branch)?

And update `CONTRIBUTING.adoc`.

**Comment by dzou** [comment]
Some of the links in the docs reference master branch in the docs; like https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-core

I.e. so we should do a find/replace on the string `tree/master` to `tree/main`

**Comment by meltsufin** [comment]
Whether to rename to `main` or `trunk` or something else is still an open question.
If there is a consensus in the community, please let us know.

**Comment by kioie** [comment]
+1 on `main`
