### ISSUE TITLE
[RFC] Closing pull requests while a new build is starting causes failures

### ISSUE THREAD

**Issue by maldoinc** [spring-cloud/spring-cloud-gcp#2465]
Build failures often indicate a fault with the software being built such as compilation or test failures. However, there is a subset of build failures (called *environmental* or *non-verification failures*) that are not expected within a standard application development lifecycle, such as build configuration failures, dependency resolution failures, infrastructure failures, and so on.

**Problem:** One type of environmental failure is due to due to git references being no longer available at the time a build job starts. For example, pull requests are merged shortly before the start of the scheduled build, causing a build failure due to an unfound (because merged) branch. In your project, we detected 3 failures of this type over the May-June timespan. For instance, we found that [Build #6159](https://travis-ci.org/spring-cloud/spring-cloud-gcp/builds/699377884) did not pass due to the above issue.

**Solution:** It is generally recommended to wait for the build results before merging a pull request. If you wish to skip builds you may also use the [SKIP CI](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build) tag in your commit message. Additionally, it is also possible to skip builds containing non-code changes as shown in [this example](https://github.com/google/EarlGrey/pull/383/files/3b38a5dea36a88aba42a42931e77a7c5429a1837) and below:

```diff

+ before_install:
+  - |
+      if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|(.png)|(.pdf)|(.html)|^(LICENSE)|^(docs)'
+      then
+        echo "Only doc files were updated, not running the CI."
+        exit
+      fi

```
---
*Disclaimer:* I developed a tool that repairs environmental build failures and I am now evaluating its usefulness for open-source projects.

*Please up/downvote the issue to indicate whether you agree/disagree with the report and the proposed fix.*

**Comment by meltsufin** [comment]
I don't think this is really a problem we're concerned about, but I'm happy to hear other opinions.

**Comment by dzou** [comment]
Cool to know this. It sounds like the solution here is just for us to be more mindful with not merging unless we see that the build passes on the PR?

**Comment by maldoinc** [comment]
Doesn't skipping the results defeat the purpose of having a CI process in the first place, especially for cases when the committer is a third-party?

Perhaps for cascading breakages(where a previous commit already broke the build) skipping a few builds until its fixed might be ok; in the context of a PR, there is no downside to waiting for the results to verify at least the portion being changed works even if the build might still be failing. This comes with the usual upsides in that the change is verified to be up to the project standards (tests, code style, etc).

I just find it a bit curious to not wait and why you think it's not waiting for the results. Also, just FYI as you can tell from the disclaimer this was done automatically and this sort of issue was one of the most popular types encountered so it's by no means specific to this project. Again, not trying to sound antagonizing here, just interested in your opinions as maintainers of a popular and active project.

PS: GitHub also has an option [documented here](https://docs.github.com/en/enterprise/2.16/admin/developer-workflow/configuring-protected-branches-and-required-status-checks#types-of-required-status-checks) which should disallow merging before the checks have finished.

**Comment by dzou** [comment]
@maldoinc - Thanks for letting us know about this. We'll discuss with our team to be more mindful to wait for builds before merging where possible.

We have debated setting the option to disallow merging before checks, but sometimes checks are flaky or things are broken upstream; in many cases we would rather have the flexibility to merge even when a build is broken.
