### ISSUE TITLE
Add Refreshing Secrets to the Secret Manager Sample

### ISSUE THREAD

**Issue by dzou** [spring-cloud/spring-cloud-gcp#2474]
Add code demonstrating how to refresh the latest secret in the secret manager sample.

**Comment by kioie** [comment]
Hey @dzou , what do you mean by refresh the latest secret?

**Comment by dzou** [comment]
Hey @kioie ! It means when a secret is updated in Google Secret Manager, a user's application will be able to pick up the updated secret without needing to restart their application.

Currently our sample still requires to be restarted if the secret values get updated upstream.

I have been told that this is possible with spring actuator? Will need to investigate more...

**Comment by dzou** [comment]
See https://github.com/spring-cloud/spring-cloud-gcp/issues/2485

Looks like the solution requires implementing the `spring.config.import` style for secret manager. This is tracked in the new repo. https://github.com/googlecloudplatform/spring-cloud-gcp
