### ISSUE TITLE
Consider differentiating TransportChannelProvider beans by purpose

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2478]
I was surprised to see that we provide a global `TransportChannelProvider` bean. This could easily interfere with other, non-Spring-Cloud-GCP services.

https://github.com/spring-cloud/spring-cloud-gcp/blob/2adf4328c819a634a3ad7a1627426badf198c4fb/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java#L387

Consider specifying the name as being at least pubsub-specific, and perhaps even overridable for individual use (Admin API likely does not need the same custom defaults as Subscriber).

**Comment by meltsufin** [comment]
You're right that we should add a qualifier for the bean. However, this is only a problem when someone else is using `@ConditionalOnMissingBean`, which is not common in normal application config, and currently, we do not use this bean anywhere other than Pub/Sub autoconfig.

**Comment by elefeint** [comment]
We can close this for now, since the end user can always override the larger subscriber/publisher factory bean.
