### ISSUE TITLE
CompositeHealthContributor instead of simple HealthIndicator

### ISSUE THREAD

**Issue by olivierboudet** [spring-cloud/spring-cloud-gcp#2491]
**Is your feature request related to a problem? Please describe.**
I am using spring-cloud-gcp 1.2.3 with spring boot 2.2.3.
My application instanciate two PubsubTemplate beans because I need to communicate with two PubSub from two Google Cloud projects.
If I enable the PubSub Health Indicator, my application can not start because of this error :
```

Parameter 0 of method pubSubHealthIndicator in org.springframework.cloud.gcp.autoconfigure.pubsub.health.PubSubHealthIndicatorAutoConfiguration required a single bean, but 2 were found:
	- project1PubSubTemplate: defined by method 'getProject1PubSubTemplate' in class path resource [io/myapp/configuration/PubSubConfiguration.class]
	- project2PubSubTemplate: defined by method 'getProject1PubSubTemplate' in class path resource [io/myapp/configuration/PubSubConfiguration.class]

```

**Describe the solution you'd like**
To avoid this, I set `management.health.pubsub.enabled=false` and created a custom CompositeHealthContributor.
```
public class PubSubHealthIndicatorAutoConfiguration extends CompositeHealthContributorConfiguration<PubSubHealthIndicator, PubSubTemplate> {

    @Bean
    @ConditionalOnMissingBean
    public HealthContributor pubSubHealthContributor(Map<String, PubSubTemplate> pubSubTemplates) {
        return createContributor(pubSubTemplates);
    }
}
```

Would this change may take place directly in Spring Cloud GCP instead of having to disable standard health indicator ?

**Comment by elefeint** [comment]
@olivierboudet And thank you extra for bringing the solution, too!

In case it's useful in the future -- when overriding autoconfiguration, it's enough to supply a custom user bean. Because all our autoconfiguration is annotated with `@ConditionalOnMissingBean`, it will back off if it sees a (non-autoconfigured) user bean of the same type. Then you might not need to disable the property.
