### ISSUE TITLE
GoogleStorageResource - add ability to set content-type and other GCS attributes

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#250]
GCS objects can have different attributes such as content-type, allow this to be set if user casts the resource to GoogleStorageResource.

**Comment by ChengyuanZhao** [comment]
How about we just let them get the Blob (the GCS object) if the type of the resource is a GoogleStorageResourceObject and then the user is free to set attributes on their own? I don't see much value in depending on those attribute-setting APIs  and just wrapping them.
