### ISSUE TITLE
GoogleStorageResource - Signed URL

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#251]
Produce signed URL for GoogleStorageResource. This is useful when sending the GCS object to end user w/o having to proxy the request in the server.  Can send signed URL to user easily.

**Comment by ChengyuanZhao** [comment]
Do you know if there is any functionality in the cloud storage client lib already for making the signed URLs? 

All I could find on our dev site is this page of instructions on how to assemble such a URL yourself ( https://cloud.google.com/storage/docs/access-control/create-signed-urls-program ).

**Comment by joaoandremartins** [comment]
If nothing in the API produces GS URIs, we should manually build them.

**Comment by ChengyuanZhao** [comment]
Should we suggest that functionality be put into the client lib? Sounds like functionality that's useful much more broadly than just in Spring.

**Comment by joaoandremartins** [comment]
Up to you if you want to open a feature request with the google-cloud-java team for this.
However, we probably shouldn't wait for them to deliver on it. Maybe add a TODO in the code to revisit this after your FR is executed?

**Comment by ChengyuanZhao** [comment]
They implemented this feature in the Storage type, actually (that takes in the bucket and object name), but I suppose we could write a little function in the resource that calls that function but just provides the bucket and object name already. I'll make a PR.

**Comment by joaoandremartins** [comment]
If they have it, that's great!
