### ISSUE TITLE
Add support to autoconfigure Cloud SQL ipTypes

### ISSUE THREAD

**Issue by ohardeng** [spring-cloud/spring-cloud-gcp#2513]
**Problem: Missing configuration option**
Currently `spring-cloud-gcp-autoconfigure` doesn't support configuring of [ipTypes](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#specifying-ip-types) for [Cloud SQL Socket Factory for JDBC drivers](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory). When the access to a Cloud SQL database is restricted to the `PRIVATE` address the connections will fail since Cloud SQL Socket Factory defaults to the `PUBLIC` address.

**Solution:**
Add missing configuration option.

**Alternatives/workarounds**
* Configure HikariCP
`spring.datasource.hikari.data-source-properties.ipTypes=PRIVATE`
Pro: Works as long as you use the ConnectionPool.
Con: Doesn't work when something else like `org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration` creates a `DataSource` based on the `DataSourceProperties`. In my case that happens since the Flyway migrations are run with another database user than the applications database user, see [FlywayAutoConfiguration#configureDataSource(...)](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration.java#L143).
* For PostgreSQL you can add a `org\postgresql\driverconfig.properties` to your classpath with `ipTypes=PRIVATE`.
Pro: Works for PostgreSQL.
Con: Hiding important configuration a really long way from where people would look for it.

**Proposed code change**
https://github.com/ohardeng/spring-cloud-gcp/tree/autoconfigure-cloud-sql-ip-types is ready to create a pull request from.

**Comment by meltsufin** [comment]
@ohardeng The documentations says that the default is `PUBLIC, PRIVATE`. I would expect it to fall back to `PRIVATE` when public IP is disabled. Is that not happening?
Aside from that, we would welcome the contribution you have prepared in your branch.

cc/ @kurtisvg

**Comment by kurtisvg** [comment]
The SocketFactory should treat `ipTypes` as a list of useable options in order of preference. With `PUBLIC,PRIVATE`, it will prefer a PUBLIC IP if the instance has one, or else use a PRIVATE one if it doesn't. 

If you have an example of this not working as expected, I would appreciate it if you could file a bug with more info over on https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory.

That said, the proposed feature would be useful for folks with instances that have both, but would like to use private IP from resources that have VPC access.

**Comment by ohardeng** [comment]
Our database instance is set up with both `PUBLIC` and `PRIVATE` IPs so the Cloud SQL Socket Factory works as expected and selects the `PUBLIC` address. 

In our setup the public address is intended for connections from our on-prem resources and is configured with `Authorized networks`. From our k8s cluster the access should be done through the private address.

So what currently happens is that my pod starts up. Flyway tries to initilaze it's `DataSource`, gets configured with the public IP, tries to connect and ends up with a `BeanCreationException` with the root cause `java.net.SocketException: Broken pipe` since it tries to connect to the public IP from a non authorized network. Full stacktrace attached.

What are the next steps to get this change request in? From your comments I assume the proposed change is accepted and then based on [Contributing a patch](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/CONTRIBUTING.adoc#contributing-a-patch) the next and final step is the creation and merging of the pull request. Should I create the PR or will you do both?

[Stacktrace.log](https://github.com/spring-cloud/spring-cloud-gcp/files/5199999/Stacktrace.log)

**Comment by meltsufin** [comment]
Your proposed change definitely makes sense then. You already have a fork with your proposed change. So, you can just open a Pull Request against this repository using your fork, and we'll review it. Thanks!
