### ISSUE TITLE
GraalVM Support

### ISSUE THREAD

**Issue by gabac** [spring-cloud/spring-cloud-gcp#2524]
**Describe the bug**
I was playing around with getting a GraalVM native image up & running on Google Cloud Run.
During startup following error was thrown

```
org.springframework.beans.factory.BeanDefinitionStoreException: @Configuration classes need to be marked as proxyBeanMethods=false. Found: [org.springframework.cloud.gcp.autoconfigure.core.GcpContextAutoConfiguration, org.springframework.cloud.gcp.logging.LoggingWebMvcConfigurer, org.springframework.cloud.gcp.autoconfigure.logging.StackdriverLoggingAutoConfiguration]
```

Checking other Spring Cloud Configuration classes I detected following issue: https://github.com/spring-cloud/spring-cloud-commons/issues/623 and corresponding commit: https://github.com/spring-cloud/spring-cloud-commons/commit/18a4227c4ef1bdf86c3103e64bce75847a53073e#diff-878bfcb22b53612b49e3b34e803d12d2

Would it make sense to move all
```
@ Configuration
```

to 
```
@Configuration(proxyBeanMethods = false)
```

If so, I'm happy to do this.

**Sample**
Google Cloud Run hello-world java sample with graalvm adaptions described here. I can create a sample repo if needed

https://repo.spring.io/milestone/org/springframework/experimental/spring-graalvm-native-docs/0.8.0/spring-graalvm-native-docs-0.8.0.zip!/reference/index.html#getting-started-buildpacks

**Comment by dzou** [comment]
Sounds reasonable, I saw @elefeint made an issue a while back for this too: https://github.com/spring-cloud/spring-cloud-gcp/issues/2500

Not too familiar with what `proxyBeanMethods` mean though; wonder if we used any of these in our integrations. Let's hear from others on the team their thoughts.

**Comment by elefeint** [comment]
It should be safe to just copy/paste the parameter in all our autoconfig. `proxyBeanMethods=true` is only needed when bean methods call each other directly.
