### ISSUE TITLE
DatastoreTemplate DatastoreResultsIterable Cursor should be null when there is no next page

### ISSUE THREAD

**Issue by abeag** [spring-cloud/spring-cloud-gcp#2535]
I am trying to implement cursor-based pagination and found that unable to determine whether DatastoreResultsIterable has the next page. Due to the DatastoreResultsIterable Cursor has NotNull value even there is no next page.

Given:
Datastore has some data in KIND
pageLimit > rowsCount for KIND

```
EntityQuery.Builder queryBuilder = Query.newEntityQueryBuilder()
				.setKind(KIND)
				.setOrderBy(StructuredQuery.OrderBy.desc(KEY))
				.setLimit(pageLimit);
```
```
if (urlSafeCursor != null) {
    queryBuilder.setStartCursor(Cursor.fromUrlSafe(urlSafeCursor));
}
```

When:
`DatastoreResultsIterable<DO> resultList = datastoreTemplate.query(queryBuilder.build(), DO.class);`

Expected:
resultList.getCursor() == null

Actual:
resultList.getCursor() != null

**Comment by dmitry-s** [comment]
In general we avoid returning `null` because it's error-prone. Instead, you can use `Iterable.iterator().hasNext()` to determine if any entities were retrieved.

Please reopen if you have further questions.

**Comment by abeag** [comment]
Iterable.iterator().hasNext() is used for iterate over items in DatastoreResultsIterable (current page)
and will be true for resultList when the current page has items.
The cursor does not correspond to the iterator and points to the first item on the next page. 

Maybe make sense to add hasNextPage flag?

```
public class DatastoreResultsIterable<T> implements Iterable<T> {
	private final Iterator<T> iterator;
	private final Cursor cursor;
	private Iterable<T> iterable;
	...
}	
```

**Comment by meltsufin** [comment]
cc/ @dmitry-s

**Comment by dmitry-s** [comment]
@abeag I see what you mean. In that case, I think you should try using `DatastoreRepository` and creating a method with return type `Slice`. `Slice` has `hasNext()` and `isLast()` methods that you could use. You can use name based methods, like this:
```
public interface TradeRepository extends DatastoreRepository<Trade, String[]> {

  Slice<TestEntity> findBySymbol(String symbol, Pageable pageable);

}
```

You can pass ordering and page size using `Pageable` parameter. See the [docs](https://docs.spring.io/spring-cloud-gcp/docs/1.2.5.RELEASE/reference/html/#query-methods-by-convention-2) for more details.

Let me know if that works for you or not, or  if you have any questions.

**Comment by abeag** [comment]
@dmitry-s Initially I tried your approach like this
`Slice<TestEntity> findAllByParentIdAndChildIdLessThanOrderByChildIdDesc(String parentId, String childId, Pageable pageable);`
in general, it works but:
- It require additional ChildIdLessThanOrderByChildIdDesc condition
- I have to have OrderBy by the same field as LessThan, so unable to use order by "name" for example
- DatastoreRepository + SpringData does not support some Datastore-specific features like composite Key, hasAncestor, etc.

So I have to use DatastoreTemplate directly with custom CursorPaginationSlice and Cursor. It works fine except the end of the data case.

```
public CursorPaginationSlice<TestEntity> findAll(String parentId, String urlSafeCursor,	int pageLimit) {
	EntityQuery.Builder queryBuilder = Query.newEntityQueryBuilder()
					.setKind(TestEntity.KIND)
					.setFilter(hasAncestor(parentKeyOf(parentId)))
					.setOrderBy(StructuredQuery.OrderBy.desc(__key__))
					.setLimit(pageLimit);

	if (urlSafeCursor != null) {
		queryBuilder.setStartCursor(Cursor.fromUrlSafe(urlSafeCursor));
	}

	DatastoreResultsIterable<TestEntity> resultList = datastoreTemplate .query(queryBuilder.build(), TestEntity.class);
	return toSlice(resultList, pageLimit, resultList.getCursor());
}
```

I agree that returning null is error-prone, let's return some constant value like EOF (end of file), etc.

**Comment by dmitry-s** [comment]
@abeag I see. That makes sense. I think that the best approach is to introduce a separate DatastoreTemplate method that would return `Slice` instead of `DatastoreResultsIterable`.  Would that work for you?

**Comment by abeag** [comment]
Actually I use [CursorPaginationSlice](https://github.com/davidepedone/spring-cursor-pagination/blob/master/spring-cursor-pagination-common/src/main/java/it/davidepedone/scp/pagination/CursorPaginationSlice.java) instead of [Slice<T>](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Slice.html)
I believe I could create CursorPaginationSlice form Slice, so let's try. 
I would be very appreciate.

**Comment by dmitry-s** [comment]
@abeag the PR is in. After a couple of iteration we came to a slightly different design. `FirestoreOprations` now has two new  methods: 
```
	<T> Slice<Key> queryKeysSlice(KeyQuery query, Class<T> entityClass, Pageable pageable);

	<T> Slice<T> queryEntitiesSlice(StructuredQuery query, Class<T> entityClass, Pageable pageable);
```

The query you pass doesn't need to have limit and offset, instead you pass a `Pageable` with page number and page size. The result is a `Slice` that can be used to get a `Pageable` for the next slice. Also you can call `hasNext()` method on it that would return true if there is the next slice.

An example: https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-data-datastore/src/test/java/org/springframework/cloud/gcp/data/datastore/it/DatastoreIntegrationTests.java#L270

**Comment by abeag** [comment]
Thank you. Cool solution.

**Comment by meltsufin** [comment]
You're welcome! Thanks for the update.
