### ISSUE TITLE
Bound the type of PubSubSubscriberOperations#ack parameter

### ISSUE THREAD

**Issue by celcius112** [spring-cloud/spring-cloud-gcp#2538]
At the moment [PubSubSubscriberOperations](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/core/subscriber/PubSubSubscriberOperations.java)'s `#ack`, `#nack` and `#modifyAckDeadline` methods accept a Collection of `AcknowledgeablePubsubMessage`. It would be appreciated to bound this Collection so that, for instance, a List of `ConvertedAcknowledgeablePubsubMessage` could be used as parameter.

This would bring a breaking change as the signature of the public interface `PubSubSubscriberOperations` would be modified.

As a temporary workaround, we can wrap our list in a `Collections.unmodifiableList` in order to downcast the type, for instance
```java
List<ConvertedAcknowledgeablePubsubMessage<T>> messages...
pubSubTemplate.ack(Collections.unmodifiableList(messages));
```
but this is less than optimal.

If necessary, and since the modification is quite trivial, I can provide a PR.

**Comment by meltsufin** [comment]
What if we changed it to `ack(Collection<? extends AcknowledgeablePubsubMessage> messages)`? I think that would work without introducing a breaking change.

**Comment by celcius112** [comment]
That's what I have in mind. However this is a breaking change, albeit a minor one, since the signature of the public interface's methods does change.

**Comment by meltsufin** [comment]
Callers of this method do not need to change their code. So, it's backwards compatible in that sense.
Feel free to propose the change in a PR, we can go from there.
Thanks!

**Comment by celcius112** [comment]
Good enough for me :) Thank you for your time
