### ISSUE TITLE
More Details on Gradle BOM

### ISSUE THREAD

**Issue by jamesward** [spring-cloud/spring-cloud-gcp#2543]
In the [docs for using the BOM](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.0.M1/#_bill_of_materials) it isn't clear how to use the BOM with Gradle.

**Comment by jamesward** [comment]
It looks like what is needed is (for `build.gradle.kts`):
```
dependencyManagement {
	imports {
		mavenBom("org.springframework.cloud:spring-cloud-dependencies:Hoxton.RELEASE")
	}
}
```

**Comment by meltsufin** [comment]
For 1.2.x versions of the project, we're actually part of the Spring Cloud BOM (`spring-cloud-dependencies`), and you don't really need to include our `spring-cloud-gcp-dependencies` BOM, unless you want a different version of the dependencies.
We should probably make this point more clear in the section of the docs.

**Comment by jamesward** [comment]
I tried without the BOM and got:
```
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.springframework.cloud:spring-cloud-gcp-starter-firestore:.
```

**Comment by jamesward** [comment]
For reference my plugins:
```
plugins {
    id("org.springframework.boot") version "2.3.4.RELEASE"
    id("io.spring.dependency-management") version "1.0.10.RELEASE"
    kotlin("jvm") version "1.4.10"
    kotlin("plugin.spring") version "1.4.10"
}
```

**Comment by meltsufin** [comment]
Taken directly from start.spring.io:
```
plugins {
  id 'org.springframework.boot' version '2.3.4.RELEASE'
  id 'io.spring.dependency-management' version '1.0.10.RELEASE'
  id 'java'
}
group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'
repositories {
  mavenCentral()
}
ext {
  set('springCloudVersion', "Hoxton.SR8")
}
dependencies {
  implementation 'org.springframework.cloud:spring-cloud-gcp-starter'
  testImplementation('org.springframework.boot:spring-boot-starter-test') {
    exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
  }
}
dependencyManagement {
  imports {
    mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
  }
}
test {
  useJUnitPlatform()
}
```

**Comment by jamesward** [comment]
Ah, so I need that BOM.  I guess that is what should be in the docs :)  I didn't start with `start.spring.io`

**Comment by meltsufin** [comment]
Yep, keeping the issue open to update the docs. Thanks!

**Comment by meltsufin** [comment]
I think we can close it. Our current reference documentation does show Spring Cloud GCP BOM usage for Gradle.
