### ISSUE TITLE
Docs: Cloud Firestore Example Link Broken

### ISSUE THREAD

**Issue by jamesward** [spring-cloud/spring-cloud-gcp#2544]
https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.0.M1/#_sample_14

Points to: https://github.com/spring-cloud-gcp/spring-cloud-gcp-samples/spring-cloud-gcp-firestore-sample

**Comment by meltsufin** [comment]
This is a really old version of the project, which no one should really be using. How did you land on that version of the refdoc? We're on 1.2.5.RELEASE right now, and the link is correct there.
https://docs.spring.io/spring-cloud-gcp/docs/1.2.5.RELEASE/reference/html/#samples-3

So, I don't know if it's worth fixing.

**Comment by jamesward** [comment]
Ah! That is where google took me and I didn't see that I was on an older version.  Whoops.  I wonder if we could have a message like Play does: https://www.playframework.com/documentation/2.6.x/JavaHome
```
You are viewing the documentation for the 2.6.x release series. The latest stable release series is 2.8.x.
```

**Comment by meltsufin** [comment]
That would be nice indeed.
@artembilan Is this something that the Spring team has thought about?

**Comment by artembilan** [comment]
Well, our docs are generated as independent static resources and we definitely are not going to regenerate every single old version when we release a new one.

That Play Framework sample is not about comparing apples with apples and what I see so far is just embedded docs directly into their original site. We have something like that when you really jump into project page: https://spring.io/projects/spring-cloud-gcp#learn, so you can see what versions are supported and what is the latest stable.

Probably @bclozel has some thought on the matter...

**Comment by bclozel** [comment]
While we could do something on pages hosted on docs.spring.io, cloud.spring.io is a different matter as it's hosted on github pages. Regenerating the docs is clearly a hard problem, but maybe replacing old versions with HTML redirects is doable here https://github.com/spring-cloud/spring-cloud-static/tree/gh-pages ?

**Comment by meltsufin** [comment]
I didn't even realize that @jamesward's link was from coming from `gh-pages` vs. our published docs are on `docs.spring.io`. Which should be the official hosting? Are both used?

**Comment by jamesward** [comment]
Maybe an iframe that reads the parent URL could render a message like Play does.

**Comment by meltsufin** [comment]
I'm closing this because going forward our home is at https://github.com/GoogleCloudPlatform/spring-cloud-gcp and we have a good control of publishing documentation there on `gh-pages`.
