### ISSUE TITLE
Docs: Wrong Gradle Dep Scope

### ISSUE THREAD

**Issue by jamesward** [spring-cloud/spring-cloud-gcp#2545]
The docs Gradle syntax uses the wrong scope and could be simplified.  For example [here](https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.0.M1/#_spring_resources) it has:

```
compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-storage'
```

This should be (for `build.gradle.kts`):
```
implementation("org.springframework.cloud:spring-cloud-gcp-starter-storage")
```

There are ~25 places in the docs that need this fix.

**Comment by dzou** [comment]
@jamesward - So just to clarify, we should replace all of our gradle snippets

from
```
dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-gcp-starter-storage'
}
```

to this:
```
dependencies {
    implementation("org.springframework.cloud:spring-cloud-gcp-starter-storage")
}
```

**Comment by jamesward** [comment]
Yup! That is the `build.gradle.kts` syntax.  What I'm not sure about is if there is a different syntax for `build.gradle` - let me know if you want me to investigate that.

**Comment by meltsufin** [comment]
@jamesward What do you mean by "wrong scope"? Sorry, I'm not very familiar with Gradle.

**Comment by jamesward** [comment]
`compile` is a scope and has been deprecated:
```
'compile(Any): Dependency?' is deprecated. The compile configuration has been deprecated for dependency declaration. Please use the 'implementation' configuration instead.
```
