### ISSUE TITLE
Add Cloud Foundry support

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#255]
Our core starter should grab `GoogleCredentials` from the right spot on a PCF cluster.

**Comment by boparp-pivotal** [comment]
How to add Cloud Foundry support to the Starters? Essentially the Starters need to be able to read Service credentials injected into it's system env variable by the Service Broker:

In Cloud Foundry, when you use a service broker, it publishes certain services in the CF marketplace
You create a service instance of a service which creates credentials for that service.
when you bind this service instance with an app, all the credentials for that service instance get injected into the system env var of the app. 
When you'd do a System.getEnv ("VCAP_SERVICES") you'd get a JSON payload, and it'll contain creds for all the service instances that are bound to that app. 
The GCP Service Broker currently supports 10 services. 

Below is a real example (with redacted values) of an CF app's env variable. The app has 2 service instances bound to it:- 1 service instance called "g-storage" of the service "google-storage" and another SI called "mydataset" of service "google-bigquery" bound to it. 

So when the app's Spring context is initialized these credentials are read, parsed and the appropriate Spring Bean is instantiated, in this example, will be com.google.cloud.storage.Storage and com.google.cloud.bigquery.BigQuery.

The way we wrote our Starters was that if there's 1 service instance of a service type bound to the app, we would just instantiate a default Bean of the correct type, with the corresponding credentials. I think in most cases you'd not have an app with with multiple SI of the same service type, but if they do, then it can get tricky. 

Here's a useful link: https://spring.io/blog/2011/10/13/using-cloud-foundry-services-with-spring-part-1-the-basics

System-Provided:
{
 "VCAP_SERVICES": {
  "google-bigquery": [
   {
    "credentials": {
     "Email": "pcf-binding-1234asdf@my-gcp-project.iam.gserviceaccount.com",
     "Name": "pcf-binding-1234asdf",
     "PrivateKeyData": "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicGRlLW1nb2RkYXJkIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiMmUxMzlhODNhMjBiNzY1N2IyNGVmZGM2NjRiNjJiYjU4OWFlOTU4MiIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L3BjZi1iaW5kaW5nLTgyMTVjN2I4JTQwcGRlLW1nb2RkYXJkLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9Cg==",
     "ProjectId": "my-gcp-project",
     "UniqueId": "105423123456789196414",
     "dataset_id": "pcf_sb_2_1518504199123456789"
    },
    "label": "google-bigquery",
    "name": "mydataset",
    "plan": "default",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "gcp",
     "bigquery"
    ],
    "volume_mounts": []
   }
  ],
  "google-storage": [
   {
    "credentials": {
     "Email": "pcf-binding-1234asdf@my-gcp-project.iam.gserviceaccount.com",
     "Name": "pcf-binding-1234asdf",
     "PrivateKeyData": "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicGRlLW1nb2RkYXJkIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiOTRhYjg0YjVmNzY1NDAxNjU4ZDcxZDUwZWEwNGY1YTIzNTEyZGNkZCIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L3BjZi1iaW5kaW5nLTJiY2JkMjU0JTQwcGRlLW1nb2RkYXJkLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9Cg==",
     "ProjectId": "my-gcp-project",
     "UniqueId": "105423123456789196414",
     "bucket_name": "my-bucket"
    },
    "label": "google-storage",
    "name": "g-storage",
    "plan": "standard",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "gcp",
     "storage"
    ],
    "volume_mounts": []
   }
  ]
 }
}

**Comment by mkjelland** [comment]
Here is a list of services that the [cf service broker](https://github.com/GoogleCloudPlatform/gcp-service-broker) uses:

- google-storage
- google-pubsub
- google-bigquery
- google-cloudsql-mysql
- google-cloudsql-postgres
- google-ml-apis
- google-stackdriver-debugger
- google-stackdriver-trace
- google-datastore
- google-bigtable
- google-spanner

These can also be found in the [manifest](https://github.com/GoogleCloudPlatform/gcp-service-broker/blob/master/manifest.yml) for the service broker application.

**Comment by mkjelland** [comment]
You can find example credential objects in this [usage guide](https://github.com/GoogleCloudPlatform/gcp-service-broker/blob/8a38732e1c813ce8f93a6721f2a547a61bcb4942/docs/use.md)

**Comment by gouthamkunduru90** [comment]
@mkjelland could you please provide the VCAP_SERVICES Json object for google-datastore.

**Comment by meltsufin** [comment]
@gouthamkunduru90 Is there a particular issue you're trying to solve? Perhaps, open a new issue for that. Thanks!

**Comment by gouthamkunduru90** [comment]
I will going to open a new issue
@meltsufin i have a spring boot application having google cloud data store as back end. my application will going to deploy to PCF in future. we are still in the process of integrating PCF and GCP using service broker. i have written a configuration file for Datastore bean attached code below. i wanted to test it from my local machine by passing a private key data(i got it by using gcp service account json file) and project id from command line. my question is only private key data is enough to get the GoogleCredentials?

/****/
@Configuration
public class GcpDatastoreConfig {

	/**
	 * Returns Google datastore credentials from PCF at runtime (VCAP_SERVICES) and
	 * Sets the service authentication credentials
	 * 
	 * @return GoogleCredentials
	 * @throws IOException
	 * @throws JSONException
	 */
	@Bean
	public GoogleCredentials credential() throws IOException, JSONException {

		String env = System.getenv("VCAP_SERVICES");
		if (env != null) {
			JSONObject vcapServicesObject = new JSONObject(env);
			if (vcapServicesObject.has("google-datastore")) {
				String privateKeyData = vcapServicesObject.getJSONArray("google-datastore").getJSONObject(0)
						.getJSONObject("credentials").getString("PrivateKeyData");
				InputStream stream = new ByteArrayInputStream(Base64.getDecoder().decode(privateKeyData));
				return GoogleCredentials.fromStream(stream);
			}

		}
		return null;

		/*String PATH_TO_JSON_KEY = "src/main/resources/spatial-acumen-213021-2a71c0e3a819.json";
		return GoogleCredentials.fromStream(new FileInputStream(PATH_TO_JSON_KEY));*/
	}

	/**
	 * Configure datastore API to use provided Google credentials
	 * 
	 * @param credentials
	 * @return DatastoreOptions
	 * @throws IOException
	 */
	@Bean
	@ConditionalOnBean(name = "credential")
	public DatastoreOptions datastoreOptions(GoogleCredentials credential) throws IOException {
		if (credential != null) {
			return DatastoreOptions.newBuilder().setProjectId("spatial-acumen-213021").setCredentials(credential)
					.build();
		}
		return null;
	}

	/**
	 * Returns Instance of Google's datastore API
	 * 
	 * @param datastoreOptions
	 * @return Datastore
	 * @throws IOException
	 */
	@Bean
	@ConditionalOnBean(name = "datastoreOptions")
	public Datastore getDatastore(DatastoreOptions datastoreOptions) throws IOException {
		if (datastoreOptions != null) {
			return datastoreOptions.getService();
		}
		return null;
	}
}

**Comment by meltsufin** [comment]
@gouthamkunduru90 I think you're right, we currently do not support Datastore in `GcpCloudFoundryEnvironmentPostProcessor`. I'll create an issue for that.
