### ISSUE TITLE
Allow ReactiveFirestoreTransactionManager to be disabled while other FirestoreReactiveAutoConfiguration beans remain usable

### ISSUE THREAD

**Issue by sohoffice** [spring-cloud/spring-cloud-gcp#2550]
**Is your feature request related to a problem? Please describe.**
I was mixing JPA with GCP firestore and rely on JPA transaction. However, as FirestoreReactiveAutoConfiguration is always enabled by autoconfigure, I'd need to specifically declare which transaction manager to use in `@Transactional`.
```
@Transactional("transactionManager")
```
However, only JPA transaction manager is used, this is a little frustrating. And quite frankly very easily forgotten.

If the `@Transactional` annotation doesn't specify the transaction manager, Spring will complain about too many transaction manager candidates.

**Describe the solution you'd like**
If possible, can a property be matched to control whether this bean is needed ?

**Comment by meltsufin** [comment]
I guess we can move the transaction manager bean to a separate auto-configuration class like we do for Datastore (`DatastoreTransactionManagerAutoConfiguration`). Then it will be easier to disable it.

@dmitry-s What do you think?

**Comment by dmitry-s** [comment]
@meltsufin we can create a configuration property `spring.data.gcp.firestore.disableTransactionManager` and make the TransactionManager bean conditional on that property. 

What do you think?

**Comment by meltsufin** [comment]
I would rather move the config to a separate class like we did for Datastore. This will naturely lend itself to a `...enabled` property, as well as become easy to disable with the standard `spring.autoconfigure.exclude` mechanism.

**Comment by elefeint** [comment]
Fixed in GoogleCloudPlatform/spring-cloud-gcp#620.
