### ISSUE TITLE
FirestoreIntegrationTests.saveAllBulkTest » StatusRuntime INVALID_ARGUMENT

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#2561]
This is happening in CI, albeit not consistently.

**Comment by meltsufin** [comment]
cc/ @dmitry-s

**Comment by dmitry-s** [comment]
I was unable to replicate this issue, but I got the following error when I increased the number of entries we write:
io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: Write stream exhausted maximum allowed queued writes.

We might want to look at it as well.
