### ISSUE TITLE
Feature Request : avoid HealthIndicator to pull an inexistent subscription

### ISSUE THREAD

**Issue by olivierboudet** [spring-cloud/spring-cloud-gcp#2570]
**Is your feature request related to a problem? Please describe.**
When using OpenTelemetry Java Instrumentation with spring-cloud-gcp, each call to /actuator/health is sampled because spans are marked as error (because my policy is to save all error traces).

![image](https://user-images.githubusercontent.com/857205/97705763-e26a8800-1ab4-11eb-9afa-f7b82db5ba48.png)

In PubSubHealthIndicator, the check is done pulling a non-existent subscription (`this.pubSubTemplate.pull("subscription-" + UUID.randomUUID().toString(), 1, true);`) which logically throws a `not found` error. So, OpenTelemetry gRPC instrumentation catch this error and mark the span as error.

**Describe the solution you'd like**

Would it be possible to avoid to call a random subscription ?

**Comment by meltsufin** [comment]
We can certainly explore alternatives to calling a non-existent subscription, but I would also like to explore the option to tell OpenTelemetry not to trace this specific API call. Is there such a mechanism in OpenTelemetry? Maybe something [like this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/docs/suppressing-instrumentation.md) would work?

**Comment by olivierboudet** [comment]
Yes, spans can be ignored in OpenTelemetry with `otel.integration.grpc.enabled` but it disable gRPC tracing completely (not just for health indicator)

**Comment by meltsufin** [comment]
Have you also looked into `otel.trace.classes.exclude`?

**Comment by meltsufin** [comment]
Would you mind posting an issue in opentelemetry-java-instrumentation repo for this specific problem with exclusions? See: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues

**Comment by elefeint** [comment]
Fixed in GoogleCloudPlatform/spring-cloud-gcp#330 -- custom subscription names are now supported.
