### ISSUE TITLE
Auditing doesn't work on entities in Datastore when running through DatastoreTemplate.performTransaction()

### ISSUE THREAD

**Issue by fpavageau** [spring-cloud/spring-cloud-gcp#2603]
When using `DatastoreTemplate.performTransaction()` with `spring-cloud-gcp-data-datastore` `1.2.6.RELEASE`, auditing doesn't work for entities.

That's because [the new `DatastoreTemplate` instance created in `performTransaction()`](https://github.com/spring-cloud/spring-cloud-gcp/blob/v1.2.6.RELEASE/spring-cloud-gcp-data-datastore/src/main/java/org/springframework/cloud/gcp/data/datastore/core/DatastoreTemplate.java#L435-L440) does not have the `ApplicationEventPublisher` of the original one, which is the mechanism by which the `AuditingHandler` eventually gets called to set the auditing properties.

I've [added a test to `DatastoreTemplateAuditingTests` in my fork](https://github.com/spring-cloud/spring-cloud-gcp/compare/master...fpavageau:bug-auditing-transaction) which demonstrates the problem.

I also have a [simple fix ready](https://github.com/spring-cloud/spring-cloud-gcp/compare/master...fpavageau:bugfix-auditing-transaction), if it's actually a bug and you want a PR.

**Comment by meltsufin** [comment]
Hi @fpavageau! Thanks for a detailed description, test, and fix!
We'll be happy to accept the fix, if you can open a PR!

**Comment by fpavageau** [comment]
OK, I've squashed the test commit with the fix commit and opened the PR.
