### ISSUE TITLE
Sprintboot/Datastore - FindAll(example, pageable)

### ISSUE THREAD

**Issue by beunick** [spring-cloud/spring-cloud-gcp#2611]
Hello mate, 

I am using Springboot and Datastore and I am having problem with findAll(example, pageable). The problem is the findAll(example, pageable) is not returning the data based on the example, but instead return everything. Here is a piece of my code.

**Entity Product I have this :**
`@Entity(name="product")
public class Product {
   
    @Id
    private Key id;

    @Reference
    private Store store;
    
    // SETTER AND GETTER
}`

**Entity Store:**

`@Entity(name="store")
public class Store {
   
    @Id
    private Key id;

    private String name;
    
    // SETTER AND GETTER
}`

**Product Repository:**
`@Repository
public interface ProductRepository extends DatastoreRepository<Product, Key> { }`

**In my service I have**
`Pageable pageable = PageRequest.of(0, 3);`
`Product product = new Product();`
`product.setStore(store);`
`Example<Product> example = Example.of(product);`
`Page<Product> pagedProduct =  this.productRepository.findAll(example, pageable);`

The findAll return everything in the Product table instead of only returning the data based on the example. Can you please let me know if you know why ?
Thank You

**Comment by meltsufin** [comment]
This might be a bug. @dmitry-s PTAL when you have a chance.

**Comment by beunick** [comment]
Thanks for the note @meltsufin, so what is the next step ? How long do you think it may take to resolve it ? Thank You. 
By the way my primary Key is based on UUID.

Thanks.

**Comment by meltsufin** [comment]
@dmitry-s Was out today, but he should be able to assess tomorrow. Thanks for you patience.

**Comment by beunick** [comment]
Thank You :)

**Comment by dmitry-s** [comment]
I was able to replicate the issue, working on a fix.

**Comment by beunick** [comment]
Thank you

**Comment by beunick** [comment]
Thank You @dmitry-s can you please let me know which version include this fix ? Thanks

**Comment by meltsufin** [comment]
This will be released in 1.2.7 and 2.0.0.

**Comment by beunick** [comment]
Do you know when the release will be available ? Because when I use 1.2.7 in my POM file I have an error. 
Thank You!

**Comment by meltsufin** [comment]
There is no date for 1.2.7, as it's dependent on the next Spring Cloud Hoxton service release, but 2.0.0 will be coming soon (a few weeks). In the meantime, you can use `1.2.7.BUILD-SNAPSHOT` if you add Spring Snapshots repository.

**Comment by beunick** [comment]
Thanks @meltsufin for the note. I add the Spring Snapshots Repository and use 1.2.7.BUILD-SNAPSHOT but here is the error I am getting when I build the application:
`[ERROR] Failed to execute goal on project [36maggregrator[m: [1;31mCould not resolve dependencies for project co.pro.aggregrator:aggregrator:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.springframework.cloud:spring-cloud-gcp-starter-data-datastore:jar:1.2.7.BUILD-SNAPSHOT[m: Failed to read artifact descriptor for org.springframework.cloud:spring-cloud-gcp-starter-data-datastore:jar:1.2.7.BUILD-SNAPSHOT: Could not transfer artifact org.springframework.cloud:spring-cloud-gcp-starter-data-datastore:pom:1.2.7.BUILD-SNAPSHOT from/to repository.spring.snapshot (http://repo.spring.io/snapshot): Access denied to http://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-gcp-starter-data-datastore/1.2.7.BUILD-SNAPSHOT/spring-cloud-gcp-starter-data-datastore-1.2.7.BUILD-SNAPSHOT.pom. Error code 403, Forbidden -> [1m[Help 1][m
`

Here is what I have in my POM file, is there something I am doing wrong ?

`	<repositories>
	    <repository> 
	        <id>repository.spring.snapshot</id> 
	        <name>Spring Snapshot Repository</name> 
	        <url>http://repo.spring.io/snapshot</url> 
	    </repository>
	</repositories>
`
`
...
...
`
`
      <dependency>
		        <groupId>org.springframework.cloud</groupId>
		        <artifactId>spring-cloud-gcp-starter-data-datastore</artifactId>
		        <version>1.2.7.BUILD-SNAPSHOT</version>
      </dependency>
`

**Comment by meltsufin** [comment]
Please use this one:
```
				<repository>
					<id>spring-snapshots</id>
					<name>Spring Snapshots</name>
					<url>https://repo.spring.io/libs-snapshot-local</url>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
					<releases>
						<enabled>false</enabled>
					</releases>
				</repository>
```
I just tested it, and it found the artifact.
