### ISSUE TITLE
Logs entires without severity

### ISSUE THREAD

**Issue by lechen26** [spring-cloud/spring-cloud-gcp#2618]
Hi

we've recently noticed some of our projects that writes logging to stackdriver does not includes severity.

in one of my kotlin project we use:
- Gradle 6.1
- springboot "2.3.4.RELEASE"
- org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR8
- org.springframework.cloud:spring-cloud-gcp-starter-loggin (should be 1.2.5)

on my code we have something like:
```
private val log = LoggerFactory.getLogger(this.javaClass)
log.warn("Can't use this")
```

and this log meesage show on stackdriver with no severity
![image](https://user-images.githubusercontent.com/7347506/103072698-bcea8e00-45ce-11eb-907a-2b84f096751d.png)

is there any known  issue on that area?

**Comment by meltsufin** [comment]
What does your Logback configuration look like?
Do you have this?
```xml
<configuration>
  <include resource="org/springframework/cloud/gcp/logging/logback-appender.xml" />

  <root level="INFO">
    <appender-ref ref="STACKDRIVER" />
  </root>
</configuration>
```

**Comment by kioie** [comment]
@lechen26 @meltsufin tried and it seemed to work fine on my end. Only difference is that I was using spring-cloud-gcp-starter-logging(2.0.1-SNAPSHOT)

Code sample

```
public String log() {
		val log = LoggerFactory.getLogger(this.getClass());
		String message = "Can't use this";
		log.warn(message);
		return message;
	}
```

What it returned

<img width="859" alt="Screenshot 2021-01-19 at 14 40 32" src="https://user-images.githubusercontent.com/20902920/105030890-81c06b00-5a65-11eb-901c-ef396f5d102f.png">

**Comment by elefeint** [comment]
Please reopen if this is still an issue.
