### ISSUE TITLE
Consider creating a spring-cloud-gcp-autoconfigure module

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-gcp#262]
I'd like you to consider moving the auto-configuration code in a central place (`spring-cloud-gcp-autoconfigure` comes to mind with a root `org.springframework.cloud.gcp.autoconfigure` package). There are 28 classes currently so it really isn't a lot of code.

There are several advantages to this:

* Getting the code in a central place allows you to easily provide support for GCP as a whole (basically, users can get a single dependency and trigger auto-config by adding depedencies to the stuff they want to use). This can lead to a generic "GCP Support" on start.spring.io
* Separating the code from the starter allows users to deviate from that opinion. If they don't like the dependencies the starter brings, they can craft their own or add them manually
* It is easier to reflect on conditions if the code and the dependencies are separated (`@ConditionalOnClass` is super cheap and a great way to backoff early)
* You don't need to add a starter to get all the available metadata integration in your IDE
* It is more consistent with what Spring Boot does (not really an argument, except it's been working great for us so far)

This would allow you to have a `spring-cloud-gcp-starter` that  brings this module (replacing what `spring-cloud-gcp-starter-core` does with basically all features ready to be enabled by adding a dependency).

One major drawback though is that you can't use the assumption an auto-configuration or an `EnvironmentPostProcessor` has to kick in based on the fact that it's available. But I think relying on that is a bit broken as well.

IMO, the documentation should also be updated to make less reference to "starter". A starter is a group of dependencies that provides a feature for something. It is not the feature itself.

I am happy to provide guidance  or review if you want to pursue this.

**Comment by meltsufin** [comment]
Hi Stéphane, and thank you for taking such a thoughtful look at the project!

I believe we've considered a separate auto-config module before, but decided that keeping auto-config in the corresponding starters was simpler. One downside I see is that all these autoconfig classes will be on the classpath even if someone is only using a single module from the project. However, I understand your arguments for aligning with how Spring Boot organizes auto-config and I think we should do this.

**Comment by joaoandremartins** [comment]
This was already in our roadmap, #155.

We can prioritise this if getting to Initializr depends on it.

**Comment by artembilan** [comment]
Good point, @joaoandremartins !

I think that one should be closed in favor of this, since we have Stephane here already with his all Spring Boot wisdom 😄

**Comment by snicoll** [comment]
> One downside I see is that all these autoconfig classes will be on the classpath even if someone is only using a single module from the project. 

What downside is this exactly? Are you talking about the size of the jar?

> We can prioritise this if getting to Initializr depends on it.

I'd like to suggest an `GCP Support` entry and the only way to make it right is via this change. It's not a definitive requirement but IMO the support on start.spring.io would be more consistent that way.

**Comment by joaoandremartins** [comment]
Initially, I thought the request here was only to extract the auto-configuration code from our starter modules to autoconfigure modules. But it seems there's more to it.

I'm also a bit skeptical of bundling all our material into one dependency. Size of the jar is definitely a factor, we'd pull in things we don't need.
What's wrong with having an entry per starter on Initializr?

I don't mind creating an uber-autoconfigure starter that just contains everything, but we should still have the option to pull in the starters separately?

I'm also not sure that having a `spring-cloud-gcp-starter` that adds functionality as you add dependencies is very different from what we have today, where you already need to add those dependencies per starter/product.

**Comment by meltsufin** [comment]
> > One downside I see is that all these autoconfig classes will be on the classpath even if someone is only using a single module from the project.
> 
> What downside is this exactly? Are you talking about the size of the jar?

I'm thinking more about the developers being potentially confused seeing unrelated classes in the IDE symbols index. It's not a big deal though.

I'm thinking that `GCP Support` as the only entry for all of our integrations may not be very useful because developers would still need to manually add dependencies after adding the starter. For example, for AWS, I see `Core`, `JDBC`, and `Messaging`. That kind of breakdown seems to make more sense. Why would we want to do it differently for GCP?

**Comment by snicoll** [comment]
> Size of the jar is definitely a factor

Sorry, I don't understand. The auto-configuration code right now is 28 classes. Surely we're talking about a few kB. How can this be a factor concretely?

> What's wrong with having an entry per starter on Initializr?

We simply aren't going to do that. start.spring.io is opinionated (and has to be) so this change would provide you a much better flexibility than the current state IMO.

> I don't mind creating an uber-autoconfigure starter that just contains everything

I think there is a misunderstanding here. All I am asking is:

1. Move the auto-configuration code to a separate module (`spring-cloud-gcp-autoconfigure`). This module declares  `optional` dependencies on the things it needs (so including that module in a project does not bring the World)
2. Create a `spring-cloud-gcp-starter` that represents the absolute minimal you need to integrate with GCP (perhaps what the core starter does now, not sure)
3. Keep the starters as you have them now except they have no code in them anymore

> I'm also not sure that having a spring-cloud-gcp-starter that adds functionality as you add dependencies is very different from what we have today

It is different. Right now, you must use the starters because the auto-configuration is in them. That's largely what I am trying to address here.

> I'm thinking more about the developers being potentially confused seeing unrelated classes in the IDE symbols index. 

Spring Boot provides auto-configuration for a _bunch_ of libraries out of the box and I am not aware of a user complaining about that.

> I'm thinking that GCP Support as the only entry for all of our integrations may not be very useful 

Sorry if I gave you the impression that my intention is to add a single entry. It isn't. As you've noted, AWS has a few entries for top use cases and I intend to do the same with GCP. I have a few ideas to make this more useful for the user and all boils down to the fact that this project ships the auto-configuration separately from the starter.

A general entry gives you more flexibility for several reasons (trying to summarize here):

* It is consistent with what Spring Boot does, which I think is a valid argument
* The starter becomes what it is intended to do (i.e. gathering dependencies for a use case as an optional feature. If the user wants to declare dependencies they can do so)
* More auto-configuration can be shipped without any change on start.spring.io (just add them to the autoconfigure module and the general entry will make that available)
* It potentially allows us to do smart stuff such as if the standard `jdbc`starter and the `GCP Support`starter are selected, add `spring-cloud-gcp-starter-sql`. The same could apply if `Integration` is selected (to add the pubsub starter). I am not sure if that's a good idea but having a general entry makes that kind of feature possible

We can also jump on a call if you have more questions. If we're on the same page, I don't understand how moving the code out of the starters is an issue concretely (I personally don't see any downside).

**Comment by meltsufin** [comment]
@snicoll Thanks for such a detailed clarification! I don't have any more concerns regarding moving auto-config code out of starters and into `spring-cloud-gcp-autoconfigure`. So, let's proceed with that.

I think there is still more to discuss regarding the set of starters that would appear in the Initializr, but let's do that separately from this issue.

**Comment by joaoandremartins** [comment]
Added this issue to the 1.0.0.M2 release, for this Friday.
Would be great to get this `autoconfigure` situation resolved and merged by then.
