### ISSUE TITLE
Allow custom subscription name for Pub/Sub healthcheck

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-gcp#2630]
Currently, the Pub/Sub healthcheck attempts a pull from a nonexistent subscription. This has two negative consequences:
1) The pull takes longer
2) Error logs get polluted 

Allowing a pull from a known existing subscription would ameliorate issues like #2628 and #2570.

**Comment by ThusithaDJ** [comment]
Hi @elefeint, I'm aware this bug has been created a couple of days before. But I would like to contribute to the spring community If this not an urgent issue.

**Comment by elefeint** [comment]
@thusithaDJ Thank you! I've recreated the issue in our new repo -- GoogleCloudPlatform/spring-cloud-gcp#236 . You'll find more information about what this task entails there.

I will close this issue, and we can continue the conversation on the new issue -- feel free to ask any questions that will help you.
