### ISSUE TITLE
Bypass spring-cloud-gcp-starter-secretmanager when default credential not exits

### ISSUE THREAD

**Issue by lz000** [spring-cloud/spring-cloud-gcp#2632]
Our application has spring-cloud-gcp-starter-secretmanager in pom.xml. When running unit test in CI, since there is no GOOGLE_APPLICATION_CREDENTIALS environment variable defined, it crashes with the following error
```
Failed to instantiate [com.google.cloud.secretmanager.v1.SecretManagerServiceClient]: Factory method 'secretManagerClient' threw exception; nested exception is java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```
Since we have a different application.properties file with the mocked values for unit tests, we don't need the secretmanager to provide values. Is it possible we either mute this error and do nothing or have a way to bypass secretmanager entirely through an environment variable

**Comment by dzou** [comment]
@lz000 -- Our Secret Manager uses [Spring bootstrap](https://www.baeldung.com/spring-cloud-bootstrap-properties), so you'll need to create a `bootstrap.properties` file for your unit tests, placed in the same location as `application.properties`, and then add the property:

```
# This will disable the Secret Manager autoconfig from starting.
spring.cloud.gcp.secretmanager.enabled=false
```

**Comment by lz000** [comment]
@dzou Thanks, it seems to have work. But want to confirm the behavior. with spring.cloud.gcp.secretmanager.enabled set to false, the Secret Manager still runs, but instead out throwing error, it throws a warning which does not stop the app. Is it the correct behavior ?

**Comment by dzou** [comment]
Gotcha I see. Could you share what the warning is?

**Comment by lz000** [comment]
The warning message is exactly same as the error 
```
java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

**Comment by dzou** [comment]
Ahh I see. Yeah that warning is normal for integration tests in the case where the environment is the same but you haven't set up credentials. Just a reminder to add credentials if running in production.

You should be good.

**Comment by dzou** [comment]
One more note -- One of our teammates mentioned the warning might indicate you still have some bean in the application context still depending on credentials.

Do you have any other spring-cloud-gcp dependencies you are using? You will have to add that `spring.cloud.gcp.xxxxx.enabled=false` for those services as well in your integration test.

**Comment by lz000** [comment]
for spring-cloud-gcp this is the only one, but i have google-cloud-storage, nothing else relates to ggogle cloud

**Comment by dzou** [comment]
Hmm I see. Maybe it means our `GcpContextAutoConfiguration` is also kicking in.

Can you also add `spring.cloud.gcp.core.enabled=false`? See if that helps.

**Comment by lz000** [comment]
Yes this got rid of the warning

**Comment by dzou** [comment]
Glad this this works. Yes, for your integration tests (where you don't want authentication) you'll have to remember to disable the service if you don't want the autoconfiguration to load the beans.

You'll be able to find the `.enabled` settings for all our integrations in the [ref doc](https://googlecloudplatform.github.io/spring-cloud-gcp/2.0.1/reference/html/index.html#configuration-11).

Let me know if you have other questions.
