### ISSUE TITLE
Invalid dependency management in spring-cloud-gcp-dependencies

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-gcp#265]
The  `spring-cloud-gcp-dependencies` is a BOM and should not have dependency management for the modules that are not strictly managed by GCP. 

This includes:

* Any other Spring Cloud project (they have a BOM themselves so this potentially overrides a choice a user would make by importing a certain release train)
* 3rd party provided by Spring Boot (mysql & postgres driver, `commons-logging`)

**Comment by joaoandremartins** [comment]
I think the rationale behind having `spring-cloud-gcp-dependencies` a child of `spring-cloud-dependencies-parent` was that `spring-cloud-gcp` is a `spring-cloud` project.

Although I do get the point that our project shouldn't provide dependency management for other projects.
However, we do need to use that dependency management internally, somewhere in our project.

Is removing the `spring-cloud-dependencies-parent` parent from `spring-cloud-gcp-dependencies` and adding it as a BOM to `spring-cloud-gcp` a reasonable solution?
Do we even need to add the BOM to `spring-cloud-gcp`, given that its parent is already `spring-cloud-build`? (I can try this one on my own)

**Comment by joaoandremartins** [comment]
Rewinding a bit, I think you might be referring to us setting the versions for `spring-cloud-context`, `spring-cloud-sleuth` and `commons-logging` rather than the `spring-cloud-dependencies-parent` BOM parent.

We do need these internally, I'll look for what the best practice is for internal dependency management.

**Comment by joaoandremartins** [comment]
spring-boot seems to be following a similar model of specifying [internal dependencies externally](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-dependencies/pom.xml).

I looked at a few spring-boot starters and none specifies versions in their poms. I'd prefer we follow the same policy.

Please let me know if you require us to have separate `spring-cloud-gcp-dependencies` and `spring-cloud-gcp-bom` modules, for internal and external dependency management respectively.

**Comment by snicoll** [comment]
@joaoandremartins Spring Boot does it because it's the "platform". There is a cascading model where Spring  Boot provides integration with a bunch of libraries, then Spring Cloud does it for their modules and the libraries they manage _directly_ (directly is key here). Using Spring Boot is not a good idea in that context.

Please have a look to other Spring Cloud projects. I didn't meant to include versions in poms (please don't do that!) but moving those as an internal concept. Here is [how spring-cloud-netflix does it](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/pom.xml#L74) (I believe it's done consistently in other spring cloud repos.
