### ISSUE TITLE
SpannerOperations.executeDmlStatement doesn't run Partitioned-DML when it's not performed in transaction.

### ISSUE THREAD

**Issue by hiracchy** [spring-cloud/spring-cloud-gcp#2650]
## Version
`1.2.1.RELEASE`

## Details
In `org.springframework.cloud.gcp.data.spanner.core.SpannerOperations`, there is this code:
```java
/**
* Execute a DML statement on Cloud Spanner. If this is not performed in a transaction
* then it is done in partitioned-mode.
* @param statement the DML statement to execute.
* @return the number of rows affected.
*/
long executeDmlStatement(Statement statement);
```
The comment describes that executeDmlStatement will run Partitioned-DML when it's not performed in transaction.
However it doesn't looks true. When I run `SpannerTemplate.executeDmlStatement`, it does the following;
- start a transaction
- execute query 
- commit

(Sample code is like this)
```java
@RequiredArgsConstructor
public class SampleService {
  private final SpannerTemplate spannerTemplate;

  public void sample() {
    spannerTemplate.executeDmlStatement("insert into singers(singerId, score) values('a', 1)");
  }
}
```

So the comment or the behavior is wrong.
Actually not to run Partitioned-DML is better because we cannot execute insert statement in Partitioned-DML. I prefer current behavior and we should fix that comment.

## Another issue (I can make another github issue about it)
As I wrote in the above, when you run `SpannerTemplate.executeDmlStatement`, it does the following;
- start a transaction
- execute query 
- commit

Is it possible to run only the `execute query` part instead of creating transaction?
To create transaction for only one query is inefficient. (If it's impossible to run plain DML without transaction, it cannot be helped)

**Comment by meltsufin** [comment]
How do you know that the transaction is started?
I don't believe there is a direct way of controlling whether the query is executed as DML or Partitioned DML.
If there is an active transaction, it will be DML, and Partitioned DML otherwise.

So, I don't think there is a problem with the comment. However, if `SpannerTemplate.executeDmlStatement()` actually starts a transaction when it shouldn't -- that would be a bug.

**Comment by hiracchy** [comment]
@meltsufin 
> How do you know that the transaction is started?

I set a breakpoint to the following lines in `com.google.cloud.spanner.v1.stub.GrpcSpannerStub` and run in debug mode.

```java
public UnaryCallable<BeginTransactionRequest, Transaction> beginTransactionCallable() {
  return beginTransactionCallable; // <- breakpoint 1
}

public UnaryCallable<ExecuteSqlRequest, ResultSet> executeSqlCallable() {
  return executeSqlCallable; // <- breakpoint 2
}

public UnaryCallable<CommitRequest, CommitResponse> commitCallable() {
  return commitCallable; // <- breakpoint 3
}
```

I saw all the breakpoint stops with following code;
```java
@RequiredArgsConstructor
public class SampleService {
  private final SpannerTemplate spannerTemplate;

  public void sample() {
    spannerTemplate.executeDmlStatement("insert into singers(singerId, score) values('a', 1)");
  }
}
```

It means `SpannerTemplate.executeDmlStatement()` starts transaction even if it runs only 1 DML.

**Comment by hiracchy** [comment]
@meltsufin 

Btw, if the following code runs Partitioned-DML, it will be also a problem.
```java
@RequiredArgsConstructor
public class SampleService {
  private final SpannerTemplate spannerTemplate;

  public void sample() {
    spannerTemplate.executeDmlStatement("insert into singers(singerId, score) values('a', 1)");
  }
}
```

The problem is that Partitioned-DML can't run insert statement, so there will be no way to run insert statement without transaction.

**Comment by meltsufin** [comment]
You're right, the transaction is always started for `executeDmlStatement`, and `executePartitionedDmlStatement` is available for running partitioned DML.

The changes were made in https://github.com/spring-cloud/spring-cloud-gcp/pull/1710 and https://github.com/spring-cloud/spring-cloud-gcp/pull/1737, but javadoc wasn't updated.
