### ISSUE TITLE
Unknown Function Lower or LOWER

### ISSUE THREAD

**Issue by beunick** [spring-cloud/spring-cloud-gcp#2666]
Hello mate,

**Here is my entity** 
```
    @Entity(name="product")
    public class Product {
        @Id
	private Key id;
	private String name;
	private String code;
	@Field(name="is_deleted")
	private Boolean isDeleted;
}
```

**My repository**

```
@Repository
public interface ProductRepository extends DatastoreRepository<Product, Key> {

       @Query("select * from product where LOWER(code) = LOWER(@product_code) and is_deleted = @is_deleted)
	Product existsByCodeIgnoreCaseAndIsDeleted(@Param("product_code")String code, @Param("is_deleted")Boolean isDeleted);
}
```

When I call the method: existsByCodeIgnoreCaseAndIsDeleted() from a service I received this error message:
`[Request processing failed; nested exception is com.google.cloud.datastore.DatastoreException: Unknown function "LOWER".] with root cause 
com.google.datastore.v1.client.DatastoreException: Unknown function "LOWER".`

I also tried with lowercase "lower", with no success. 
 
Please help. 
Thanks

**Comment by meltsufin** [comment]
@beunick I don't believe Datastore supports functions like that. Where have you seen this in documentation?

**Comment by elefeint** [comment]
Reopen if this is still a question.
