### ISSUE TITLE
Huge amount of ScheduledFutureTask in memory in case pubsub.googleapis.com isn't available

### ISSUE THREAD

**Issue by AcridFantasy** [spring-cloud/spring-cloud-gcp#2677]
**Describe the bug**
If pubsub.googleapis.com isn't available, there is a huge amount of _io.grpc.netty.shaded.io.netty.util.concurrent.ScheduledFutureTask_ objects instantiated (millions) that uses a huge amount of memory and can cause OOM and our service outage. Issue should be reproduced within 10 minutes after application is started. Prerequisite for this issue is that pubsub.googleapis.com isn't available. Originally it has been found in our docker environment, but I was able to reproduce it by simply adding this line to my **/etc/hosts** file: 
**127.0.0.2 pubsub.googleapis.com**
Also, in our case, even full GC doesn't cleanup a lot of objects. For some reason, it is different for the sample project but it anyway causes OutOfMemoryError after some time. 
This case is quite important for us because it can cause service outage (due to OOM) for all our service instances using PubSub. Fortunately, DNS failure happens rarely but still, it can happen and affect a lot of our users.

Screenshots from **VisualVM** tool and some extra information is attached.
![heap_histo](https://user-images.githubusercontent.com/9916010/132505494-c9b621a2-e9af-4484-84bd-4c7f41f3d000.jpeg)
![mem_history](https://user-images.githubusercontent.com/9916010/132505499-694336a4-b088-4a7b-8537-3c64f29e19ff.png)
![per_thread_allocation](https://user-images.githubusercontent.com/9916010/132505501-80838d88-a45c-43c4-853d-aff5d4c4a10d.jpeg)
[memory_issue_gcp.nps.zip](https://github.com/spring-cloud/spring-cloud-gcp/files/7128668/memory_issue_gcp.nps.zip)

**Sample**
I attached zip archive with the simple project reproducing the issue. Simply import it to your IDE and run main method in com.example.gcp_report.Main.kt file. Please don't forget to update your hosts as I mentioned above before run.
[gcp_report.zip](https://github.com/spring-cloud/spring-cloud-gcp/files/7128664/gcp_report.zip)

Please let me know if there are any questions.

**Comment by meltsufin** [comment]
Do you experience the same issue with the `2.x` version?
See: https://github.com/GoogleCloudPlatform/spring-cloud-gcp

**Comment by AcridFantasy** [comment]
> Do you experience the same issue with the `2.x` version?

No, we haven't tried yet, should we?

**Comment by meltsufin** [comment]
> > Do you experience the same issue with the `2.x` version?
> 
> No, we haven't tried yet, should we?

Yes. The 1.x version is outside of the support period now.

**Comment by AcridFantasy** [comment]
> > > Do you experience the same issue with the `2.x` version?
> > 
> > 
> > No, we haven't tried yet, should we?
> 
> Yes. The 1.x version is outside of the support period now.

Ok, I'll try during working time. 
Thanks for the information.

**Comment by meltsufin** [comment]
Yes. Here: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues
Thanks!

**Comment by AcridFantasy** [comment]
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/614 - same issue is reproduced and logged to the new repo for 2.0.4 version. 
If there is no plans to fix this issue for the version I used here, then this issue can be closed.

Thanks

**Comment by elefeint** [comment]
I'll close this one in favor of GoogleCloudPlatform/spring-cloud-gcp#614
