### ISSUE TITLE
Health Indicator for Cloud Spanner

### ISSUE THREAD

**Issue by ikeyat** [spring-cloud/spring-cloud-gcp#2680]
I think Spring Boot's `DataSourceHealthIndicator` does not work for `spring-cloud-gcp-data-spanner` because it does not use JDBC DataSource.
A custom health indicator Such as `SpannerHealthIndicator` and its auto configures should be added into `spring-cloud-gcp-data-spanner` to avoid boilerplate.

https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health.writing-custom-health-indicators

**Comment by suztomo** [comment]
I copied this feature request to https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/640

**Comment by elefeint** [comment]
Closing this one; will discuss on the new repo issue.
