### ISSUE TITLE
spring-cloud-gcp-starter-pubsub fail on enforcer plugin

### ISSUE THREAD

**Issue by zgrzybek** [spring-cloud/spring-cloud-gcp#2684]
The spring-cloud-gcp-starter-pubsub artifact fails on maven enforcer plugin

[WARNING] 
Dependency convergence error for com.google.errorprone:error_prone_annotations:2.5.1 paths to dependency are:
    +-com.google.cloud:spring-cloud-gcp-starter-pubsub:2.0.6
      +-com.google.cloud:spring-cloud-gcp-starter:2.0.6
        +-com.google.cloud:spring-cloud-gcp-core:2.0.6
          +-com.google.cloud:google-cloud-core:2.2.0
            +-com.google.protobuf:protobuf-java-util:3.18.1
              +-com.google.errorprone:error_prone_annotations:2.5.1
and
    +-com.google.cloud:spring-cloud-gcp-starter-pubsub:2.0.6
      +-com.google.cloud:spring-cloud-gcp-pubsub:2.0.6
        +-com.google.cloud:google-cloud-pubsub:1.114.7
          +-com.google.api.grpc:proto-google-cloud-pubsub-v1:1.96.7
            +-com.google.errorprone:error_prone_annotations:2.9.0

**Comment by elefeint** [comment]
We are targeting upper bound convergence, not strict convergence -- see [this comment](https://github.com/spring-cloud/spring-cloud-gcp/issues/1975#issuecomment-540001211) for an explanation.

Also note that all work on Spring Cloud GCP happens in the new repo: https://github.com/GoogleCloudPlatform/spring-cloud-gcp .
