### ISSUE TITLE
Copy/pasted documention in READMEs

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-gcp#270]
Part of the reference guide is copy/pasted in the README. This makes it quite hard to be consistent. The PR I've recently submitted makes the readme of `spring-cloud-starter-config` inconsistent.

**Comment by meltsufin** [comment]
What would you suggest as the solution to this?

**Comment by snicoll** [comment]
The readme can have a link to ref guide section if you want to keep it.

**Comment by joaoandremartins** [comment]
I think @snicoll means fixes like [this](https://github.com/spring-cloud/spring-cloud-gcp/pull/268/files#diff-53772f03cf390c50569d1bd513a3a0fdR35).

I can sweep our READMEs next week to find similar issues.
