### ISSUE TITLE
Add reference documentation for Stackdriver Logging support

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#288]

**Comment by joaoandremartins** [comment]
When did we intend to add this?

**Comment by meltsufin** [comment]
Before M2. :)

**Comment by joaoandremartins** [comment]
#346 added Logging content to the refdoc.
@meltsufin would you mind going over it and applying any necessary fixes, or closing this issue?

**Comment by meltsufin** [comment]
Will do.

**Comment by meltsufin** [comment]
Since the documentation is already there, I think we can close this PR. However, I don't think logging documentation should be lumped together with trace docs.

**Comment by joaoandremartins** [comment]
It might be me who (still) doesn't understand what the logging module does, but I think in its current form, the logging module only really makes sense if coupled to the trace module?

That might change if we add any other functionality to the logging module in the future.

Feel free to suggest docs changes.

**Comment by meltsufin** [comment]
They are definitely related, especially since the main feature we're adding is passing around the Trace ID. However, just like Stackdriver Logging can be used independently from Stackdriver Trace, our support for logging is not strictly dependent on Trace. One use-case of what we're providing is to just link log messages by HTTP request.
