### ISSUE TITLE
Add config choices for stackdriver logging trace id header

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#296]
@meltsufin mentioned potentially adding choices for the user to choose their own prioritizing `x-cloud-trace-context` over `x-b3-traceid` or vice versa if both are present. Also a setting that would throw an exception if both are present and user only wants one to be present.

**Comment by meltsufin** [comment]
See: https://github.com/spring-cloud/spring-cloud-gcp/pull/295#pullrequestreview-87583173
