### ISSUE TITLE
Project ID has multiple competing sources

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-gcp#303]
I guess I don't really know what a proect ID is, but there seem to be multiple sources of configuration for it. There is this slightly weird idiom in one of the core modules:

```java
@Bean
    @ConditionalOnMissingBean
    public GcpProjectIdProvider gcpProjectIdProvider() {
        GcpProjectIdProvider projectIdProvider =
                this.gcpProperties.getProjectId() != null
                        ? () -> this.gcpProperties.getProjectId()
                        : new DefaultGcpProjectIdProvider();

        if (LOGGER.isInfoEnabled()) {
            LOGGER.info("The default project ID is " + projectIdProvider.getProjectId());
        }

        return projectIdProvider;
    }
```

and then this kind of thing elsewhere:

```java
			this.projectId = gcpConfigPropertiesProvider.getProjectId() != null
					? gcpConfigPropertiesProvider.getProjectId()
					: projectIdProvider.getProjectId();
```

I would have thought there should be one source of truth for a project ID in an app. I would expect it should therefore come from one place. Maybe I just didn't understand something.

**Comment by joaoandremartins** [comment]
What you're seeing in the first snippet is getting the project ID from the user-defined properties (`() -> this.gcpProperties.getProjectId()`) vs auto-detecting the project ID (`new DefaultGcpProjectIdProvider()`).

What you see in the second snippet is getting the project ID from the core module (e.g., a blanket project ID for every integration/service, `spring.cloud.gcp.core.project-id`) vs getting the project ID from the service-specific configuration (e.g., you might have Google Cloud SQL running from one project and Google Cloud Storage running from another one, `spring.cloud.gcp.sql.project-id=my-sql-project-id`, `spring.cloud.gcp.storage.project-id=my-storage-project-id`).

Hope this helps!

**Comment by dsyer** [comment]
What is a project ID then? Why would I want to have more than one in the same app?

**Comment by joaoandremartins** [comment]
Good question!

https://cloud.google.com/resource-manager/docs/creating-managing-projects

A project ID can be associated to a billing account and has APIs associated to it (enabled/disabled). A possible scenario is when you have Storage in a project being charged to a cost center (i.e., billing account) and Pub/Sub in a different project charged to a different cost center.
Or you might activate different services in different projects for other reasons. From my customer support days, I know folks do this.
