### ISSUE TITLE
Enforce blank lines after fields and methods using checkstyle

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#309]
http://checkstyle.sourceforge.net/config_whitespace.html#EmptyLineSeparator

TODO: Find reference in the Spring Framework code style guide for this requirement. @artembilan

**Comment by joaoandremartins** [comment]
Oh! I'm so sorry, I was looking for a rule to enforce no extra lines between method descriptions and at-clauses in method Javadoc.
I agree this one should be in, will add it to #318
