### ISSUE TITLE
CredentialsAutoConfiguration: use Resource.getInputStream() directly

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-gcp#31]
Right now we have a code:
```
return GoogleCredentials.fromStream(
					new FileInputStream(resourceLoader.getResource(
							this.environment.getProperty(AUTH_LOCATION_KEY)).getFile()));
```
Where it doesn't not make sense to try to get file and wrap it into `FileInputStream` when we can use `Resource.getInputStream()` directly.

OTOH not all `Resource` implementations provide `getFile()`. I can use something like `ByteArrayResource` to load credentials from my local DB, for example.

**Comment by joaoandremartins** [comment]
I was considering addressing this in #29. Are there any issues with that?

**Comment by artembilan** [comment]
No, that's fine.
I just followed with your comment which looked like you are not going to address that or even comment 😄 

Please, mention this issue in the commit message to close it automatically when the PR is merged:
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by artembilan** [comment]
Fixed via: https://github.com/spring-cloud/spring-cloud-gcp/commit/b0864e3c90e8f58585162a00a6ee7b46eeda611e
