### ISSUE TITLE
Readme changes for stackdriver logging for multiple trace ID headers

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#310]
In the logging project, starter project, and sample project.

**Comment by ChengyuanZhao** [comment]
Will do this after #297 is submitted and finalized.

**Comment by joaoandremartins** [comment]
Added this to the 1.0.0.M2 milestone. Would be great to get this in by Friday.
WDYT @ChengyuanZhao ?

**Comment by ChengyuanZhao** [comment]
Yup sounds good  @joaoandremartins, working on a PR and it'll be up shortly.
