### ISSUE TITLE
Fix issues with logging code sample

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#315]
- [ ] Something on `logging` is not reading the project ID from the context. You can reproduce that by clearing Cloud SDK's project ID (and credentials for that matter) with `gcloud config unset core/project`. We should either make it so or, if impossible, document in the README/refdoc that the project ID from Cloud SDK/some envvar is used instead.
+
```
ERROR in ch.qos.logback.core.joran.spi.Interpreter@15:14 - RuntimeException in Action for tag [appender] java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:163)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:81)
```

- [x] With the project ID in, running the sample gets stuck loading the Boot app. It never finishes loading. Removing the `logback-spring.xml` makes the app start. **NON-ISSUE**

- [ ] Documentation reads `Browse to "localhost:8080/log".` but this steps seems useless without a trace ID. Maybe remove this bit and just ask users to make the curl call with the trace ID?

- [ ] Like the project ID, credentials are also not being read from the `spring.cloud.gcp.credentials.location` property.

**Comment by meltsufin** [comment]
@ChengyuanZhao Can you look into this please?

**Comment by ChengyuanZhao** [comment]
Hmm, it's starting up just fine for me and running and handing that /log request just fine. Why would you try it without the project ID set though? The instructions tell the user to set all that up with SDK before trying this. 

Yea I agree that first sentence could be removed, though the following sentence starting with "However" explains what you mention.

**Comment by ChengyuanZhao** [comment]
(tried both mvn appengine:deploy and mvn spring-boot:run )

**Comment by meltsufin** [comment]
2) I'm able to repro from `gh-262-autoconfigure` branch. Make sure you rebuild the whole project.
It seems to be caused by the `CONSOLE` appender missing. See similar issue [here](https://stackoverflow.com/questions/40762547/springboot-application-stuck-at-springboot-logo).

This config in the sample, fixes the problem for me:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/cloud/gcp/logging/logback-appender.xml" />
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml" />

    <root level="INFO">
        <appender-ref ref="CONSOLE"/>
        <appender-ref ref="STACKDRIVER" />
    </root>
</configuration>
```

**Comment by ChengyuanZhao** [comment]
I tried this on master branch, and I did git pull and the most recent version of gh-262-autoconfigure doesn't build for me (some failed tests). 

cccz@cccz:~/IdeaProjects/spring-cloud-gcp$ ./mvnw clean install -am -projects=spring-cloud-gcp-samples/spring-cloud-gcp-logging-sample




Results :

Tests in error: 
  test(org.springframework.cloud.gcp.autoconfigure.sql.GcpCloudSqlAutoConfigurationMockTests$GcpCloudSqlAutoConfigurationPostgresTest): Failed to load ApplicationContext
  test(org.springframework.cloud.gcp.autoconfigure.sql.GcpCloudSqlAutoConfigurationMockTests$GcpCloudSqlAutoConfigurationWithUserAndPassTest): Failed to load ApplicationContext
  test(org.springframework.cloud.gcp.autoconfigure.sql.GcpCloudSqlAutoConfigurationMockTests$GcpCloudSqlAutoConfigurationWithDatasourcePropertiesTest): Failed to load ApplicationContext
  test(org.springframework.cloud.gcp.autoconfigure.sql.GcpCloudSqlAutoConfigurationMockTests$GcpCloudSqlAutoConfigurationWithInstanceConnectionNameTest): Failed to load ApplicationContext
  test(org.springframework.cloud.gcp.autoconfigure.sql.GcpCloudSqlAutoConfigurationMockTests$CloudSqlAppEngineDataSourceTest): Failed to load ApplicationContext
  test(org.springframework.cloud.gcp.autoconfigure.sql.GcpCloudSqlAutoConfigurationMockTests$CloudSqlDataSourceTest): Failed to load ApplicationContext

**Comment by meltsufin** [comment]
I added issue to Spring Boot tracker: https://github.com/spring-projects/spring-boot/issues/11700

**Comment by joaoandremartins** [comment]
@ChengyuanZhao it's unreasonable to require a dependency on Cloud SDK when one isn't needed.
The whole project was designed so that you don't have to use Cloud SDK to be able to use it.

As with all other modules, the `logging` module should use the provided `GcpProjectIdProvider` bean if it's possible. Or, if not, we should find out what environment variable is used by Cloud SDK so we can ask users to fill it.

**Comment by meltsufin** [comment]
2. is a non-issue. The app only appears to be hung because logs are no longer produced to the console.

**Comment by ChengyuanZhao** [comment]
@joaoandremartins Could you give it another try? I unset the project in the SDK as you mentioned and supplied a json key file to the GOOGLE_APPLICATION_CREDENTIALS env var and it still works fine for me.

**Comment by joaoandremartins** [comment]
Using GOOGLE_APPLICATION_CREDENTIALS, it seems to work fine.
But using the `spring.cloud.gcp.credentials.location` property, which is preferable to the envvar way, doesn't work.

**Comment by meltsufin** [comment]
`spring.cloud.gcp.credentials.location` Won't work here because the appender itself is not part of the Spring context when used in the log4j config.

**Comment by joaoandremartins** [comment]
If we're sure that we can't use the property for that, then let's move on without it.
I'm wondering if there's a chance our Spring Boot starter can set the `GOOGLE_APPLICATION_CREDENTIALS` envvar in time for the logging agent to read it?
Having to set an envvar for logging to work feels like a step back in usability and breaks our contract where users either set the credentials property or let's Spring Boot do its autoconfiguration thing.
I remember having seen somewhere that credentials can be explicitly provided using a `LoggingOptions` class, though I haven't seen it used by any dependencies we use (e.g., `TraceLoggingEnhancer`).

**Comment by joaoandremartins** [comment]
Any progress here?

**Comment by ChengyuanZhao** [comment]
I  thought this was resolved as 

- the sample is working
- credentials can be provided via SDK or the env var
- credentials are not expected to able to be provided via the property as @meltsufin mentioned

**Comment by joaoandremartins** [comment]
With this issue, I expected that some research would have actually been made in order to see if we could use our properties to feed into the `logging` objects, as I've read somewhere they can be.
There is no trace of any investigation carried in this issue at all.

@meltsufin said that maybe it isn't possible to use the properties, not that they are not expected to be used, since that would be very non-sensical, in the sense that the properties are used everywhere else in our project, and it's actually the added value our `core` module offers -- a central place to declare all your GCP metadata.

I'll just get to that research myself whenever I have some free time.

**Comment by ChengyuanZhao** [comment]
Alas, no time was dedicated to researching what you mentioned as it did not seem to be an issue, but more of a nice-to-have, and the time was instead spent on other priorities.
