### ISSUE TITLE
Jetty ALPN/NPN failure

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-gcp#327]
I can't build from master (even before 4c02b1354e34) because of a failure in the Pub/Sub Module

```
Caused by: java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:34)
	at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:153)
```

**Comment by joaoandremartins** [comment]
I'm not being able to reproduce this.
Does it fail when you're doing `mvn clean install` from the project root?
Or when you're building an app that uses our modules?

**Comment by dsyer** [comment]
Just building from root. Maybe a platform thing? Did you try with Linux.

**Comment by joaoandremartins** [comment]
I'm using Linux too. I even tried deleting my `.m2` folder, but still got the same result.
Travis is passing, I'm wondering if this is anything with your local setup?

**Comment by dsyer** [comment]
This issue suggests a classpath problem: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2740, but it looks fine to me (the versions are a supported combination of the projects listed). I suspect you have something in your environment that makes it work. E.g. look at this line in `GrpcSslContexts`

```java
  private static SslProvider defaultSslProvider() {
    return OpenSsl.isAvailable() ? SslProvider.OPENSSL : SslProvider.JDK;
  }
```

So if you have OpenSSL available in some way that I don't, then the code path is different.

**Comment by dsyer** [comment]
It was a bad jar file. I cleared the local cache and that fixed it, I think.

**Comment by renannprado** [comment]
I got the same error while running inside of alpine so had to:

1 - include below two libraries
2 - I had to install the `lib6-compat` in alpine

```groovy
compile group: 'io.netty', name: 'netty-tcnative-alpine', version: '2.0.8.Final'
compile 'org.conscrypt:conscrypt-openjdk-uber:1.1.4'
```

```Dockerfile
RUN apk add --no-cache libc6-compat
```

also use this as a reference of which libraries to use:
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty
