### ISSUE TITLE
Maven jar plugin has strange looking version override

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-gcp#329]
The version override seems unnecessary, but if it is there for a reason, maybe a comment in the pom would be a good idea? See e.g. in pubsub module.

**Comment by joaoandremartins** [comment]
Good catch. Version isn't needed there.

I removed the version and moved `maven-jar-plugin` to the top level `pom.xml` in https://github.com/spring-cloud/spring-cloud-gcp/pull/308/commits/138c5016a91c4a8608e67632a23a0a84038afa29 since all packages will need their version in their MANIFEST.MF file.

**Comment by joaoandremartins** [comment]
Fixed by #308
