### ISSUE TITLE
zuulproxy auto config, NoClassDefFoundError com/google/api/gax/rpc/EmptyRequestParamsExtractor

### ISSUE THREAD

**Issue by inventoryz** [spring-cloud/spring-cloud-gcp#333]
HI,   

Found below dependency error after adding spring cloud zuul proxy dependency
tried manually adding google api gax dependency,  new error was thrown

below is the original error
`2018-01-23 23:03:27.058 ERROR [api-gateway,,,] 44432 --- [ost-startStop-1] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'org.springframework.cloud.netflix.zuul.ZuulProxyAutoConfiguration': Unsatisfied dependency expressed through field 'requestCustomizers'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'apacheHttpRibbonRequestCustomizer' defined in class path resource [org/springframework/cloud/sleuth/instrument/zuul/TraceZuulAutoConfiguration.class]: Unsatisfied dependency expressed through method 'apacheHttpRibbonRequestCustomizer' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sleuthTracer' defined in class path resource [org/springframework/cloud/gcp/trace/autoconfig/StackdriverTraceAutoConfiguration.class]: Unsatisfied dependency expressed through method 'sleuthTracer' parameter 4; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'traceSpanReporter' defined in class path resource [org/springframework/cloud/gcp/trace/autoconfig/StackdriverTraceAutoConfiguration.class]: Unsatisfied dependency expressed through method 'traceSpanReporter' parameter 3; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'traceConsumer' defined in class path resource [org/springframework/cloud/gcp/trace/autoconfig/StackdriverTraceAutoConfiguration$TraceConsumerConfiguration.class]: Unsatisfied dependency expressed through method 'traceConsumer' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'traceServiceClientTraceConsumer' defined in class path resource [org/springframework/cloud/gcp/trace/autoconfig/StackdriverTraceAutoConfiguration$TraceConsumerConfiguration.class]: Unsatisfied dependency expressed through method 'traceServiceClientTraceConsumer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'traceServiceClient' defined in class path resource [org/springframework/cloud/gcp/trace/autoconfig/StackdriverTraceAutoConfiguration$TraceConsumerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.google.cloud.trace.v1.TraceServiceClient]: Factory method 'traceServiceClient' threw exception; nested exception is java.lang.NoClassDefFoundError: com/google/api/gax/rpc/EmptyRequestParamsExtractor`

**Comment by joaoandremartins** [comment]
@inventoryz thanks for your report.

I've tried to reproduce, but kept on running into other issues. Are you able to post your `pom.xml` file here so I can take a closer look?

**Comment by inventoryz** [comment]
Here is the pom
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.test</groupId>
  <artifactId>com.test</artifactId>
  <version>1.0-SNAPSHOT</version>

  <dependencyManagement>
    <dependencies>

      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>2.0.0.M7</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      
      
      
      
      
      
      

    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
      <version>2.0.0.M5</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.16.6</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>21.0</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.github.tomakehurst</groupId>
      <artifactId>wiremock</artifactId>
      <version>1.58</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
      <version>1.10.19</version>
      <scope>test</scope>
    </dependency>
    
    
    
    
    

    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-sleuth</artifactId>
      <version>2.0.0.M5</version>
    </dependency>
    
      
      
      
    


  </dependencies>


</project>`

here is the main application
`package com.test;

import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.BeansException;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;
import org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration;
import org.springframework.cloud.netflix.zuul.EnableZuulProxy;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;

@Slf4j
@EnableZuulProxy
@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class, HibernateJpaAutoConfiguration.class})
public class application implements ApplicationContextAware
{
  private static ApplicationContext contextInstance;

  /**
   * Spring boot start.
   * @param args arguments.
   */
  public static void main(String[] args)
  {
    log.info("Initializing Context...");
    final ApplicationContext ctx = SpringApplication.run(application.class, args);
    log.info("Context initialized: " + ctx);
  }

  /**
   * {@inheritDoc}
   */
  public void setApplicationContext(ApplicationContext applicationContext) throws BeansException
  {
    contextInstance = applicationContext;
  }
}
`

**Comment by joaoandremartins** [comment]
Try adding our BOM to your `<dependencyManagement>` pom section.

```
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-gcp-dependencies</artifactId>
				<version>1.0.0.M1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>2.0.0.M7</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

It will add the correct `gax` version and you shouldn't see that error anymore.

**Comment by joaoandremartins** [comment]
Also, `1.0.0.M1` isn't compatible with Spring Boot 2, so you should also set `spring-boot-dependencies` version to something like `1.5.9.RELEASE`.

**Comment by meltsufin** [comment]
@inventoryz I tried to repro using your example, but I get a completely different error.
`java.lang.ClassNotFoundException: org.springframework.core.KotlinDetector`.
I think this problem has to do with what @joaoandremartins said regarding M1 not supporting Spring Boot 2.

**Comment by saturnism** [comment]
@inventoryz have you given M2 a try against Spring Boot 2? Thanks!

**Comment by inventoryz** [comment]
I tried M2 today, compilation works fine.
