### ISSUE TITLE
Enforce newline at end of file using checkstyle

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#338]
Add `<module name="NewlineAtEndOfFile"/>` to our `checkstyle.xml` config.
See: http://checkstyle.sourceforge.net/config_misc.html#NewlineAtEndOfFile

**Comment by meltsufin** [comment]
I guess, I should've spent 2 seconds checking our `checkstyle.xml` before posting this! :smile:

**Comment by meltsufin** [comment]
For those of us using IntelliJ, there is the `Settings -> Editor -> General -> "Ensure line feed at file end on Save"` option.

**Comment by artembilan** [comment]
Correct, something similar there is for STS as well.

According the `NewlineAtEndOfFile` docs it checks `all the files` by default.

Maybe we somehow have a suppression for `/test` scope?
Or our Travis config just doesn't run `checkstyle` to reveal similar problems.

**Comment by joaoandremartins** [comment]
As I mentioned, I suspect it only acts on `all the files (that are compiled)`, which actually makes sense.

It doesn't happen only to files in `/test`, but I also found it to be true with the `app.yaml` file in the `logging` sample, as well as `pom.xml` files, etc.

I can't find any suppression in the `checkstyle.xml` file...

**Comment by meltsufin** [comment]
I think we need to add `<includeTestResources>true</includeTestResources>` to the plugin config.

**Comment by meltsufin** [comment]
OK, the real reason it doesn't work is because Checkstyle only supports Java files, although those Java files may have an extension other than `.java`. We may need to look into a different tool.

**Comment by artembilan** [comment]
I think we won't be able to find any other tool even if that's already not a first flaw we found in the Checkstyle. And it's still a standard in Spring projects. No choice unless switch on the option in the IDE and request such a fix during review.

**Comment by meltsufin** [comment]
Agreed. It's pretty much infeasible.
