### ISSUE TITLE
Support `spring.cloud.gcp.credentials.location` for Logging

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#339]
The `com.google.cloud.logging.logback.LoggingAppender` in `logback-appender.xml` is not part of the Spring Context. So it doesn't have access to the `spring.cloud.gcp.credentials.location` property. However, it needs credentials to be passed in. By default, it will get credentials from `GOOGLE_APPLICATION_CREDENTIALS` env var. However, it would be more consistent to have a way to provide credentials using the `spring.cloud.gcp.credentials.location` property.

**Comment by joaoandremartins** [comment]
So our logging stuff reads environment variables like `GOOGLE_APPLICATION_CREDENTIALS`.

I was wondering whether there is any way of setting the credentials property and then writing its content to the `GOOGLE_APPLICATION_CREDENTIALS` envvar before logging is setup.
What I'm observing is that logging is one of the first things to be configured. Even if I have bootstrap configuration that writes to those environment variables, logging startup comes first.

@artembilan do you know of any way to run code before logging is configured?

**Comment by joaoandremartins** [comment]
Another alternative is to instruct users to fill out the `GOOGLE_CLOUD_PROJECT` and `GOOGLE_APPLICATION_CREDENTIALS` envvars in their `logback-spring.xml` file.

**Comment by artembilan** [comment]
Well, I know something like `EnvironmentPostProcessor`, but I'm not sure that it is used enough early to transfer our `spring.cloud.gcp.credentials.location` configuration property to the ENV variable.

I see something like `<springProperty>` in Spring Boot: https://docs.spring.io/spring-boot/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#_environment_properties

Might be definitely what you are looking for...

**Comment by joaoandremartins** [comment]
That was very promising, but I didn't find any mechanism in Logback's configuration that let us write to envvars.
The simplest way out of this seems to be to just tell users which environment variables to fill with what data.
It breaks the consistency of `spring.cloud.gcp.credentials` being used everywhere in the project, but I can't find any better alternative that works...

**Comment by arpan2501** [comment]
@joaoandremartins saw you Spring Developer video of last year and was following that.....

_:: Spring Boot :: (v2.0.3.RELEASE)_

When running spring boot app from eclipse its getting connected **perfectly**

Used **application.properties** and added file in classpath-
`spring.cloud.gcp.credentials.location=classpath:ArpanShoppingApp-863d536d1f93.json`

But after building it and running **jar** file gives **exception** of _FileNotFound_
`java -jar CloudSQLConnect-1.0.jar`

**Exception** - 
```
2018-06-22 10:46:38.393  INFO 1172 --- [           main] o.s.c.g.s.a.GcpCloudSqlAutoConfiguration : Default MYSQL JdbcUrl provider. Connecting to jdbc:mysql://google/google_sql?cloudSqlInstance=mindful-highway-207309:asia-south1:shopping-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false with driver com.mysql.jdbc.Driver
2018-06-22 10:46:38.401  INFO 1172 --- [           main] o.s.c.g.s.a.GcpCloudSqlAutoConfiguration : Error reading Cloud SQL credentials file.

java.io.FileNotFoundException: class path resource [ArpanShoppingApp-863d536d1f93.json] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/Users/arpan/Documents/workspace-sts-3.8.4.RELEASE/CloudSQLConnect/target/CloudSQLConnect-1.0.jar!/BOOT-INF/classes!/ArpanShoppingApp-863d536d1f93.json
at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:217) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:133) ~[spring-core-5.0.7.RELEASE.jar!/:5.0.7.RELEASE]
at org.springframework.cloud.gcp.sql.autoconfig.GcpCloudSqlAutoConfiguration.setCredentialsProperty(GcpCloudSqlAutoConfiguration.java:167) [spring-cloud-gcp-starter-sql-1.0.0.M1.jar!/:1.0.0.M1]
at org.springframework.cloud.gcp.sql.autoconfig.GcpCloudSqlAutoConfiguration.defaultJdbcInfoProvider(GcpCloudSqlAutoConfiguration.java:107) [spring-cloud-gcp-starter-sql-1.0.0.M1.jar!/:1.0.0.M1]
at org.springframework.cloud.gcp.sql.autoconfig.GcpCloudSqlAutoConfiguration$$EnhancerBySpringCGLIB$$edf77794.CGLIB$defaultJdbcInfoProvider$1(<generated>) [spring-cloud-gcp-starter-sql-1.0.0.M1.jar!/:1.0.0.M1]
```

Posted same on StackOverflow - 
[](https://stackoverflow.com/questions/50981257/spring-boot-project-jar-file-not-reading-file-placed-on-classpath?noredirect=1#comment88957931_50981257)

**Comment by meltsufin** [comment]
@arpan2501 Have you tried opening the jar file as a zip file and checking if the `ArpanShoppingApp-863d536d1f93.json` is in there somewhere?

**Comment by arpan2501** [comment]
@meltsufin yes i installed the Zip Editor plugin from Eclipse MarketPlace to check the content of Jar and it is present in /BOOT-INF/classes.
It is giving FileNotFoundException only when running as Jar but when running from IDE it is getting connected perfectly!!
Stuck with it for some time - waiting for someone to help me understand the thing!!

**Comment by meltsufin** [comment]
It sound like this problem: https://stackoverflow.com/questions/49684665/java-io-filenotfoundexception-class-path-resource-even-though-file-exists-in-sr
Can you see if the proposed solution works for you?

**Comment by arpan2501** [comment]
@meltsufin - No please refer to my Stackoverflow question - https://stackoverflow.com/questions/50981257/spring-boot-project-jar-file-not-reading-file-placed-on-classpath/50990669#50990669

**Comment by meltsufin** [comment]
Thank you for the link! Indeed, Phil is right that it's a limitation in this project, specifically in the `SqlCredentialFactry` class. That class is used outside of the Spring application context, which makes it hard to reuse the Spring utilities to read the files from the JAR. We should open an issue for this, if one doesn't already exist.

**Comment by meltsufin** [comment]
@arpan2501 Can you try using `spring.cloud.gcp.credentials.encoded-key` property?

**Comment by arpan2501** [comment]
Sure will try it out and update....
But as of now anyone looking for answer - I have used the actual file path in my local machine and created the jar.
Then i have built the docker image for it and in Docker file I have added the file according to the path in application properties.
Currently my Spring Boot Application is up and running with Google Cloud SQL - **http://35.200.210.45**

**Comment by meltsufin** [comment]
That's definitely a good way to do it. Storing private keys inside the JAR is usually not the best option.

BTW, the apples are way to expensive in your store at $7 an apple! Good deals on bananas and hats though! 😄

**Comment by PTanwarCS** [comment]
Any update on this issue faced by @meltsufin ? I am experiencing the same. Is there an official solution to this?
