### ISSUE TITLE
google-cloud-bom is too broad

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-gcp#343]
Unfortunately, `google-cloud-bom` is too broad. I understand that from a platform perspective having a opinion about the Netty version to use is logical but the platform here is Spring Boot and it may very well have a different opinion.

The changes in #201 to force `2.0.7` is not  good at all as this bom shouldn't have an opinion on that in the first place and another Spring Boot version may very well use another version.

A solution  to that is to see what we really need from the `google-cloud-bom`. If it turns out that it is really required, we should probably ask that project to split it in managed dependencies and "platform dependencies"

**Comment by joaoandremartins** [comment]
I had already filed https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2781 so they split their dependencies into the ones they export vs the ones they use, kinda like what we did in https://github.com/spring-cloud/spring-cloud-gcp/pull/273

**Comment by snicoll** [comment]
Awesome, thank you!

**Comment by joaoandremartins** [comment]
I believe this got sorted already.
