### ISSUE TITLE
Merge spring-cloud-gcp(-starter)-core with autoconfigure

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#347]

**Comment by meltsufin** [comment]
I don't think we're merging the `spring-cloud-gcp-starter` into `autoconfigure`, but maybe we should still merge `spring-cloud-gcp-core` into `autoconfigure`? Should this be done for M2? @joaoandremartins

**Comment by joaoandremartins** [comment]
I'd like to ponder a bit more on this change.
This will effectively mean that every module in the project will depend on `autoconfigure`, which I'm not sure is reasonable...

**Comment by joaoandremartins** [comment]
This was already done in #341.
