### ISSUE TITLE
Implement ApiFuture -> ListenableFuture adapter for PubSubTemplate's send()

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#36]
Currently, `PubSubTemplate.send()` returns a String with `PubsubMessage`'s ID. We block the call to publish() and, ideally, we'd return a future instead.

We should implement a PubSub `ApiFuture` adapter to Spring's `ListenableFuture`, so the user doesn't have to use anything PubSub.

**Comment by artembilan** [comment]
I think we can just have a `SettableListenableFuture` bridging adaptation directly in the `send()` implementation without any target `Adapter` class exposure:
````java
ApiFuture<String> publishApiFuture = publisher.publish(PubsubMessage.newBuilder()
			.setData(ByteString
					.copyFrom(message.getPayload().toString().getBytes()))
				.build());

final SettableListenableFuture<String> future = new SettableListenableFuture<>();

ApiFutures.addCallback(publishApiFuture,
		new ApiFutureCallback<String>() {

			@Override
			public void onFailure(Throwable t) {
				future.setException(t);
			}

			@Override
			public void onSuccess(String result) {
				future.set(result);
			}

});

return future;
````
Does it make sense ?
