### ISSUE TITLE
Fix @Deprecated warnings

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-gcp#372]
For example the `WebMvcConfigurerAdapter` is `@Deprecated`:
```
 * @deprecated as of 5.0 {@link WebMvcConfigurer} has default methods (made
 * possible by a Java 8 baseline) and can be implemented directly without the
 * need for this adapter
```
So, `LoggingWebMvcConfigurer` has to be fixed respectively.

**Comment by joaoandremartins** [comment]
Hell yeah!
Piggybacking on this, there's a ton of deprecated stuff, both in Spring and google-cloud-java, that we're using and should probably be updated.

**Comment by artembilan** [comment]
Updated the subject to broader audience.
We definitely may fix all of them at once.
