### ISSUE TITLE
The spring-cloud-gcp-trace brings a lot of not related dependencies

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-gcp#374]
I wasn't managed to understand why do we need `spring-web` and `spring-boot-actuator` there.

Also I don't see any reason in the `spring-boot-configuration-processor` and there is no any usage classes from the `spring-cloud-gcp-core`.

In other words: please, revise all the dependencies and maybe we don't need them all.

**Comment by joaoandremartins** [comment]
Fixed by #381
