### ISSUE TITLE
JPA sample can't create tables

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#380]
`Caused by: java.sql.SQLException: Storage engine MyISAM is disabled (Table creation is disallowed).`

It appears that something maybe in SB2 changed JPAs dialect to something that Cloud SQL doesn't like.

https://cloud.google.com/sql/docs/mysql/diagnose-issues (search for MyISAM).

I've tried a few dialects, but haven't found one that works yet.

`spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect`
`spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLInnoDBDialect`

It should be a matter of finding one that Cloud SQL likes.
https://docs.jboss.org/hibernate/orm/3.5/api/org/hibernate/dialect/package-summary.html

**Comment by meltsufin** [comment]
This might work:
`hibernate.dialect.storage_engine = innodb`

**Comment by joaoandremartins** [comment]
The title should've actually read "JPA sample" instead of "SQL sample".

**Comment by meltsufin** [comment]
Adding the following to `application.properties` fixes the problem. Thanks to the [answer by Oliver Sahner](https://stackoverflow.com/questions/1459265/hibernate-create-mysql-innodb-tables-instead-of-myisam) on StackOverflow.

`spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect`

It looks like an issue(?) introduced in Spring Boot 2.0.

**Comment by mahen025** [comment]
add spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect in application.properties file to solve java.sql.SQLException: Storage engine MyISAM is disabled (Table creation is disallowed).

**Comment by niranjan-sathindran** [comment]
Thanks! That solved my issue of not being able to perform any DDL operations on GCP Cloud SQL.
