### ISSUE TITLE
Autoconfigure InnoDB for Cloud SQL (MySQL)

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#392]
See #390.

**Comment by joaoandremartins** [comment]
@meltsufin was this solved by #390?

Please reopen if not.

**Comment by meltsufin** [comment]
No, it didn't solve it.

**Comment by saturnism** [comment]
Related: spring-projects/spring-boot#15342

**Comment by meltsufin** [comment]
Need to verify that this is resolved by https://github.com/spring-projects/spring-boot/issues/16172.
