### ISSUE TITLE
Should Spring Cloud Config be extracted from Autoconfigure module?

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#397]
It was weird to see Spring Cloud Config related doc in the Autoconfigure README.

https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/README.adoc

It took me a while to realize that Spring Cloud Config for GCP is now folded into Autoconfigure. Even thought there is few classes involved, organizationally it feels a little weird.

**Comment by meltsufin** [comment]
We went back and fourth on this quiet a bit. Everyone seemed to be happy in the end to have it in the autoconfigure module and use a flag to turn it on.

**Comment by saturnism** [comment]
it looks like we have the config starter, but the starter has no README like other starters.

**Comment by saturnism** [comment]
Oh interesting, there are READMEs for both the implementing module and the starter module. Not quite sure where the line is. I see moving the README straight out of Autoconfigure in #409 is probably incomplete.

**Comment by meltsufin** [comment]
I think, ultimately, we should try to cut down on the module READMEs and link to the refdoc wherever possible instead. Currently, there is too much documentation duplication.

**Comment by saturnism** [comment]
+1. That would make sense if we can extract all READMEs to the ref doc.

**Comment by joaoandremartins** [comment]
I think we can live with config in the `autoconfigure` module, let's close this one out.
