### ISSUE TITLE
update Spring Data JPA sample README with same instructions as Cloud SQL sample has

### ISSUE THREAD

**Issue by balopat** [spring-cloud/spring-cloud-gcp#398]
I ran into a similar issue as described in #376, in the sense, that the README seems to lack information about what to do with passwords and I had a root password setup. I did remember my password, and setting `spring.datasource.password` did the trick. If someone creates an extra user, we can add `spring.datasource.username` as well.

All in all I'd recommend keeping the "create a sql instance & database" section exactly the same between the two samples (manually if there is no automated way).

**Comment by balopat** [comment]
Updating the password section is even more so important as CloudSQL PostgreSQL root password is mandatory.

**Comment by joaoandremartins** [comment]
@balopat would you mind submitting a proposal for this issue's solution whenever you have the time?

**Comment by balopat** [comment]
Yes, happy to do so!

**Comment by balopat** [comment]
Actually I meant *sample*s not *starter*s. I'll update the description of this issue.
