### ISSUE TITLE
Use DefaultCredentialsProvider in all product integrations

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#403]
Currently, it's only used in core and config.

**Comment by kohago** [comment]
I am also think that using the DefaultCredentialsProvider is the best practice!!

In the case of local development,I use a google service account and set it's JSON key file to [spring.cloud.gcp.credentials.location] ,worrying the security problems.
But When published to gce|gae, it use DefaultCredentialsProvider defaultly,
So The [spring.cloud.gcp.credentials.location] is meaningless?
