### ISSUE TITLE
`v1.0.0.M2` tag still exists

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-gcp#410]
Looks like a release was cancelled. The tag still exists though so you may want to remove it.

**Comment by meltsufin** [comment]
@snicoll Why do you say it was cancelled? The release was completed on Friday.

**Comment by snicoll** [comment]
The last commit is named "revert 1.0.0m2 release". I hardly find any reason to have that if the release hasn't been rollbacked or something.

**Comment by meltsufin** [comment]
That's just part of the release process where we temporarily change versions in master to M2 and after the release revert back to SNAPSHOT. It's a bit misleading indeed.
cc/ @sobychacko

**Comment by snicoll** [comment]
Wow, ok. 

I am curious which version of spring cloud you've used for this as there aren't any milestone that works with RC1 atm.

**Comment by meltsufin** [comment]
[Finchley.M5](https://github.com/spring-cloud/spring-cloud-gcp/blob/94bce62e3e635e143168dbba30c5ad3951327290/pom.xml#L43) seems to have worked.

**Comment by bcholmes** [comment]
Which repo has that been put in to? It doesn't appear to be in the milestones repo (https://repo.spring.io/milestone/org/springframework/cloud/spring-integration-gcp/), and my attempt to use spring-cloud-gcp-starter-pubsub fails with "Could not find artifact org.springframework.cloud:spring-integration-gcp:jar:1.0.0.M2".

**Comment by dsyer** [comment]
We can't support Finchley.M5 with Boot RC1 across the board, so I don't recommend releasing the GCP libraries with that combination. User apps will break for sure. Wait for Finchley.M6.

**Comment by meltsufin** [comment]
We haven't found any issues yet in our testing. We can push an `M3` as soon as `Finchley.M6` is ready. In the meantime, if any issues are encountered, we'll try to recommend workarounds.
