### ISSUE TITLE
pre signed Cloud Storage URL

### ISSUE THREAD

**Issue by gavinwilliams** [spring-cloud/spring-cloud-gcp#411]
I'm trying to create a pre-signed URL for an upload for cloud storage. However I can't seem to get a value other than null from spring cloud gcp. Sample code is below.

```  
    /**
     * Generates a file with for a media type
     * @param extension The media type
     * @return The file you can upload to
     */
    private fun fileForExtension(extension: String) : File {

        val objectID = generateCloudObjectID(extension)
        val resource = (uploadBucket as GoogleStorageResourceBucket).createRelative(objectID) as GoogleStorageResourceObject
        val url = resource.createSignedUrl(TimeUnit.DAYS, 7L)
        return File(put = url, objectID = objectID)

    }
```

**Comment by ChengyuanZhao** [comment]
In your example where the signed URL is null, what is the full path of the resource? Is it a valid path for GCS and also in a bucket to which your application has permission?

**Comment by joaoandremartins** [comment]
I think the issue is that we don't actually create the object in GCS on `createRelative()`.

https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceBucket.java#L114
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-storage/src/main/java/org/springframework/cloud/gcp/storage/GoogleStorageResourceObject.java#L57

We should make `GoogleStorageResourceObject.createBlob()` public and call it from `GoogleStorageResourceBucket.createRelative()`.

**Comment by ChengyuanZhao** [comment]
Yes that's right, at the moment we create the GCS objects on getting the output stream to write to, but not when getting the signed URL.

**Comment by gavinwilliams** [comment]
@ChengyuanZhao & @joaoandremartins correct, if I could I would inject the BlogInfo into the `createSignedUrl` method to get around this.

**Comment by gavinwilliams** [comment]
This now just puts an empty object on GCS directly from my Spring application. This needs to return a pre-signed URL so a third party application can make a PUT request to upload to GCS.

**Comment by meltsufin** [comment]
@gavinwilliams Please file this as a new issue, if you don't mind. Thanks!

**Comment by joaoandremartins** [comment]
Not sure if I understand that issue.
`createSignedUrl()` returns a `URL` object containing the signed URL.

**Comment by gavinwilliams** [comment]
Hi @meltsufin no need now, I managed to work it out. @joaoandremartins, this returns a URL to read/GET the object, not to PUT. I managed to just use `com.google.cloud.storage.Storage`.

```
        val blobInfo = BlobInfo
                .newBuilder("bucket", "object.mp4")
                .setContentType("video/mp4")
                .build()

        val url = storage.signUrl(blobInfo, 7L, TimeUnit.DAYS, Storage.SignUrlOption.httpMethod(HttpMethod.PUT), Storage.SignUrlOption.withContentType())

````
