### ISSUE TITLE
Spring Cloud GCP is not enabled by default when starter is specified

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#418]
This is easily missed unless reading into the documentation reference.  Is there a way to auto-enable based on other attributes/properties? E.g., existence of bootstrap properties?

**Comment by joaoandremartins** [comment]
I think you're referring to the Config bit, right?

**Comment by joaoandremartins** [comment]
I'll go ahead and close this due to the lack of a workaround.
