### ISSUE TITLE
Join the Spring Cloud release train

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-gcp#425]
Finchley [is due to GA in March](https://github.com/spring-cloud/spring-cloud-release/milestones?direction=asc&sort=due_date&state=open)

If that is too early, we can shoot for the next train, Greenwich.

**Comment by meltsufin** [comment]
Thanks for the heads up! March might be too early for us, but we'll discuss it.

**Comment by spencergibb** [comment]
Not a problem

**Comment by meltsufin** [comment]
Related: #951.
Currently targeting Spring Cloud Greenwich release train.

**Comment by meltsufin** [comment]
We're in master of Spring Cloud Release now!
https://github.com/spring-cloud/spring-cloud-release/pull/102
