### ISSUE TITLE
Drop support for auto-creating GCS buckets

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#426]

**Comment by ChengyuanZhao** [comment]
Why remove it?

**Comment by meltsufin** [comment]
Since buckets names are globally unique, they should be created very deliberately. It's unlikely that anyone would just hard-code a bucket name in their configuration and expect it to be auto-created.
We can revisit this in the future, if anyone finds a convincing use-case for it. For now, I think requiring users to explicitly create buckets, is less error-prone.

**Comment by ChengyuanZhao** [comment]
But this feature already exists, and I disagree about this point. It's parentalism. The client lib already so easily lets users programaticaly create buckets. Furthermore, the client lib already trivially lets people create buckets for names generated at run time! Whereas our code uses the Value annotation and requires hard coding in config.

Furthermore, the functionality already was written.
