### ISSUE TITLE
Consider having binder integration tests start the emulator

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#435]
The idea is to have something like the `PubSubEmulator` rule in https://github.com/spring-cloud/spring-cloud-gcp/pull/431/commits/d9dc51867227ac0452e872b602598882528d1f52#diff-6ff85717ce7e17b90d04f38c7b5cc8d0 so that the emulator doesn't need to be started before running the tests.

The rule should also be called with `@ClassRule` instead of `@Rule` so that the same instance of the emulator is used.

**Comment by meltsufin** [comment]
Are we documenting anywhere that the emulator needs to be started manually before running the tests?

**Comment by joaoandremartins** [comment]
Not yet. But if this change goes through, we probably won't need to, as the tests themselves will run the emulator.
