### ISSUE TITLE
Support autoconfiguration of GCP Project ID

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#44]
Project ID may be obtained from the environment on GCP using `GOOGLE_CLOUD_PROJECT` or the [metadata server](https://cloud.google.com/compute/docs/storing-retrieving-metadata).

This may require introduction of `GcpProjectIdProvider`.

**Comment by markfisher** [comment]
perhaps it's worth considering a `PropertySource` implementation that wraps the metadata server?

**Comment by meltsufin** [comment]
For the project ID, we can actually just use `ServiceOptions.getDefaultProjectId()` as suggested in https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2094.

Exposing the whole metadata server as a `PropertySource` is also an interesting idea but probably a much bigger effort with a wider scope.
