### ISSUE TITLE
PubSub subscriber thread config not working

### ISSUE THREAD

**Issue by dintualex** [spring-cloud/spring-cloud-gcp#450]
I tried using the configuration spring.cloud.gcp.pubsub.subscriber-executor-threads to increase the number  of threads used by the subscriber but seems to be not working. Its still having the core thread-pool size of 4

i'm using the version 1.0.0.BUILD-SNAPSHOT

**Comment by meltsufin** [comment]
Please provide some more specifics about how you're using the Pub/Sub support. Are you using the autoconfigured `PubSubTemplate`? Which method are you calling on it? How are you determining that the thrad-pool size is actually 4? Thanks!

**Comment by dintualex** [comment]
I'm using autoconfigured PubSubTemplate with Spring Integration. Below is the code snippet
`
        @Bean
	public PubSubInboundChannelAdapter inboundChannelAdapter(
			@Qualifier("inputChannel") MessageChannel inputChannel,
			@Qualifier("errorChannel") MessageChannel errorChannel,
			PubSubOperations pubSubTemplate) {

		PubSubInboundChannelAdapter adapter =
				new PubSubInboundChannelAdapter(pubSubTemplate, "test");`


Interesting thing to be noted is that when i mention spring.cloud.gcp.pubsub.publisher-executor-threads, both the SubscriberFactory and PublisherFactory executor core pool is set to the provided value.

Below are the two ways i checked the values ::
1) Inspected the pubSub object instance
2) In log its printing the threadNumber when we consume the message
