### ISSUE TITLE
missing labels for logs of container running in gcp / gke

### ISSUE THREAD

**Issue by Andy2003** [spring-cloud/spring-cloud-gcp#453]
using:

	<dependency>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-gcp-logging</artifactId>
	</dependency>

in my spring boot app with all the settings mentioned in https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-logging the logs of the app have almost no labels for filter them out correcltly. See the following log entry:

	{
		insertId: "abc"
		labels: {
			levelName: "INFO"
			levelValue: "20000"
		}
		logName: "projects/<project-id>/logs/<app-name>"
		receiveTimestamp: "2018-02-23T11:34:20.947913720Z"
		resource: {
			labels: {
				cluster_name: ""
				container_name: ""
				instance_id: ""
				namespace_id: ""
				pod_id: ""
				project_id: "<project-id>"
				zone: "europe-west3-b"
			}
			type: "container"
		}
		severity: "INFO"
		textPayload: "message"
		timestamp: "2018-02-23T11:34:20.865Z"
	}

The app ist deployed to gcp / gke as a docker image. Additionally the trace Id of `spring-cloud-gcp-trace`is also not present in the log  entry.

I also tried using

	<dependency>
		<groupId>com.google.cloud</groupId>
		<artifactId>google-cloud-logging</artifactId>
		<version>1.17.0</version>
	</dependency>

without any improvement in the logs.

**Comment by meltsufin** [comment]
What's your logging configuration? Which logging library and appender are you using?

**Comment by Andy2003** [comment]
I used logback with the settings from the readme:

	<configuration scan="true" scanPeriod="1 minutes">
		<jmxConfigurator/>
		<include resource="org/springframework/cloud/gcp/logging/logback-appender.xml"/>
	
		<logger name="com.kiwigrid" level="DEBUG"/>
	
		<root level="INFO">
			<appender-ref ref="STACKDRIVER"/>
		</root>
	
	</configuration>

so `com.google.cloud.logging.logback.LoggingAppender` is used

**Comment by meltsufin** [comment]
This suggests a problem in the `google-cloud-logging` library. I suspect this class [`MonitoredResourceUtil`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/MonitoredResourceUtil.java) is not handling all the labels for GKE correctly. In fact, I see a related issue in their tracker: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2912.

**Comment by Andy2003** [comment]
OK, so we need to stay with logging to the `std.out`. Is there a way to get the traceId logged correctly, so that the logs gets connected to the traces (recorded via `spring-cloud-gcp-starter-trace`)

I tried it by logging in json fromat but the relevant labels (`labels."appengine.googleapis.com/trace_id"`) are not present. There will be only the fields `X-B3-SpanId` and `X-B3-TraceId`from the MDC in the jsonPayload:

	{
		insertId:  "xxxx"
		jsonPayload: {
			@timestamp:  "2018-02-22T18:07:46.631+00:00"
			@version:  1
			X-B3-SpanId:  "xxxxx"
			X-B3-TraceId:  "xxxxx"
			X-Span-Export:  "true"
			level:  "INFO"
			level_value:  20000
			logger_name:  "com.xxxx"
			message:  "msg"
			thread_name:  "registrationTask1"
		}
		labels: {
			compute.googleapis.com/resource_name:  "fluentd-gcp-v2.0.9-mgljq"
			container.googleapis.com/namespace_name:  "xxx"
			container.googleapis.com/pod_name:  "xxx"
			container.googleapis.com/stream:  "stdout"
		}
		logName:  "projects/xxx/logs/xx"
		receiveTimestamp:  "2018-02-22T18:07:50.893906523Z"
		resource: {
			labels: {
				cluster_name:  "xxx"
				container_name:  "xxx"
				instance_id:  "xxx"
				namespace_id:  "xxx"
				pod_id:  "xxx"
				project_id:  "xxx"
				zone:  "europe-west3-b"
			}
			type:  "container"
		}
		severity:  "INFO"
		timestamp:  "2018-02-22T18:07:46Z"
	}

**Comment by meltsufin** [comment]
I think that in the JSON payload, you need to include the `trace` field. Can you  give that a try?
The code that processes the JSON is [here](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb).
@igorpeshansky Do we have docs for this?

**Comment by igorpeshansky** [comment]
No public docs yet, but they're coming. FWIW, the default value of the trace key is `"logging.googleapis.com/trace"`, so you should use that name for the field in your JSON.

**Comment by Andy2003** [comment]
@igorpeshansky I've tried to use the field `logging.googleapis.com/trace`. This only resulted in:

	{
		insertId:  "xxxx"
		jsonPayload: {
			@timestamp:  "2018-02-22T18:07:46.631+00:00"
			@version:  1
			X-B3-SpanId:  "xxxxx"
			X-B3-TraceId:  "xxxxx"
			X-Span-Export:  "true"
			level:  "INFO"
			level_value:  20000
			logger_name:  "com.xxxx"
			message:  "msg"
			thread_name:  "registrationTask1"
		}
		labels: {
			compute.googleapis.com/resource_name:  "fluentd-gcp-v2.0.9-mgljq"
			container.googleapis.com/namespace_name:  "xxx"
			container.googleapis.com/pod_name:  "xxx"
			container.googleapis.com/stream:  "stdout"
		}
		logName:  "projects/xxx/logs/xx"
		receiveTimestamp:  "2018-02-22T18:07:50.893906523Z"
		resource: {
			labels: {
				cluster_name:  "xxx"
				container_name:  "xxx"
				instance_id:  "xxx"
				namespace_id:  "xxx"
				pod_id:  "xxx"
				project_id:  "xxx"
				zone:  "europe-west3-b"
			}
			type:  "container"
		}
		severity:  "INFO"
		timestamp:  "2018-02-22T18:07:46Z"
		trace: "xxx"
	}

However, the link to display logs from the stack driver trace page expects the trace id to be under `labels."appengine.googleapis.com/trace_id"`.

**Comment by igorpeshansky** [comment]
@draffensperger to comment on the trace field and the logs link.

**Comment by Andy2003** [comment]
@igorpeshansky / @draffensperger I have already figured out how to log so that stackdriver can find the logs linked to a traceId too. See PR #454

**Comment by joaoandremartins** [comment]
Fixed by #454
