### ISSUE TITLE
Adding support for Google Cloud Datastore

### ISSUE THREAD

**Issue by laszlocsontos** [spring-cloud/spring-cloud-gcp#455]
Hey Guys,

I'm building an app on top of GCP with Spring Boot and [Cloud Datastore](https://cloud.google.com/datastore/) would be a good fit for my use case. For the time being, I'll be using [Cloud SQL](https://cloud.google.com/sql/) instead as it seems to be well supported already. Nevertheless, I don't need OLTP capabilities at all and using a hosted service without having to worry about scaling and managing MySQL instances really appeals to me.

When _Datastore_ support comes to my mind, it would be nice to have both a low level API (eg. `DatastoreTemplate`, `DatastoreTransactionManager`, etc.) and also high level abstractions through Spring Data (eg. `DatastoreRepository`) and Spring TX for interacting with it.

I wanted to ask you if you've thought about adding _Datastore_ support as a sub-module to this project?

Cheers,
László

PS: I'd be gladly take part in the development of adding _Datastore_ support, should you need a helping hand.

**Comment by meltsufin** [comment]
Hi László, thanks for the issue submission. Datastore is definitely on the project roadmap, and close to as you described, with the low-level `DatastoreTemplate` and Spring Data support. We plan to start working on it soon. The current focus is on Spanner, but Datastore is next.
We're happy to accept contributions from the community as well. Cheers!

**Comment by ChengyuanZhao** [comment]
We're working on this now and we have a label with tons of issues for implementing Spring Data Datastore: https://github.com/spring-cloud/spring-cloud-gcp/labels/datastore
