### ISSUE TITLE
Support injection of Google Storage objects as Resource

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#46]
The `spring-cloud-gcp-starter-storage` already supports loading `gs://...` resources using `DefaultResourceLoader`, but direct injection using `@Value` does not work.

```java
@Value("gs://<bucket>/<object>")
private Resource gcsResource;
```

Currently, for some reason it tries to resolve the resource via ServletContext.
```
java.io.FileNotFoundException: Could not open ServletContext resource [/gs://<bucket>/<object>]
	at org.springframework.web.context.support.ServletContextResource.getInputStream(ServletContextResource.java:141) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at com.example.HelloController.readGcs(BootDemoApplication.java:164) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
```

**Comment by artembilan** [comment]
Well, actually it works. See `GoogleStorageTests`:
```
@Value("gs://test-spring/images/spring.png")
private Resource remoteResource;
...
@Configuration
static class GoogleStorageTestsConfiguration implements ResourceLoaderAware{

	private ResourceLoader defaultResourceLoader;
        ...
        @Bean
	public GoogleStorageProtocolResolver googleStorageProtocolResolver(Storage storage) {
		return new GoogleStorageProtocolResolver(this.defaultResourceLoader, storage);
	}
```
The main trick here is exactly that `GoogleStorageProtocolResolver` bean definition.
The `StorageAutoConfiguration` does the stuff for us when we use Boot and have `spring-cloud-gcp-starter-storage` in the classpath. Otherwise we have to declare that `GoogleStorageProtocolResolver` bean manually in one of our configuration.

Does it make sense to you?

**Comment by meltsufin** [comment]
@artembilan It makes sense that it should work and it does work in the test. However, I can't get it to work with a web-based boot app. I added `spring-cloud-gcp-starter-storage`, but I just keep getting `Could not open ServletContext resource [/gs://<bucket>/<object>]`. What am I missing?

**Comment by artembilan** [comment]
I think we should consider this as a bug and try to come up with the test-case on the matter.
I'll take it.

**Comment by meltsufin** [comment]
Thanks for taking this on. It could entirely be just me missing something obvious.

**Comment by sanjayjha9950** [comment]
I am still facing the same issue, am i missing something?

**Comment by meltsufin** [comment]
`/gs:///` doesn't look right. Do you have a `/` in the beginning of the path? You don't need it.
We need to see more of the code to try to help.

**Comment by sanjayjha9950** [comment]
no '/' in the beginning, its only in the exception (it is in the original exception as well). 

`
@RestController
public class WarrantyTransformerController {

@Value("gs://<bucket>/<file name>")
private Resource wnmFile;

@PostMapping("/readFile")
	public void publishWarranty() throws IOException {
	
		String s = StreamUtils.copyToString(
				this.wnmFile.getInputStream(),
				Charset.defaultCharset());
		System.out.println(s);

	}
}`

**Comment by meltsufin** [comment]
We have a very similar sample application [here](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample/src/main/java/com/example/WebController.java) and it works fine. Can you identify the difference in what you're doing?
