### ISSUE TITLE
Generate meta-data for the @ConfigurationProperties

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-gcp#47]
http://docs.spring.io/spring-boot/docs/1.5.3.RELEASE/reference/htmlsingle/#configuration-metadata-annotation-processor

**Comment by joaoandremartins** [comment]
I think this is currently happening for the two places we have `@ConfigurationProperties` at: our Core and SQL starters.

I'm thinking we should probably transform the `@Values` we have in https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-starters/spring-cloud-gcp-starter-pubsub/src/main/java/org/springframework/cloud/gcp/pubsub/autoconfig/GcpPubSubAutoConfiguration.java#L56 to `@ConfigurationProperties`.

`@Value` doesn't do that trick where `executorThreads` is aliased to `executor-threads`, which is the rule with our other properties.

**Comment by meltsufin** [comment]
What do you mean by aliasing to `executor-threads`? If the meta-data is not generated for `@Value`, let's just switch to structured properties like you're suggesting.

**Comment by artembilan** [comment]
I think you need to take a look here: https://docs.spring.io/spring-boot/docs/1.5.7.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-vs-value

The most important feature there is about https://docs.spring.io/spring-boot/docs/1.5.7.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-relaxed-binding

**Comment by joaoandremartins** [comment]
Yes, relaxed binding is exactly what I meant. I didn't know there were even other options like underscore and upper case notation. Thanks @artembilan !

I might file a PR on this soon so we get parity across all our config.
