### ISSUE TITLE
Setup GitHub Pages for Project Page

### ISSUE THREAD

**Issue by garyrussell** [spring-cloud/spring-cloud-gcp#48]

**Comment by garyrussell** [comment]
[Initial page here](http://cloud.spring.io/spring-cloud-gcp/)

[Maintenance Instructions here](https://github.com/spring-projects/gh-pages#edit-the-content-of-your-home-page).

If there's a "global" GCP logo, we can look at getting a "springified" version created for the page [example here](http://projects.spring.io/spring-kafka/) (light gray on gray).

**Comment by meltsufin** [comment]
Thanks for setting up the initial page!! We can definitely work on the Spring/GCP logo! @joaoandremartins can you look into that please?

**Comment by joaoandremartins** [comment]
#52 
On it!
