### ISSUE TITLE
Add README.md for Postgres starter

### ISSUE THREAD

**Issue by jabubake** [spring-cloud/spring-cloud-gcp#480]
https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-starters/spring-cloud-gcp-starter-sql-postgresql

**Comment by meltsufin** [comment]
Is the documentation in the [refdoc](https://docs.spring.io/spring-cloud-gcp/docs/1.0.0.M3/reference/htmlsingle/#_spring_jdbc) sufficient?
We're trying to avoid keeping docs in READMEs and focus on the refdoc instead.

**Comment by jabubake** [comment]
That works, in that case it might be worth keeping it consistent. I see some modules have READMEs and some not.  It also works to have a simple README that just points to the appropriate reference doc page. (and hence does n't need to be maintained).

**Comment by meltsufin** [comment]
@dmitry-s Can you take this on? It should help with debugging https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/74.
