### ISSUE TITLE
Add sample application for PubSub Channel Adapter

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#49]
Maybe Storage Resource Abstraction as well.

**Comment by joaoandremartins** [comment]
Regarding channel adapters, my test toy app lives in https://github.com/joaoandremartins/chatroom-springintegration/blob/master/src/main/java/com/google/springongcp/pubsub/PubSubApplication.java

Maybe we could use this as a starting point for a samples repo (new or existing) and link it from http://cloud.spring.io/spring-cloud-gcp/ ?

Brain dump of some more things we might want to showcase in our samples:
- GCS resource abstraction,
- Manual/automatic ACK mode (toy app only uses manual now),
- (A)sync message sending ([not yet built](https://github.com/spring-cloud/spring-cloud-gcp/issues/51)),
- (Non-)Boot usage (toy app uses Boot heavily),
- Programmatic topic/subscription creation ([not yet built](https://github.com/spring-cloud/spring-cloud-gcp/issues/26)).

@jabubake do you have any advice for us here? Thanks!

**Comment by jabubake** [comment]
Regarding samples repo : I'd advise keeping it under [java-docs-samples](https://github.com/GoogleCloudPlatform/java-docs-samples) : under a spring-cloud-gcp directory or just spring.
I was going to get started on the GCS resource abstraction showcase : create a sample , then a community article and Spring guide with it.  Happy to help if you want to do it yourself, if not, just file an issue under java-docs-samples, assigned to me.
