### ISSUE TITLE
Consider using vcap.services map instead of manually parsing VCAP_SERVICES

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#503]
One issue with using the Cloud Foundry map provided by Spring Boot was identified in https://github.com/spring-cloud/spring-cloud-gcp/pull/449#discussion_r174920421.

In short, services are identified by a name given by the user (e.g., `vcap.services.mypubsub`) and that aren't a convention.

We should traverse all services, looking for the conventioned keyword, e.g., `google-pubsub`, and then use that service metadata.

**Comment by joaoandremartins** [comment]
After some experimentation and chatting with @balopat, it seems we're left with two options here:

1. Use the property source generated by [VcapServiceCredentialsEnvironmentPostProcessor](https://github.com/spring-cloud/spring-cloud-cloudfoundry/blob/master/spring-cloud-cloudfoundry-web/src/main/java/org/springframework/cloud/cloudfoundry/environment/VcapServiceCredentialsEnvironmentPostProcessor.java).

We would need to traverse all the values in the map and retrieve the binding name by detecting which entry's key ends with `.label` and has the expected value (e.g., `google-pubsub`).
This is basically a hack which still has to do extra parsing of a data structure, but instead of encoded JSON like we're doing currently in #449, it's the processed map.

2. Create our own `EnvPP` that parses the `VCAP_SERVICES` JSON and produces a map indexed by service name, instead of binding name. In case of multiple bindings of the same service to the same CF app, the `EnvPP` would throw an error.

This approach still requires us to do explicit parsing of the JSON, like we're doing currently, only to produce a map data structure.

It makes sense to go this way if the map is going to be used by someone else, as if we're the only ones using the map, there is no real use or need for it, since we can still parse the JSON and use it to add beans to the context, like we're doing in #449.

---

@artembilan @snicoll your input here is required to proceed. Thanks!

**Comment by joaoandremartins** [comment]
It would seem it's also possible to feed our existing configuration properties (e.g., `spring.cloud.gcp.pubsub.project-id`) straight from the `EnvPP`. This approach makes more sense to me.
I'll look into this tomorrow.

**Comment by artembilan** [comment]
>  it's also possible to feed our existing configuration properties

That's exactly what I expect to see there. At least I hoped to have it worked from the beginning.
And that is exactly what Dave commented a while ago: https://github.com/spring-cloud/spring-cloud-gcp/pull/449#discussion_r177316678. And that's (one more time) exactly what I try to pull from you. The sample is in the mentioned not one time: https://github.com/spring-cloud/spring-cloud-cloudfoundry/blob/master/spring-cloud-cloudfoundry-web/src/main/java/org/springframework/cloud/cloudfoundry/environment/VcapServiceCredentialsEnvironmentPostProcessor.java

**Comment by snicoll** [comment]
> This is basically a hack 

Why? The way I understand it, you're processing the values of a map to index them with a different value.

**Comment by joaoandremartins** [comment]
But why going to the lengths of doing that? Just to delegate JSON parsing to Spring Boot?
What advantage is there in using the map provided by Spring Boot, which is not made for our purposes? We're not even using it as a map. We'll be doing expensive O(n) queries over the map's entry set rather than O(1) reads, which I'm sure is how that map is supposed to be used by other users.

Rather, instead of parsing a map, why not just parsing JSON? In fact, other Cloud Foundry support I've seen is doing just that -- parsing the JSON on their own (even though within an `EnvPP`) and changing the environment, instead of parsing the Spring Boot map.

Regarding Dave's comment, I wish someone had told me "use and `EnvPP` in order to change the properties you're using and let your autoconfig classes be CF agnostic".
My interpretation of Dave's comment was that I should use the mapping produced by `VcapServiceCredentialsEnvironmentPostProcessor`, which is basically 1).

In any case, I think we all agree that a post-processor which parses the `VCAP_SERVICES` JSON to change the existing config properties is the right way to go, so that's a good outcome for this discussion!

**Comment by snicoll** [comment]
> Just to delegate JSON parsing to Spring Boot?

Of course. That works is done regardless of you asking for it or not so post-processing a standard map is much better than redo the parsing yourself IMO.

> use and EnvPP in order to change the properties you're using and let your autoconfig classes be CF agnostic

Sorry to hear that as I thought that's exactly what I've told you during our last meeting.
