### ISSUE TITLE
Make SpannerTemplate.executeQuery/executeRead public

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#525]
`SpannerTemplate.executeQuery` and `SpannerTemplate.executeRead` could be useful when querying tables that are not mapped to entities.

**Comment by balopat** [comment]
We should not do this as it exposes the Spanner Resultset. 
Even [`JdbcTemplate`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html) doesn't have this.

**Comment by balopat** [comment]
Maybe we could do similar `RowMapper` or a `Map` based solution.

**Comment by ChengyuanZhao** [comment]
After over a year of changes this actually got done incidentally. 

We now have 

```
public ResultSet executeQuery(Statement statement, SpannerQueryOptions options)
public long executeDmlStatement(Statement statement)
```

executeRead is still private, but its method signature is actually less useful than other public methods we have that accomplish the same thing but is cleaner

```
private ResultSet executeRead(String tableName, KeySet keys, Iterable<String> columns,
			SpannerReadOptions options)

public <T> T read(Class<T> entityClass, Key key)
public <T> T read(Class<T> entityClass, Key key, SpannerReadOptions options)
public <T> List<T> read(Class<T> entityClass, KeySet keys)
public <T> List<T> read(Class<T> entityClass, KeySet keys,
			SpannerReadOptions options)
```
