### ISSUE TITLE
Eliminate SpannerRepository

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#526]
`SpannerRepository`'s goal appears to be to expose `SpannerOperations`.
However, if a user needs `SpannerOperations`, they should autowire it from an application context.
If there is no other compelling reason to keep it, it should be removed.

**Comment by ChengyuanZhao** [comment]
I insist on keeping this. The other Spring Data projects have their own repositories that they inevitably start putting their storage-technology specific functionality in. If we get rid of this now it will be a pain to put it back in the future. @balopat what do you think

**Comment by joaoandremartins** [comment]
The Template pattern is independent from Spring Data.
As the issue mentions, the right way to get `SpannerOperations` should be to autowire it, not get it from the template.

The way I see it, it's harder to revert launching an interface that has to be rolled back in later version (i.e., breaking change).

**Comment by joaoandremartins** [comment]
As it turns out, it appears that other Spring Data projects follow the model of having their own repository implementation with vendor-specific functionality.
There appears to be some for Spanner as well, so it could make sense to leave this.
