### ISSUE TITLE
Allow ExecutorProvider to be passed in to PubSubTemplate

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#53]
In #50, some suggested polishing changes surfaced a bigger issue. We might want to either use the default `ExecutorProvider` (with 4 threads by default) or, instead, allow the user to specify their own `ExecutorProvider` implementation.

We should look into injecting the `ExecutorProvider` into the `PubSubTemplate` which, right now, isn't possible in SI, since `PubSubMessageHandler` uses `new PubSubTemplate()` instead of injecting it.

Another issue is that re-using the same `ExecutorProvider` does not guarantee that only one `Executor` is generated, thereby reducing the number of created threads, which was the motivation behind the reuse.

**Comment by meltsufin** [comment]
As mentioned in the comments on the PR #50. We should probably just create a `PublisherFactory` abstraction and make `PubSubTemplate` depend on it.

**Comment by joaoandremartins** [comment]
The same should probably also apply for the `Subscriber` in `PubSubInboundChannelAdapter`.

**Comment by artembilan** [comment]
The `PubsubTemplate` is based now on the `PublisherFactory`, where the `DefaultPublisherFactory` is supplied with the `ExecutorProvider`, so, I consider this issue as fixed.
(Can't find the commit, but fix is in the place any way...)

**Comment by joaoandremartins** [comment]
FTR the fix is #61 (GitHub doesn't appear to understand "Fixes #x, #y" notation)
