### ISSUE TITLE
GcpSpannerAutoConfiguration should expose SpannerTemplate

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#533]
Currently, it only autoconfigures a `SpannerOperations` bean. Instead, we can just autoconfigure the `spannerTemplate` bean.

**Comment by artembilan** [comment]
Why this doesn't work for you https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/spanner/GcpSpannerAutoConfiguration.java#L115-L122 ?

**Comment by meltsufin** [comment]
It works, but I have declare the field as `SpannerOperations` instead of `SpannerTemplate`.

**Comment by artembilan** [comment]
That's correct. It's better to rely on the interface instead of its implementation.
May do you mean that `@Bean` must return `SpannerTemplate` instead of its interface ?

**Comment by balopat** [comment]
We came to this conclusion based on other Spring template autoconfigs: 
e.g.: 
[JdbcTemplate](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jdbc/JdbcTemplateAutoConfiguration.java#L68)
[CassandraTemplate](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/cassandra/CassandraDataAutoConfiguration.java#L130)

**Comment by ChengyuanZhao** [comment]
@mp911de Hey Mark, I noticed you're an author on the Cassandra config file Balint linked above. Just wanted to ask why the choice  to use the Template vs the Operations being exposed as the bean. 

Thanks!

**Comment by mp911de** [comment]
There are two perspectives: Producer and consumer. 

* A consumer should inject the lowest-possible API (`…Operations`) to not require more than is really necessary. 
* Producer methods should declare the actual type they produce (sometimes there are requirements to expose a supertype/interface but that's more specific) to allow for the case you really want to get hold of the `…Template` object.

**Comment by meltsufin** [comment]
@artembilan Sorry, for my poor wording of the issue. :)
