### ISSUE TITLE
Spanner - Ability to ignore mapping properties and/or computed values

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#540]
Currently `@Column` requires name attribute. It can/should be inferred by the naming strategy if not present.

**Comment by balopat** [comment]
+1 
Some more relevant discussion on this PR for table name resolution too: 
https://github.com/spring-cloud/spring-cloud-gcp/pull/504#issuecomment-379162363

**Comment by meltsufin** [comment]
@Column is not required.

**Comment by saturnism** [comment]
On the other hand then, we need a way to ignore columns in the POJO. Those columns/getters could be computed values.

**Comment by meltsufin** [comment]
@ChengyuanZhao @balopat Please prioritize this because it seems pretty important.

**Comment by ChengyuanZhao** [comment]
https://github.com/spring-cloud/spring-cloud-gcp/pull/576

**Comment by ChengyuanZhao** [comment]
looks like this is a duplicate issue of #429

**Comment by ChengyuanZhao** [comment]
should this one be closed? that PR about the `@NotMapped` annotation is in.

**Comment by meltsufin** [comment]
Docs should be updates first, I think.

**Comment by balopat** [comment]
This can be closed now, the docs are in as well: https://github.com/spring-cloud/spring-cloud-gcp/pull/608
