### ISSUE TITLE
Use Pubsub instead of PubSub in identifiers

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#56]
Example: `PubsubTemplate` rather than `PubSubTemplate`.

**Comment by artembilan** [comment]
Why? What is the motivation?
Would be better to have some ground for the issue.

Thanks

**Comment by meltsufin** [comment]
Fair enough. The reason is that the Pub/Sub client library uses that convention, which in turn is derived from the [service definition](https://github.com/googleapis/googleapis/blob/cc6f9332e648a05b8504cd7b3c0cee3dd58648b2/google/pubsub/v1/pubsub.proto#L214) where the convention was established..

**Comment by Mistic92** [comment]
There is newer repo for google cloud libs but yes, they are using Pubsub not PubSub
https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-pubsub
