### ISSUE TITLE
configurability of SpannerOptions and SessionPoolOptions as properties

### ISSUE THREAD

**Issue by balopat** [spring-cloud/spring-cloud-gcp#591]
Expose the options as properties available on [`SpannerOptions`](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerOptions.java), it is very important to have a look at `SessionPoolOptions` in particular as large use cases will want fine tuneability on these knobs. 

Please discuss here first the details before jumping into implementation.

**Comment by ChengyuanZhao** [comment]
should this be M4?
