### ISSUE TITLE
Add support for Spring's declarative transaction management (@Transactional)

### ISSUE THREAD

**Issue by balopat** [spring-cloud/spring-cloud-gcp#592]
Add support for Spring's declarative transaction management ([@Transactional](https://docs.spring.io/spring/docs/4.2.x/spring-framework-reference/html/transaction.html#tx-decl-explained)) if possible to Spring Data Spanner.

**Comment by mp911de** [comment]
Here's an example for a [`MongoTransactionManager`](https://github.com/spring-projects/spring-data-mongodb/blob/issue/DATAMONGO-1920/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/MongoTransactionManager.java) (work in progress).

**Comment by ChengyuanZhao** [comment]
Spanner client lib does not provide a transaction object and explicit commit or rollback functions. The only way to run a transaction is via a callback. 

We are provided a transaction context that lives only for the duration of the callback function, and to make this work with the doBegin and doCommit functions of PlatformTransactionManager, I need to get that transaction-specific context to come out of that callback function.

One way I got to work with using CompleatableFuture objects to make the callback wait while the context is used outside of the callback.

Summary of how it works in my prototype:

- doBegin provides a reference to context to the callback and runs the call back async. it then waits for the callback to set the given reference to the transaction context
- the callback sets the context reference to the transaction context, and then waits for the doCommit to be called
- the context is given the user /business logic annotated with the Transactional annotation.
- doCommit releases the block on the callback, and the transaction then completes.

**Comment by ChengyuanZhao** [comment]
an alternative that didn't seem to pan out involves not keeping the callback function waiting, but instead only running it at doCommit time.  Instead of the context from the callback, I tried giving a fake wrapper context that accumulates actions done to it in the user /business logic and that fake wrapper context is then run inside the callback. 

the one main barrier to making that work is the context needs to return results , too. For example count() and read(); how would those work?

**Comment by ChengyuanZhao** [comment]
@mp911de 

Hi Mark, is there an example from spring-data-mongodb of injecting the entityManager-invokerhandler/factory-equivalent-for-mongo? I noticed for spring-data-jpa there is a class that custom injects the proxy entityManagers by detecting the PersistenctContext annotation. Is that how it's done in mongo too?

**Comment by mp911de** [comment]
For MongoDB, we use our own abstraction [`MongoDbFactory`](https://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/MongoDbFactory.html). That's typically either auto-wired or users can override injection points adding `@Qualifier("name-of-the-bean")` to specify which bean to inject.

**Comment by ChengyuanZhao** [comment]
Closing in favor of #845. the client lib now exposes more low level transaction functions. discussions taking advantage of the new functionality will be on the new issue.
