### ISSUE TITLE
Supporting Pageable and Sort in @Query annotations

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#601]
This appears in the JPA project as an example

**Comment by ChengyuanZhao** [comment]
The only thing that comes to mind is adding  "SORT BY a ASC/DESC LIMIT x OFFSET y" at the end of their queries. @balopat @meltsufin

**Comment by balopat** [comment]
I think that's fine. 
If the query has no LIMIT/ORDER already, then 
 - `Pageable` should be straightforward
 -  With `Sort` we have to make sure to sanitize the properties. 

If the query already has `LIMIT`/`ORDER BY` we have to decide on how to fail - maybe just add it in anyway and let it fail on the Spanner side?

**Comment by ChengyuanZhao** [comment]
If the user already has sort / limit / offset in his query at the base level (because he might have inner sub queries, too), then I think there still is a valid interpretation where he wants to further page or sort his query. 

For example, his query might have LIMIT 100000000 at the end of it, but his Pageable param wants pages of 50 items. That is a valid use case in my opinion.

As a result, I think we should prepend his query  `SELECT * FROM (` and then append `) SORT... LIMIT... OFFSET" 
@balopat

**Comment by balopat** [comment]
Agreed! Sounds good.
