### ISSUE TITLE
Logging - JSON Logged Trace ID needs to conform format: projects/PROJECT_ID/traces/128_BIT_TRACEID

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#625]
Currently the trace ID is outputted like this:
```
{"traceId":"58f6bbea713ab60e", ... }
```
It should be:
```
{"traceId":"projects/PROJECT_ID/[PREPENDED WITH 0]58f6bbea713ab60e",
```

**Comment by saturnism** [comment]
@joaoandremartins is there anyway we could extrapolate the current project ID that's already configured? Perhaps w/ `springProperty`?
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_environment_properties

**Comment by meltsufin** [comment]
@saturnism I wasn't aware of this format requirement. Is this to enable association with traces? Is this documented somewhere?

**Comment by joaoandremartins** [comment]
@saturnism where do you want to have access to the configured project ID?

Spring property could be a good option, but you should take into account that each service has a project ID override, e.g., for Pub/Sub, you'd need to check first `spring.cloud.gcp.pubsub.project-id`, then `spring.cloud.gcp.project-id`.

**Comment by meltsufin** [comment]
I kind of like the `springProperty` via the `Action`. Maybe we can give it try?

**Comment by saturnism** [comment]
I took a look at this; it's a lot more involved. I.e., the `SpringPropertyAction` is created by [LogbackLoggingSystem](https://github.com/spring-projects/spring-boot/blob/v2.0.1.RELEASE/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/logback/LogbackLoggingSystem.java), which is created by [LoggingSystem](https://github.com/spring-projects/spring-boot/blob/236b1bc4b634e06657f35829eb86ac996b36fed3/spring-boot-project/spring-boot/src/main/java/org/springframework/boot/logging/LoggingSystem.java) static initializer... We can't really hook into it.

**Comment by saturnism** [comment]
Also, the trace ID format is documented here: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry

**Comment by saturnism** [comment]
I think a compromise might be using `<springProperty/>` to try to grab `spring.cloud.gcp.project-id`. And if that's not set, override it w/ `DefaultGcpProjectIdProvider`.
