### ISSUE TITLE
Cloud SQL sample doesn't return values for PostgreSQL

### ISSUE THREAD

**Issue by balopat** [spring-cloud/spring-cloud-gcp#629]
I was experimenting today with both MySQL and PostgreSQL. The SQL sample works with MySQL, returns the rows from the database, but if I change the starter to `spring-cloud-gcp-starter-sql-postgresql`, it returns an empty list - potentially because there might be issues during insertion? Not sure, we should investigate.

**Comment by meltsufin** [comment]
This has been fixed by #765.
