### ISSUE TITLE
Sanitize PubsubMessage headers

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#63]
Currently, the SI-generated headers, like ID and timestamp, are being preserved on message conversion (Spring to PubsubMessage).

We should remove those messages on conversion, as well as any GcpHeaders, while at the same time, providing some means of preserving those headers if the users wants.

More details [here](https://github.com/spring-cloud/spring-cloud-gcp/pull/61#discussion_r124899136).

**Comment by joaoandremartins** [comment]
`id` and `timestamp` are the only two internal Spring Integration headers that I can make out.
Should we have a `KEEP_INTERNAL_HEADERS` header that, when set to false, excludes these headers?
Is there any point in doing this?
@artembilan @meltsufin wdyt?

**Comment by artembilan** [comment]
Well, actually in other Spring Integration places we use `HeaderMapper` pattern: https://github.com/spring-projects/spring-integration/blob/master/spring-integration-core/src/main/java/org/springframework/integration/mapping/HeaderMapper.java

In the Spring Integration AWS I did recently this: https://github.com/spring-projects/spring-integration-aws/blob/master/src/main/java/org/springframework/integration/aws/support/AbstractMessageAttributesHeaderMapper.java

Pay attention to a set of *headers do not map*:
```
private volatile String[] outboundHeaderNames = {
			"!" + MessageHeaders.ID,
			"!" + MessageHeaders.TIMESTAMP,
			"!" + AwsHeaders.MESSAGE_ID,
			"!" + AwsHeaders.QUEUE,
			"!" + AwsHeaders.TOPIC,
"*" };
```
You can apply similar technique here as well.
