### ISSUE TITLE
Sample for multiple GCP SQL configuration

### ISSUE THREAD

**Issue by bendol-i3** [spring-cloud/spring-cloud-gcp#635]
I am currently trying to get multiple SQL data source connectors set up with GCP. I haven't been able to find any samples on how this can be achieved.

Can someone provide a sample or perhaps point me in the right direction?

**Comment by bendol-i3** [comment]
Okay thanks for the advice. Will it be simple enough to check how the auto configuration sets up the `DataSource` and mimic that for multiple configurations?

**Comment by artembilan** [comment]
Yes, I think that can be considered as a one way to go. 
Here are all the classes you need to investigate: https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/sql

**Comment by bendol-i3** [comment]
Thanks a lot for taking the time to help! Will close this "issue"
