### ISSUE TITLE
Find out why provided JDBC URL does not work from within a CF instance

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#644]
Connecting to a Cloud SQL instance isn't working from a CF instance, both using our URL (e.g., `jdbc:mysql://google/...`) or the GCP service broker provided one (e.g., `jdbc:mysql://...`).

If we can't figure this out in time for RC1, we should probably roll back the SQL CF support PR.

**Comment by saturnism** [comment]
https://github.com/GoogleCloudPlatform/gcp-service-broker/pull/206
