### ISSUE TITLE
Disabling trace for local development

### ISSUE THREAD

**Issue by tylercoville** [spring-cloud/spring-cloud-gcp#657]
How can I disable GCP Credential lookup and trace for local development?

I tried setting `spring.cloud.gcp.trace.enabled` to false in both application.properties and bootstrap.properties and got the same result.

Currently getting this error:

> ERROR o.s.c.g.c.DefaultCredentialsProvider.<init> - No credentials were found.
> java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
>                 at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:119)
>                 at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:127)
>                 at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:100)
>                 at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:53)
>                 at org.springframework.cloud.gcp.core.DefaultCredentialsProvider.<init>(DefaultCredentialsProvider.java:110)

**Comment by joaoandremartins** [comment]
You can disable credential lookup by disabling auto-configuration altogether.
Alternatively, you may also provide your own `googleCredentials` bean, which will bypass creds discovery.

I will also say that that error line is not malign -- if you set credentials per service but not the core ones (i.e., `spring.cloud.gcp.credentials.location`), that error message is printed but your app will still work. There is only an issue if a service needs credentials and your app isn't providing them anywhere.

Hope this helps! Please reopen if you have further questions.

**Comment by meltsufin** [comment]
@tylercoville Trace auto-configuration is conditional on the `spring.cloud.gcp.trace.enabled` property. So, setting that to `false` should work.

However, `GcpContextAutoConfiguration` is not conditional on any properties. As Joao suggested, you can avoid the creation of the `DefaultCredentialsProvider` by providing your own dummy `CredentialsProvider` like
```java
	public CredentialsProvider googleCredentials() {
		return () -> null;
	}
```
Or, simply ignore the error in the log. It shouldn't actually break anything, if you are not connecting to any GCP services.
