### ISSUE TITLE
Datastore Persistent Entities, Properties, Mapping Context, Annotations

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#676]
- Classes are annotated with `@Entity(name = “kind_name”)`. This is because in Datastore documentation the “Kind” is analogous to a table in SQL, and an `entity` is analogous to a row in a table. 
Note that many different classes can be annotated with the same Kind name, because DS allows different schemas for entities of the same Kind. 

- The Spring Data `@Id` annotation is optional. If used on a property, then that property is used as the key in Datastore AND also stored as a field. 
If no properties are annotated with it, then DS will auto-generate an ID.

- Optional single property of type `Iterable<KeyValue<String, Object>>` can be annotated `@Ancestors`. 

- This property will not be stored as a field. It will be used as the ancestors of this entity, where the String component is that ancestor’s Kind, and the Object component is the specific key of that ancestor. 
POJO properties:
1. can be annotated `@Reference`, which means that POJO must also be of a type annotated with `@Kind`, and then the DS Key of that entity is stored in this field in DS. (the Key type is a data type that a field can have in DS).
2. can be annotated `@Embedded`, which means they will be stored as an embedded entity in DS. This is also a data type that a field can have in DS. Embedded entities do not need to have a Key or Kind, and are stored in their entirety in that field in DS.
3. Both of these also apply to Iterable properties where the inner type is a POJO, because DS can store any singular field type as elements of an array column type.

**Comment by artembilan** [comment]
@ChengyuanZhao ,

Please, consider to learn how to comment on GitHub: https://help.github.com/articles/basic-writing-and-formatting-syntax/#mentioning-people-and-teams

Right now you are mentioning too much people not related to the project :smile: 

I mean that all those annotations with the `@` symbol must be wrapped to the code: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by ChengyuanZhao** [comment]
Yes I am aware, so I fixed it right away. I copied and pasted this from a separate document where this wasn't an issue, so it was a momentary lapse.

**Comment by artembilan** [comment]
Well, the fix doesn't though: people have been notified already.
OK, never mind: let's hope it's not harmful :smile:

**Comment by ChengyuanZhao** [comment]
Yes, i hope they're used to this happening :) Perhaps it's the price of having a valuable general-meaning username.
