### ISSUE TITLE
Add publish(topic, payload) to PubSubOperations

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#686]
We should add a `publish(topic, payload)` convenience method to `PubSubOperations`.

Should we also add different flavours of payload, like `String`, `byte[]` and `ByteString`, or just `String`?

**Comment by ChengyuanZhao** [comment]
I vote for adding the methods for all 4 types. Personally if I were the user I would be trying to infer things about why the other 3 types aren't available if I only saw the String one.
