### ISSUE TITLE
Add support for Sort.Order.ignoreCase()

### ISSUE THREAD

**Issue by gustavo-gm-globant** [spring-cloud/spring-cloud-gcp#691]
Currently, when the sorting options are being validated and the `ORDER BY` clause is being constructed in the `SpannerTemplate ` class, the` Sort.Order.ignoreCase() ` flag is not being consulted, therefore, the `ORDER BY` clause is not quite correct and the returned data set is not sorted as expected.

These are reference links in the spring data repo about this issue:

- [Jira ticket in the SpringData project](https://jira.spring.io/browse/DATAJPA-296)
- [SpringData commit 1](https://github.com/kraymondksc/spring-data-jpa/commit/c3adce0bd36799d3754a5f4c61aee64982abd7e0)
- [SpringData commit 2](https://github.com/spring-projects/spring-data-jpa/commit/4c65ad1df6ea281036b5d35c25473a57f0bc3ac0)

**Comment by ChengyuanZhao** [comment]
Thank you for spotting this issue ! looking into it.
