### ISSUE TITLE
Clean up unused classes

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#70]
There are a few packages that aren't used currently and could cause user confusion.
org.springframework.cloud.gcp.pubsub.converters.* (except SimpleMessageConverter)
org.springframework.cloud.gcp.pubsub.converters.support
org.springframework.cloud.gcp.pubsub.*

We should remove them before launching anything to the public.

They cover areas that we already have issues for: (a)sync mode (#51) and topic/message conversion (#54). We should wait until those issues are worked on in order to provide those features. Until then, it's better to remove the classes so they don't confuse users.

@artembilan wdyt?

**Comment by artembilan** [comment]
I don't think so that it is a time to remove something.
Let's come back to this when we will be on RC at least!
Any Milestone assumes some breaking changes anyway.

**Comment by joaoandremartins** [comment]
We're really close to an alpha release -- [only three issues left to resolve](https://github.com/spring-cloud/spring-cloud-gcp/issues?q=is%3Aopen+is%3Aissue+milestone%3Asi-channel-adapters-alpha), which are already half-resolved.

We would like to launch an alpha version of the channel adapters + storage resource abstraction sooner rather than later. Feel free to add anything to the milestone if you think it's a blocker.

I don't think we should release the alpha with those unused classes, but I also don't think that those issues are alpha blockers, hence the suggestion to remove them for the time being (and possibly add them again later).

**Comment by artembilan** [comment]
OK. I can't answer to this question. I don't manage this project.
I only review the code for quality and share some ideas if I can.

All the management steps our outside of my responsibility.

@markfisher , @viniciusccarvalho , who manages this project?
Who makes decision what and when should be released?

Thanks

**Comment by meltsufin** [comment]
I think the release plans is something we can discuss in the next meeting.

The question here is whether it's OK to remove these classes for now. We can always bring them back if the need arises.

**Comment by viniciusccarvalho** [comment]
Those classes can all be removed. It was part of a pilot on getting a reactive support for pubsub binder. 

After our discussions with the pubsub team, I'm not really convinced of a pubsub binder at all ATM. Making more sense as a SI and Source/Sink for stream right now.

Until we revisit the binder API for 2.0, I'd say there's little benefit on trying to get a pubsub binder

**Comment by joaoandremartins** [comment]
I took the liberty to open a PR to address this issue, to be merged when we think it's the right time.

I would personally like to see these classes removed sooner rather than later so that snapshot users don't get sidetracked by classes that don't work. The [getting started guide](https://github.com/spring-guides/getting-started-guides/pull/47) should be almost ready and snapshots are now being published so, in practice, we could start seeing some users now.
