### ISSUE TITLE
Shade non-GA Trace dependencies

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#700]
Related to https://github.com/openzipkin/zipkin-gcp/issues/79

**Comment by artembilan** [comment]
> Are non-GA dependencies in starters considered GA blocker?

Correct. Or you just don't GA that starter.
I'm fully against the idea to pursue GA if you don't ensure GA for your dependencies...

How you can say that your project is stable, if it is based on non-stable API? 

We had that discussion not one time and I won't mind to have a meeting again.
Let's also invite some other people from my team you would like to discuss this with!

**Comment by adriancole** [comment]
why is it a problem for autoconfigure to depend on renamed internal
packages? first i have heard of such a thing..

**Comment by adriancole** [comment]
for example even autoconfiguration types can be package private to prevent
people from linking to it.

ex
https://github.com/openzipkin/zipkin/blob/master/zipkin-autoconfigure/collector-kafka10/src/main/java/zipkin/autoconfigure/collector/kafka10/ZipkinKafka10CollectorAutoConfiguration.java

really curious why in this repo there is such a constraint. seems we should
guard that property values are reliable but beyond that, autoconfiguration
is an implementation detail.

**Comment by adriancole** [comment]
PS I think we don't need to worry so much. This functionality is dependent on sleuth 2.0 which isn't final for another 2 weeks. Sleuth always releases last even if everything is on time.

https://github.com/spring-cloud/spring-cloud-release/milestones

So, discussing the GA status of something that's dependent on something not GA seems a bit of a waste of time especially as it limits the amount of time I have to help get things together.

Let's focus on code vs meta-discussion? If anyone wants to help please find me on gitter.
https://gitter.im/openzipkin/zipkin

**Comment by meltsufin** [comment]
@adriancole Sorry for the confusion as I think I wasn't very clear.

Our concern as stated in the linked issue is around `zipkin-sender-stackdriver`, not Sleuth 2.0. It looks like we couldn't expect `zipkin-sender-stackdriver` to be GA for quiet a while and should instead shade it as its simply an implementation detail as far as Spring Cloud GCP is concerned.

My question was regarding how you suggest we shade it. We have the `autoconfigure` module that has `zipkin-sender-stackdriver` as an optional dependency, and it auto-configures some beans based on the presence of classes from `zipkin-sender-stackdriver`. If we repackage `zipkin-sender-stackdriver`, the `autoconfigure` module will instead have to depend on a module that contains the repackaged (i.e. `zipkin2.reporter.stackdriver.shaded`) classes coming from some other module. The problem is where should these `zipkin2.reporter.stackdriver.shaded` classes be? Which module/jar? The natural place seems to be the starter (`spring-cloud-gcp-starter-trace`), where `zipkin-sender-stackdriver` is a required dependency. However, then the `spring-cloud-gcp-autoconfigure` would have to depend on `spring-cloud-gcp-starter-trace` which would be a circular dependency.

The alternative is to just shade `zipkin-sender-stackdriver` in its own module. We can have a module in our project called `spring-cloud-gcp-zipkin-sender-stackdriver` or something like that, and have both the starter and the autconfigure module depend on that. Is that what you are suggesting? Thanks!

**Comment by adriancole** [comment]
>
> We can't have these classes in the autoconfigure module because they will
> cause the autocnfiguration to be always triggered as it's conditional on
> StackdriverSender being present.
>
I didn't think this would be conditional only on classpath because
stackdriver doesn't work unless other things are present for example
authorization input right? Interesting if not..

> Why would it be possible to remove shading by end of next week? Would
> zipkin-sender-stackdriver be GA by then?
>
Yes, we are working on it. @anuraaga is already using it in prod and from
an api stability POV (which is the main concern), there's very little api,
so not a big risk.

If meanwhile you can create a second condition besides classpath to test
the code from here, that would be good.

**Comment by meltsufin** [comment]
Thanks for the clarification! It's great to hear that `zipkin-sender-stackdriver` is moving quickly towards GA and there are users!
I think we will just wait for that to happen and hold off on the shading.

Regarding the autoconfiguration, it's already conditional on `spring.cloud.gcp.trace.enabled` in addition to `StackdriverSender.class`, but it's on by default. I think it's fine.
