### ISSUE TITLE
Add extractor for x-cloud-trace-context header

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#703]
After #695, tracing will support the `X-B3-TraceId` header. To work in Google Cloud Platform, we should also add support for the `x-cloud-trace-context` header.

The suggestion is to modify the existing [`B3Propagation`](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/B3Propagation.java) extractor to also contemplate the `x-cloud-trace-context` header. However, since there will be no span IDs or parent trace IDs at initial incoming request time, we must still decide on what to do [there](https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/propagation/B3Propagation.java#L134).

As reference, here is [another extractor](https://github.com/openzipkin/brave/tree/master/propagation/aws) implementation that takes full control of the propagation. I don't think we want to do that, it will probably do just to adapt the current `B3Propagation`.

**Comment by adriancole** [comment]
I wouldn't recommend editing the B3Propagation, rather make one like AWS, possibly contributing a policy thing which is a dispatching PropagationFactory that prefers one or another. Composition over inheritance basically...

PS there's also this, which is only loosely related https://github.com/openzipkin/brave/pull/688

**Comment by saturnism** [comment]
Composition here is good. The Injector can probably just be the existing B3 Injector, while the Extractor can be a composite of a x-cloud-trace-context extractor + existing B3 Extractor?

**Comment by adriancole** [comment]
right I was thinking similarly as usually it is incoming which you'd need
more flexibility (read tolerant). A composing Propagation thing could be
more flexible than things we have now in this regard.

**Comment by joaoandremartins** [comment]
My issue with the AWS propagation is that I don't really understand most of what's going on there.
There seems to be a bunch of low level optimization that I have no context about, so it's hard for me to make any progress, hard to test if it's correct and easy to make mistakes.

I thought `B3Propagation` is a lot simpler and implementing a similar propagation on our end could be a good starting point that we could incrementally improve.

Let me crank out something first and we can go on from there.
