### ISSUE TITLE
Run samples on CI

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#705]
Currently we do not automatically check if samples work, so we should have CI verify that everything is in working order

**Comment by meltsufin** [comment]
It's a great idea, and I think this will all serve the goals of #171.

**Comment by meltsufin** [comment]
One thing to consider here is adding `@SpringBootTest` [tests](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications) to samples.

**Comment by dzou** [comment]
At this point in time, all samples have tests covering them so I will close this issue.
