### ISSUE TITLE
Pageable sort parameter

### ISSUE THREAD

**Issue by daniel-bonelli-globant** [spring-cloud/spring-cloud-gcp#706]
Hi,
Was the intended purpose of sort to use actual db column names?
For example:
I call this repository in spanner (which extends SpannerRepository<Tenant, Key>)
tenantRepository.findAll(pageable) with pageable being:
number:0
size: 20
sort: tenantName ASC
if I use tenantName it does not work and throws: com.google.cloud.spanner.SpannerException: INVALID_ARGUMENT: Unrecognized name: tenantName; Did you mean tenant_name? [at 1:47]
SELECT * FROM (SELECT * FROM tenant) ORDER BY tenantName ASC LIMIT 20 OFFSET 0
if i use tenant_name it does work.
is that a correct behaviour?
thx

**Comment by ChengyuanZhao** [comment]
When specifying the sort like `Sort.by(Order.asc("column_name"))` we think it makes most sense that since you are providing the string column name to sort on that you should provide the Spanner table's column name, and NOT the string name of the java property. 

In your situation, is "tenantName" the name of the java property, while "tenant_name" is the name of the column in the Spanner table?

**Comment by meltsufin** [comment]
> When specifying the sort like Sort.by(Order.asc("column_name")) we think it makes most sense that since you are providing the string column name to sort on that you should provide the Spanner table's column name, and NOT the string name of the java property.

@ChengyuanZhao I'm not sure about this because everywhere in the Spring Data docs that parameter is  calls "property", not "column", and I'm pretty sure if you're using Spring Data JPA, you'd be passing in the mapped property name, not the column name. @mp911de WDYT?

**Comment by ChengyuanZhao** [comment]
I see, I will make the change according to Mark's description and make a PR.

**Comment by ChengyuanZhao** [comment]
Change merged now. It now first checks if the given name is that of a java property. If not, then it uses the given name directly as the column name.

**Comment by daniel-bonelli-globant** [comment]
Thx @ChengyuanZhao 
Great job
