### ISSUE TITLE
Link to sample apps in the refdoc

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#715]

**Comment by dmitry-s** [comment]
We can link to the correct version of samples passing current git version to asciidoctor plugin as cli argument and using that attribute in sample links

Something like that:
`mvn generate-resources -Dasciidoctor.attributes="git_version=$VERSION"`

see https://github.com/asciidoctor/asciidoctor-maven-plugin

**Comment by meltsufin** [comment]
@artembilan @sobychacko Would it be possible for you to modify the Jenkins config to make this work for our refdoc?

**Comment by artembilan** [comment]
Give me, please, the valid command and I'll add it into our config there.
Right now it looks like:
```
./mvnw clean deploy -U generate-resources -Dasciidoctor.attributes=git_version=
```

I assume that `$VERSION` doesn't resolve properly. So, what do you expect there for this variable?

Thanks

**Comment by dmitry-s** [comment]
We would like $VERSION to have current commit's hash
VERSION=$(git rev-parse HEAD)

It will be used to construct links to the version of samples that correspond to current commit, so we can keep it in sync with docs

**Comment by dmitry-s** [comment]
That's how we can use the hash in the links:
https://github.com/spring-cloud/spring-cloud-gcp/tree/{git_version}/spring-cloud-gcp-samples

**Comment by artembilan** [comment]
@dmitry-s ,

Thanks for coming back here, but sorry: that's not clear to me what and how should I do on the CI server.
Is it really possible what you are asking?

Thanks for understanding

**Comment by artembilan** [comment]
OK.

I did it like this:
```
./mvnw clean deploy -U generate-resources -Dasciidoctor.attributes="git_version=$GIT_COMMIT"
```

The current build shows me this resolution:
```
./mvnw clean deploy -U generate-resources -Dasciidoctor.attributes=git_version=465ebfe3ff8feeb489546f7c6f1cb35482cd7f78
```

Not sure if that is what you expect, but at least your URL pattern works well with that. From here it sounds like we show samples against the latest commit in master.

Does it make sense ?

**Comment by dmitry-s** [comment]
@artembilan 
That looks great, thanks!

**Comment by meltsufin** [comment]
Do you need escaped quotes around `git_version=465ebfe3ff8feeb489546f7c6f1cb35482cd7f78`?

**Comment by dmitry-s** [comment]
I think that's not required, but let me double check.

**Comment by dmitry-s** [comment]
The quotes are not needed.

**Comment by meltsufin** [comment]
@artembilan Can you try adding this to our Jenkins config? Thanks!

**Comment by meltsufin** [comment]
Never mind, I guess it's already there.

**Comment by artembilan** [comment]
Right, it there and I'm waiting for you to confirm and I guess then it's issue id ready to be closed.

**Comment by meltsufin** [comment]
We need to keep the issue open until Dmitry puts in the links to the refdoc that take advantage of this change.

**Comment by dmitry-s** [comment]
@artembilan it doesn't work for some reason. 

It works fine if I run it locally like this:
```
VERSION=abc
mvn generate-resources -P full  -Dasciidoctor.attributes=git_version=$VERSION
```

I can see all the links are good:
```
grep abc/spring-cloud-gcp-samples spring-cloud-gcp-docs/target/generated-docs/index.xml
```

`https://github.com/spring-cloud/spring-cloud-gcp/tree/abc/spring-cloud-gcp-samples/spring-cloud-gcp-vision-api-sample`



But in the published doc https://docs.spring.io/spring-cloud-gcp/docs/1.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#_getting_started it looks like that:
`
https://github.com/spring-cloud/spring-cloud-gcp/tree/%7Bgit_version%7D/spring-cloud-gcp-samples/spring-cloud-gcp-vision-api-sample
`

**Comment by artembilan** [comment]
Well, as I said before: give me, please, the proper Maven command and I'll place it into the Jenkins CI plan. I do this blind way: I just don't understand what you would like to achieve.

I can add that `-P full` there as well, but then I need to know what and where to search to determine the difference. 

Thanks

**Comment by dmitry-s** [comment]
I wonder, how does it even works without `-P full`?It is only enabled for this profile (see https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-docs/pom.xml )

Anyway, what we actually need is to add this argument to the command that is currently used for docs generation:
` -Dasciidoctor.attributes=git_version=$(git rev-parse HEAD)`

**Comment by artembilan** [comment]
@dmitry-s ,

Would you mind to check now this: https://docs.spring.io/spring-cloud-gcp/docs/1.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#_code_samples ?

With the proper browser cache clean up, please 😃

**Comment by dmitry-s** [comment]
Now it looks good. Thanks!

**Comment by artembilan** [comment]
Fixed as discussed here.
