### ISSUE TITLE
Remove `google-api-client` version.

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#718]
#716 set the version of `google-api-client` internally as `1.23.0`.
Ideally, we wouldn't have had to set any version and our Google libraries would just use the version from `dependencyManagement`.

1) Ask the Cloud SQL sockets factory team to update the version of `com.google.apis:google-api-services-sqladmin` to `v1beta4-rev26-1.23.0` in `com.google.cloud.sql:postgres-socket-factory` and `com.google.cloud.sql:mysql-socket-factory`,
2) Have them, as well as `com.google.apis:google-api-services-sqladmin`, start getting dependency versions from `dependencyManagement`.

**Comment by meltsufin** [comment]
@patflynn FYI as it relates to the diamond dependency issues.

**Comment by patflynn** [comment]
thanks @meltsufin.

Have you filed any bugs related to this with library authors?

**Comment by meltsufin** [comment]
@joaoandremartins ?

**Comment by joaoandremartins** [comment]
It isn't clear if `com.google.apis:google-api-services-sqladmin` has any GitHub repo.
Making the sockets factory change is trivial, I'll submit a PR some time today.

**Comment by joaoandremartins** [comment]
https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/pull/76 will allow us to not set the version of `google-api-client` on our side (provide a `1.24.0` one isn't released in the meantime and things break again...)
