### ISSUE TITLE
Upgrade GoogleStorageResource to WritableResource

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#72]

**Comment by artembilan** [comment]
??? Can we have more context, please?
What is the goal you pursue to do this?

Thanks

**Comment by meltsufin** [comment]
@artembilan The idea is to allow using Spring's Resource Abstraction to write to GCS.
So, something like this would be supported.

```
@Value("gs://path-to/some-file.txt")
private Resource gcsResource;

void write() {
  try (OutputStream os = ((WritableResource) gcsResource).getOutputStream()) {
    os.write("file contents".getBytes());
  }
}
```

Ideally, we would avoid the cast from `Resource` to `WritableResource`, but that's currently not supported. See https://jira.spring.io/browse/SPR-10656.
