### ISSUE TITLE
Caused by: java.lang.ClassCastException: org.springframework.web.context.support.ServletContextResource cannot be cast to org.springframework.core.io.WritableResource

### ISSUE THREAD

**Issue by sayi65** [spring-cloud/spring-cloud-gcp#734]
I referred this URL:
https://docs.spring.io/spring-cloud-gcp/docs/1.0.0.M3/reference/htmlsingle/#_google_cloud_storage

#254 has same error

**code:**
```java
                   String bucket = "gs://BUCKET-NAME/";

                   filename = UUID.randomUUID().toString() + ".jpg";

                   WritableResource gcs = (WritableResource)
                           context.getResource(bucket + "/" + filename);

                   try (OutputStream os = gcs.getOutputStream()) {
                       os.write(profile.getAvatar().getBytes());
                   } catch (IOException e) {
                       e.printStackTrace();
                   }

```

application.properties
```
spring.cloud.gcp.project-id=PROJECT-ID
spring.cloud.gcp.credentials.location=file://*.json
spring.cloud.gcp.storage.credentials.scopes=https://www.googleapis.com/auth/devstorage.read_write

```

build.gradle
```
dependencies {
    compile 'org.springframework.cloud:spring-cloud-gcp:1.0.0.M3'
}repositories {
    maven {
        url 'https://repo.spring.io/libs-milestone'
    }
}
```

ERROR:
`java.lang.ClassCastException: org.springframework.web.context.support.ServletContextResource cannot be cast to org.springframework.core.io.WritableResource`

**Comment by meltsufin** [comment]
@sayi65 Thank you for the issue submission!
We have a [sample app](https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-storage-resource-sample) that is doing something very similar and does not encounter this error.
We can't debug this further unless with can reproduce the issue. Can you please start with our sample, and see it how needs to be modified to cause this error?

**Comment by ChengyuanZhao** [comment]
It looks like you're adding an extra slash because the bucket string already has one at the end. (but then again you have a placeholder "BUCKET-NAME" bucket name there, so i don't know if your actual  code has this extra slash also)

**Comment by sayi65** [comment]
@ChengyuanZhao 
thank you for your comment.
i will delete the slash.

**Comment by orhan-swe** [comment]
@sayi65 Did you ever manage to resolve the issue?

**Comment by meltsufin** [comment]
@orhan-swe Are you able to reproduce the issue? If so, can you share some code that we can try?

**Comment by orhan-swe** [comment]
Actually I am getting another error so I do not think this is relevant anymore. If I do find it relevant I will post my findings here later.
