### ISSUE TITLE
Replace SI adapters' MessageConverters by Inbound/OutboundMessageMapper

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#753]
The current `MessageConverter` implementations do the opposite of what we need in the adapters.

For example, `MappingJackson2MessageConverter` expects a `String` or `byte[]` already representing a JSON object and turns them into the JSON's original type, whereas we want to turn an object into its `String` or `byte[]` representation to go on the wire.

`InboundMessageMapper` and `OutboundMessageMapper` sound like better interfaces. For example, `JsonOutboundMessageMapper` contains the following method, which sounds just like what we need:

```
    public String fromMessage(Message<?> message) throws Exception {
        return this.jsonObjectMapper.toJson(this.shouldExtractPayload ? message.getPayload() : message);
    }
```

**Comment by meltsufin** [comment]
Obsolete.
