### ISSUE TITLE
Remove all of the options for the TraceIdExtractor for logging

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#761]
These extractors are now only relevant if someone is not using Sleuth but wants to have log grouping by trace id. In this case, we should only use the `XCLOUD` option because others simply don't make sense without Sleuth/Zipkin.

@saturnism FYI

**Comment by ChengyuanZhao** [comment]
This means we can remove the composite and zipkin trace id extractors, correct?

**Comment by meltsufin** [comment]
Yes.
