### ISSUE TITLE
Add Webflux WebFilter for Logging trace ID extraction

### ISSUE THREAD

**Issue by dan-j** [spring-cloud/spring-cloud-gcp#766]
Currently the `StackdriverLoggingAutoConfiguration` class is dependent on a web-mvc application by importing a `WebMvcConfigurer` implementation to add the `TraceIdLoggingWebMvcInterceptor` as an mvc-style interceptor.

It would be ideal if this auto-configuration was also supported in webflux environments.

**Comment by artembilan** [comment]
Looks like for this purpose we have to implement similar functionality via:
```
/**
 * Contract for interception-style, chained processing of Web requests that may
 * be used to implement cross-cutting, application-agnostic requirements such
 * as security, timeouts, and others.
 *
 * @author Rossen Stoyanchev
 * @since 5.0
 */
public interface WebFilter {
```

**Comment by meltsufin** [comment]
@dan-j Thanks for the issue submission. Can you share how you're looking to use Stackdriver Logging in your app? Are you looking for log grouping by request? Are you using Stackdriver Trace as well?

**Comment by dan-j** [comment]
I was actually just looking at configuring slf4j/logback to output to StackDriver for now, and after submitting this issue and looking at what I needed to do to make this work for webflux, realised that it's not really doing what I need. That being said, I'd say it's still a valid issue.

I've followed the instructions here https://cloud.google.com/logging/docs/setup/java for configuring the appender manually via a logback.xml configuration file and using this blog https://simonbasle.github.io/2018/02/contextual-logging-with-reactor-context-and-mdc/ as a basis for logging context-based information.

I've actually just disabled StackDriver Trace because I've ran into an issue with it being enabled in conjunction with pubsub. Not managed to figure out the cause of that issue yet but will create an issue if I get time to figure out whether it's my fault or a library bug.

**Comment by meltsufin** [comment]
The `WebMvcConfigurer` is really not required to use our support for Stackdriver Logging. You can use our Logback configuration files to setup logging via JSON on console or direct API calls to Stackdriver. See [refdoc](https://docs.spring.io/spring-cloud-gcp/docs/1.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#_log_via_api).

**Comment by dan-j** [comment]
Ooooooo, that's amazing. I wasn't aware of `StackdriverJsonLayout`, even attaching MDC entries too! 

👍

**Comment by artembilan** [comment]
I think we need slightly to change this issue to the `traceId` subject, since it really doesn't looks like we need to worry about that if we are not interested in the tracing, but just logging.

**Comment by dan-j** [comment]
Agreed, I created the issue with different intentions but as I said, if there's a feature supporting mvc then there should also be support for webflux.

I don't actually know what the auto configuration this issue references is doing, I just saw the name `StackdriverLoggingAutoConfiguration` and got issue-happy.

**Comment by dan-j** [comment]
Can I make a suggestion to add `@ConditionalOnWebApplication` on the auto configuration classes too? At the moment I have to manually exclude the auto configuration.

**Comment by artembilan** [comment]
@dan-j ,

I think your last comment is really valid concern.
And all those WEB-based auto-configuration really must be conditional like you mention.

Thank you for the pointer!

**Comment by meltsufin** [comment]
@artembilan The auto-configuration is already conditional on `HandlerInterceptorAdapter.class` which is a class in `spring-webmvc`. Is that not enough?
@dan-j What kind issue are you facing now if you don't exclude the auto-configuration?

**Comment by meltsufin** [comment]
Note that `@ConditionalOnWebApplication` has been resolved in #779.

**Comment by meltsufin** [comment]
Doesn't Sleuth take care of this? We rely on SL4J MDC when that's available rather than the `ThreadLocal`.

**Comment by artembilan** [comment]
Yeah... The `LogbackMDCAdapter` is still based on the `ThreadLocal`:
```
final ThreadLocal<Map<String, String>> copyOnThreadLocal = new ThreadLocal<Map<String, String>>();
```

Let's really take a look into Sleuth to determine what the do in regards Reactive Streams and population to the `ThreadLocal` to make it available for the downstream logging!

Here is some info to study: https://simonbasle.github.io/2018/02/contextual-logging-with-reactor-context-and-mdc/

**Comment by meltsufin** [comment]
@marcingrzejszczak Do you have any suggestions for this?

**Comment by michael-barker** [comment]
Since there's no reactive MDC at this point, my initial though would be to provide a utility function that could be used with Reactor's `transform`.  This because even nicer with Kotlin extension functions.  Something like this.

```kotlin
// Example of how the utility function would be consumed
class ConsumerExample {

    private val logger = LoggerFactory.getLogger(ConsumerExample::class.java)

    fun fluxExample(): Flux<String> {
        return Flux.just("foo", "bar")
            .transform(logFlux { signal ->
                if (signal.isOnError) {
                    logger.error("Uh Oh!", signal.throwable)
                }
            })
    }

    fun monoExample(): Mono<String> {
        return "foo".toMono()
            .transform(logMono { signal ->
                if (signal.isOnError) {
                    logger.error("Uh Oh!", signal.throwable)
                }
            })
    }

    fun fluxExtension(): Flux<String> {
        return Flux.just("foo", "bar")
            .log { signal ->
                if (signal.isOnError) {
                    logger.error("Uh Oh!", signal.throwable)
                }
            }
    }

    fun monoExtension(): Mono<String> {
        return "foo".toMono()
            .log { signal ->
                if (signal.isOnError) {
                    logger.error("Uh Oh!", signal.throwable)
                }
            }
    }
}

// Provided utility functions and extension methods
fun <T> logFlux(consumer: (Signal<T>) -> Unit): (Flux<T>) -> Flux<T> {
    return { flux ->
        flux.doOnEach { consumeWithTraceId<T>(it, consumer) }
    }
}

fun <T> logMono(consumer: (Signal<T>) -> Unit): (Mono<T>) -> Mono<T> {
    return { mono ->
        mono.doOnEach { consumeWithTraceId<T>(it, consumer) }
    }
}

fun <T> Flux<T>.log(consumer: (Signal<T>) -> Unit): Flux<T> = this.transform(logFlux(consumer))

fun <T> Mono<T>.log(consumer: (Signal<T>) -> Unit): Mono<T> = this.transform(logMono(consumer))

private fun <T> consumeWithTraceId(signal: Signal<T>, consumer: (Signal<T>) -> Unit) {
    val traceId = signal.context.getOrDefault<String>("X-B3-TraceId", null)
    MDC.putCloseable("X-B3-TraceId", traceId).use {
        consumer(signal)
    }
}
```

**Comment by marcingrzejszczak** [comment]
We already support mdc and reactor integrationin Sleuth.

**Comment by michael-barker** [comment]
Although Sleuth has Reactor integration it adds the span to the Reactor context where the key is `Span.class` and the value is a `Span`.  Would Spring Cloud GCP Logging then require a dependency on Sleuth?

**Comment by meltsufin** [comment]
In the `TraceIdExtractor`, we currently have 
```java
String traceId = org.slf4j.MDC.get(StackdriverTraceConstants.MDC_FIELD_TRACE_ID);
```
for integrating with MDC. Are you saying we should check some other context as well?

**Comment by michael-barker** [comment]
@meltsufin Something has to put the value in MDC.  This is easy for WebMVC since the `ThreadLocal` can be used and we can just pull it back out in the `TraceIdExtractor`.  The issue with Reactor is that we can't use a `ThreadLocal` so we have to put the value in MDC temporarily at the point something is being logged.  The `TraceIdExtractor` could still look for the same key in MDC but the value has to be put into MDC somehow.  I think that's where some sort of utility function would be nice so that the consumer doesn't have to worry about or know how to put the trace ID into MDC.

**Comment by meltsufin** [comment]
If I understood correctly, Sleuth already does exactly this. MDC and its propagation in reactive use-cases is not a problem specific to this project. I would expect it to be solved in Sleuth like @marcingrzejszczak seemed to imply. We are just piggy-backing on the MDC mechanism when Sleuth is used.

**Comment by marcingrzejszczak** [comment]
Correct, we already set things for you in MDC. I'm a little but confused about what you're trying to achieve here, since Sleuth does all the work for you.

**Comment by michael-barker** [comment]
The value can't be put into MDC ahead of time for a reactive app. When set it's only set on the current thread but we don't know which thread on which something will be logged. As mentioned in the post that @artembilan linked, the value needs to he set in MDC immediately before the log statement and then removed immediately afterwards. Since MDC has no integration with reactive streams, the user  has to do this manually at every point something is logged otherwise logs either won't have a trace ID or the wrong trace ID.

**Comment by marcingrzejszczak** [comment]
Exactly, that's the place. Brute force way of passing the trace info around :)

**Comment by meltsufin** [comment]
Any special configuration needed to turn this on? Otherwise, I think we can close this. Thanks to everyone for chiming in and asking the question.

**Comment by davinkevin** [comment]
Following your discussion, I thought doing this will allow to have access in the logger part, in the `MDC` to the value `Foo`. But in my case, it only has those coming from Spring-Boot-GCP.

```kotlin
    @PostMapping(consumes = ["application/json"])
    @ResponseStatus(HttpStatus.OK)
    fun receiveMessage() h: String): Mono<Unit> {
           return Mono.just(1)
                .doOnSubscribe { log.info("A message on subscribe 👍") }
                .subscriberContext { it.put("Foo", "Bar") }
                .doOnTerminate { log.info("This is a termination message") }
    }
```

![image](https://user-images.githubusercontent.com/1970922/52576740-012c7500-2e21-11e9-8664-1edc6fdca50f.png)

This endpoint was used from [here](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/logging/StackdriverJsonLayout.java#L155)

Do you have any idea how to "transfer" data from the context to the `MDC` to be able to use them inside a logger like the `StackdriverJsonLayout`

**Comment by meltsufin** [comment]
@davinkevin This sounds more like a general WebFlux + Logback MDC question, or do you think Spring Cloud GCP is interfering somehow with the context transfer? You might want to ask this question in the larger Spring Boot community.

**Comment by davinkevin** [comment]
Yeah, you are right, but I thought this discussion leads to a solution to my problem. The spring GCP part didn't interfere in my question. 

I will try to find a place to ask this 😉but I thinks this a very wide subject not already handle in the `reactive` world, in Java...
