### ISSUE TITLE
Update refdoc to reflect that Cloud Configurator support is Beta/Preview

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#768]
The [Runtime Configurator](https://cloud.google.com/deployment-manager/runtime-configurator/) is in Beta. So, it can't be part of the RELEASE.

**Comment by ChengyuanZhao** [comment]
I added the awaiting label as with the spanner module for the GA branch to be created.

**Comment by ChengyuanZhao** [comment]
It has been removed from the 1.0.x branch, and its ref doc has been updated in the master branch.
