### ISSUE TITLE
integration-storage-sample - fix don't try transferring the same file more than once

### ISSUE THREAD

**Issue by dmitry-s** [spring-cloud/spring-cloud-gcp#777]
I followed the instructions from the integration-storage-sample and seeing this error continually appearing:

```
The remote file 'Blob{bucket=test-test3, name=file1, generation=1529694509798668, size=4, 
content-type=application/octet-stream, metadata=null}' has not been transferred to the existing local file
```

Looks like the file is delivered to the local fs, and then for some reason, the app tries to re-write it.
The output bucket is filled with copies of the file.

**Comment by meltsufin** [comment]
I'm not sure if it's an issue with the sample or the actual integration. We need to investigate to see if it's a blocker for M4.

**Comment by artembilan** [comment]
Via `FileListFilter`: https://docs.spring.io/spring-integration/docs/5.0.6.RELEASE/reference/html/files.html#file-reading.

The problem that we not always have control over the file system so we might be just not able to rename already polled files.

For your sample the existing `GcsPersistentAcceptOnceFileListFilter` should be sufficient, although I’m curious why it isn’t use by default...

**Comment by meltsufin** [comment]
Thanks for the suggestion. This seems to work. How would we use it by default? Where would we wire it up? Is it done in other projects?

**Comment by artembilan** [comment]
Wait. Something is wrong.
Please, take a look into SI FTP support:
```
public FtpInboundFileSynchronizer(SessionFactory<FTPFile> sessionFactory) {
		super(sessionFactory);
		doSetRemoteDirectoryExpression(new LiteralExpression(null));
		doSetFilter(new FtpPersistentAcceptOnceFileListFilter(new SimpleMetadataStore(), "ftpMessageSource"));
}
```

something like that has to be implemented here in the `GcsInboundFileSynchronizingMessageSource` .

The `GcsStreamingMessageSource` has to have such a code as well:
```
public FtpStreamingMessageSource(RemoteFileTemplate<FTPFile> template,
			Comparator<AbstractFileInfo<FTPFile>> comparator) {
		super(template, comparator);
		doSetFilter(new FtpPersistentAcceptOnceFileListFilter(new SimpleMetadataStore(), "ftpStreamingMessageSource"));
}
```
