### ISSUE TITLE
Refactor Pubsub* to PubSub* (revert #56)

### ISSUE THREAD

**Issue by balopat** [spring-cloud/spring-cloud-gcp#80]
Based on discussions with the Cloud Pub/Sub team, I submitted [an issue on googleapis ](https://github.com/googleapis/googleapis/issues/414) to have the PubSub proto refactored to PubSub instead of Pubsub. That probably isn't going to happen anytime soon due to all the dependencies, given this code was out there for 2 years now. However we can stop the pattern propagating and follow the style guide for the correct camel case.
note: this would be essentially the reversion of #56

**Comment by joaoandremartins** [comment]
It might be worth getting this in before the starter is published, so I'll get right on it.
