### ISSUE TITLE
org.springframework.integration.gcp.outbound.PubsubMessageHandler swallows errors on published messages

### ISSUE THREAD

**Issue by balopat** [spring-cloud/spring-cloud-gcp#81]
The following line in [org.springframework.integration.gcp.outbound.PubsubMessageHandler](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-integration-gcp/src/main/java/org/springframework/integration/gcp/outbound/PubsubMessageHandler.java#L41
) should be a blocking call to be able to determine whether the returned listenableFuture failed or succeeded: 
````
    protected void handleMessageInternal(Message<?> message) throws Exception {
        this.pubsubTemplate.send(this.topic, message); // this fails silently if e.g. a topic is not defined
    }
````
This could be just a simple ``.get()`` call, or we can even have a debug log which would print out the result in case of success.  

Optionally we could even take into account timeout configuration?

**Comment by artembilan** [comment]
The idea how it should be implemented can be borrowed from the https://github.com/spring-projects/spring-integration-kafka/blob/master/src/main/java/org/springframework/integration/kafka/outbound/KafkaProducerMessageHandler.java

**Comment by joaoandremartins** [comment]
Yep, this is in our roadmap already (#51). IIUC this issue is a duplicate.

**Comment by meltsufin** [comment]
I'm not clear on why we can't even output an error to the log even if it's async?
