### ISSUE TITLE
Merge relevant commits from master branch to 1.0.x

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#814]
Any changes exclusively to samples, tests, and docs, excluding Spanner and Config should be merged.
Other changes should be carefully considered to be backwards-compatible.

**Comment by artembilan** [comment]
We can try this and other way, but as I said not one time: it would be much easier to cherry-pick commits just after merging original PR.
This way we really hardly ever lose some change here and there.
Now imagine when we come to the situation to support 3-4 versions in parallel...

**Comment by meltsufin** [comment]
#813 changes was made to both branches

#800 was an oversight. We should make the change in master now.

**Comment by artembilan** [comment]
https://github.com/spring-cloud/spring-cloud-gcp/commit/828f90a5b1717b2cf11555618a997adcd3c571e1

**Comment by meltsufin** [comment]
9349cb9

**Comment by meltsufin** [comment]
55d0d98

**Comment by meltsufin** [comment]
2186e93

**Comment by meltsufin** [comment]
d3dea6a

**Comment by meltsufin** [comment]
9540d32

**Comment by meltsufin** [comment]
318c087 - converter generics

**Comment by ChengyuanZhao** [comment]
c8d1cd8

**Comment by meltsufin** [comment]
22dfd7b - remove acknowledger (#875)

**Comment by meltsufin** [comment]
dc2bf23 - `AcknowledgeablePubSubMessage` interface

**Comment by meltsufin** [comment]
I think we should also port the disabling of the magic configuration of the `JacksonPubSubMessageConverter`.
7d9662d

**Comment by artembilan** [comment]
Oh, really?! I thought we treated that as a bug and really considered for back-porting.
That's one more minus do not have ability to cherry-pick during merge...

**Comment by meltsufin** [comment]
e21f90d - Make SQL auto-config conditional on jdbc-socket-factory-core

**Comment by meltsufin** [comment]
Fixed by #814.
