### ISSUE TITLE
PubSubTemplate can't be used for a publish only use case without a SubscriberFactory

### ISSUE THREAD

**Issue by dhoard** [spring-cloud/spring-cloud-gcp#816]
My team and I have various use cases, most of which are subscribe only ... but we have few publish only use cases.

The `PubSubTemplate` class has methods for both publish and subscribe use cases.

From a subscribe only use case, from looking at the code, I know I can just pass `null` for the `PublisherFactory` and use it only for the subscribe use case.

From a publish only use case, I can't use `PubSubTemplate` without a creating a `SubscriberFactory` because of the code in the constructor.

Quick fix ...

1) make the constructor of `PubSubTemplate` check for a null `SubscriberFactory`.  In that case, assume that `PubSubTemplate` is only going to be used for a publish use case and don't make the methods calls in the constructor that use the `SubscriberFactory`

Clean fix ...

1) separate the interface `PubSubOperations` into `PubSubPublisherOperations` (publish methods) and `PubSubSubscriberOperations` (subscription / pull methods)

2) create a `PubSubPublisherTemplate` that implements `PubSubPublisherOperations`

3) create a `PubSubSubscriberTemplate` that implements `PubSubSubscriberOperations`

4) change `PubSubTemplate` to implement `PubSubPublisherOperations` and `PubSubSubscriberOperations`

5) change `PubSubTemplate` to contain instances of `PubSubPublisherTemplate` and `PubSubSubscriberTemplate`.  Have the methods in `PubSubTemplate` delegate to the appropriate methods in the contained instances

**Comment by meltsufin** [comment]
I like the idea of separating the concerns of publishing and subscribing - the clean fix. I'll take a closer look at the PR a bit later. Thanks for the thorough issue description and the PR!

**Comment by dhoard** [comment]
@meltsufin I create PR #819 to implement a solution that should be considered clean.

**Comment by meltsufin** [comment]
@dhoard Thanks! I did the same. So, we'll need to resolve differences. :)
I'm happy to accept your PR once any differences are resolved.
