### ISSUE TITLE
PubsubInboundChannelAdapter swallows error when connected to non-existent subscription

### ISSUE THREAD

**Issue by balopat** [spring-cloud/spring-cloud-gcp#82]
Currently if I connect a PubsubInboundChannelAdapter to a non-existent subscription, it silently fails. 
We could change this behaviour by changing [this line](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/spring-integration-gcp/src/main/java/org/springframework/integration/gcp/inbound/PubsubInboundChannelAdapter.java#L61):
````
    protected void doStart() {
        super.doStart();
        this.subscriber = this.subscriberFactory.getSubscriber(this.subscriptionName, this::receiveMessage);
        this.subscriber.startAsync(); // <---- this fails silently. 
    }
````
We could add an ``.awaitRunning()`` to ensure that when the subscriber started that it is actually running.

**Comment by artembilan** [comment]
The ` .awaitRunning()` is not good. It eliminates the purpose of the `startAsync()`.

Would be better to use `void addListener(ApiService.Listener var1, Executor var2);` to log in case of 
`failed(ApiService.State from, Throwable failure) `

**Comment by joaoandremartins** [comment]
Another (more expensive, but more explicit) alternative is to make an explicit check for the existence of the Subscription using the `[getSubscription() method](http://googlecloudplatform.github.io/google-cloud-java/0.20.0/apidocs/com/google/cloud/pubsub/v1/SubscriptionAdminClient.html#getSubscription-com.google.pubsub.v1.SubscriptionName-)`. We could also create the Subscription if it doesn't exist.

This behaviour should be parameterised.

**Comment by balopat** [comment]
@artembilan logging sounds good, however, that still doesn't solve the need from the client code to have an explicit way to inspect/handle subscription errors and have the option to fail/retry/ignore.

**Comment by artembilan** [comment]
Well, in other places we expose the `ApplicationEvent` architecture to let end-user to do what is the best for him there. For example `ListenerContainerConsumerFailedEvent` in the Spring AMQP: http://docs.spring.io/spring-amqp/reference/html/_reference.html#consumer-events. Or `MqttIntegrationEvent` hierarchy: http://docs.spring.io/spring-integration/reference/html/mqtt.html#mqtt-inbound

**Comment by joaoandremartins** [comment]
This was apparently fixed in a recent version of the google-cloud-pubsub library, as I'm now seeing errors logged when trying to subscribe to a non-existing subscription.
