### ISSUE TITLE
Track usage of other APIs by Spring

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#83]
We're currently working with the Pub/Sub team to fix the metrics backend to allow us to track Pub/Sub API usage by Spring integrations.

There are other APIs where we should also track usage. Right now, we're using:
- Storage API
- Cloud SQL Admin API

The Cloud SQL Admin API's `SQLAdmin.Builder` provides an `applicationName` parameter that we could populate. It's not clear that the Storage API provides any such method for usage tracking.

**Comment by meltsufin** [comment]
Fixed in #308
