### ISSUE TITLE
Add @since 1.1 to all Spanner and Config classes

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#837]
Since Spanner and Config were pulled out of the 1.0 track, we should label those classes with `@since 1.1`.

**Comment by dhoard** [comment]
@meltsufin I have checked out a branch and added the `since 1.1` in all of the classes in the module `spring-cloud-gcp-data-spanner`.

Can you clarify exactly which module / classes are you referring to as `Config` and I'll make those Javadoc changes.

**Comment by meltsufin** [comment]
Config is all contained in the `autoconfigure.config` package. Thanks!
