### ISSUE TITLE
FR - Spanner - Add More Transaction Support to support @Transactional

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#845]
Low level transaction management feature was added to Spanner client library:
https://github.com/GoogleCloudPlatform/google-cloud-java/issues/1810

Spring Cloud GCP could benefit from this transaction manager and adopt it for JTA / Spring.

However, I can't tell whether the transaction isolation level is comparable to JTA.

**Comment by meltsufin** [comment]
@ChengyuanZhao PTAL

**Comment by ChengyuanZhao** [comment]
Thank you for the notice !

This new functionality is much more similar to what traditional SQL servers offer, and from my look into implementing the `@Transactional` should result in a much more traditional implementation. 

We have another ticket discussing this https://github.com/spring-cloud/spring-cloud-gcp/issues/592, but that was based on the original way to do transactions, which didn't allow access to explicitly committing or rolling back.

**Comment by alexkhimich** [comment]
Created a PR https://github.com/spring-cloud/spring-cloud-gcp/pull/1001
