### ISSUE TITLE
Deprecate PubSubInboundChannelAdapter constructor

### ISSUE THREAD

**Issue by dhoard** [spring-cloud/spring-cloud-gcp#848]
I think we should deprecate the `PubSubInboundChannelAdapter` constructor ...

`public PubSubInboundChannelAdapter(PubSubSubscriberOperations pubSubSubscriberOperations, String subscriptionName)`

... because it uses a default `AckMode` of `AckMode.AUTO`.

Without requiring a developer to explicitly specify the `AckMode`, he / she may not realize messages will be lost if an exception occurs processing a Pub / Sub message.

I have created PR https://github.com/spring-cloud/spring-cloud-gcp/pull/847 to add a new constructor in `PubSubInboundChannelAdapter` that accepts `AckMode`.

**Comment by artembilan** [comment]
That's a bit wrong direction in the logic.
Even if we change ctor to always request `AckMode`, you still can't stop me to configure it into the `AckMode.AUTO` and as you said I still "lose messages if an exception occurs".
So, such a ctor enforcement doesn't bring any value.

What am I missing?

**Comment by dhoard** [comment]
You are correct - we won’t lose messages ... totally missed that code. 

The real value in requiring the `AckMode` In the constructor is that it forces a developer to make an *explicit* decision on the acknowledgment mode.

**Comment by dhoard** [comment]
For reference / related - https://github.com/spring-cloud/spring-cloud-gcp/issues/850 describes a very common third acknowledgment mode `PubSubInboundChannelAdapter` is currently not handling.

**Comment by meltsufin** [comment]
@dhoard We tried to document the default ack mode in the refdoc. Perhaps, it's not sufficient, and we can improve the docs. We can also add javadoc to the existing constructor to make sure it says that the default ack mode of `AUTO` will be configured.

**Comment by artembilan** [comment]
>  it forces a developer to make an explicit decision

This is clearly just your own opinion. We follow here some cold rules. And I explained you before the reason we have a setter for `AckMode` instead of ctor arg.
I may agree about some docs improvement, but I am strongly against the change in this PR.

**Comment by dhoard** [comment]
@meltsufin if you concur ... please close
