### ISSUE TITLE
Implement Google Cloud Pub/Sub Spring Cloud Stream binder

### ISSUE THREAD

**Issue by joaoandremartins** [spring-cloud/spring-cloud-gcp#85]

**Comment by Andy2003** [comment]
Is there currently any work on this Ticket? I have already done some implementation on this at: https://github.com/spring-cloud/spring-cloud-stream-binder-google-pubsub/pull/5 and was redirected to this project.

**Comment by meltsufin** [comment]
@Andy2003 thank you for the interest in the Spring Cloud Stream binder for Pub/Sub. As you can see it's on our roadmap for 1.0.0.M1. However, we haven't really started work on it yet. We will look at the PR you referenced. In any case, would you be interested in contributing the work you've done in that PR to this project?

**Comment by Andy2003** [comment]
@meltsufin Yes I can port my former work to use the artifacts of this project, this should not be a big deal. Before I start I just wanted to be sure that @joaoandremartins is not already working on this topic. Feel free to assign the Issue to me.

**Comment by joaoandremartins** [comment]
Haven't worked much on it besides some initial research.
Feel free to submit your PR and we can have a look.

**Comment by joaoandremartins** [comment]
Seems I can't assign you because you aren't a collaborator on the project.
Probably makes sense for me to keep the assignment as the owner of this feature overall, anyway.
