### ISSUE TITLE
Add third acknowledgment mode to PubSubInboundChannelAdapter / AckMode

### ISSUE THREAD

**Issue by dhoard** [spring-cloud/spring-cloud-gcp#850]
`AckMode` currently defines two modes ...

`MANUAL` - the message receiver / sink must ack or nack the message.

`AUTO` - the framework acks the message when the message receiver / sink successfully processes the message. When An exception occurs processing the message, the framework nacks the message. 

The third acknowledgment mode, which is not modeled, is the scenario where an exception occurs when processing the message, but we do not want to nack the message.

This is a very common use case that leverages the Pub / Sub ack deadline timeout as a delay mechanism for message retry. 

Implementation would require adding the new mode in `AckMode` (name ?) and changing `PubSubInboundChannelAdapter`

**Comment by meltsufin** [comment]
@dhoard Are you suggesting something like `AckMode.NONE`? If so, how would that be different from `MANUAL` where the user app doesn't do any (n)acking?

**Comment by artembilan** [comment]
You are missing the fact that with `AUTO` and configured `errorChannel` we indeed can handle exception and don't propagate it back to the `PubSubInboundChannelAdapter` which in the end will do `ack()`.
However I agree with @meltsufin that for such an "acking on error" scenario a `MANUAL` is going to be better.

No sure what is the point to catch exceptions manually, but still rely on the auto acking...

**Comment by dmitry-s** [comment]
It's a little bit more complicated. There is maxAckExtentionPeriod setting in the subscriber, that is also involved. By default we set it to 0, but if it is set to some other value, it effectively increases ack deadline. You can see how it works here https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/MessageDispatcher.java

So, message is back to the queue after ackDeadline+maxAckExtensionPeriod seconds, not just after ackDeadline seconds.

**Comment by dhoard** [comment]
@meltsufin I was thinking *possibly* `AckMode.AUTO_SUCCESS` with the concept to only ack the message when successfully processed; ignoring the message on a processing failure.

Insight to the approach ...

Based on several GCP experts both from Google (suppor, subject matter experts, etc.) as well as other end users, we *never* nack a message. If there is an issue processing the message, we want a re-delivery delay. By not nack'ing the message, the Pub / Sub ack deadline timeout provides the re-delivery delay.

Requiring `AckMode.MANUAL` seems overly burdensome.

**Comment by meltsufin** [comment]
@dhoard I see. In other words, you're asking for something like `AUTO_ACK`, but not `AUTO_NACK`.

**Comment by dhoard** [comment]
@meltsufin correct

**Comment by artembilan** [comment]
OK. Let it be then `AUTO_ACK` in contradiction to the default `AUTO`, but you still can't make an assumption that everybody would like to have this as a default one and also would insist to have it as a required ctor arg.

**Comment by dhoard** [comment]
@artembilan agreed on the assumption, so https://github.com/spring-cloud/spring-cloud-gcp/issues/848 was closed since we won't implement the `AckMode` as a requirment in the constructor.  That doesn't invalidate this change.

I *still* think a constructor with `AckMode`, even if it's an *additional* constructor, is very useful ... but we can agreed to disagree :smile:

**Comment by dhoard** [comment]
@meltsufin @saturnism your thoughts? ... just want to make sure there is buy-in from you all on `AckMode.AUTO_ACK` functionality before I perform any work.

**Comment by meltsufin** [comment]
I'm OK with `AUTO_ACK`, as long as it's properly documented.
