### ISSUE TITLE
Spanner eager Parent-Child (1-to-many) relationships

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#853]
We recently discussed relationships in spring data with Oliver, and arrived at some common points among spring data integrations:

- eager retrieval of children should be the default implementation, and it is OK to let the user know the limitations of it. this is the recommendation for single children or multiple children in a collection.
- lazy retrieval can be very complicated especially after involving other features like transactions, and should definitely come second if at all.
- the idea of aggregates (parents) is strong in spring data, and relationships should be reflected in POJOs one-way from aggregate to its sub-items (children).
- recommend users use identifier properties instead of POJO references , which forces the user to do retrieval themselves.

**Comment by ChengyuanZhao** [comment]
Main points

- if property is a type (or inner type if iterable) annotated with Table(name = ...)  and it's not annotated embedded, then it is a child POJO relationship

Reads
- single-item children will be will be immediately recursively retrieved
- collection children will be retrieved on first touch (to prevent exponentially increasing number of retrievals). The subsequent "lazy" retrieval is done using the same SpannerOperations, and we already have functionality to create single-transaction-SpannerOperations (so even though it's "lazy" the data is exactly the same as immediate retrieval) 

Writes
- client lib allows batch write of mutations, so a pojo and all of its children can be saved in the same request
- single-item children will be saved 
- collection children that have been touched will be saved.

**Comment by nov1vinni** [comment]
It would be good to have annotation defined for onjetomany/manytoone , we can specify if this needs to be eagerly/lazy loaded something like below . We want to define this on spanner persistent entity to save parent/child records at one shot and also to retrieve them at one shot.

It would be good to expose a detailed doc explaining features. 

@onetomany("getChild",LoadType.Eager) 
or
@onetomany
@Eager

**Comment by ChengyuanZhao** [comment]
Tasks, in order:

- [ ] create admin client methods for checking table schema of given child tables if they are interleaved 
- [ ] create `@OneToMany` annotation to mark child collections
- [ ] read method recursively eagerly gets children
- [ ] write method creates single batch write for all children recursively 
- [ ] ref doc updates

**Comment by vineela-gampa** [comment]
@ChengyuanZhao 
1) Does this parent/child or @onetoMany relationship defined on an entity works only if the tables are INTERLEAVED?
2) is there a plan to integrate more queryOptions for filtering/Grouping results. Currently support exists for sort/pagination.

**Comment by vineela-gampa** [comment]
@ChengyuanZhao  Do you have plans to extend parent-child concept to non interleaved tables ? Whyregular tables which are not interleaved skipped from this implementation ?

**Comment by ChengyuanZhao** [comment]
@vineela-gampa We want to support parent-child relationships using the Spanner interleaved feature first because Spanner itself takes care of enforcing the one-to-many relationship , cascading deletes, physical co-location of rows, and removes the burden of the aforementioned from the clients. Spanner does not support traditional foreign keys, though the closest thing is the parent-child key requirement from parent-child interleaved tables.

**Comment by vineela-gampa** [comment]
@ChengyuanZhao With this feature is there was to specify any option where i might not need child information but just need one table data ? How do we do that ?
Say table A (parent) with cols (x,y,z columns)
                   -> List<B>
                                -> List<C>
say i want to retrieve only X,Y,Z and dont retrieve List<B>.

**Comment by ChengyuanZhao** [comment]
@vineela-gampa If you do not have a `List<B>` property in the parent class then the children will not be retrieved.

**Comment by vineela-gampa** [comment]
@ChengyuanZhao  Parent class iwll have it as in some cases we might want all the details but there might be specific scenarios where that joins might not be needed and want to retrieve only few fields. in that case how do we do ?

**Comment by ChengyuanZhao** [comment]
Currently if the property for the children is there then they will be retrieved. We will need to look into how to provide the option to do this if we are to support it.

**Comment by meltsufin** [comment]
@vineela-gampa It sounds like you want the collection of children to be lazily fetched. Am I understanding your usecase correctly?
Also, if there are cases when you don't need to retrieve the children, I would try using two different entities.
B (with children collection) extends A without children, and use A when you don't want to fetch children, and B when you do.

**Comment by vineela-gampa** [comment]
@meltsufin yeah there might be usecases where we need to fetch children lazily. It would be great if we can send a flag to skip retrieving child elements , bcoz i can see it can be done as per teh current code. 

we are waiting for this functionality to plan our iterations. By when can we expect read/write eagerlly loaded stuff to be merged so that we can use it ?

**Comment by meltsufin** [comment]
@vineela-gampa We're working on reviewing the `@Interleaved` support. If you would like to help out, we would appreciate feedback on it. Maybe you have the opportunity to review/try the code that is currently in PRs. Thanks!

**Comment by vineela-gampa** [comment]
@meltsufin  sure we can try and post the update.

One other question is how do we specify which columns should not be updated during an update.

**Comment by ChengyuanZhao** [comment]
@vineela-gampa On SpannerTemplate the update and upsert functions provide overloaded methods that take sets of column names to include. By default not specifying those will let all columns be written.

The SpannerRepository save method is an implementation of CrudRepository and that method will save all columns.

**Comment by vineela-gampa** [comment]
I tried write / read with @Interleaved option. Its working as expected.

https://github.com/spring-cloud/spring-cloud-gcp/pull/911
https://github.com/spring-cloud/spring-cloud-gcp/pull/916 

@meltsufin @ChengyuanZhao  tried insert/read with all of the data set in /Skip data (set null for some interleaved entities)

Tried negative tests by not giving primary key columns to child entities - works and throws exception as expected. 

@meltsufin  i believe we should be good to merge read ?

**Comment by vineela-gampa** [comment]
i see code changes for @onetomany annotation but dont see any changes related to it for read/write.

**Comment by vineela-gampa** [comment]
@meltsufin @ChengyuanZhao  did you get a chance to review my comments ?whats the plan to merge 
 Open
Spanner eager read parent-child relationships #916 ?

**Comment by meltsufin** [comment]
We're focusing on our 1.0 release. So, this 1.1 track work has been put on hold for a few days. We'll get back to you later this week. Thanks!

**Comment by vineela-gampa** [comment]
Thanks . Will wait for you update.

**Comment by vineela-gampa** [comment]
@ChengyuanZhao is there any performance impact with eagerly loading of child for an entity of 3-4 level depth ?

**Comment by meltsufin** [comment]
@vineela-gampa Undoubtedly there is a cost to loading all of the children, especially several levels deep. However, this is more of a question of whether the entities are modeled correctly for the app. If the app rarely accesses the children, then maybe you shouldn't load them every time the parent is loaded and not model them with an `@Interleaved` collection. Lazy loading is another option, but we currently do not support it.

**Comment by vineela-gampa** [comment]
@meltsufin  do you have performance numbers for it ?

**Comment by meltsufin** [comment]
@vineela-gampa That would be highly application and data-specific. At a minimum, loading the collection is another round-trip the database. Secondly, there's a cost of transferring all the data for the collection from the database to the app, and that's dependent on the number of children and columns.
