### ISSUE TITLE
JacksonPubSubMessageConverter with generics

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#854]
Current:
`public Object fromPubSubMessage(PubsubMessage message, Class<?> payloadType)`

Proposed:
`public <T> T fromPubSubMessage(PubsubMessage message, Class<T> payloadType)`

If we decide to make this change, I think it should be pushed into the 1.0.x stream.

@artembilan

**Comment by artembilan** [comment]
Let's see how it works with the real code and in the samples!

Feel free to PR solution!

**Comment by meltsufin** [comment]
Created #855.
No changes to any samples needed.
