### ISSUE TITLE
Doc - GCS - Example of setting content type

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#861]
Add documentation to show how to set content type while uploading file and/or updating the content type / metadata after the upload.

**Comment by bountin** [comment]
Sharing my findings to save the next soul some research time:

I see (at least) two ways to add metadata to a resource: The first is to go through `com.google.cloud.storage.Storage` which is put into the context by the GCP starter. 

My favorite is the second one which directly uses the resource instance: 
```kotlin
val resource = resourceLoader.getResource("gs://...") as GoogleStorageResource
resource.blob.toBuilder()
    .setContentType("text/html")
    .build().update()
```

**Comment by meltsufin** [comment]
@bountin thanks for sharing!
