### ISSUE TITLE
Stop auto-configuring JacksonPubSubMessageConverter

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#865]
Ever since we decided to auto-configure the `JacksonPubSubMessageConverter` based on the presence of the Jackson dependencies in the classpath, we've had multiple issues due to the surprising aspect of that. For example, see #863.

This issue is a proposal require explicit configuration of the `JacksonPubSubMessageConverter`.

**Comment by saturnism** [comment]
Agreed on the surprise. An alternative is to use create a `CompositePubSubMessageConverter`, and delegate String to `Simple` converter, and unrecognized objects to `Jackson` converter.

**Comment by meltsufin** [comment]
One issue I see with the composite idea is that certain basic types like `byte[]` and `String` could be handled by `Jackson` or the `Simple` converter. How would we choose which one to give priority to? If we say use `Simple` in this case, it could be surprising to someone assuming everything is JSON.
Maybe it's not an issue because no one would want to transfer strings or bytes as JSON. I dunno.
