### ISSUE TITLE
Allow configuration of message payload type in Pub/Sub Binder

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#866]
The Pub/Sub inbound  channel adapter allows the specification of the payload type which is useful for the message conversion. However, this property is currently not exposed in `PubSubExtendedBindingProperties`.

**Comment by artembilan** [comment]
I think this is an invalid issue: Binder **always** must return data as `byte[]`. 
See my review in the https://github.com/spring-cloud/spring-cloud-gcp/pull/867#discussion_r202781316

**Comment by meltsufin** [comment]
Agreed.
