### ISSUE TITLE
Pub/Sub Annotation-driven Message Listener Endpoints

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#874]
The `MessageListenerContainer` pattern and an appropriate `@...Listener` annotation should be added like in other projects:

- https://docs.spring.io/spring-kafka/docs/2.1.7.RELEASE/reference/html/_reference.html#kafka-listener-annotation
- https://docs.spring.io/spring-amqp/docs/2.0.4.RELEASE/reference/html/_reference.html#async-annotation-driven
- https://docs.spring.io/spring/docs/5.0.7.RELEASE/spring-framework-reference/integration.html#jms-annotated

The idea was floated in the beginning of the project, but then we really decided that it would be enough to advertise a Spring Integration `MessageDriverChannelAdapter` appoach, since `@...Listener` really mimics that functionality.

Something like this would become possible:

```java
public class Listener {

    @PubSubListener(id = "foo", subscription = "mySubscription")
    public void listen(String data, AckReplyConsumer ackReply) {
        ...
    }

}
```

**Comment by dhoard** [comment]
My concern with the sample listener above is that we don't have access to the underlying Pub / Sub attributes or publishTime.

**Comment by artembilan** [comment]
> we don't have access to the underlying Pub / Sub attributes or publishTime.

They are going to be available via parameter in your listener method with the `@Header`. See the mention documentations.
For example:
```
@KafkaListener(id = "qux", topicPattern = "myTopic1")
public void listen(@Payload String foo,
        @Header(KafkaHeaders.RECEIVED_MESSAGE_KEY) Integer key,
        @Header(KafkaHeaders.RECEIVED_PARTITION_ID) int partition,
        @Header(KafkaHeaders.RECEIVED_TOPIC) String topic,
        @Header(KafkaHeaders.RECEIVED_TIMESTAMP) long ts
        ) {
    ...
}
```
Am I still missing anything?

**Comment by dhoard** [comment]
Thanks for the information on the attributes. 👍

**Comment by meltsufin** [comment]
Obsolete.
