### ISSUE TITLE
Please default the config of the credential locations for Runtime Config to the generic config location

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-gcp#881]
If i specify `spring.cloud.gcp.config.credentials.location=${spring.cloud.gcp.credentials.location}` in my `bootstrap.properties` then it works correctly. for most (all?) of the other services the autoconfig draws the config location from the generic credentials location.

**Comment by ChengyuanZhao** [comment]
Do you mean that Runtime Config doesn't work for you unless you set `spring.cloud.gcp.config.credentials.location` in `bootstrap.properties`?

**Comment by ChengyuanZhao** [comment]
I think I see the error. The autoconfig for Runtime Config is basically all in `GoogleConfigPropertySourceLocator`. 

The constructor for that class expects a credential provider that if , but in our implementation right now in `GcpConfigBootstrapConfiguration` the constructor for `GoogleConfigPropertySourceLocator` is given a `new DefaultCredentialsProvider(configProperties)` instead. 

Then these lines in the constructor 
```
			this.credentials = gcpConfigProperties.getCredentials().hasKey()
					? new DefaultCredentialsProvider(gcpConfigProperties).getCredentials()
					: credentialsProvider.getCredentials();
```
are choosing from the same 2 options, which is causing the problem.

**Comment by meltsufin** [comment]
See https://github.com/spring-cloud/spring-cloud-gcp/pull/368#issue-166207389 for a discussion of the differences between bootstrap context an autoconfigure and why they should not be mixed.
It might be OK to add `@EnableConfigurationProperties(GcpProperties.class)` to `GcpConfigBootstrapConfiguration` and resolve this issue that way, but I'm not sure if it will mix properly with the regular autoconfigure context.

**Comment by meltsufin** [comment]
Works as intended.
