### ISSUE TITLE
Datastore operations functions can take Kind string, add overloads.

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#883]
These would be the same as functions as the ones that now take the domain types. The functions can work just the same if provided kind string names. 

TBH this seems like a strange idea, because it seems to go counter to the entire idea of using POJO types to stand in for Datastore concepts like Kind.

**Comment by meltsufin** [comment]
Closing due to lack of interest from the community.
