### ISSUE TITLE
Integration tests for creating local spanner db instance for integration tests

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#909]
Looking for options to spin up in memory spanner instance to run integration tests. 
Currenlty we have created an test db instance on spanner against which we are running our tests. But my notion of test would be not to depend on any external dependencies to run your tests. 
Here there is always this work of syncing up schema against actual instance vs test instance which is error prone and manual work involved.

**Comment by vineela-gampa** [comment]
@ChengyuanZhao @meltsufin  Please let us know your thoughts and looking to hear for a way to do integration testing for spring boot applications which uses spanner ?

**Comment by ChengyuanZhao** [comment]
@vineela-gampa There is no local Cloud Spanner emulator or instance, unfortunately. As a result we have to use a special integration testing instance to run our CI Travis tests for this repository.

The client library actually does allow you to start up instance pretty easily : https://cloud.google.com/spanner/docs/create-manage-instances

While we have our instance up all the time , you could start one up without too much code and shut it down after testing. 

We have a Spanner admin template class as well that will generate schemas from your POJOs and also create the corresponding tables, which is what we do for our integration tests. After starting an instance you could take advantage of this functionality too.
