### ISSUE TITLE
Make GcpCloudSqlAutoConfiguration conditional on com.google.cloud.sql:jdbc-socket-factory-core

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#914]
Currently, `GcpCloudSqlAutoConfiguration` is only conditional on `spring-jdbc` which is not sufficient. We need to make sure that it is only turned on when either `com.google.cloud.sql:mysql-socket-factory` or `com.google.cloud.sql:postgres-socket-factory` are present, both of which have `com.google.cloud.sql:jdbc-socket-factory-core` as a common dependency.

Related to #913.

**Comment by artembilan** [comment]
But that is exactly what is ensured by the `@ConditionalOnClass` in the particular inner auto-config class.
Even if `GcpCloudSqlAutoConfiguration` passes its conditions, that doesn't matter that everything else is going to be applied.
See my comment in that issue. 

On  the other hand what is the point to create a new issue if we can fix the problem in the context of that one?
(If the problem exists, of course...)

**Comment by meltsufin** [comment]
I see your point. I missed the fact that everything in `GcpCloudSqlAutoConfiguration` was grouped into inner classes. However, I'm still not 100% sure that having our `GcpCloudSqlAutoConfiguration` has zero impact when the inner classes don't get processed. For example, the properties would still be enabled via `EnableConfigurationProperties`. Do we really need that? There seems to be a bit of overhead with all that, and we can just short-circuit it by adding a condition on `com.google.cloud.sql:jdbc-socket-factory-core` at the very root.

**Comment by artembilan** [comment]
OK. Fair enough, but I don't know if it is going to be possible: there is no `OR` conditional...
