### ISSUE TITLE
@Transactional annotation impleentation

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#918]
Looking for similar support of https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/annotation/Transactional.html that exists for Spring JDBC/Hibernate on spanner.

instead of having to put embed code in spannerTemplate.readONlyTransactoin or readwritetransaction etc.

**Comment by artembilan** [comment]
Thank you the report, but this is already on our radar - #845.

So, this one is duplication, therefore closed respectively.

You can report your concerns there.
