### ISSUE TITLE
Change a field to null is ignored when a save is perform

### ISSUE THREAD

**Issue by benjacarp** [spring-cloud/spring-cloud-gcp#919]
I'm trying to change a field of an entity to null, but when I save the entity the previous value in the data base remain the same.

I found this in spring-cloud-gcp-data-spanner-1.0.0.BUILD-TVC-SNAPSHOT-sources.jar
org.springframework.cloud.gcp.data.spanner.core.convert
.ConverterAwareMappingSpannerEntityWriter. writeProperty
if (propertyValue == null) {
return;
}

Is this intentional or a bug? What is the suggested work around to remove an association id of another table? setting the associated id field to empty?
Thanks so far

**Comment by ChengyuanZhao** [comment]
@benjacarp Thank you for reporting this! 

I think this is indeed an oversight and I'll make a fix. It looks like it is always safe to construct `Value` of NULL for any of the types Spanner accepts and send that in a mutation. I'll include this case in our integration tests, too.
