### ISSUE TITLE
Enhance Spring Cloud Pub/Sub Template/Operation

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#92]
Currently PubSubOperation has only 1 method, send(topic, message). It can be further enhanced with better Pub/Sub support
- [x] JavaDoc on key public interfaces, like PubSubOperation
- [ ] Additional Surface
  - [x] A way to send just a string, e.g., send(topic, String message)
  - [x] A way to do a sync send
  - [ ] A way to send an object and marshall w/ converter, e.g., send(topic, Object message) & use converter, potentially detect Jackson in classpath and automatically register a JSON converter.
  - [ ] Revisit MessageHeaders, make sure headers captures and propagates Pub/Sub metadata
  - [x] Revisit configuration, make sure all settings are configurable via a bean, e.g., RetrySetting
  - [x] A way to pull a message, e.g., pull(subscription)
  - [x] A way to subscribe to a topic, e.g., subscribe(messageListener)
  - [x] Expose underlying API, e.g., getSubscriberClient(), getPublisherClient()
  - [x] Clean up converter, currently converter is not symmetric (e.g., toMessage() & fromMessage() returns very different types
  - [ ] Add SubscriberConfiguration and PublsiherConfiguration
- [x] Sanity check - Spring Integration Pub/Sub should probably use PubSubOperation for everything

**Comment by jabubake** [comment]
+1 on a way to send an object w encoder /decoder support

**Comment by joaoandremartins** [comment]
We should probably also rename `send()` to `publish()` as part of this issue.

**Comment by joaoandremartins** [comment]
@saturnism can you please clarify the requirements around `Add SubscriberConfiguration and PublsiherConfiguration` ?

**Comment by meltsufin** [comment]
I created separated issues for all unfinished tasks here.
