### ISSUE TITLE
Pubsub emulator support

### ISSUE THREAD

**Issue by nikartix** [spring-cloud/spring-cloud-gcp#928]
Does pub sub integration support emulation ?
There is a configuration property `spring.cloud.gcp.pubsub.emulator-host` which when I assign value doesn't seem to change anything.
I get the `The project ID can't be null or empty.` error which should not be required for emulator.

Do I need to explicitly change something else ?

**Comment by nikartix** [comment]
Fixed it.
I was using older version `1.0.0.M3`
updating to '1.1.0.M1' fixed the issue.
closes #928

**Comment by meltsufin** [comment]
Thanks for the update! Apologies for not getting back to you sooner.
