### ISSUE TITLE
Spring Data JPA doesn't work on gcp flexible environment.

### ISSUE THREAD

**Issue by victoy** [spring-cloud/spring-cloud-gcp#929]
I added a controller in "spring-cloud-gcp-data-jpa-sample" project. 
When I use Controller instead of CommandLineRunner, it doesn't work on gcp flex environment. 

It increases instances continuously or keep dropping instances and run start script again. 

Is this a known issue? 

`
@RequestMapping("/demo")
public class HouseController {

	private static final Log LOGGER = LogManager.getLogger();

	@Autowired
	private HouseRepository houseRepository;

	@GetMapping("")
	String house()  {
		this.houseRepository.deleteAll();

		Stream.of(new House("111 8th Av., NYC"),
				new House("636 Avenue of the Americas, NYC"),
				new House("White House"),
				new House("Pentagon"))
				.forEach(this.houseRepository::save);
		String res = "Number of houses is " + this.houseRepository.count();
		LOGGER.info(res);
		this.houseRepository.findAll().forEach(house -> LOGGER.info(house.getAddress()));
		return res;
	}
}
`

**Comment by meltsufin** [comment]
It looks like your Flex instance is just running out of memory.
[Try adding more memory](https://stackoverflow.com/questions/47830477/deploy-a-springboot-angular-4-on-google-app-engine-with-maven/48774859#48774859).
In `app.yaml`:
```
resources:
  memory_gb: 4
```

**Comment by victoy** [comment]
@meltsufin 
That's the one I should know. It works now. 
Thanks a lot.
