### ISSUE TITLE
Support custom host for Cloud Spanner

### ISSUE THREAD

**Issue by olavloite** [spring-cloud/spring-cloud-gcp#930]
The Cloud Spanner client library allows a custom host to be specified instead of using the default https://spanner.googleapis.com. Setting a custom host makes it possible to connect to a (local) emulator instead of a real Cloud Spanner instance for testing/development purposes. Adding a 'host' configuration property to GcpSpannerAutoConfiguration could solve this.

**Comment by ChengyuanZhao** [comment]
Thank you for the issue and PR. However, we can't merge this since we don't plan to support 3rd party emulators/services endpoints right now.
