### ISSUE TITLE
Spanner @InterleavedTable annotation for child-table POJOs to imply PK columns of parent

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#934]
This issue is for recording the discussion and the ideas. (We moved from an internal doc to using github issues some months ago)

**Comment by ChengyuanZhao** [comment]
Discussion today mentioned the idea of a new annotation `@InterleavedTable(table_name)` in addition to the standard `@Table(table_name)`.  

- The child type annotated with InterleavedTable would only be usable when used as a `Collection<childType>` and cannot be used as a "root" type. 
- child types would not contain the properties/columns of the parent. the values and metadata of these PK columns would come from the parent instance holding these child instances
- This means users cannot define SpannerRepository with types annotated InterleavedTable as the domain type because the return types of the repo functions are root types (not contained within a parent POJO).


pros:
- users don't need to define and set the PK columns repeatedly for generations of children

cons:
- users need to define a regular `@Table` version of the child table if they wish to use it as a root type or a domain type.
- if users are sure they want to use the child type both as root type and a child-collection type then our code will be more complicated to support both cases of children being fully-defined-children or the InterleavedTable children.

preliminary conclusions:
- Given the use case where the user wants to use the child type alone and in a child collection, then for sure it is preferable to only have him define the fully-defined child class. This means we need to support using `@Table` children even if we support `@InterleavedTable`
- because InterleavedTable cannot be used as a root type and cannot be the domain type of a repository, this implies supporting this feature doesn't affect the repository implementation and Query Method related classes
- the changes would be in SpannerTemplate (to pass in a parent-object when writing a child object) and SpannerMutationFactory (to pass in a parent-object when writing a child object)

**Comment by ChengyuanZhao** [comment]
@meltsufin I think actually these changes might not be as drastic as I originally thought. I think the changes would be perhaps 100-200 lines, (not including tests).

**Comment by ChengyuanZhao** [comment]
I think we should do this separately from the current support for fully-defined children. I don't think it's a good idea to prohibit the use of fully-defined children, because that forces people people to make 2 classes that are harder to read  (with columns spread through both) if they intend to use the type in a child-collection as well as a domain type (root type for repo). Therefore, the current fully-defined child support is necessary in any case.

**Comment by meltsufin** [comment]
Closing, due to low demand and high complexity.
Re-open if you care about this feature.
