### ISSUE TITLE
Move Spring Integration Pub/Sub guide location

### ISSUE THREAD

**Issue by saturnism** [spring-cloud/spring-cloud-gcp#94]
Currently the guide takes on the URL https://spring.io/guides/gs/spring-cloud-gcp/

However, spring-cloud-gcp is very general, what happens if we added more guides for other Spring Cloud GCP components?

Suggest moving the guide to a more specific URL, e.g, https://spring.io/guides/gs/spring-integration-gcp-pubsub/

**Comment by artembilan** [comment]
Duplicates of https://github.com/spring-guides/gs-spring-cloud-gcp/issues/2.

That is already not this project responsibility.
