### ISSUE TITLE
Upgrade to Spring Cloud Build 2.1.0 to be aligned with the upcoming Spring Cloud Greenwich

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/spring-cloud-gcp#951]

**Comment by meltsufin** [comment]
One issue encountered so far is that MySQL Connector J version 8.0 imports protobuf-java:2.6.0 which is incompatible with Google Cloud Java libraries. See https://github.com/spring-projects/spring-boot/issues/13688

**Comment by meltsufin** [comment]
@saturnism Filed a [bug](https://bugs.mysql.com/bug.php?id=91999) against MySQL driver.
For the time being, it might be best for Spring Boot to explicitly exclude `protobuf-java` from the MySQL dependency.

**Comment by spencergibb** [comment]
PR for protobuf issue https://github.com/spring-projects/spring-boot/pull/14062
