### ISSUE TITLE
The URI of Spring Cloud Stream traces are not very informative

### ISSUE THREAD

**Issue by johanhaleby** [spring-cloud/spring-cloud-gcp#953]
I just tried integrating `org.springframework.cloud:spring-cloud-gcp-starter-trace:1.0.0.RELEASE` with one of our services and while the functionality seem to work very well (thank you!) but the URI generated for Spring Cloud Stream's that is shown in the GCP console could be more informative imho.

For example in our application we have multiple cloud stream channels that receives messages from RabbitMQ and due to auto-configuration Spring automatically ships traces for these streams to Stackdriver. This is all good but when I login to the GCP console and navigate to "Tracing" I see traces such as these:

![trace1](https://user-images.githubusercontent.com/187029/44004916-330fa83a-9e6b-11e8-9f74-e025b82871c4.png)

Which is not very informative. Clicking on one of the traces reveals some more info though:

![trace2](https://user-images.githubusercontent.com/187029/44004960-aa8bdd16-9e6b-11e8-845e-1d80f832198c.png)

Here you can see the component and channel name which is good. But when you have multiple services (components in Stackdriver parlance I assume) it's really not very helpful that all you see in the overview (first screenshot) is just "send". It would be much more informative to call the URI something like `<scheme>://<component>/<channel>` and if possible perhaps even include some data such as the event type (`<scheme>://<component>/<channel>/<event type>`). For example `rabbitmq://order-system/orders/OrderPlacedEvent`

WDYT?

**Comment by meltsufin** [comment]
/cc @adriancole 
I don't believe we control this in this project at all. Maybe it's more of an OpenZipkin question?

**Comment by marcingrzejszczak** [comment]
@saturnism this is the Brave's default. It can be easily overridden though. E.g. https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/web/SleuthHttpServerParser.java

**Comment by johanhaleby** [comment]
Thanks. @marcingrzejszczak, do you mean that it's easy for *me* as an end user to override it? If so I don't exactly understand how to do it from the link you provided.

**Comment by meltsufin** [comment]
@johanhaleby It looks like you just need to register your own bean of type `brave.http.HttpClientParser` in the Spring application context to overwrite it.
See: http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/2.0.1.RELEASE/multi/multi__customizations.html#_http

**Comment by marcingrzejszczak** [comment]
Precisely. The link I've passed is an example of such a bean. There's a client and a server parser.

**Comment by saturnism** [comment]
@marcingrzejszczak iirc sleuth used to put url's as the span name. but sleuth 2 started to use `get`. For `http` calls, we already provide a [custom parser](https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/trace/sleuth)

But, I think the issue here is related to messaging w/ spring cloud stream (and similar in spring integration), where trace headers are parsed via messaging headers - which I don't think is customized by a `HttpParser`?

**Comment by marcingrzejszczak** [comment]
So for http if you pass a property you can turn on the old way of setting tags.

For messaging we add an easy way of working with message headers in 2.1.0 (https://cloud.spring.io/spring-cloud-sleuth/single/spring-cloud-sleuth.html#_messaging). I guess tags are not yet easily customizable. You can file an issue so that we fix that.

As a workaround you can copy the package scope messaging related code and modify it.

**Comment by saturnism** [comment]
I think the specific file that is tagging the span name is here:
https://github.com/spring-cloud/spring-cloud-sleuth/blob/master/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TracingChannelInterceptor.java#L147

there is no easy way to customize, and that `TracingChannelInterceptor` is a final class.  Added an issue in Sleuth to track for the FR :) /cc @marcingrzejszczak

**Comment by meltsufin** [comment]
@adriancole I still don't see how to use `SpanCustomizer`. All interface methods simply return `SpanCustomizer` (`this`) and the inputs to the methods are strings (immutable). 😕

**Comment by adriancole** [comment]
I somehow thought you were asking how to change a span name to something else. guess I answered wrong question?

**Comment by meltsufin** [comment]
Yes, that's the question, but how do you use `SpanCustomizer` to change the span name?

**Comment by adriancole** [comment]
my brain is not aligned.. so span customizer's only job is to allow things
like span name change

https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/SpanCustomizer.java

are you asking how to make a good name? by the way previous comments are
still true.. which is that a facility to make good names is on the way
(provided I can manage time to work on it). if you are asking again for a
feature to make better names automatically in other words.. this is already
accepted and work in progress there comes when time isnt spent on support
questions.

my suggestion to use span customizer was to mention how to do something
meanwhile. still sounds I dont understand what you are asking as the type
literally has a method called name which is used to change the name.

**Comment by meltsufin** [comment]
@adriancole I think I'm just missing something really simple. I don't understand how to use `SpanCustomizer.name()`.
I'm looking at this method signature which simply return the `SpanCustomizer` itself.
```java
SpanCustomizer name(String name);
```
I was expecting to see something like:
```java
String name(String name);
```

Apologies for being so dense, but can you please point out what I'm missing? Thanks!

**Comment by adriancole** [comment]
this function is to set a name, an example below. If you are overriding a
name, you put the name you want into the span customizer.  You cannot read
any existing name with this api.

String service = invoker.getInterface().getSimpleName();
String method = RpcUtils.getMethodName(invocation);
spanCustomizer.name(service + "/" + method);

**Comment by meltsufin** [comment]
I think the part I was missing is that we don't need to implement `SpanCustomizer`, but just use it via `TracingChannelInterceptorCustomizer` introduced in https://github.com/spring-cloud/spring-cloud-sleuth/pull/1066.

Now we're just waiting for that code to be published.

**Comment by adriancole** [comment]
glad wheels are back on the rails mutually!

**Comment by meltsufin** [comment]
Closing since support was added in spring-cloud/spring-cloud-sleuth#1066.
