### ISSUE TITLE
Unable to run integration tests on concourse on spanner.

### ISSUE THREAD

**Issue by vineela-gampa** [spring-cloud/spring-cloud-gcp#966]
Hi @ChengyuanZhao @meltsufin we need your help as we are unable to run integraiton tests on our concourse server. 

but we are continuously running into issue reported below. Need your expertise or location where your build scripts to run integration tests exist to see what differently we need to do it. 

> #Install in GCP
> # Create environment variable for correct distribution
> export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
> 
> file="google-cloud-sdk-206.0.0-linux-x86_64.tar.gz"
> link="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/"
> 
> curl -L "$link""$file" | tar xz 
> CLOUDSDK_CORE_DISABLE_PROMPTS=1 ./google-cloud-sdk/install.sh
> 
> echo "PWD: $(pwd)"
> 
> source $PRESENT_FOLDER/google-cloud-sdk/completion.bash.inc
> source $PRESENT_FOLDER/google-cloud-sdk/path.bash.inc
> 
> echo "Google cloud SDK installation is success"
> 
> export CLOUDSDK_CORE_PROJECT=$1
> 
> 
> export CLOUDSDK_CORE_PROJECT=$1
> echo $json > "/tmp/gcloud_key.json"
> 
> echo "env variable value for GOOGLE_APPLICATION_CREDENTIALS :"
> echo "$GOOGLE_APPLICATION_CREDENTIALS"
> 
> gcloud auth activate-service-account --key-file /tmp/gcloud_key.json
> 
> gcloud auth list
> echo "Authenticated service account to gcloud"
> 
> 
> 
> we are installing gcloud and setting GOOGLE_APPLICATION_CREDENTIALS as above.

 

> Caused by: java.net.SocketTimeoutException: connect timed out
> 	at java.net.PlainSocketImpl.socketConnect(Native Method)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
> 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
> 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
> 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
> 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
> 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
> 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
> 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
> 	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
> 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
> 	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:283)
> 	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
> 	at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:384)
> 	at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489)
> 	at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:217)
> 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:859)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
> 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
> 	at com.homedepot.loyalty.service.common.BqComponent.insertRowsIntoBq(BqComponent.java:42)
> 	... 36 common frames omitted

**Comment by meltsufin** [comment]
It looks like your CI server has trouble connecting to Spanner. Is it able to access other GCP services?

**Comment by vineela-gampa** [comment]
@meltsufin  gcloud operations are working fine but "GRPC" calls have issues .

**Comment by ChengyuanZhao** [comment]
See related issue. closing
