### ISSUE TITLE
`@ConditionalOnProperty` target property with no metadata

### ISSUE THREAD

**Issue by snicoll** [spring-cloud/spring-cloud-gcp#973]
Several auto-configurations use a condition on a property that has no metadata. As a result, trying to use it to customize the auto-configuration lead to a warning in an IDE.

The report detected the following:

```
org.springframework.cloud.gcp.autoconfigure.logging.StackdriverLoggingAutoConfiguration [spring.cloud.gcp.logging.enabled]
org.springframework.cloud.gcp.autoconfigure.pubsub.GcpPubSubAutoConfiguration [spring.cloud.gcp.pubsub.enabled]
org.springframework.cloud.gcp.autoconfigure.sql.GcpCloudSqlAutoConfiguration [spring.cloud.gcp.sql.enabled]
org.springframework.cloud.gcp.autoconfigure.trace.StackdriverTraceAutoConfiguration [spring.cloud.gcp.trace.enabled]
  
```

**Comment by artembilan** [comment]
The mentioned configuration properties just don't have a particular `@ConfigurationProperties` class representative.

@snicoll ,

any ideas what would you like to see as a fix?

Thanks

**Comment by snicoll** [comment]
Thanks for the feedback.

> any ideas what would you like to see as a fix?

Yes, that's what manual metadata is for. When a property is not used by the code directly, it doesn't make much sense to fake a property by adding it to the model. For those cases, we can [document the keys manually](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#configuration-metadata-additional-metadata).

**Comment by artembilan** [comment]
Thanks, @snicoll , for the right direction!

Any pointers how to test or at least reproduce?
Is it just a content assistance issue in the IDE?

**Comment by snicoll** [comment]
I can't provide you with a way to test it doesn't happen again I am afraid as this is some code from Jetbrains scanning the code and spotting those mistakes (See also https://youtrack.jetbrains.com/issue/IDEA-197990).

> Is it just a content assistance issue in the IDE?

Like any other property the project may define, yes.
