### ISSUE TITLE
Batch Insert/Upsert

### ISSUE THREAD

**Issue by TamasNeumer** [spring-cloud/spring-cloud-gcp#974]
Hi!

I'm currently trying to optimise the upsert(ion) of multiple entities (resulting in 100k-500k rows). According to the [official Google docs](https://cloud.google.com/spanner/docs/getting-started/java/) I should crate a list of mutations (`List<Mutation>`) and handle these over to the dbClient (`dbClient.write(mutations);`), while making sure that the list of mutations and hence the resulting commit won't exceed the 5MB limit as suggested by [the docs](https://cloud.google.com/spanner/docs/bulk-loading). 

Currently the only way I found to upsert (or insert) into the database is to use the `SpannerTemplate.upsert(Object o)`method. Hence currently I can imagine something like this:

```java
 public void bulkUpsert(Iterable<Car> objectsToUpsert){

    carRepository.getSpannerTemplate().performReadWriteTransaction(spannerTemplate -> {
      for(Car car : objectsToUpsert){
        spannerTemplate.upsert(car);
      }
      return objectsToUpsert;
    });
  }
```

Is it really the "most I can get out of" `spring-cloug-gcp`? Does the library issue 100k commits towards the database, or is there optimisation in the background?

Or am I overcomplicating the things and I should simply issue a `carRepository.saveAll(objectsToUpsert);` ? 

Thank you for your effort in the library!

**Comment by ChengyuanZhao** [comment]
Hi @TamasNeumer thanks for the question! 

The method you're using now is basically a passthrough to the `TransactionCallable` of the client library, and is the Cloud Spanner way to make all the inserts in a single commit. https://cloud.google.com/spanner/docs/transactions 
The benefit of having this spannerTemplate anonymous variable is that you can act on multiple tables in the same transaction that gets committed or do reads too. 

You can also use saveAll, and that also does all the saves in a single commit. The difference is just that it's very simple and you just upsert to a single table.

**Comment by meltsufin** [comment]
@ChengyuanZhao Both ways results in a single commit, but I guess the question is about the number of roundtrips to the database. With `performReadWriteTransaction`, it looks like there will be a roundtrip to the database per item? Is there a way to send more than one mutation to Spanner at once?

**Comment by meltsufin** [comment]
@ChengyuanZhao Looking at our `SpannerMutationFactory`, we don't allow something like `insert(List<Object> objects)`, although Spanner `DatabaseClient` can write multiple mutations at once.

**Comment by ChengyuanZhao** [comment]
@meltsufin Yea you're right that, it looks `saveAll` in `SpannerRepository` right now saves each object individually, though each individual object results in multiple mutations because of its children relationships. I'll make an issue for saving multiple root objects in a single batch.

**Comment by TamasNeumer** [comment]
@meltsufin   This was exactly my point! 😄 Basically I want to save 50k rows with 50k mutations in a single batch / commit.

> Looking at our SpannerMutationFactory, we don't allow something like insert(List<Object> objects), although Spanner DatabaseClient can write multiple mutations at once.

**Comment by TamasNeumer** [comment]
@ChengyuanZhao When can we anticipate a release/milestone that includes this feature?

Thank you very much for your fast work!

**Comment by ChengyuanZhao** [comment]
@TamasNeumer our next milestone will include this and should be out late September. 

Thanks again!

**Comment by meltsufin** [comment]
@TamasNeumer In the meantime you can pick up our snapshot build.
```xml
<dependencies>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-gcp</artifactId>
        <version>1.1.0.BUILD-SNAPSHOT</version>
    </dependency>
</dependencies><repositories>
    <repository>
        <id>spring-snapshots</id>
        <name>Spring Snapshots</name>
        <url>https://repo.spring.io/libs-snapshot</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```
