### ISSUE TITLE
Document how to use Cloud Memorystore for Redis with Spring Cache

### ISSUE THREAD

**Issue by meltsufin** [spring-cloud/spring-cloud-gcp#981]
Note that Cloud Memorystore for Redis is currently in BETA.

See: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-caching.html#boot-features-caching-provider-redis
See: https://cloud.google.com/memorystore/docs/redis/

**Comment by dmitry-s** [comment]
Created a code lab:
https://codelabs.developers.google.com/codelabs/cloud-spring-cache-memorystore/
