### ISSUE TITLE
Pubsub variable polling times and retry logic

### ISSUE THREAD

**Issue by justbaum30** [spring-cloud/spring-cloud-gcp#984]
Apologize if this isn't the appropriate place to ask questions.

We are attempting to use Pubsub as a queue of jobs to work through. To complete this job, we are dependent on a external system that is occasionally unavailable. I'm looking to better understand if we can utilize Pubsub in our desired way but have been unable to figure out how to configure several aspects:

1. By default, it seems that the subscriber is being polled (we're using a Pull subscriber currently), about every 1.5 seconds (I couldn't find the where this value is) when an executor thread is available. This is fine normally, but if the system is down, we'd ideally want to not poll as often. I toyed with sending back `nack`s in this scenario and was hoping that the retry settings would come into effect, but it seems that is only for polling itself failing (I think?). Am I misunderstanding how to configure for something like this?

2. As a suggestion, I would recommend adding a bit more clarification to the retry properties docs. I find it unclear as to *when* those retries actually happen. Also not sure when the `rpc` values take effect vs. the other retry values.

Currently, we're utilizing Spring integration (`@ServiceActivator` with the input channel specified) if that is relevant.

**Comment by meltsufin** [comment]
We'll try to help answer your questions, although some answers might be in the [Pub/Sub client library](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-pubsub) that we rely on.

1. The subscriber in the Pub/Sub client library will automatically pull more messages than your application is consuming. If your application is not able to process the messages as quickly or failing, you should probably set the `spring.cloud.gcp.pubsub.subscriber.flow-control.max-outstanding-element-count` to some small number. It should also stop the polling as soon as that target count is reached. Which retry setting are you experimenting with or confused about?

2. Can you clarify which settings? Note that some of the docs are [here](https://cloud.google.com/pubsub/docs/pull).

**Comment by justbaum30** [comment]
Thank you very much for your time.

When you say it will pull more message than the application is consuming, does this mean that if there are 100 messages published to the topic and the application only processes them 1 every 10 sec, then it will pull all 100 messages and put them in memory unless a max element count is specified? 

I had tried experimenting with  `spring.cloud.gcp.pubsub.subscriber.retry.initial-retry-delay-second` but wasn't sure under what conditions the retry actually occurs. This circles back with my second note, where, at least to me, I was unsure under what conditions a retry occurs.

**Comment by meltsufin** [comment]
Yes it pulls messages into memory before delivering them to the client code. See: https://cloud.google.com/pubsub/docs/pull#message-flow-control

I believe the retry logic refers to situations where the application just cannot get a response from the Pub/Sub service.

**Comment by dhoard** [comment]
Based on you described use case, what I have done is ...

1. Set the subscription up with a 300 seconds (5 minutes) ack deadline
2. Create a `PubSubSubscriberTemplate`
3. Create an `ExecutorService` using a fixed thread pool.
4. Submit a `Runnable` that will loop ... pulling a single message from the `PubSubSubscriberTemplate` via the synchronous `public List<AcknowledgeablePubsubMessage> pull(String subscription, 1, false)` method, process the message, and then acknowledge the message.

This will allow your code to pull a message, process it, and then acknowledge it.  If there is an issue processing the message, then I would *not* nack it ... simply let the ack deadline expire, so you won't see the message for another 5 minutes.

If the external system is down, you can sleep before performing the loop again.

**Comment by justbaum30** [comment]
@meltsufin @dhoard Thank you. That was very helpful, and we've utilized some of this behavior into our solution. I do have one more question on something that has been nagging me on how to configure properly (and I do apologize that this might be more of a pubsub rather than spring-pubsub question)... 

We are currently utilizing the async streaming pull to get messages as they come in. As I mentioned before, each of these operations is a longer running task (5-10 seconds). Even though I configured flow control to say each subscriber should only hold up to 1 at a time (`spring.cloud.gcp.pubsub.subscriber.flow-control.max-outstanding-element-count=1`), it looks like the streaming pull grabs many at a time and holds onto them. I see this in `MessageDispatcher.processReceivedMessages`.

The result is that if 10 messages come in at once, it seems that each of the subscribers get 5, regardless if one of the subscribers processes all their messages in only a few seconds and is left with nothing to do while the other subscriber is still working through it's 5.

 Is there something I'm missing here? Do I need to switch to synchronous pulling or are there other configurations I should be modifying? Thanks for all your suggestions and ideas here!

**Comment by dhoard** [comment]
@justbaum30 A synchronous pull with one message *should* do what you are wanting.

From a performance standpoint, pulling a batch of messages is more performant.

Are the subscribers in different applications / processes?

Is there a specific reason you need them evenly dispatched?

**Comment by meltsufin** [comment]
@justbaum30 It sounds like a bug in the client library around flow control settings. Is it the same as https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3152? In any case, can you please create an issue in https://github.com/GoogleCloudPlatform/google-cloud-java/issues? Thanks!

**Comment by justbaum30** [comment]
@dhoard The different subscribers are different instances of the same application. The expectation is that the different instances should all be processing messages as soon as they can so they spend the least amount of time possible in the topic. Since the processing time of each message is relatively long (but variable), we figure the performance hit of only pulling a single message at a time is relatively small compared to a single instance potentially hoarding a lot of messages.

@meltsufin It sounds like that issue is exactly the issue we're facing. I'll comment there and see if there are any updates on it.

**Comment by meltsufin** [comment]
@justbaum30 Based on an offline conversation with the Pub/Sub team, it looks like the first subscriber always gets 10MB of messages and starts hoarding them. There seems to be no workaround right now other than using pulling. We might consider switching our listener implementation and the SI adapter to use pulling as well. I'll update the issue when I get more info from the Pub/Sub team.

**Comment by justbaum30** [comment]
Thanks for the responsiveness. I'll definitely keep an eye out on both the issues.

**Comment by meltsufin** [comment]
Pull-based subscriptions should be a workable solution for this.
