### ISSUE TITLE
Datastore support DELETE query methods

### ISSUE THREAD

**Issue by ChengyuanZhao** [spring-cloud/spring-cloud-gcp#996]
perhaps using performTransaction to do the get then delete for the user.

**Comment by ChengyuanZhao** [comment]
I just implemented this at https://github.com/spring-cloud/spring-cloud-gcp/tree/datastore-delete-part-tree-queries complete with integration test but upon running it I get the error that transactions must have an ancestor (meaning the entire transaction can only act on the family tree under a single entity). This actually makes sense, since we've been mentioning that the purpose of the ancestors feature is that it is the only way to have transactions. To support this single transaction read-delete we will need to wait until we have implemented ancestors. @meltsufin @dmitry-s FYI

**Comment by meltsufin** [comment]
Are you saying that we wouldn't be able to support DELETE query methods for entities that don't have ancestors? This seems very restrictive. What if we just do the keys fetch for delete and the delete keys in two different transactions?

**Comment by ChengyuanZhao** [comment]
@meltsufin Because of eventual consistency and if the data is being accessed by more than one user then we really might be deleting data that doesn't exist or not deleting things that the user expects to delete. I think the expected behavior would be an atomic operation, since all the other verbs for the part tree (count, exists, find, get) etc are all atomic. 

I think again this boils down to respecting and exposing the tech of the underlying storage medium rather than trying to hit every single feature available in Spring Data.

**Comment by ChengyuanZhao** [comment]
@meltsufin @dmitry-s I did more reading and trying it out myself. I don't think it will be possible to do this DELETE in a single transaction even using cross-group transactions. 

The reason is that queries in transactions must have an ancestor specified regardless of it is cross-group or single-group. That is a problem for us because the user specifies a method like `deleteByColorAndSize` then the query that is run is based on those 2 fields, and there is no ancestor at all specified. 

We can do this in a 2-request non-transaction.
